### ISSUE TITLE
Cannot install cupy via pip

### ISSUE THREAD

**Issue by saharudra** [cupy/cupy#1062]
System: Ubuntu 14.04
Python Version: 3.4.3
I tried installing via `pip install cupy` but got the following error:

```
sudo pip3 install cupy
Downloading/unpacking cupy
  Downloading cupy-2.5.0.tar.gz (1.8MB): 1.8MB downloaded
  Running setup.py (path:/tmp/pip_build_root/cupy/setup.py) egg_info for package cupy
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    /tmp/tmpso5xgb05/a.cpp:7:19: fatal error: nvrtc.h: No such file or directory
     #include <nvrtc.h>
                       ^
    compilation terminated.
    Options: {'no_cuda': False, 'linetrace': False, 'profile': False, 'annotate': False}
    Include directories: ['/usr/include']
    Library directories: ['/usr/lib']
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h', 'nvToolsExt.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/cupy/setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip_build_root/cupy/cupy_setup_build.py", line 385, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip_build_root/cupy/cupy_setup_build.py", line 275, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    Complete output from command python setup.py egg_info:
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

/tmp/tmpso5xgb05/a.cpp:7:19: fatal error: nvrtc.h: No such file or directory

 #include <nvrtc.h>

                   ^

compilation terminated.

Options: {'no_cuda': False, 'linetrace': False, 'profile': False, 'annotate': False}

Include directories: ['/usr/include']

Library directories: ['/usr/lib']

command 'x86_64-linux-gnu-gcc' failed with exit status 1

**************************************************

*** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h', 'nvToolsExt.h']

*** WARNING: Skip installing cuda support

*** WARNING: Check your CFLAGS environment variable

**************************************************

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/cupy/setup.py", line 32, in <module>

    ext_modules = cupy_setup_build.get_ext_modules()

  File "/tmp/pip_build_root/cupy/cupy_setup_build.py", line 385, in get_ext_modules

    extensions = make_extensions(arg_options, compiler, use_cython)

  File "/tmp/pip_build_root/cupy/cupy_setup_build.py", line 275, in make_extensions

    raise Exception('Your CUDA environment is invalid. '

Exception: Your CUDA environment is invalid. Please check above error log.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cupy
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```
I have already tried the options present in [#952](https://github.com/cupy/cupy/issues/952). The output of my `nvcc --version`:

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
I tried using the binary package but that showed the following error:
```
sudo pip3 install --pre cupy-cuda80
Downloading/unpacking cupy-cuda80
  Could not find any downloads that satisfy the requirement cupy-cuda80
Cleaning up...
No distributions at all found for cupy-cuda80
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```
My cuda path is properly set and both cuda and cudnn are installed at their usual location.

**Comment by kmaehashi** [comment]
`pip` comes with Ubuntu 14.04 is too old to install binary package.
Could you try this?

```
pip install -U setuptools pip
pip install cupy-cuda80
```

**Comment by rohit12** [comment]
@kmaehashi @saharudra and I work on the same machine where this error was occurring. This resolved the issue. Do you think the same issue will arise when we try installing cupy on Ubuntu 16.04?

**Comment by kmaehashi** [comment]
Good to hear that the issue has resolved. AFAIK pip comes with Ubuntu 16.04 is sufficient to install binary package, although I recommend you to use the latest one.
