### ISSUE TITLE
ImportError: CuPy is not correctly installed.

### ISSUE THREAD

**Issue by yangshao** [cupy/cupy#1073]
Hi, I'm using python 3.6.4(anaconda version) and pip command to install the cupy, but when i try to import cupy, it throws the following error:
>>> import cupy
Traceback (most recent call last):
  File "/mnt/home/yangshao/workspace/cupy/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/mnt/home/yangshao/workspace/cupy/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: cannot import name 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/home/yangshao/workspace/cupy/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/mnt/home/yangshao/anaconda2/envs/fastai/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/mnt/home/yangshao/workspace/cupy/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/mnt/home/yangshao/workspace/cupy/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

**Comment by yangshao** [comment]
After installing cupy with cuda 9.0 and gcc6, this problem is fixed.

**Comment by kmaehashi** [comment]
Thanks for the feedback.

**Comment by cristipurdel** [comment]
I am also getting a similar error on a win10 with anaconda install and no gpu:

```
 File "***\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "***\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Share/Documents/Python/TensorSolve/untitled0.py", line 1, in <module>
    import cupy as cp

  File "***\Anaconda3\lib\site-packages\cupy\__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])

  File "***\Anaconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)

  File "***\Anaconda3\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA

  File "***\Anaconda3\lib\site-packages\cupy\core\__init__.py", line 6, in <module>
    from cupy.core.core import absolute  # NOQA

ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: cannot import name 'absolute'
```

**Comment by kmaehashi** [comment]
How did you install CuPy? (wheel, conda or built from source?)
What do you mean by "no gpu"?

**Comment by kmaehashi** [comment]
Unfortunately, currently you cannot import CuPy on Windows without GPU. This is becauase NVIDIA Display Driver (named `nvcuda.dll` on Windows), which is one of the dependency of CuPy, will not be installed by the CUDA installer if GPU is not detected on your machine.

**Comment by kmaehashi** [comment]
I'd suggest you to do sth like:

```py
try:
    import cupy
except ImportError:
    cupy = None
```

**Comment by cristipurdel** [comment]
The suggestion works, but it would be nice to have a feature request to do this automatically.
I have no issues with import numba

**Comment by kmaehashi** [comment]
I understand your concern. I started to work on this (#1781) and will discuss with the team.
