### ISSUE TITLE
Cupy Cuda Compiler CompileException

### ISSUE THREAD

**Issue by rohit12** [cupy/cupy#1085]
System: `Ubuntu 16.04`
Python version: `3.5.2`

I am using Cupy with Chainer. I am trying to run a code which requires chainer and cupy. My CUDA version is 8.0 and my cuDNN version is 7.1.2.

I get the following error from cupy:

```

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 206, in update_core
    loss = _calc_loss(self._master, batch)
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 235, in _calc_loss
    return model(*in_arrays)
  File "/home/ubuntu/src/see/chainer/utils/multi_accuracy_classifier.py", line 44, in __call__
    self.y = self.predictor(*x)
  File "/home/ubuntu/src/see/chainer/models/svhn.py", line 209, in __call__
    h = self.localization_net(images)
  File "/home/ubuntu/src/see/chainer/models/svhn.py", line 41, in __call__
    h = self.bn0(self.conv0(images))
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 154, in __call__
    self._initialize_params(x.shape[1])
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 141, in _initialize_params
    self.W.initialize(W_shape)
  File "/usr/local/lib/python3.5/dist-packages/chainer/variable.py", line 1250, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/usr/local/lib/python3.5/dist-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/usr/local/lib/python3.5/dist-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 229, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chainer/train_svhn.py", line 257, in <module>
    trainer.run()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 206, in update_core
    loss = _calc_loss(self._master, batch)
  File "/usr/local/lib/python3.5/dist-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 235, in _calc_loss
    return model(*in_arrays)
  File "/home/ubuntu/src/see/chainer/utils/multi_accuracy_classifier.py", line 44, in __call__
    self.y = self.predictor(*x)
  File "/home/ubuntu/src/see/chainer/models/svhn.py", line 209, in __call__
    h = self.localization_net(images)
  File "/home/ubuntu/src/see/chainer/models/svhn.py", line 41, in __call__
    h = self.bn0(self.conv0(images))
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 154, in __call__
    self._initialize_params(x.shape[1])
  File "/usr/local/lib/python3.5/dist-packages/chainer/links/connection/convolution_2d.py", line 141, in _initialize_params
    self.W.initialize(W_shape)
  File "/usr/local/lib/python3.5/dist-packages/chainer/variable.py", line 1250, in initialize
    data = initializers.generate_array(self.initializer, shape, xp)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/normal.py", line 68, in __call__
    Normal(s)(array)
  File "/usr/local/lib/python3.5/dist-packages/chainer/initializers/normal.py", line 36, in __call__
    array[...] = xp.random.normal(**args)
  File "/usr/local/lib/python3.5/dist-packages/cupy/random/distributions.py", line 94, in normal
    cupy.multiply(x, scale, out=x)
  File "/usr/local/lib/python3.5/dist-packages/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: __nv_nvrtc_builtin_header.h(49099): error: expected a ";"

__nv_nvrtc_builtin_header.h(49100): error: expected a ";"

__nv_nvrtc_builtin_header.h(49101): error: expected a ";"

__nv_nvrtc_builtin_header.h(49102): error: expected a ";"

__nv_nvrtc_builtin_header.h(49103): error: expected a ";"

__nv_nvrtc_builtin_header.h(49104): error: expected a ";"

__nv_nvrtc_builtin_header.h(49105): error: expected a ";"

__nv_nvrtc_builtin_header.h(49106): error: expected a ";"

__nv_nvrtc_builtin_header.h(49107): error: expected a ";"

__nv_nvrtc_builtin_header.h(49108): error: expected a ";"

__nv_nvrtc_builtin_header.h(49109): error: expected a ";"

__nv_nvrtc_builtin_header.h(49144): error: expected a ";"

__nv_nvrtc_builtin_header.h(49145): error: expected a ";"

__nv_nvrtc_builtin_header.h(49146): error: expected a ";"

__nv_nvrtc_builtin_header.h(49147): error: expected a ";"

__nv_nvrtc_builtin_header.h(49148): error: expected a ";"

__nv_nvrtc_builtin_header.h(49149): error: expected a ";"

__nv_nvrtc_builtin_header.h(49150): error: expected a ";"

__nv_nvrtc_builtin_header.h(49151): error: expected a ";"

__nv_nvrtc_builtin_header.h(49152): error: expected a ";"

__nv_nvrtc_builtin_header.h(49153): error: expected a ";"

__nv_nvrtc_builtin_header.h(49154): error: expected a ";"

__nv_nvrtc_builtin_header.h(49155): error: expected a ";"

__nv_nvrtc_builtin_header.h(49156): error: expected a ";"

__nv_nvrtc_builtin_header.h(49157): error: expected a ";"

__nv_nvrtc_builtin_header.h(49158): error: expected a ";"

__nv_nvrtc_builtin_header.h(49159): error: expected a ";"

__nv_nvrtc_builtin_header.h(49160): error: expected a ";"

__nv_nvrtc_builtin_header.h(49161): error: expected a ";"

__nv_nvrtc_builtin_header.h(49162): error: expected a ";"

__nv_nvrtc_builtin_header.h(49163): error: expected a ";"

__nv_nvrtc_builtin_header.h(49164): error: expected a ";"

__nv_nvrtc_builtin_header.h(49165): error: expected a ";"

__nv_nvrtc_builtin_header.h(49166): error: expected a ";"

__nv_nvrtc_builtin_header.h(49167): error: expected a ";"

__nv_nvrtc_builtin_header.h(49168): error: expected a ";"

__nv_nvrtc_builtin_header.h(49169): error: expected a ";"

__nv_nvrtc_builtin_header.h(49170): error: expected a ";"

__nv_nvrtc_builtin_header.h(49171): error: expected a ";"

__nv_nvrtc_builtin_header.h(49172): error: expected a ";"

__nv_nvrtc_builtin_header.h(49173): error: expected a ";"

__nv_nvrtc_builtin_header.h(49174): error: expected a ";"

__nv_nvrtc_builtin_header.h(49231): error: expected a ";"

__nv_nvrtc_builtin_header.h(49232): error: expected a ";"

__nv_nvrtc_builtin_header.h(49233): error: expected a ";"

__nv_nvrtc_builtin_header.h(49234): error: expected a ";"

__nv_nvrtc_builtin_header.h(49238): error: expected a ";"

__nv_nvrtc_builtin_header.h(49239): error: expected a ";"

__nv_nvrtc_builtin_header.h(49240): error: expected a ";"

__nv_nvrtc_builtin_header.h(49241): error: expected a ";"

__nv_nvrtc_builtin_header.h(49242): error: expected a ";"

__nv_nvrtc_builtin_header.h(49243): error: expected a ";"

__nv_nvrtc_builtin_header.h(49244): error: expected a ";"

__nv_nvrtc_builtin_header.h(49245): error: expected a ";"

__nv_nvrtc_builtin_header.h(49246): error: expected a ";"

__nv_nvrtc_builtin_header.h(49247): error: expected a ";"

__nv_nvrtc_builtin_header.h(49248): error: expected a ";"

__nv_nvrtc_builtin_header.h(49283): error: expected a ";"

__nv_nvrtc_builtin_header.h(49284): error: expected a ";"

__nv_nvrtc_builtin_header.h(49285): error: expected a ";"

__nv_nvrtc_builtin_header.h(49286): error: expected a ";"

__nv_nvrtc_builtin_header.h(49287): error: expected a ";"

__nv_nvrtc_builtin_header.h(49288): error: expected a ";"

__nv_nvrtc_builtin_header.h(49289): error: expected a ";"

__nv_nvrtc_builtin_header.h(49290): error: expected a ";"

__nv_nvrtc_builtin_header.h(49291): error: expected a ";"

__nv_nvrtc_builtin_header.h(49292): error: expected a ";"

__nv_nvrtc_builtin_header.h(49293): error: expected a ";"

__nv_nvrtc_builtin_header.h(49294): error: expected a ";"

__nv_nvrtc_builtin_header.h(49295): error: expected a ";"

__nv_nvrtc_builtin_header.h(49296): error: expected a ";"

__nv_nvrtc_builtin_header.h(49297): error: expected a ";"

__nv_nvrtc_builtin_header.h(49298): error: expected a ";"

__nv_nvrtc_builtin_header.h(49299): error: expected a ";"

__nv_nvrtc_builtin_header.h(49300): error: expected a ";"

__nv_nvrtc_builtin_header.h(49301): error: expected a ";"

__nv_nvrtc_builtin_header.h(49302): error: expected a ";"

__nv_nvrtc_builtin_header.h(49303): error: expected a ";"

__nv_nvrtc_builtin_header.h(49304): error: expected a ";"

__nv_nvrtc_builtin_header.h(49305): error: expected a ";"

__nv_nvrtc_builtin_header.h(49306): error: expected a ";"

__nv_nvrtc_builtin_header.h(49307): error: expected a ";"

__nv_nvrtc_builtin_header.h(49308): error: expected a ";"

__nv_nvrtc_builtin_header.h(49309): error: expected a ";"

__nv_nvrtc_builtin_header.h(49310): error: expected a ";"

__nv_nvrtc_builtin_header.h(49311): error: expected a ";"

__nv_nvrtc_builtin_header.h(49312): error: expected a ";"

__nv_nvrtc_builtin_header.h(49313): error: expected a ";"

__nv_nvrtc_builtin_header.h(49370): error: expected a ";"

__nv_nvrtc_builtin_header.h(49371): error: expected a ";"

__nv_nvrtc_builtin_header.h(49372): error: expected a ";"

__nv_nvrtc_builtin_header.h(49373): error: expected a ";"

__nv_nvrtc_builtin_header.h(49377): error: expected a ";"

__nv_nvrtc_builtin_header.h(49378): error: expected a ";"

__nv_nvrtc_builtin_header.h(49379): error: expected a ";"

__nv_nvrtc_builtin_header.h(49380): error: expected a ";"

__nv_nvrtc_builtin_header.h(49381): error: expected a ";"

__nv_nvrtc_builtin_header.h(49382): error: expected a ";"

__nv_nvrtc_builtin_header.h(49383): error: expected a ";"

__nv_nvrtc_builtin_header.h(49384): error: expected a ";"

Error limit reached.
100 errors detected in this compilation.
Compilation terminated.


```

Do you have any idea what the error could be? Google turned up nothing. I am amazed that I am the first one with this problem!

**Comment by rohit12** [comment]
@kmaehashi thank you! It works! 

I have an AWS machine which comes preinstalled with CUDA 7.5. We tried uninstalling it and installing CUDA 8. But somehow, CUDA 7.5 remains. We are unable to purge it completely.

So, I tried setting up setting up the `CUDA_PATH` environment variable. It didn't work.

Uninstalling cupy and installing `cupy-cuda80` worked instead. Thanks a lot!

One final question: Why does this happen? Do you have any idea of the issue? I would like to know more in depth if I face more issues like this in the future,

**Comment by kmaehashi** [comment]
Glad to hear that!

> One final question: Why does this happen? Do you have any idea of the issue? I would like to know more in depth if I face more issues like this in the future,

There are three key components involved: CUDA runtime, CUDA shared library called `libnvrtc-builtins.so` (which is dlopened at runtime), and CUDA header files. Versions of all three must be the same.
The first two components are discovered using the system standard behavior (see `man ld-linux`), and the last one will be discovered via `CUDA_PATH` (which is CuPy specific).

So I'd recommend not to mix multiple CUDA installations on the same host.
