### ISSUE TITLE
Intermediate array of cupy.einsum is unnecessarily large

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#1197]
The current implementation of `cupy.einsum` has much different time complexity than `numpy.einsum` with `optimize=False`.  For example, `cupy.einsum('i,i->', x, y)` is O(n^2)-time, because it computes the diagonal of the tensor product of `x` and `y`.
https://github.com/cupy/cupy/blob/v5.0.0a1/cupy/linalg/einsum.py#L342

**Comment by toslunar** [comment]
```
>>> x = numpy.random.randn(1024)
>>> numpy.einsum('i,i,i,i->i', x, x, x, x)
array([23.37171553,  0.33109015,  0.04600123, ...,  3.09197196,
        0.36658771,  2.13602117])
>>> x_gpu = cupy.array(x)
>>> cupy.einsum('i,i,i,i->i', x_gpu, x_gpu, x_gpu, x_gpu)
Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 785, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
    arena_index.begin(), arena_index.end(),
  File "cupy/cuda/memory.pyx", line 710, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
    arena[index] = None
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
    cpdef MemoryPointer _malloc(Py_ssize_t size):
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
    mem = Memory(size)
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
    self.ptr = runtime.malloc(size)
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
    check_status(status)
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
    raise CUDARuntimeError(status)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 791, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
    continue
  File "cupy/cuda/memory.pyx", line 710, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
    arena[index] = None
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
    cpdef MemoryPointer _malloc(Py_ssize_t size):
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
    mem = Memory(size)
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
    self.ptr = runtime.malloc(size)
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
    check_status(status)
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
    raise CUDARuntimeError(status)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 797, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
    _compact_index(self, stream_ptr, False)
  File "cupy/cuda/memory.pyx", line 710, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
    arena[index] = None
  File "cupy/cuda/memory.pyx", line 423, in cupy.cuda.memory._malloc
    cpdef MemoryPointer _malloc(Py_ssize_t size):
  File "cupy/cuda/memory.pyx", line 424, in cupy.cuda.memory._malloc
    mem = Memory(size)
  File "cupy/cuda/memory.pyx", line 58, in cupy.cuda.memory.Memory.__init__
    self.ptr = runtime.malloc(size)
  File "cupy/cuda/runtime.pyx", line 212, in cupy.cuda.runtime.malloc
    check_status(status)
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
    raise CUDARuntimeError(status)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/linalg/einsum.py", line 342, in einsum
    result, subscript = calc_combined_view(results, subscripts)
  File "/home/kataoka/cupy/cupy/linalg/einsum.py", line 189, in calc_combined_view
    result = cupy.matmul(result, operand)
  File "cupy/core/core.pyx", line 3475, in cupy.core.core.matmul
    cpdef ndarray matmul(ndarray a, ndarray b, ndarray out=None):
  File "cupy/core/core.pyx", line 3577, in cupy.core.core.matmul
    out = ndarray(out_shape, dtype=dtype)
  File "cupy/core/core.pyx", line 96, in cupy.core.core.ndarray.__init__
    self.data = memory.alloc(self.size * self.dtype.itemsize)
  File "cupy/cuda/memory.pyx", line 468, in cupy.cuda.memory.alloc
    return _current_allocator(size)
  File "cupy/cuda/memory.pyx", line 939, in cupy.cuda.memory.MemoryPool.malloc
    blocks are managed for each device, so one instance of this class can be
  File "cupy/cuda/memory.pyx", line 960, in cupy.cuda.memory.MemoryPool.malloc
    def __init__(self, allocator=_malloc):
  File "cupy/cuda/memory.pyx", line 740, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
    if hooks:
  File "cupy/cuda/memory.pyx", line 803, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
    remaining = chunk.split(size)
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 8589934592 bytes (total 24597975552 bytes)
```
