### ISSUE TITLE
cupy.einsum does not support broadcast along non-ellipsis axes

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#1214]
I don't know why numpy supports this.
```
>>> cupy.einsum('i,i', cupy.ones(3), cupy.ones(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/linalg/einsum.py", line 343, in einsum
    result, subscript = calc_single_view(result, subscript)
  File "/home/kataoka/cupy/cupy/linalg/einsum.py", line 56, in calc_single_view
    shape_b))
ValueError: dimensions in operand 0 for collapsing index 'i' don't match (1 != 3)
>>> numpy.einsum('i,i', numpy.ones(3), numpy.ones(1))
3.0
```

BTW, diagonal axes should match.  (Related: #1197)
```
>>> numpy.einsum('ii', numpy.ones((3, 1)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/.pyenv/versions/anaconda3-4.2.0/envs/n/lib/python3.6/site-packages/numpy/core/einsumfunc.py", line 1069, in einsum
    return c_einsum(*operands, **kwargs)
ValueError: dimensions in operand 0 for collapsing index 'i' don't match (3 != 1)
```

**Comment by fukatani** [comment]
Thank you for opening the issue.

I'm somewhat unconvinced about this numpy behavior, so I asked a question here.
https://github.com/numpy/numpy/issues/10930
