### ISSUE TITLE
Possible issue with cupy sparse?

### ISSUE THREAD

**Issue by PM1980** [cupy/cupy#1261]
Hi there,

I am trying to build a sparse matrix using Cupy. For some reason the same matrix is stored using Scipy, but fails whenever cupy sparse is called. 

```
import numpy as np
import cupy as cp
import cupy.sparse
from scipy.sparse import csc_matrix
```

```
row1 = np.array([0, 2, 2, 0, 1, 2])
col1 = np.array([0, 0, 1, 2, 2, 2])
data1 = np.array([1., 2., 3., 4., 5., 6.])
test1=csc_matrix((data1, (row1, col1)), shape=(3, 3))
```

```
row2 = cp.array(row1)
col2 = cp.array(col1)
data2 = cp.array(data1)
test2=cupy.sparse.csc_matrix((data2, (row2, col2)), shape=(3, 3))
```

This code assigns variable "test1" and fails on "test2" with the following message:

### Traceback (most recent call last):

  File "<ipython-input-255-d9d68d5c5e40>", line 1, in <module>
    runfile('C:/Users/paulo/.spyder-py3/temp.py', wdir='C:/Users/paulo/.spyder-py3')

  File "C:\Users\paulo\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\paulo\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/paulo/.spyder-py3/temp.py", line 55, in <module>
    teste2=cupy.sparse.csc_matrix((data2, (row2, col2)), shape=(3, 3))

  File "C:\Users\paulo\Anaconda3\lib\site-packages\cupy\sparse\compressed.py", line 95, in __init__
    'Unsupported initializer format')

ValueError: Unsupported initializer format

**Am I doing something wrong? Thanks!
Regards,
Paulo**

**Comment by kmaehashi** [comment]
Thank you for the feedback. Currently initializer of that form is not implemented.

https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.sparse.csc_matrix.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html

**Comment by PM1980** [comment]
Mr Maehashi and others following this thread,

Thanks for your reply. I wonder how do you feed data into sparse arrays in Cupy. While I can generate sparse arrays with:

`sparse_array=cupy.sparse.coo_matrix((n, n))`

and can retrieve to full matrix format with:

`array=cp.sparse.coo_matrix.toarray(sparse_array)`

no option is given for retrieving or assigning an array element to Cupy sparse_array:

**d[1,1]**
Traceback (most recent call last):
  File "<ipython-input-71-1520633b6b34>", line 1, in <module>
    d[1,1]
TypeError: 'coo_matrix' object is not subscriptable
**d[1,1]=10**
Traceback (most recent call last):

  File "<ipython-input-72-471541d7d44a>", line 1, in <module>
    d[1,1]=10

TypeError: 'coo_matrix' object does not support item assignment

**Therefore, how can one assign or retrieve data on a sparse array?**

Thanks. Regards,
Paulo

**Comment by PM1980** [comment]
For those following this thread,

I made a very simple example/tutorial of a 5x5 sparse matrix with only two indexes:

```
rol=cp.array([1,2]).astype('Float32')                      # rows with data
col=cp.array([2,3]).astype('Float32')                     # columns with data
data=cp.array([1000,1000]).astype('Float32')             # data (number 1000 on both positions)
sparse_array=cupy.sparse.coo_matrix((data, (rol, col)),(5,5))      # cupy 5x5 sparse array

# to retrieve in full matrix format
full=cp.sparse.coo_matrix.toarray(sparse_array)
```

The following warning might be present:
**DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.**

Hope this helps. 
Paulo
