### ISSUE TITLE
real method for a zero-dim complex causes an error

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#1278]
```
>>> numpy.array(1, dtype=numpy.complex64).real
array(1.0, dtype=float32)
>>> cupy.array(1, dtype=numpy.complex64).real
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1402, in cupy.core.core.ndarray.real.__get__
    view = self.view(self.dtype.char.lower())
  File "cupy/core/core.pyx", line 423, in cupy.core.core.ndarray.view
    shape[-1] = shape[-1] * self.dtype.itemsize // v.dtype.itemsize
IndexError: list index out of range
```

**Comment by toslunar** [comment]
I'd fix `ndarray.view`, not by #1280.
