### ISSUE TITLE
CUSOLVER_STATUS_EXECUTION_FAILED raised with CUDA 9.1

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1365]
```py
>>> import cupy as cp
>>> a = cp.eye(4)
>>> a
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
>>> cp.linalg.svd(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cupy/linalg/decomposition.py", line 263, in svd
    workspace.data.ptr, buffersize, 0, dev_info.data.ptr)
  File "cupy/cuda/cusolver.pyx", line 522, in cupy.cuda.cusolver.dgesvd
  File "cupy/cuda/cusolver.pyx", line 531, in cupy.cuda.cusolver.dgesvd
  File "cupy/cuda/cusolver.pyx", line 175, in cupy.cuda.cusolver.check_status
cupy.cuda.cusolver.CUSOLVERError: CUSOLVER_STATUS_EXECUTION_FAILED
>>> b = cp.eye(2)
>>> cp.linalg.svd(b)
(array([[-1.,  0.],
       [-0.,  1.]]), array([ 1.,  1.]), array([[-1., -0.],
       [ 0.,  1.]]))```
```

This issue does not reproduce with CUDA 9.0.

**Comment by YoshikawaMasashi** [comment]
I think this is not caused by cupy code.
I execute this code.

```c++
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <cuda_runtime.h>
#include <cusolverDn.h>

int main()
{
    const int n = 4;
    double A[n*n];
    double S[n];
    double U[n*n];
    double VT[n*n];
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
            A[i*n + j] = 0;
            if (i == j){
                A[i*n + j] += 1;
            }
        }
    }

    cusolverDnHandle_t handle;
    cusolverDnCreate(&handle);
    int lwork;

    cusolverDnDgesvd_bufferSize(
        handle,
        n,
        n,
        &lwork);

    double *d_A;
    cudaMalloc(&d_A, sizeof(double)*n*n);
    cudaMemcpy(d_A, A, sizeof(double)*n*n, cudaMemcpyHostToDevice);

    double *d_S;
    cudaMalloc(&d_S, sizeof(double)*n);

    double *d_U;
    cudaMalloc(&d_U, sizeof(double)*n*n);

    double *d_VT;
    cudaMalloc(&d_VT, sizeof(double)*n*n);

    double *d_work;
    cudaMalloc(&d_work, sizeof(double)*lwork);

    double *d_rwork;
    cudaMalloc(&d_rwork, sizeof(double)*(n - 1));

    int *devInfo;
    cudaMalloc(&devInfo, sizeof(int));

    
    signed char jobu = 'A';
    signed char jobvt = 'A';
    
    cusolverStatus_t status;
    status = cusolverDnDgesvd(
        handle,
        jobu,
        jobvt,
        n,
        n,
        d_A,
        n,
        d_S,
        d_U,
        n,
        d_VT,
        n,
        d_work,
        lwork,
        d_rwork,
        devInfo);
    cudaMemcpy(U, d_U, sizeof(double)*n*n, cudaMemcpyDeviceToHost);
    cudaMemcpy(S, d_S, sizeof(double)*n, cudaMemcpyDeviceToHost);
    cudaMemcpy(VT, d_VT, sizeof(double)*n*n, cudaMemcpyDeviceToHost);
    
    
    printf("A\n");
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
          printf("%f ", A[i * n + j]);
        }
        printf("\n");
    }

    switch(status){
      case CUSOLVER_STATUS_SUCCESS:
        printf("Status:CUSOLVER_STATUS_SUCCESS \n");
        break;
      case CUSOLVER_STATUS_EXECUTION_FAILED:
        printf("Status:CUSOLVER_STATUS_EXECUTION_FAILED \n");
        break;
      default:
        printf("Status:Other \n");
        break;
    }
    
    printf("U\n");
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
          printf("%f ", U[i * n + j]);
        }
        printf("\n");
    }
    
    printf("S\n");
    for (int i = 0; i < n; i++)
    {
        printf("%f ", S[i]);
    }
    printf("\n");
    
    printf("VT\n");
    for (int i = 0; i < n; i++)
    {
        for (int j = 0; j < n; j++)
        {
          printf("%f ", VT[i * n + j]);
        }
        printf("\n");
    }

    
    cudaFree(d_A);
    cudaFree(d_rwork);
    cudaFree(d_S);
    cudaFree(d_U);
    cudaFree(d_VT);
    cudaFree(d_work);
}
```

the result is
```
A
1.000000 0.000000 0.000000 0.000000
0.000000 1.000000 0.000000 0.000000
0.000000 0.000000 1.000000 0.000000
0.000000 0.000000 0.000000 1.000000
Status:CUSOLVER_STATUS_EXECUTION_FAILED
U
-1.000000 -0.000000 -0.000000 -0.000000
nan nan nan nan
-nan -nan -nan -nan
-nan -nan -nan -nan
S
-1.000000 -nan -nan -nan
VT
1.000000 0.000000 0.000000 0.000000
0.000000 -nan -nan -nan
0.000000 nan -nan -nan
0.000000 nan -nan -nan
```

When I use not identity matrix, the result is success.
```
A
2.000000 1.000000 1.000000 1.000000
1.000000 2.000000 1.000000 1.000000
1.000000 1.000000 2.000000 1.000000
1.000000 1.000000 1.000000 2.000000
Status:CUSOLVER_STATUS_SUCCESS
U
-0.500000 -0.500000 -0.500000 -0.500000
0.866025 -0.288675 -0.288675 -0.288675
0.000000 0.000000 -0.707107 0.707107
-0.000000 0.816497 -0.408248 -0.408248
S
5.000000 1.000000 1.000000 1.000000
VT
-0.500000 0.866025 0.000000 0.000000
-0.500000 -0.288675 0.000000 0.816497
-0.500000 -0.288675 -0.707107 -0.408248
-0.500000 -0.288675 0.707107 -0.408248
```

**Comment by okuta** [comment]
CUDA 10 has been released.
https://developer.nvidia.com/cuda-toolkit/whatsnew
Maybe bug was fixed.

**Comment by kmaehashi** [comment]
This issue was specific to CUDA 9.1.
I confirmed this does not reproduce any more with CUDA 9.2.
