### ISSUE TITLE
Support numpy 1.13

### ISSUE THREAD

**Issue by unnonouno** [cupy/cupy#137]

**Comment by niboshi** [comment]
master branch is failing:

```
 ======================================================================
18:32:41 FAIL: test_subtract (test_fusion.TestFusionArithmetic)
18:32:41 ----------------------------------------------------------------------
18:32:42 Traceback (most recent call last):
18:32:42   File "/work/cupy/tests/cupy_tests/core_tests/test_fusion.py", line 480, in test_subtract
18:32:42     self.check_binary('subtract')
18:32:42   File "/work/cupy/cupy/testing/helper.py", line 404, in test_func
18:32:42     impl(self, *args, **kw)
18:32:42   File "/work/cupy/cupy/testing/helper.py", line 94, in test_func
18:32:42     accept_error=accept_error)
18:32:42   File "/work/cupy/cupy/testing/helper.py", line 43, in _check_cupy_numpy_error
18:32:42     self.fail('Only numpy raises error\n\n' + numpy_tb)
18:32:42 AssertionError: Only numpy raises error
18:32:42 
18:32:42 Traceback (most recent call last):
18:32:42   File "/work/cupy/cupy/testing/helper.py", line 20, in _call_func
18:32:42     result = impl(self, *args, **kw)
18:32:42   File "/work/cupy/tests/cupy_tests/core_tests/test_fusion.py", line 19, in res
18:32:42     return g(*val)
18:32:42   File "/work/cupy/cupy/core/fusion.py", line 629, in __call__
18:32:42     return self.func(*args)
18:32:42   File "/work/cupy/tests/cupy_tests/core_tests/test_fusion.py", line 16, in g
18:32:42     return f(*args)
18:32:42   File "/work/cupy/cupy/core/fusion.py", line 690, in __call__
18:32:42     return self._numpy_op(*args, **kwargs)
18:32:42 TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
18:32:42 
18:32:42 -------------------- >> begin captured stdout << ---------------------
18:32:42 dtype is <type 'numpy.bool_'>
```

```
18:35:55 Document: reference/difference
18:35:55 ------------------------------
18:35:55 **********************************************************************
18:35:55 File "reference/difference.rst", line ?, in default
18:35:55 Failed example:
18:35:55     np.array([True]) ** 2
18:35:55 Expected:
18:35:55     array([ True], dtype=bool)
18:35:55 Got:
18:35:55     array([1], dtype=int8)
18:35:55 **********************************************************************
18:35:55 1 items had failures:
18:35:55    1 of  21 in default
18:35:55 21 tests in 1 items.
18:35:55 20 passed and 1 failed.
18:35:55 ***Test Failed*** 1 failures.
```

**Comment by unnonouno** [comment]
Wow. boolean exp bug was fixed!!

**Comment by unnonouno** [comment]
This issue is not solved yet. We need to fix behavior of negative operator for boolean array.

**Comment by niboshi** [comment]
OK, sorry.

**Comment by beam2d** [comment]
Note that the above PR has been reverted and is now retrying at #347.
