### ISSUE TITLE
Some cupy functions does not check device integrity

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#1389]
Currently Elementwise kernels asserts that argument arrays are on the current device.
On the other hand, some functions in CuPy like `ndarray.dot` does not check it.
Is it a responsibility of users to guarantee that arrays are on the current device?

```py
import cupy

# x is on device 0
x = cupy.ones((10,10), dtype=cupy.float32)

# OK
y = x.dot(x)
print(y)

# FAIL
with cupy.cuda.Device(1):
   y = x.dot(x)
print(y)  # error raised from here
```

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1660, in cupy.core.core.ndarray.__str__
  File "cupy/core/core.pyx", line 1707, in cupy.core.core.ndarray.get
  File "cupy/cuda/memory.pyx", line 372, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy/cuda/runtime.pyx", line 255, in cupy.cuda.runtime.memcpy
  File "cupy/cuda/runtime.pyx", line 135, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

Related to #4144.

**Comment by kmaehashi** [comment]
Related to #828
