### ISSUE TITLE
Inconsistent behaviour of cupy.random with size option

### ISSUE THREAD

**Issue by Hakuyume** [cupy/cupy#1427]
`cupy.random.randint` ignores `size` option if it is a `cupy.ndarray`. `cupy.random.choice` has the same problem.

numpy: 1.14.5
cupy: 4.2.0

```python
import numpy as np
import cupy

np.random.randint(10, size=np.array(3))  # array([5, 6, 7])
cupy.random.randint(10, size=cupy.array(3))  # array(1)

np.random.choice(np.arange(10), size=np.array(3))  # array([0, 7, 4])
cupy.random.choice(cupy.arange(10), size=cupy.array(3))  # array(9)
```

**Comment by toslunar** [comment]
Even we don't allow `size` of type `cupy.ndarray` at the moment, such attempt should fail.
```
>>> numpy.random.randint(10, size=numpy.array([3]))
array([3, 0, 7])
>>> cupy.random.randint(10, size=cupy.array([3]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/random/sample.py", line 112, in randint
    return rs.randint(low, high, size, dtype)
  File "cupy/random/generator.py", line 473, in randint
    x = self.interval(diff, size).astype(dtype, copy=False)
  File "cupy/random/generator.py", line 210, in interval
    sample = cupy.empty((n,), dtype=dtype)
  File "cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype=dtype, order=order)
  File "cupy/core/core.pyx", line 105, in cupy.core.core.ndarray.__init__
    self._shape = internal.get_size(shape)
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_Py_ssize_t
TypeError: 'cupy.core.core.ndarray' object cannot be interpreted as an index
```
