### ISSUE TITLE
Some cupy.random distribution does not support `size=None`

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#1644]
`size=None` is different from `size=()`.
```
>>> np.random.uniform([2], [[3]])
array([[2.63150331]])
>>> np.random.uniform([2], [[3]], size=())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 1317, in mtrand.RandomState.uniform
  File "mtrand.pyx", line 267, in mtrand.cont2_array
ValueError: size is not compatible with inputs
>>> 
>>> cupy.random.uniform([2], [[3]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/random/distributions.py", line 454, in uniform
    return rs.uniform(low, high, size=size, dtype=dtype)
  File "/home/kataoka/cupy/cupy/random/generator.py", line 484, in uniform
    return RandomState._scale_kernel(low, high, rand)
  File "cupy/core/_kernel.pyx", line 532, in cupy.core._kernel.ElementwiseKernel.__call__
    out_args = _get_out_args_with_params(
  File "cupy/core/_kernel.pyx", line 368, in cupy.core._kernel._get_out_args_with_params
    raise ValueError('Out shape is mismatched')
ValueError: Out shape is mismatched
```

**Comment by kmaehashi** [comment]
I guess not all fixed yet? @asi1024

**Comment by andfoy** [comment]
@kmaehashi @asi1024, do you know which distributions are still not supporting `size=None` properly?

**Comment by andfoy** [comment]
After a little bit of inspection using the following [script](https://gist.github.com/andfoy/2b52426b4e0bddcb4c264b1f1e9eb4b7), the status regarding the broadcasting support when `size=None`. Checked means that the generator supports array broadcasting on its parameters, otherwise not.

## Valid generators
- [x] `beta`
- [x] `binomial`
- [x] `chisquare`
- [x] `dirichlet`
- [x] `exponential`
- [x] `f`
- [x] `gamma`
- [x] `geometric`
- [x] `gumbel`
- [x] `hypergeometric`
- [x] `laplace`
- [x] `logistic`
- [x] `lognormal`
- [x] `logseries`
- [x] `negative_binomial`
- [x] `noncentral_chisquare`
- [x] `noncentral_f`
- [x] `normal`
- [x] `pareto`
- [x] `poisson`
- [x] `power`
- [x] `rayleigh`
- [x] `standard_gamma`
- [x] `standard_t`
- [x] `triangular`
- [x] `uniform`
- [x] `vonmises`
- [x] `wald`
- [x] `zipf`

## Potentially invalid or restricted generators
- [x] `multinomial` → Both CuPy and NumPy documentation state that it operates over 1D values only.
- [x] `multivariate_normal` → All arguments need to be 2D
- [ ] `randint` → CuPy only supports int as parameters for `low` and `high`, whereas NumPy allows for arrays
- [ ] `random_integers` → Deprecated in NumPy, CuPy only supports int ranges.
- [ ] `weibull` → Does not support array input

**Comment by andfoy** [comment]
@kmaehashi @asi1024 I had a question regarding `randint`, the current implementation makes use of `_interval`, which states that `generates multiple integers independently sampled uniformly from [0, mx]`. What would be the difference from using `uniform`? 

I'm asking this since now `uniform` supports array inputs, and since it seems that `randint` samples random uniform integers, wouldn't be a good idea to recycle the `uniform` implementation?

**Comment by andfoy** [comment]
Nevermind, `uniform` only supports floating types
