### ISSUE TITLE
Remote debugg error

### ISSUE THREAD

**Issue by zhoulukuan** [cupy/cupy#1666]
I encountered a problem when I debug the code remotely. 
In the server, the project could run successfully. However, when I debug the code remotely in the server with Pycharm and set the same  python interpreter , it tells me:
```
ssh://zlk@XX.XXX.X.XXX:XX/home/zlk/anaconda3/bin/python3.6m -u /home/zlk/simple-faster-rcnn-pytorch/train.py train --env='fasterrcnn-caffe' --plot-every=100 --caffe-pretrain
Traceback (most recent call last):
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zlk/simple-faster-rcnn-pytorch/train.py", line 3, in <module>
    import cupy as cp
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/zlk/anaconda3/lib/python3.6/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs-cupy.chainer.org/en/latest/install.html

original error: libcublas.so.9.0: cannot open shared object file: No such file or directory

Process finished with exit code 1
```
However, the program can run successfully if I use MobaXterm to access the server directly. Related command such as 'import cupy' can run successfully too. If I use ` find /home/zlk -name libcublas.so.9.0
` to find related file, it seems to be ok as well.
I am sure they are using the same python interpreter. Can anyone tell me why this is?

**Comment by fiarabbit** [comment]
PyCharm overrides the environment variable LD_LIBRARY_PATH, which specifies the location (path) of `.so` files.
Therefore, the solution is set the proper LD_LIBRART_PATH on your PyCharm, as given in [this stackoverflow](https://stackoverflow.com/questions/33812902/pycharm-cannot-find-library).

**Comment by zhoulukuan** [comment]
@fiarabbit Thank you very much. I try to edit Run/Debug configurations and add PATH/CUDA_PATH/LD_LIBRARY_PATH to environment variables, it seems to be ok now.
