### ISSUE TITLE
CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by psychopa4** [cupy/cupy#1691]
I'm trying to build a CNN on Chainer, which uses Cupy for calculating on GPU.
It seems that Cudnn is not installed correctly, but I can run Tensorflow, Keras and Pytorch successfully on my PC, while failing to run Chainer with Cupy.
I tried all kinds of way from  [Cupy Installation Guide](https://docs-cupy.chainer.org/en/stable/install.html?highlight=cudnn#installation-guide), but failed with same mistake.
Can anybody solve this issue? Thanks!
- Conditions
Chainer version 4.5.0
CuPy version 4.5.0
OS/Platform Ubantu 16.04
CUDA/cuDNN version 8.0.61/5.1.10

```
Traceback (most recent call last):
  File "main.py", line 207, in <module>
    train()
  File "main.py", line 140, in train
    sr = generator(lr)
  File "main.py", line 86, in __call__
    x0 = self.first(x)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/links/connection/convolution_2d.py", line 175, in __call__
    groups=self.groups)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 582, in convolution_2d
    y, = fnode.apply(args)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/function_node.py", line 258, in apply
    outputs = self.forward(in_data)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/function_node.py", line 367, in forward
    return self.forward_gpu(inputs)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 161, in forward_gpu
    return self._forward_cudnn(x, W, b, y)
  File "/root/anaconda3/envs/tf/lib/python3.6/site-packages/chainer/functions/connection/convolution_2d.py", line 234, in _forward_cudnn
    auto_tune=auto_tune, tensor_core=tensor_core)
  File "cupy/cudnn.pyx", line 820, in cupy.cudnn.convolution_forward
  File "cupy/cudnn.pyx", line 590, in cupy.cudnn._get_algorithm_fwd
  File "cupy/cuda/cudnn.pyx", line 807, in cupy.cuda.cudnn.getConvolutionForwardAlgorithm_v6
  File "cupy/cuda/cudnn.pyx", line 514, in cupy.cuda.cudnn.check_status
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM
```

**Comment by kmaehashi** [comment]
* Are you using wheel (`pip install cupy-cuda80`), or installing from source? Note that wheels includes cuDNN 7.x.
* Generally `CUDNN_STATUS_BAD_PARAM` indicates that the argument being passed to cuDNN is wrong. Could you share the details of `first` layer and shape/dtype of `x`?

>   File "main.py", line 86, in __call__
>    x0 = self.first(x)

**Comment by kmaehashi** [comment]
Continue discussion in https://github.com/chainer/chainer/issues/5442.
