### ISSUE TITLE
Illegal memory access in `cp.sum`

### ISSUE THREAD

**Issue by gdgrant** [cupy/cupy#1766]
I'm encountering an error where CuPy fails to de-allocate GPU memory after processing a sum operation after a reshape operation.  However, this only occurs if a certain memory threshold is passed.  In the code example, I start with two arrays, reshape them, and then perform the cp.sum operation.  If n is set to <800, the error does not occur, but if n>=1000 the errors occurs (up to failure to allocate due to arrays being too large).  A simple matrix multiplication on the starting 'a' and 'b' to get 'c' does not produce this error.

```
import cupy as cp

n = 1000
a = cp.ones([n,256,100], dtype=cp.float32)
b = cp.ones([n,100,100], dtype=cp.float32)

a = cp.reshape(a, [n,256,100,1])
b = cp.reshape(b, [n,1,100,100])
c = cp.sum(a*b, axis=-2)

print('Complete.')
```

When the code is run and the error occurs, the traceback is as follows.
```
Complete.
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

I have tested this in CuPy 4.5.0 and CuPy 5.0.0.  I am using NVIDIA Driver Version 390.48 and CUDA 9.0, with the appropriate Cupy installation.

**Comment by fiarabbit** [comment]
I could reproduce the error.

```hoge.py
>>> chainer.print_runtime_info()
Platform: Linux-4.4.0-135-generic-x86_64-with-Ubuntu-16.04-xenial
Chainer: 5.0.0rc1
NumPy: 1.15.1
CuPy:
  CuPy Version          : 6.0.0a1
  CUDA Root             : /usr/local/cuda
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10000
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7300
  cuDNN Version         : 7300
  NCCL Build Version    : 2213
>>> import cupy as cp
>>>
>>> n = 1000
>>> a = cp.ones([n,256,100], dtype=cp.float32)
>>> b = cp.ones([n,100,100], dtype=cp.float32)
>>>
>>> a = cp.reshape(a, [n,256,100,1])
>>> b = cp.reshape(b, [n,1,100,100])
>>> c = cp.sum(a*b, axis=-2)
>>>
>>> print('Complete.')
Complete.
>>> ^D
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 192, in cupy.cuda.driver.moduleUnload
  File "cupy/cuda/driver.pyx", line 81, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by kmaehashi** [comment]
Thanks for reporting, I could reproduce this issue and will investigate on it.

**Comment by kmaehashi** [comment]
#1774 should fix this issue.
