### ISSUE TITLE
Out of memory error with Chainer-5.0-Cupy-5.0-Python2.7 

### ISSUE THREAD

**Issue by surajkota** [cupy/cupy#1772]
Hi,

I am trying to run synthetic data training with Chainer on a 8 GPU machine. The [scripts](https://github.com/surajkota/deep-learning-benchmark-mirror/blob/master/chainer_examples/imagenet/train_imagenet_data_parallel.py) I am running are modification of [imagenet example scripts from chainers official repository](https://github.com/chainer/chainer/tree/v5/examples/imagenet) to run synthetic data.

For, python2.7
Training processes errors out with **out of memory error for more than 16 batch size** and below is the stack trace

Python3.6
I am able to go upto **128** batch size with same setup

Same scripts run fine for Chainer==4.5 for both python2.7 and python3.6 upto 128 batch size
Note that running mnist passes but resnet fails for batch size more than 16 within first few epochs. 

**Stack trace:**

```
Epoch: [3] 	 Batch_speed: 3158.273 samples/sec
Epoch: [3] 	 Speed: 3099.142 samples/sec 	 Time cost=0.323
Exception in main training loop: out of memory to allocate 205520896 bytes (total 16068929536 bytes)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/trainer.py", line 315, in run
    update()
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/standard_updater.py", line 165, in update
    self.update_core()
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 237, in update_core
    loss = _calc_loss(self._master, batch)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 271, in _calc_loss
    return model(*in_arrays)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 101, in forward
    h = self.res2(h)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 78, in forward
    x = f(x)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/chainer/examples/imagenet/resnet50.py", line 36, in forward
    h1 = self.bn3(self.conv3(h1))
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/link.py", line 242, in __call__
    out = forward(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/links/normalization/batch_normalization.py", line 299, in forward
    running_var=self.avg_var, decay=decay, axis=self.axis)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 832, in batch_normalization
    axis).apply((x, gamma, beta))[0]
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
    outputs = self.forward(in_data)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/chainer/functions/normalization/batch_normalization.py", line 204, in forward
    y = cuda.cupy.empty_like(x)
  File "/home/ubuntu/anaconda3/envs/chainer_p271/lib/python2.7/site-packages/cupy/creation/basic.py", line 42, in empty_like
    return cupy.ndarray(a.shape, dtype)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1085, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 899, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 920, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 694, in cupy.cuda.memory._try_malloc

```

I checked the output of nvidia-smi and it increases for a while and then some of the processes crash making GPU utilization 0 for the GPUs which it was using. Other processes keep running and GPU utilization also looks good

For example if only Process _Worker-1 crashed the output would look like this:
```
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:17.0 Off |                    0 |
| N/A   45C    P0    56W / 300W |  16045MiB / 16160MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:18.0 Off |                    0 |
| N/A   45C    P0    67W / 300W |  15795MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:19.0 Off |                    0 |
| N/A   46C    P0    67W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1A.0 Off |                    0 |
| N/A   51C    P0    73W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   51C    P0    68W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   49C    P0    71W / 300W |  15771MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   45C    P0    71W / 300W |  15575MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   50C    P0    71W / 300W |  15575MiB / 16160MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      9516      C   python                                     16034MiB |
|    1      9582      C   python                                     15784MiB |
|    2      9583      C   python                                     15760MiB |
|    3      9584      C   python                                     15760MiB |
|    4      9585      C   python                                     15760MiB |
|    5      9586      C   python                                     15760MiB |
|    6      9587      C   python                                     15564MiB |
|    7      9588      C   python                                     15564MiB |
+-----------------------------------------------------------------------------+
```

The program becomes like a zombiee process after this and I need to find the pid to kill it.

**Replication steps**

```
pip install chainer==5.0.0
pip install cupy=5.0.0
```

```
git clone https://github.com/surajkota/deep-learning-benchmark-mirror
python train_imagenet_data_parallel.py --arch resnet50 --dataset synthetic --epoch 30 --loaderjob 30 --samples 10000 --batchsize 128 ~/ ~/ -g 0 1 2 3 4 5 6 7
```

**Instance type:** 
AWS EC2 p3.16xlarge 
it has 8 NVIDIA Tesla V100 GPUs, 64 Intel Xeon E5-2686 v4 (Broadwell) processors, 488 GB RAM

CPU info:
```
processor	: 61
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
stepping	: 1
microcode	: 0xb00002a
cpu MHz		: 1514.496
cache size	: 46080 KB
physical id	: 1
siblings	: 32
core id		: 13
cpu cores	: 16
apicid		: 91
initial apicid	: 91
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq monitor est ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt ida
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips	: 4600.12
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

```

Let me know if more information is needed

TIA

**Comment by fiarabbit** [comment]
This is cupy's repository, so you'd better ask it at  [Chainer's repository](https://github.com/chainer/chainer/issues).
 
In my opinion, t is the regression in Chainer (not in cupy), because you can run your code w/ Chainer==4.5 but cannot w/ Chainer==5.0,.

**Comment by surajkota** [comment]
Sure I can ask on Chainer's repo too.

But, when I was using Chainer 4.5, CuPy was also 4.5

**Comment by kmaehashi** [comment]
Let us continue discussion in https://github.com/chainer/chainer/issues/5621.
