### ISSUE TITLE
Regression: Many operations fail

### ISSUE THREAD

**Issue by themightyoarfish** [cupy/cupy#1813]
* versions:
CuPy Version          : 6.0.0a1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 9000
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7201
cuDNN Version         : 7201
NCCL Build Version    : 2213
* Code to reproduce:
```
import cupy as np
a = np.random.rand(10, 10, 10, 10)
```
* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "tmp.py", line 2, in <module>
    array = np.random.rand(10, 10, 10, 10)
  File "/home/share/miniconda3/envs/torch/lib/python3.6/site-packages/cupy-6.0.0a1-py3.6-linux-x86_64.egg/cupy/random/sample.py", line 46, in rand
    return random_sample(size=size, dtype=dtype)
  File "/home/share/miniconda3/envs/torch/lib/python3.6/site-packages/cupy-6.0.0a1-py3.6-linux-x86_64.egg/cupy/random/sample.py", line 158, in random_sample
    return rs.random_sample(size=size, dtype=dtype)
  File "/home/share/miniconda3/envs/torch/lib/python3.6/site-packages/cupy-6.0.0a1-py3.6-linux-x86_64.egg/cupy/random/generator.py", line 515, in random_sample
    RandomState._mod1_kernel(out)
  File "cupy/core/_kernel.pyx", line 569, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/cuda/function.pyx", line 161, in cupy.cuda.function.Function.linear_launch
  File "cupy/cuda/function.pyx", line 125, in cupy.cuda.function._launch
  File "cupy/cuda/function.pyx", line 79, in cupy.cuda.function._pointer
  File "cupy/core/core.pyx", line 1925, in cupy.core.core.ndarray._set_shape_and_strides
ValueError: len(shape) != len(strides)
```

**Comment by themightyoarfish** [comment]
The same happens in other cases, e.g. when converting to complex. So I assume it's something with my setup.

```
import cupy as np
array = np.asarray([10, 10, 10, 10])
array_complex = array.astype('complex64')
```

**Comment by themightyoarfish** [comment]
I'm running a clean build and will check if the problem persists.

**Comment by themightyoarfish** [comment]
Building from scratch seems to solve the issue.
