### ISSUE TITLE
2 errors detected in the compilation of "/tmp/tmpgX1d3K/kern.cu"

### ISSUE THREAD

**Issue by SongweiGe** [cupy/cupy#1901]
Hi I'm trying to run the codes from [neural_renderer](https://github.com/hiroharu-kato/neural_renderer). But got following errors:

Traceback (most recent call last):
File "./examples/example1.py", line 66, in
run()
File "./examples/example1.py", line 52, in run
images = renderer.render(vertices, faces, textures) # [batch_size, RGB, image_size, image_size]
File "build/bdist.linux-x86_64/egg/neural_renderer/renderer.py", line 90, in render
File "build/bdist.linux-x86_64/egg/neural_renderer/lighting.py", line 40, in lighting
File "build/bdist.linux-x86_64/egg/neural_renderer/cross.py", line 59, in cross
File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 235, in call
ret = node.apply(inputs)
File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function_node.py", line 263, in apply
outputs = self.forward(in_data)
File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 135, in forward
return self._function.forward(inputs)
File "cmr/venv_cmr/lib/python2.7/site-packages/chainer/function.py", line 342, in forward
return self.forward_gpu(inputs)
File "build/bdist.linux-x86_64/egg/neural_renderer/cross.py", line 39, in forward_gpu
File "cupy/core/_kernel.pyx", line 558, in cupy.core._kernel.ElementwiseKernel.call
File "cupy/core/_kernel.pyx", line 579, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
File "cupy/core/_kernel.pyx", line 392, in cupy.core._kernel._get_elementwise_kernel
File "cupy/core/_kernel.pyx", line 26, in cupy.core._kernel._get_simple_elementwise_kernel
File "cupy/core/_kernel.pyx", line 46, in cupy.core._kernel._get_simple_elementwise_kernel
File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
ptx = compile_using_nvrtc(source, options, arch)
File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
ptx = prog.compile(options)
File "cmr/venv_cmr/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 245, in compile
raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: cmr/venv_cmr/lib/python2.7/site-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]"
/tmp/tmpgX1d3K/kern.cu(10): here

/tmp/tmpgX1d3K/kern.cu(13): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"

/tmp/tmpgX1d3K/kern.cu(14): error: a value of type "const float *" cannot be used to initialize an entity of type "float *"

2 errors detected in the compilation of "/tmp/tmpgX1d3K/kern.cu".

Here are my configurations:
CuPy Version          : 5.1.0
CUDA Root             : /share/apps/cuda-9.0
CUDA Build Version    : 9000
CUDA Driver Version   : 9010
CUDA Runtime Version  : 9000
cuDNN Build Version   : 7005
cuDNN Version         : 7005
NCCL Build Version    : None

I thought it was CUDA detection problem. I've tried reset $CUDA_PATH and $LD_LIBRARY_PATH, also reinstall the cupy-cuda90 version, but none helped. Could you give me some soggestions? Thanks a lot!

**Comment by SongweiGe** [comment]
I think I got the right configuration of CUDA in the beginning since cupy works normally in some simple tests such as a+b or chainer.functions.concat((a, b), axis=0). But it fails when I used the other's codes. That's so weird.

**Comment by SongweiGe** [comment]
Just found a weird place: the CUDA Runtime Version was automatically changed to 8000 during running codes from neural_renderer.

**Comment by SongweiGe** [comment]
Found the reason: my torch used CUDA8.0

**Comment by sunshineatnoon** [comment]
Hi, I met the same problem, my cuda version is 9.0, how did you solve this?

**Comment by kmaehashi** [comment]
@sunshineatnoon Please check this: https://docs-cupy.chainer.org/en/latest/install.html#cupy-always-raises-cupy-cuda-compiler-compileexception
