### ISSUE TITLE
UserWarning: Shared memory size is too small. Please set shared_mem option for MultiprocessIterator. 

### ISSUE THREAD

**Issue by zhangxiaodi** [cupy/cupy#1948]
Expect shared memory size: 131072 bytes. Actual shared memory size: 98304 bytes.   UserWarning)

I use p100，16G memory！ 

the error information is follow.
Exception in main training loop: Unsupported dtype object
Traceback (most recent call last):
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
    x_real, y_real = self.get_batch(xp)
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
    print(type(xp.asarray(x)))
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    main()
  File "train.py", line 132, in main
    trainer.run()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 94, in update_core
    x_real, y_real = self.get_batch(xp)
  File "/home/user012/GAN_poster/sngan_projection/updater.py", line 73, in get_batch
    print(type(xp.asarray(x)))
  File "/home/user012/anaconda3/envs/GAN_znb/lib/python3.6/site-packages/cupy/creation/from_data.py", line 61, in asarray
    return core.array(a, dtype, False)
  File "cupy/core/core.pyx", line 2017, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2048, in cupy.core.core.array
ValueError: Unsupported dtype object

what should i do, i have no idea to solve it!

**Comment by fiarabbit** [comment]
aAccording to the [contribution guide](https://docs-cupy.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow with a cupy tag.

```
Warning

If you have a question on usages of CuPy, it is highly recommended to send a post to CuPy User
Group instead of the issue tracker. The issue tracker is not a place to share knowledge on practices.
We may suggest these places and immediately close how-to question issues.
```

**Comment by fiarabbit** [comment]
And also, this repository is `cupy`, not `chainer`. The question is strongly related to `chainer`, so it should be raised to SO with `chainer` tag.

**Comment by fiarabbit** [comment]
I think the source of the error is not `cupy` but you passed `chainer.Variable` to a function whose input argument should be `np.ndarray`.

**Comment by fiarabbit** [comment]
(maybe) moved to chainer/chainer#5996.

**Comment by yfchen97** [comment]
I get the same question and do not konw how to solve it. Could you give me some advices?
