### ISSUE TITLE
`__eq__` to does not handle common non-ndarray types

### ISSUE THREAD

**Issue by hvy** [cupy/cupy#1989]
A `TypeError` is raised when comparing ndarrays with unsupported dtypes for comparison which is inconsistent with NumPy.

```bash
In [7]: numpy.array([1]) == None
Out[7]: array([False])

In [8]: cupy.array([1]) == None
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-0e157d55df3d> in <module>()
----> 1 cupy.array([1]) == None
cupy/core/core.pyx in cupy.core.core.ndarray.__richcmp__()
cupy/core/_kernel.pyx in cupy.core._kernel.ufunc.__call__()
cupy/core/_kernel.pyx in cupy.core._kernel._preprocess_args()
TypeError: Unsupported type <class 'NoneType'>
```

**Comment by toslunar** [comment]
I don't think it's beneficial to handle this until CuPy supports arrays of `object`s.
```
>>> numpy.array(None)
array(None, dtype=object)
>>> cupy.array(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupy/creation/from_data.py", line 45, in array
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1666, in cupy.core.core.array
  File "cupy/core/core.pyx", line 1701, in cupy.core.core.array
ValueError: Unsupported dtype object
```
