### ISSUE TITLE
Creating a CuPy array causes CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by pentschev** [cupy/cupy#2044]
After https://github.com/cupy/cupy/pull/2022, creating a CuPy array causes a CUDA_ERROR_INVALID_VALUE error. If I revert that merge in master, everything works again.

Sample and traceback follow.

```python
import cupy

a = cupy.ones(1000)
```

```python
Traceback (most recent call last):
  File "invarg_cupy.py", line 3, in <module>
    a = cupy.ones(1000)
  File "/home/nfs/pentschev/.local/lib/python3.5/site-packages/cupy/creation/basic.py", line 133, in ones
    a.fill(1)
  File "cupy/core/core.pyx", line 474, in cupy.core.core.ndarray.fill
  File "cupy/core/core.pyx", line 492, in cupy.core.core.ndarray.fill
  File "cupy/core/_kernel.pyx", line 572, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy/cuda/function.pyx", line 162, in cupy.cuda.function.Function.linear_launch
  File "cupy/cuda/function.pyx", line 131, in cupy.cuda.function._launch
  File "cupy/cuda/driver.pyx", line 229, in cupy.cuda.driver.launchKernel
  File "cupy/cuda/driver.pyx", line 82, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
````

Could someone tell me if I'm expected to do anything differently after that PR? I'm also happy to help track down the source of the issue.

**Comment by niboshi** [comment]
As you're building from source, the remnants from the previous build may be causing the problem.
How about cleaning up the repository by the following command?
```
$ git clean -ffdx
```

**Comment by pentschev** [comment]
@niboshi thanks for the help. Indeed, you were right. I wasn't aware of how many remnants were still there, I even made sure to clean up my build directory before building, but didn't realize how much more there was elsewhere.
