### ISSUE TITLE
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch) error

### ISSUE THREAD

**Issue by BornInWater** [cupy/cupy#2087]
CuPy version: 2.3.0

OS: Ubuntu 16.04

CUDA Version: 8.0

GPU: Tesla V100
cuDNN:
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 +CUDNN_PATCHLEVEL)

Code: while running python examples/example1.py in the following github repo: [Neural Mesh Renderer](https://github.com/hiroharu-kato/neural_renderer)
Error:
Traceback (most recent call last):
  File "examples/example1.py", line 66, in <module>
    run()
  File "examples/example1.py", line 52, in run
    images = renderer.render(vertices, faces, textures)  # [batch_size, RGB, image_size, image_size]
  File "build/bdist.linux-x86_64/egg/neural_renderer/renderer.py", line 78, in render
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/chainer/functions/array/concat.py", line 90, in concat
    y, = Concat(axis).apply(xs)
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/chainer/function_node.py", line 245, in apply
    outputs = self.forward(in_data)
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/chainer/functions/array/concat.py", line 44, in forward
    return xp.concatenate(xs, self.axis),
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/cupy/manipulation/join.py", line 49, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/core.pyx", line 2439, in cupy.core.core.concatenate_method
  File "cupy/core/core.pyx", line 2482, in cupy.core.core.concatenate_method
  File "cupy/core/core.pyx", line 2533, in cupy.core.core.concatenate
  File "cupy/core/core.pyx", line 1630, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/core.pyx", line 3101, in cupy.core.core._scatter_op
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/home/ubuntu/mnt/Work/CMR_TESTING/cmr/cmr_venv/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

**Comment by fiarabbit** [comment]
I (partially) succeeded to reproduce the situation. BTW, why is your cupy is so old version? 

```spec.sh
#CUDA8.0 and cudnn6.0.2
$ nvidia-smi
Wed Mar  6 12:35:40 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:02:00.0 Off |                  N/A |
| 29%   34C    P8    15W / 250W |      1MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:81:00.0 Off |                  N/A |
| 29%   36C    P8     8W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ python --version
Python 2.7.12

$ pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
cupy==2.3.0
Cython==0.29.6
fastrlock==0.4
numpy==1.16.2
pkg-resources==0.0.0
six==1.12.0

$ python -c "import cupy; cupy.arange(10)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hashimoto/python27-cuda80-cudnn602/local/lib/python2.7/site-packages/cupy/creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/elementwise.pxi", line 823, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 622, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/home/hashimoto/python27-cuda80-cudnn602/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/home/hashimoto/python27-cuda80-cudnn602/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/home/hashimoto/python27-cuda80-cudnn602/local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: failed to load builtins
```

Also, it should be noted that this error occurred for python35.

**Comment by BornInWater** [comment]
The github repo that I am trying to work with requires chainer 3.3.0 which needs cupy version 2.3.0
@fiarabbit Any solution?

**Comment by fiarabbit** [comment]
@BornInWater 
At least, Neural Mesh Renderer seems to be compatible to Chainer v5.0.0 w/ Cupy v5.0.0. I checked that when using `pip install cupy-cuda80==5.0.0` and set `LD_LIBRARY_PATH` correctly, the bug I confirmed did not happen. Therefore, it is possible you use `cupy-cuda80` for Neural Mesh Renderer.

**Comment by fiarabbit** [comment]
@BornInWater 
I found the solution for my case. Just setting `export LD_LIBRARY_PATH=/path/to/cuda/lib64:/path/to/cudnn/lib64:$LD_LIBRARY_PATH` solved my situation. It seems that when `cupy` is compiled with local CUDA, some functions work well because it is linked to the static library, but other functions fails because it needs to be compiled on the runtime. I hope this may help you.

**Comment by BornInWater** [comment]
@fiarabbit How do I find cudnn path? I am working on an AWS instance, so for accessing different versions of CUDA and their paths, I use this link: [AWS CUDA](https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-base.html).

**Comment by fiarabbit** [comment]
@BornInWater 
According to the [contribution guide](https://docs-cupy.chainer.org/en/stable/contribution.html), any general question is preferred to be raised at the StackOverflow.

```
Warning

If you have a question on usages of CuPy, it is highly recommended to send a post to CuPy User
Group instead of the issue tracker. The issue tracker is not a place to share knowledge on practices.
We may suggest these places and immediately close how-to question issues.
```

In addition, that is not related to `cupy`, that is just an issue of AWS and/or cudnn. Generally, cudnn library file is installed to `/usr/lib/x86_64-linux-gnu/libcudnn.so`, but it depends on your environment.
