### ISSUE TITLE
cupy.cuda.memory.OutOfMemoryError

### ISSUE THREAD

**Issue by eawer** [cupy/cupy#2098]
Hello! I'm using:
```
CuPy Version          : 5.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7402
cuDNN Version         : 7402
NCCL Build Version    : 2307
NCCL Runtime Version  : 2307
Ubuntu 16.04x64
GeForce 1060 3Gb
Python 3.7
spaCy 2.0.18
```
I'm trying to load a pretty small text file (5k lines, 270kb, one sentence per line), using spacy in GPU mode and for some reason I'm seeing  this:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    doc = nlp(open('headlines.txt').read())
  File "py37/lib/python3.7/site-packages/spacy/language.py", line 346, in __call__
    doc = proc(doc)
  File "nn_parser.pyx", line 338, in spacy.syntax.nn_parser.Parser.__call__
  File "nn_parser.pyx", line 401, in spacy.syntax.nn_parser.Parser.parse_batch
  File "nn_parser.pyx", line 730, in spacy.syntax.nn_parser.Parser.get_batch_model
  File "nn_parser.pyx", line 85, in spacy.syntax.nn_parser.precompute_hiddens.__init__
  File "py37/lib/python3.7/site-packages/spacy/_ml.py", line 149, in begin_update
    self.W.reshape((self.nF*self.nO*self.nP, self.nI)).T)
  File "py37/lib/python3.7/site-packages/cupy/linalg/product.py", line 35, in dot
    return a.dot(b, out)
  File "cupy/core/core.pyx", line 1791, in cupy.core.core.ndarray.dot
  File "cupy/core/core.pyx", line 3810, in cupy.core.core.dot
  File "cupy/core/core.pyx", line 4157, in cupy.core.core.tensordot_core
  File "cupy/core/core.pyx", line 151, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1065, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1086, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 900, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 921, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 695, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 1144041984 bytes (total 2958865408 bytes)
```

I believe 270kb is way to small to cause OOM, so can you please tell if it's a bug or am I doing something wrong?

UPD: actually, it throws even with ~90kb file (1800 lines) with:
`cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 411944448 bytes (total 2128117760 bytes)`

**Comment by gwtnb** [comment]
> cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 1144041984 bytes

It seems that spaCy attempts to allocate about 1GB, so it is not surprising that memory allocation fail on GPU with 3GB RAM.

**Comment by eawer** [comment]
@gwtnb I've added an update `cupy.cuda.memory.OutOfMemoryError: out of memory to allocate 411944448 bytes (total 2128117760 bytes)` where the error is thrown while trying to allocate 410mb. Before the script starts, `nvidia-smi` shows 727mb out of 3GB is used. Isn't ~400mb in such conditions too little to fail?

**Comment by gwtnb** [comment]
Thank you for the update.

> Isn't ~400mb in such conditions too little to fail?

If the required memory size is only 400MB, too little. But usually such size is larger than the size for one memory allocation. `total 2128117760 bytes` says that it is attempted to allocate about 2.1GB memory in total. 2.1GB plus 772MB is comparable to 3GB.

**Comment by eawer** [comment]
so the problem lies outside the cupy, in spaCy?

**Comment by gwtnb** [comment]
One of the cause may be [calling `reshape`](https://github.com/explosion/spaCy/blob/40d33261d62fb5faabd7288843e46f935fad14b4/spacy/_ml.py#L149). `reshape` allocates memory in some cases.
