### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by harshalcse** [cupy/cupy#2106]
I am using AWS p3 type 2xlarge instance type with following GPU details:
root@awsml04:~# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
![nvidia-smi](https://user-images.githubusercontent.com/5838252/54536986-ba014900-49b7-11e9-9231-a21dcc85b207.PNG)

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version
    cupy==5.3.0
  - OS/Platform
   Ubuntu 16.04 x86_64
  - CUDA version 
    CUDA 9.0
  - cuDNN version: 7.3.1
  -NCCL version:  2.3.5 
* Code to reproduce
* Error messages, stack traces, or logs : 

```
Exception in main training loop: cudaErrorNoDevice: no CUDA-capable device is detected
Traceback (most recent call last):
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.see-master/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 195, in update_core
    self.setup_workers()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 186, in setup_workers
    with cuda.Device(self._devices[0]):
  File "cupy/cuda/device.pyx", line 106, in cupy.cuda.device.Device.__enter__
  File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 136, in cupy.cuda.runtime.check_status
Will finalize trainer extensions and updater before reraising the exception.
Traceback (most recent call last):
  File "chainer/train_svhn.py", line 258, in <module>
    trainer.run()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 313, in run
    six.reraise(*sys.exc_info())
  File "/usr/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 302, in run
    entry.extension(self)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/.see-master/lib/python3.5/site-packages/chainer/reporter.py", line 98, in scope
    yield
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/trainer.py", line 299, in run
    update()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updater.py", line 223, in update
    self.update_core()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 195, in update_core
    self.setup_workers()
  File "/root/.see-master/lib/python3.5/site-packages/chainer/training/updaters/multiprocess_parallel_updater.py", line 186, in setup_workers
    with cuda.Device(self._devices[0]):
  File "cupy/cuda/device.pyx", line 106, in cupy.cuda.device.Device.__enter__
  File "cupy/cuda/runtime.pyx", line 164, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 136, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected

```

**Comment by kmaehashi** [comment]
* Please paste the output of `python -c 'import cupy; cupy.show_config()'`.
* Could you try using `pip install cupy-cuda90` instead of `pip install cupy`?

**Comment by kmaehashi** [comment]
I've posted the response to the list. Let's continue discussion there.
https://groups.google.com/d/msg/cupy/0jJ-Gc39gTQ/lQmoLrC6CwAJ

**Comment by harshalcse** [comment]
>>> import cupy
>>> cupy.show_config()
CuPy Version          : 5.3.0
CUDA Root             : /usr/local/cuda/bin:
CUDA Build Version    : 9000
CUDA Driver Version   : 9000
CUDA Runtime Version  : CUDARuntimeError('cudaErrorNoDevice: no CUDA-capable device is detected',)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : 2307
NCCL Runtime Version  : 2307

**Comment by kmaehashi** [comment]
For later reference:

* You don't have to specify `CUDA_VISIBLE_DEVICES` environment variable unless you want to limit CUDA device available in CuPy.
* If you encounter this error, unset `CUDA_VISIBLE_DEVICES` environment variable if you encounter this error (`unset CUDA_VISIBLE_DEVICES`). Do NOT leave it blank (`export CUDA_VISIBLE_DEVICES=` is **wrong**; this will make all CUDA devices invisible to CuPy).

**Comment by say2sarwar** [comment]
I tried this but the error is still thee. the same error.

**Comment by say2sarwar** [comment]
My GPU is working find for other scripts. I only face this issue for cupy. i am facing this issue to run some code related to faster RCNN.

**Comment by kmaehashi** [comment]
@say2sarwar Could you please copy and paste the full stacktrace?

**Comment by say2sarwar** [comment]
print(cupy.show_config())
CuPy Version          : 6.4.0
CUDA Root             : /usr/local/cuda-10.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7603
cuDNN Version         : 7603
NCCL Build Version    : 2402
NCCL Runtime Version  : 2402
None
>>print(chainer.print_runtime_info())
Platform: Linux-5.0.0-31-generic-x86_64-with-debian-buster-sid
Chainer: 6.4.0
NumPy: 1.17.2
CuPy:
  CuPy Version          : 6.4.0
  CUDA Root             : /usr/local/cuda-10.0
  CUDA Build Version    : 10000
  CUDA Driver Version   : 10010
  CUDA Runtime Version  : 10000
  cuDNN Build Version   : 7603
  cuDNN Version         : 7603
  NCCL Build Version    : 2402
  NCCL Runtime Version  : 2402
iDeep: Not Available
None
I install cupy as pip install cupy-cuda100
I am am using Ubuntu 18.04 with python 3.6 also tried 3.7. cupy and chainer version are latest and also tried the old compatible version. 
but the issue is the same. If you need any specific information, i will provide. 

Can you help?

**Comment by say2sarwar** [comment]
![Screenshot from 2019-10-08 16-31-47](https://user-images.githubusercontent.com/34134990/66380111-55581b00-e9e9-11e9-9c87-4eab79c9ec73.png)

**Comment by kmaehashi** [comment]
Thanks, the installation seems correct. Could you share the output of `nvidia-smi`?
Also, if you are on anaconda, could you try uninstalling `cudatoolkit` if it is installed?

**Comment by say2sarwar** [comment]
![Screenshot from 2019-10-08 17-56-30](https://user-images.githubusercontent.com/34134990/66387101-d74e4100-e9f5-11e9-9b1c-45b46610196b.png)
I already removed cudatoolkit but the error remain the same. nvidis-smi output is attached.
