### ISSUE TITLE
trying import cupy twice causes cython error

### ISSUE THREAD

**Issue by Hakuyume** [cupy/cupy#2148]
When I tried `import cupy` twice, it raises cython-related errors. The error changes according to the veriosn of `cython`.
 
The following steps can reproduce the error.

1. Put `Dockerfile` and `check.py` into an empty directory.
    ```dockerfile
    # Dockerfile
    FROM nvidia/cuda:9.2-cudnn7-devel-ubuntu18.04

    RUN apt-get update -y && apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        python3-dev \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*
    RUN curl -LO https://bootstrap.pypa.io/get-pip.py \
        && python3 get-pip.py --no-cache-dir \
        && rm get-pip.py

    ARG CYTHON
    RUN pip3 install --no-cache-dir \
        cython==${CYTHON} \
        'git+https://github.com/cupy/cupy.git@v6.0.0rc1#egg=cupy'

    ADD check.py .
    RUN python3 check.py
    ```
    ```python
    # check.py
    try:
        import cupy
    except ImportError:
        pass

    try:
        import cupy
    except ImportError:
        pass
    ```

2. Run `docker build`.
    ```
    $ docker build --build-arg CYTHON=0.28.0 .
    ...
    Step 7/7 : RUN python3 check.py
     ---> Running in d3b62bc1bedd
    Segmentation fault (core dumped)
    The command '/bin/sh -c python3 check.py' returned a non-zero code: 139
    ```
    ```
    $ docker build --build-arg CYTHON=0.29.0 .
    Step 7/7 : RUN python3 check.py
     ---> Running in 9b93400b9185
    Traceback (most recent call last):
      File "check.py", line 7, in <module>                                                                               
        import cupy                                                                                                      
      File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 11, in <module>                               
        from cupy import core  # NOQA                                                                                    
      File "/usr/local/lib/python3.6/dist-packages/cupy/core/__init__.py", line 1, in <module>                           
        from cupy.core import core  # NOQA                                                                               
      File "cupy/core/carray.pxi", line 50, in init cupy.core.core                                                       
    AttributeError: type object 'cupy.core.core.Indexer' has no attribute '__reduce_cython__'                            
    The command '/bin/sh -c python3 check.py' returned a non-zero code: 1
    ```

**Comment by kmaehashi** [comment]
Renamed the issue title.
Currently we require `except Exception` to catch CuPy import failure, but it is better if we can always raise `ImportError`.
