### ISSUE TITLE
CUDARuntimeError printing empty split

### ISSUE THREAD

**Issue by hvy** [cupy/cupy#2163]
`CUDARuntimeError` printing empty split with out-of-bounds indices.

Code to reproduce follows.
```python
import cupy as cp
a = cp.array([])
out = cp.split(a, [1])  # Indices must be 1, i.e. out-of-bounds to reproduce the error.

# Trying to print `out` yields an error while numPy would print `[array([], dtype=float64), array([], dtype=float64)]`
print(out) 
```

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    print(out)
  File "cupy/core/core.pyx", line 1290, in cupy.core.core.ndarray.__repr__
  File "cupy/core/core.pyx", line 1388, in cupy.core.core.ndarray.get
  File "cupy/cuda/memory.pyx", line 422, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy/cuda/runtime.pyx", line 265, in cupy.cuda.runtime.memcpy
  File "cupy/cuda/runtime.pyx", line 145, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

**Comment by takagi** [comment]
It seems that it is not only for an empty array but for any array split with over-run.

```Python
>>> import cupy as cp
>>> cp.split(cp.array([1]), [2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1348, in cupy.core.core.ndarray.__repr__
    return repr(self.get())
  File "cupy/core/core.pyx", line 1439, in cupy.core.core.ndarray.get
    a_cpu = numpy.empty(self._shape, dtype=self.dtype, order=order)
ValueError: negative dimensions are not allowed
>>> cp.split(cp.array([1]), [2])[0].shape
(2,)
```
