### ISSUE TITLE
Cannot convert cupy ndarry to numpy ndarray

### ISSUE THREAD

**Issue by jha929** [cupy/cupy#2236]
* Problem Description
Hi, I have a diagonal of a cupy ndarry, and am trying to convert the type of the diagonal to numpy array. However, it throws a catastrophic error, specified below. Any help will be appreciated.

* Conditions
CuPy Version          : 5.1.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10000
CUDA Driver Version   : 10000
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7301
cuDNN Version         : 7301
NCCL Build Version    : 1000

* Code to reproduce
```python
import cupy as cp
zeros_cp = cp.zeros(shape=(12288, 12288), dtype=cp.float32)
zeros_cp_diag = cp.diagonal(zeros_cp, 0)

cp.asnumpy(zeros_cp_diag)
```

* Error messages, stack traces, or logs

Traceback (most recent call last):
  File "/home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 241, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 98, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 108, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 53, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "temp.py", line 7, in <module>
    cp.asnumpy(zeros_cp_diag)
  File "/home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/__init__.py", line 645, in asnumpy
    return a.get(stream=stream)
  File "cupy/core/core.pyx", line 1800, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 1815, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 1816, in cupy.core.core.ndarray.get
  File "cupy/core/core.pyx", line 2426, in cupy.core.core.ascontiguousarray
  File "cupy/core/_kernel.pyx", line 821, in cupy.core._kernel.ufunc.__call__
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "cupy/core/_kernel.pyx", line 612, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 46, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
  File "/home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /home/jinsung/miniconda3/lib/python3.6/site-packages/cupy/core/include/cupy/carray.cuh(10): catastrophic error: cannot open source file "cuda_fp16.h"

1 catastrophic error detected in the compilation of "/tmp/tmpe1wxx9vw/kern.cu".
Compilation terminated.

**Comment by harshalchaudhari35** [comment]
Just replicated your code. It's working on cupy version 6.0 with cuda 10.1

**Comment by jha929** [comment]
Hi, thanks for your comment it really helps.

Ermm, I cannot update cupy for some reason..
In fact, every time I try to update cupy with "pip install -U cupy", it shows the output below.
```
Collecting cupy
Using cached https://files.pythonhosted.org/packages/08/68/e62805ba2d3e595ba07d1db8e46e780392466ea2cbc44a4de7af69a584c1/cupy-6.0.0.tar.gz
```
and never proceed further.

Will there be any workaround?

**Comment by harshalchaudhari35** [comment]
Not sure why its not downloading from the there, but you could download the tar.gz file from here https://pypi.org/project/cupy/#files and using ```pip install path-to-tar.gz/filename.tar.gz``` install it from the tar.gz file

**Comment by jha929** [comment]
Thanks for the help.

I tried to install cupy from local but had no luck.
"pip install cupy-6.0.0.tar.gz" gives the following output then never proceed again.
```
Processing ./cupy-6.0.0.tar.gz
```

In fact, I solved the installation problem by 
```
conda install cupy=6
```

Anyway, I appreciate your help, I will close the issue as it has been resolved.
