### ISSUE TITLE
connot import in1d

### ISSUE THREAD

**Issue by irondachui** [cupy/cupy#2597]
I can install cupy, I suppose. Because the code said that
```
Successfully installed cupy-cuda101-6.5.0
ERROR: Exception:
Traceback (most recent call last):
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_internal\commands\install.py", line 501, in run
    wheel_cache.cleanup()
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_internal\utils\temp_dir.py", line 80, in __exit__
    self.cleanup()
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_internal\utils\temp_dir.py", line 100, in cleanup
    rmtree(self._path)
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_vendor\six.py", line 693, in reraise
    raise value
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "E:\anaconda\envs\ts\lib\site-packages\pip\_internal\utils\misc.py", line 140, in rmtree
    onerror=rmtree_errorhandler)
  File "E:\anaconda\envs\ts\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "E:\anaconda\envs\ts\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\anaconda\envs\ts\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\anaconda\envs\ts\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "E:\anaconda\envs\ts\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "E:\anaconda\envs\ts\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\WANG\\AppData\\Local\\Temp\\pip-install-gat6a1wf\\cupy-cuda101\\cupy\\cuda\\cudnn64_7.dll'
```
I don't know what these mean, am I install it correctly?
And when I run `import cupy`, it can work, but I cannot use `in1d`.
When I run `from cupy import in1d`, I got this `ImportError: cannot import name 'in1d' from 'cupy' (E:\anaconda\envs\ts\lib\site-packages\cupy\__init__.py)`

here is my information
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168
my system is windows10
i reinstall cupy with `pip install cupy-cuda101 --no-cache-dir`

thx for ur time.

**Comment by kmaehashi** [comment]
Do you still see this issue?
It seems that the installation succeeds but it fails to clean-up temproary file.
I would suggest trying in fresh env or trying again after reboot.
