### ISSUE TITLE
A size-0 array should not be reshaped into a size-1 array

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#2637]
It seems the `reshape()` function missed a size check somewhere?
```python
>>> import cupy as cp
>>> a = cp.zeros((0,))
>>> a.size
0
>>> a = a.reshape(())
>>> a.size
1
>>> a.shape
()
```
NumPy behaves as expected:
```python
>>> import numpy as np
>>> a = np.zeros((0,))
>>> a.size
0
>>> a = a.reshape(())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot reshape array of size 0 into shape ()
```

**Comment by kmaehashi** [comment]
Thanks, it should be fixed...

```py
>>> import cupy as cp
>>> a = cp.zeros((0,))
>>> a.get()
array([], dtype=float64)
>>> a.reshape(()).get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1367, in cupy.core.core.ndarray.get
    cpdef get(self, stream=None, order='C', out=None):
  File "cupy/core/core.pyx", line 1434, in cupy.core.core.ndarray.get
    with self.device:
  File "cupy/core/core.pyx", line 1440, in cupy.core.core.ndarray.get
    a_gpu.data.copy_to_host(ptr, a_gpu.nbytes)
  File "cupy/cuda/memory.pyx", line 444, in cupy.cuda.memory.MemoryPointer.copy_to_host
    runtime.memcpy(mem.value, self.ptr, size,
  File "cupy/cuda/runtime.pyx", line 378, in cupy.cuda.runtime.memcpy
    check_status(status)
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
    raise CUDARuntimeError(status)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

**Comment by leofang** [comment]
Yeah, `CUDARuntimeError` happens because the data pointer for a size-0 array is `NULL`, while for a size-1 array is a valid one.
