### ISSUE TITLE
PointAttributes error on Windows with cuda toolkit v10.1

### ISSUE THREAD

**Issue by dloney** [cupy/cupy#2656]
I'm compiling cupy from source on Windows 10 to contribute to the sparse matrix functions. I upgraded to the v10.1 cuda toolkit and am receiving the following error on the cupy 7.0rc1 build:

Traceback (most recent call last):
  File "D:\local\projects_current\cupy\cupy\__init__.py", line 15, in <module>
    from cupy import core  # NOQA
  File "D:\local\projects_current\cupy\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
    # distutils: language = c++
  File "D:\local\projects_current\cupy\cupy\cuda\__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "D:\local\projects_current\cupy\cupy\cuda\compiler.py", line 12, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 8, in init cupy.cuda.device
    cdef class PointerAttributes:
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/local/projects_current/cupy/sparse_test.py", line 2, in <module>
    import cupy, time
  File "D:\local\projects_current\cupy\cupy\__init__.py", line 36, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "C:\Anaconda3\envs\cupy\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "D:\local\projects_current\cupy\cupy\__init__.py", line 15, in <module>
    from cupy import core  # NOQA
  File "D:\local\projects_current\cupy\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
    # distutils: language = c++
  File "D:\local\projects_current\cupy\cupy\cuda\__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "D:\local\projects_current\cupy\cupy\cuda\compiler.py", line 12, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 8, in init cupy.cuda.device
    cdef class PointerAttributes:
ImportError: CuPy is not correctly installed.

I am able to replicate any time I import cupy from the command line. I have the cuda toolkit in my path and confirmed it was working by compiling the bundled examples in Visual Studio 17. 

It appears that the PointerAttributes functionality is deprecated in v10.1 of the toolkit. Has this been propagated to the Windows builds?

**Comment by leofang** [comment]
PointerAttributes is a central piece of GPU software design that allows unified memory access. It is not deprecated. Some of its struct members are renamed/marked deprecated, but your symptom seems like a bad build to me. 

Did you upgrade your CUDA after compiling CuPy? If so you need to rebuild it from source. Different versions of CUDA are not guaranteed ABI compatible.

**Comment by dloney** [comment]
Thanks leofang. I'm still learning CUDA, so I was going off of what I read elsewhere.

I upgraded to v10.1 and then rebuilt the package, anticipating the cupy wouldn't be compatible. So it should be a clean build.

**Comment by leofang** [comment]
If you happen to have multiple versions of CUDA installed, you need to make sure 10.1 gets picked during both compile time and runtime. Could be that the runtime library is wrongly linked/loaded.

Also, are you using 10.1 Update 2? Not sure if this is relevant: #2569.

**Comment by dloney** [comment]
Thanks leofang. I traced this back to an issue that happened when I merged into my fork which produced some unexpected behavior. I built a clean version of the repository and it worked without an issue. I'm closing the issue.
