### ISSUE TITLE
linalg.norm won't take lists in cupy

### ISSUE THREAD

**Issue by gauthamzz** [cupy/cupy#3027]
Version

```
CuPy Version          : 6.7.0
CUDA Root             : /usr/local/cuda-10.0
CUDA Build Version    : 10000
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10000
cuDNN Build Version   : 7605
cuDNN Version         : 7600
NCCL Build Version    : 2406
NCCL Runtime Version  : 2406
Python 3.7.6
```

* Code to reproduce

```
>>> a = [1.2,3.4,5.4]
>>> np.linalg.norm(a, axis=-1)
6.493073232299171
```
```
>>> cp.linalg.norm(a, axis=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/py37/lib/python3.7/site-packages/cupy/linalg/norms.py", line 34, in norm
    if not issubclass(x.dtype.type, numpy.inexact):
AttributeError: 'list' object has no attribute 'dtype'
```

Both are expected to behave the same, i suppose.

**Comment by grlee77** [comment]
This is an intentional design decision for CuPy. This is explained for ufuncs at he link below, but tends to apply in general across the library.
https://docs-cupy.chainer.org/en/stable/reference/difference.html#universal-functions-only-work-with-cupy-array-or-scalar

I believe the reason is to avoid unexpectedly slow performance due to host/device data transfers.
