### ISSUE TITLE
Got ValueError when `ord` in `cupy.linalg.norm()` is 2 or -2

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#3053]
Reproducer:
```python
>>> import numpy as np
>>> a  = [[2, 0, 1], [-1, 1, 0], [-3, 3, 0]]
>>> a = np.asarray(a, dtype=np.float64)
>>> np.linalg.norm(a, ord=2)
4.723421263784789
>>>
>>> import cupy as cp
>>> b = cp.asarray(a)
>>> cp.linalg.norm(a, ord=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leofang/test/cupy2/cupy/linalg/norms.py", line 124, in norm
    raise ValueError('Invalid norm order for matrices.')
ValueError: Invalid norm order for matrices.
```
`ord=2` returns the largest singular value and `-2` the smallest.

**Comment by rushabh-v** [comment]
I would like to tackle this.

Will be opening a PR soon!
