### ISSUE TITLE
map_reduce.py example: AttributeError: 'NoneType' object has no attribute 'eventDestroy'

### ISSUE THREAD

**Issue by drcdr** [cupy/cupy#3173]
When running examples/streams/map_reduce.py, I get the following:
```
elapsed time 0.12984609603881836
total bytes 167778304
total bytes 167778304
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC0572E8>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057278>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057208>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057198>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057128>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC0570B8>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057048>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC04DEF0>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC04DF28>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
Exception ignored in: <bound method Event.__del__ of <cupy.cuda.stream.Event object at 0x00000180AC057358>>
Traceback (most recent call last):
  File "cupy\cuda\stream.pyx", line 103, in cupy.cuda.stream.Event.__del__
AttributeError: 'NoneType' object has no attribute 'eventDestroy'
```

**_Conditions:_**
CuPy Version          : 7.2.0
CUDA Root             : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : 10200
cuFFT Version         : 10010
cuRAND Version        : 10010
cuSOLVER Version      : (10, 1, 0)
cuSPARSE Version      : 10010
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : None
NCCL Runtime Version  : None

I've had the same results on two different computers (Windows and Linux, both cupy 7.2.0)

**_Code to reproduce_**
[cupy/examples/streams/map_reduce.py](https://github.com/cupy/cupy/blob/master/examples/stream/map_reduce.py) - no changes

**Comment by leofang** [comment]
Could you try building the master branch? I think this is fixed recently in #2809 but was not included in v7.2.0 yet.

**Comment by leofang** [comment]
Hmmm, it *is* included in v7...see #2811. @emcastillo Any idea?

**Comment by emcastillo** [comment]
`Event` did not had the fix applied ...

**Comment by leofang** [comment]
I feel awkward about this...It's like we're playing whac-a-mole but never hit the mole (the shutdown bug)...😞

**Comment by leofang** [comment]
Chatted with a few colleagues and it seems we're not alone. h5py had similar shutdown issues (see e.g., https://github.com/h5py/h5py/issues/534). I was told they resolved by holding a hard reference to the needed module/function, but for the moment I can't find the PR/code snippet that does this. Will ask if needed.

Another ref: 
https://docs.python.org/3/library/weakref.html#comparing-finalizers-with-del-methods 
Not sure whether this is a better, permanent solution or not.
