### ISSUE TITLE
Concatenating arrays from different devices results in a CUDARuntimeError

### ISSUE THREAD

**Issue by trivialfis** [cupy/cupy#3283]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : CUBLASError('CUBLAS_STATUS_NOT_INITIALIZED')
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2506
NCCL Runtime Version  : 2506
```

* Code to reproduce
``` python
import cupy
print(cupy.__version__)

arrs = []
rng = cupy.random.RandomState(1994)

for i in range(100):
    cupy.cuda.runtime.setDevice(i % 2)
    a = rng.randn(1000, 100)
    arrs.append(a)


cat = cupy.concatenate(arrs, axis=0)
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "with-cupy.py", line 14, in <module>
    cat = cupy.concatenate(arrs, axis=0)
  File "/home/fis/Workspace/XGBoost/lib/python3.7/site-packages/cupy/manipulation/join.py", line 54, in concatenate
    return core.concatenate_method(tup, axis)
  File "cupy/core/_routines_manipulation.pyx", line 577, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 623, in cupy.core._routines_manipulation.concatenate_method
  File "cupy/core/_routines_manipulation.pyx", line 649, in cupy.core._routines_manipulation._concatenate
  File "cupy/core/_routines_manipulation.pyx", line 770, in cupy.core._routines_manipulation._concatenate_single_kernel
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1243, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1264, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1042, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1062, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 764, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 761, in cupy.cuda.memory._try_malloc
  File "cupy/cuda/memory.pyx", line 1011, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 499, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 500, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 99, in cupy.cuda.memory.Memory.__init__
  File "cupy/cuda/runtime.pyx", line 296, in cupy.cuda.runtime.malloc
  File "cupy/cuda/runtime.pyx", line 201, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

I'm using cupy with `dask` on multiple GPUs.  If the operation is not supported, a more friendly error message for further debugging would be appreciated. ;-)

**Comment by emcastillo** [comment]
Thanks for the report.

The array should be explicitly moved to the device before doing the concatenation, but I believe that there should be an assertion that prints a friendly error message.

**Comment by leofang** [comment]
might be relevant: https://github.com/dask/dask/issues/5992

**Comment by takagi** [comment]
@trivialfis  How many GPUs your environment has?

**Comment by trivialfis** [comment]
2 GPUs for reproducing the issue.

**Comment by takagi** [comment]
Sorry, I completely saw wrong.
