### ISSUE TITLE
Issue adding `-arch` to RawModule options

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3292]
```bash
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2507
```

When I try and add `"--gpu-architecture=compute_X0"`, where **X** is a compute major version, I get the following message. The whole command looks like `module2 = cp.RawModule(
            code=src, options=("-std=c++11", "-use_fast_math","--gpu-architecture=compute_30",)`

```bash
Traceback (most recent call last):
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 438, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy/cuda/nvrtc.pyx", line 101, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 111, in cupy.cuda.nvrtc.compileProgram
  File "cupy/cuda/nvrtc.pyx", line 56, in cupy.cuda.nvrtc.check_status
cupy.cuda.nvrtc.NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.14.0a0+179.g639fccf.dirty-py3.8.egg/cusignal/__init__.py", line 15, in <module>
    from cusignal.signaltools import (
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.14.0a0+179.g639fccf.dirty-py3.8.egg/cusignal/signaltools.py", line 54, in <module>
    from ._upfirdn import upfirdn, _output_len
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.14.0a0+179.g639fccf.dirty-py3.8.egg/cusignal/_upfirdn.py", line 509, in <module>
    _populate_kernel_cache()
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cusignal-0.14.0a0+179.g639fccf.dirty-py3.8.egg/cusignal/_upfirdn.py", line 311, in _populate_kernel_cache
    module2 = cp.RawModule(
  File "cupy/core/raw.pyx", line 252, in cupy.core.raw.RawModule.__init__
  File "cupy/core/carray.pxi", line 146, in cupy.core.core.compile_with_cache
  File "cupy/core/carray.pxi", line 194, in cupy.core.core.compile_with_cache
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 286, in compile_with_cache
    return _compile_with_cache_cuda(source, options, arch, cache_dir,
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 308, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 246, in _preprocess
    result = prog.compile(options)
  File "/home/belt/anaconda3/envs/cusignal/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 442, in compile
    raise CompileException(log, self.src, self.name, options, 'nvrtc')
cupy.cuda.compiler.CompileException: nvrtc: error: --gpu-architecture (-arch) defined more than once
```

**Comment by leofang** [comment]
Hi Matt, I think it's because CuPy internally sets the arch for you: https://github.com/cupy/cupy/blob/e3ad9d44c15bf39b125ff85b9538e7b50c4dc2c4/cupy/cuda/compiler.py#L56-L70
(note the error message is `error: --gpu-architecture (-arch) defined more than once`). 

Is there a use case in which overwriting the arch is a must? I guess this snippet could potentially have an issue with heterogeneous GPUs.

**Comment by mnicely** [comment]
Hi Leo, that's what I was expecting but I couldn't find where it was occurring. Thanks. 

I'll close the issue.
