### ISSUE TITLE
cupy.put behaves differently than numpy.put

### ISSUE THREAD

**Issue by PBernalPolo** [cupy/cupy#3325]
First of all, let me thank you for the effort you put into this project. Thank you.
When I try to execute the following code:
```
import numpy as np
import cupy as cp

xn = np.array([[ 1.0 , 2.0 , 3.0 ] , [ 4.0 , 5.0 ,6.0 ]])
indn = np.array([ 0 , 3 , 4 ])
xn.put( indn , 10.0 )
print( xn )

xc = cp.array([[ 1.0 , 2.0 , 3.0 ] , [ 4.0 , 5.0 ,6.0 ]])
indc = cp.array([ 0 , 3 , 4 ])
xc.put( indc , 10.0 )
print( xc )
```
I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 601, in cupy.core.core.ndarray.put
  File "cupy/core/core.pyx", line 608, in cupy.core.core.ndarray.put
  File "cupy/core/_routines_indexing.pyx", line 109, in cupy.core._routines_indexing._ndarray_put
  File "cupy/core/core.pyx", line 98, in cupy.core.core.ndarray.__init__
  File "cupy/core/internal.pyx", line 38, in cupy.core.internal.get_size
ValueError: size should be None, collections.abc.Sequence, or int
```
I'm not sure if I'm doing something wrong, or if it's a bug...
The output of `python -c 'import cupy; cupy.show_config()'` is:
```
CuPy Version          : 7.1.1
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10010
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2406
```

**Comment by emcastillo** [comment]
cupy functions usually do not accept inputs other than cupy arrays.

The above code works if you create a cupy array for the scalar value
```
xc = cp.array([[ 1.0 , 2.0 , 3.0 ] , [ 4.0 , 5.0 ,6.0 ]])
indc = cp.array([ 0 , 3 , 4 ])
xc.put( indc , cp.array(10.0))
print( xc )
```
However, this is not intuitive at all and we will discuss to allow scalar values as inputs.
