### ISSUE TITLE
CuPy 8.0.0 kernel launch overhead/time

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3326]
Is there anything different about how CUDA kernels are launched between CuPy 7.3 and 8.0? I'm seeing a small drop in performance in nearly all of my CuPy raw kernels with 8.0.0b2. It's not much but is seems pretty consistent.

Most CuPy calls seem to be faster (which is nice).

I've attached a pytest-benchmark comparison [pytest_730vs800.txt](https://github.com/cupy/cupy/files/4604474/pytest_730vs800.txt). 

But as an example.
```bash
-------------------------------------------------------------------------------------------------------- benchmark 'Convolve2d': 36 tests -------------------------------------------------------------------------------------------------------
Name (time in us)                                                  Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_convolve2d_gpu[valid-symm-5-256] (0001_cupy730)         114.9480 (1.0)         215.6430 (1.0)        118.5592 (1.0)          6.1043 (1.30)       117.3260 (1.0)        1.0840 (1.0)       365;760  8,434.6081 (1.0)        8510           1
bench_convolve2d_gpu[valid-wrap-5-256] (0001_cupy730)         115.0150 (1.00)     35,550.1420 (164.86)     129.4123 (1.09)       394.3276 (84.01)      117.3320 (1.00)       1.5945 (1.47)      11;1365  7,727.2425 (0.92)       8543           1
bench_convolve2d_gpu[valid-fill-5-256] (0001_cupy730)         119.1470 (1.04)      7,633.0270 (35.40)      131.7770 (1.11)       130.5539 (27.81)      121.5260 (1.04)       1.5328 (1.41)      28;1259  7,588.5763 (0.90)       8135           1
bench_convolve2d_gpu[valid-symm-5-256] (0002_cupy800)         131.2820 (1.14)     10,547.4940 (48.91)      146.7623 (1.24)       165.0781 (35.17)      134.6530 (1.15)       2.3915 (2.21)      20;1344  6,813.7405 (0.81)       7465           1
bench_convolve2d_gpu[valid-wrap-5-256] (0002_cupy800)         131.8490 (1.15)        233.9780 (1.09)       136.6235 (1.15)         7.2768 (1.55)       134.6980 (1.15)       1.5060 (1.39)      567;949  7,319.3836 (0.87)       7379           1
bench_convolve2d_gpu[valid-fill-5-256] (0002_cupy800)         135.7890 (1.18)        317.2970 (1.47)       141.2737 (1.19)         9.9237 (2.11)       138.6090 (1.18)       1.6240 (1.50)      549;983  7,078.4567 (0.84)       7224           1
bench_convolve2d_gpu[same-fill-5-256] (0001_cupy730)          220.0250 (1.91)     21,787.2470 (101.03)     248.6903 (2.10)       402.6031 (85.77)      223.3620 (1.90)       3.1948 (2.95)       13;585  4,021.0650 (0.48)       4469           1
bench_convolve2d_gpu[full-fill-5-256] (0001_cupy730)          225.5980 (1.96)      8,674.5710 (40.23)      255.7666 (2.16)       248.0299 (52.84)      230.4640 (1.96)       5.0588 (4.67)       16;690  3,909.8146 (0.46)       4303           1
bench_convolve2d_gpu[same-wrap-5-256] (0001_cupy730)          249.6160 (2.17)        404.5100 (1.88)       258.5249 (2.18)         8.6587 (1.84)       256.9800 (2.19)       3.9755 (3.67)      290;342  3,868.0996 (0.46)       3929           1
bench_convolve2d_gpu[same-fill-5-256] (0002_cupy800)          254.1690 (2.21)        583.6530 (2.71)       260.1703 (2.19)        11.0884 (2.36)       258.1140 (2.20)       2.4165 (2.23)      161;398  3,843.6364 (0.46)       3735           1
bench_convolve2d_gpu[full-wrap-5-256] (0001_cupy730)          255.5680 (2.22)        463.3020 (2.15)       262.0389 (2.21)        10.6966 (2.28)       260.0770 (2.22)       2.6040 (2.40)      186;305  3,816.2270 (0.45)       3830           1
bench_convolve2d_gpu[same-symm-5-256] (0001_cupy730)          255.8330 (2.23)        385.0860 (1.79)       263.3686 (2.22)         4.6941 (1.0)        263.0425 (2.24)       2.4610 (2.27)      392;312  3,796.9595 (0.45)       3830           1
bench_convolve2d_gpu[full-fill-5-256] (0002_cupy800)          261.2810 (2.27)     28,152.8840 (130.55)     294.4878 (2.48)       476.4559 (101.50)     266.9770 (2.28)       6.1625 (5.68)       14;572  3,395.7262 (0.40)       3727           1
bench_convolve2d_gpu[full-symm-5-256] (0001_cupy730)          261.8460 (2.28)     13,590.6950 (63.02)      319.9241 (2.70)       261.0537 (55.61)      269.5450 (2.30)      53.2543 (49.13)      20;613  3,125.7414 (0.37)       3715           1
bench_convolve2d_gpu[same-wrap-5-256] (0002_cupy800)          287.3020 (2.50)     10,319.2490 (47.85)      326.2510 (2.75)       273.3862 (58.24)      296.2840 (2.53)       6.7770 (6.25)       24;591  3,065.1244 (0.36)       3434           1
bench_convolve2d_gpu[same-symm-5-256] (0002_cupy800)          292.1490 (2.54)      6,791.0310 (31.49)      329.1211 (2.78)       198.8153 (42.35)      299.6780 (2.55)       6.6305 (6.12)       80;570  3,038.3953 (0.36)       3376           1
bench_convolve2d_gpu[full-wrap-5-256] (0002_cupy800)          294.3020 (2.56)      6,894.8440 (31.97)      325.7672 (2.75)       179.1243 (38.16)      299.9030 (2.56)       8.9795 (8.28)       82;458  3,069.6764 (0.36)       2665           1
bench_convolve2d_gpu[full-symm-5-256] (0002_cupy800)          297.6980 (2.59)     13,736.2680 (63.70)      328.8248 (2.77)       329.1252 (70.12)      302.8480 (2.58)       4.5440 (4.19)       22;522  3,041.1335 (0.36)       3294           1
bench_convolve2d_gpu[valid-wrap-100-256] (0001_cupy730)     1,606.8980 (13.98)     1,765.0200 (8.18)     1,621.5128 (13.68)       15.9099 (3.39)     1,614.5380 (13.76)     11.6590 (10.76)     119;112    616.7080 (0.07)        621           1
bench_convolve2d_gpu[valid-symm-100-256] (0001_cupy730)     1,606.9310 (13.98)    10,364.9360 (48.07)    1,699.3196 (14.33)      490.6496 (104.53)   1,615.9810 (13.77)     28.5055 (26.30)        9;92    588.4708 (0.07)        620           1
bench_convolve2d_gpu[valid-fill-100-256] (0001_cupy730)     1,608.2400 (13.99)     2,453.6990 (11.38)    1,700.3170 (14.34)      213.3465 (45.45)    1,615.1715 (13.77)     11.2620 (10.39)       61;62    588.1256 (0.07)        446           1
bench_convolve2d_gpu[valid-wrap-100-256] (0002_cupy800)     1,623.3870 (14.12)     6,947.2920 (32.22)    1,709.7970 (14.42)      389.0638 (82.88)    1,629.9425 (13.89)     26.4200 (24.37)       9;104    584.8648 (0.07)        614           1
bench_convolve2d_gpu[valid-symm-100-256] (0002_cupy800)     1,623.8970 (14.13)     1,661.2350 (7.70)     1,630.7732 (13.75)        4.8489 (1.03)     1,629.0260 (13.88)      5.6245 (5.19)       142;17    613.2060 (0.07)        613           1
bench_convolve2d_gpu[valid-fill-100-256] (0002_cupy800)     1,627.8100 (14.16)     6,960.3760 (32.28)    1,836.7233 (15.49)      410.2788 (87.40)    1,665.5840 (14.20)    292.8815 (270.19)       18;7    544.4478 (0.06)        451           1
bench_convolve2d_gpu[same-fill-100-256] (0001_cupy730)      3,217.3610 (27.99)     3,583.7770 (16.62)    3,231.7568 (27.26)       28.4001 (6.05)     3,225.8565 (27.49)     10.1075 (9.32)        13;19    309.4292 (0.04)        308           1
bench_convolve2d_gpu[same-wrap-100-256] (0001_cupy730)      3,244.5420 (28.23)    19,070.7760 (88.44)    3,478.2051 (29.34)    1,183.4700 (252.12)   3,257.8750 (27.77)    121.8700 (112.43)       7;22    287.5046 (0.03)        227           1
bench_convolve2d_gpu[same-fill-100-256] (0002_cupy800)      3,252.2680 (28.29)    26,789.1500 (124.23)   3,445.3604 (29.06)    1,394.2662 (297.03)   3,269.3370 (27.87)     75.4260 (69.58)        5;32    290.2454 (0.03)        307           1
bench_convolve2d_gpu[same-symm-100-256] (0001_cupy730)      3,252.8540 (28.30)    10,608.9280 (49.20)    3,570.5240 (30.12)      736.2826 (156.85)   3,301.2800 (28.14)    228.0785 (210.40)      30;32    280.0709 (0.03)        227           1
bench_convolve2d_gpu[same-wrap-100-256] (0002_cupy800)      3,283.0430 (28.56)     4,481.9060 (20.78)    3,406.6877 (28.73)      329.8262 (70.26)    3,300.7760 (28.13)     18.5910 (17.15)       20;29    293.5403 (0.03)        226           1
bench_convolve2d_gpu[same-symm-100-256] (0002_cupy800)      3,286.3810 (28.59)     4,452.7300 (20.65)    3,347.9291 (28.24)      237.7220 (50.64)    3,294.7930 (28.08)     10.1937 (9.40)        10;13    298.6921 (0.04)        225           1
bench_convolve2d_gpu[full-fill-100-256] (0001_cupy730)      6,152.5650 (53.52)    12,701.7910 (58.90)    6,492.6414 (54.76)      852.2611 (181.56)   6,168.5815 (52.58)    339.4900 (313.18)       8;22    154.0205 (0.02)        136           1
bench_convolve2d_gpu[full-symm-100-256] (0001_cupy730)      6,183.2290 (53.79)     6,642.7990 (30.80)    6,231.9070 (52.56)       72.5656 (15.46)    6,203.6550 (52.88)     42.3120 (39.03)       13;14    160.4645 (0.02)        118           1
bench_convolve2d_gpu[full-wrap-100-256] (0001_cupy730)      6,185.1640 (53.81)    15,431.1240 (71.56)    6,613.9338 (55.79)    1,087.9448 (231.77)   6,332.8605 (53.98)    448.9280 (414.14)        7;9    151.1959 (0.02)        122           1
bench_convolve2d_gpu[full-fill-100-256] (0002_cupy800)      6,186.1080 (53.82)     6,794.2840 (31.51)    6,288.3675 (53.04)      202.2969 (43.10)    6,197.0730 (52.82)     17.9327 (16.54)       20;21    159.0238 (0.02)        119           1
bench_convolve2d_gpu[full-wrap-100-256] (0002_cupy800)      6,217.8560 (54.09)     6,549.1520 (30.37)    6,239.1438 (52.62)       35.2079 (7.50)     6,232.9380 (53.12)     12.0200 (11.09)         6;8    160.2784 (0.02)        118           1
bench_convolve2d_gpu[full-symm-100-256] (0002_cupy800)      6,224.7550 (54.15)     6,446.2190 (29.89)    6,249.2002 (52.71)       33.0107 (7.03)     6,236.9630 (53.16)     20.6007 (19.00)       11;11    160.0205 (0.02)        117           1
```

I'm comparing the following configurations.
```bash
CuPy Version          : 7.3.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10010
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10010
cuBLAS Version        : 10201
cuFFT Version         : 10101
cuRAND Version        : 10101
cuSOLVER Version      : (10, 2, 0)
cuSPARSE Version      : 10300
NVRTC Version         : (10, 1)
cuDNN Build Version   : 7605
cuDNN Version         : 7600
NCCL Build Version    : 2406
NCCL Runtime Version  : 2604

CuPy Version          : 8.0.0b2
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
```

**Comment by leofang** [comment]
I don't have resource to verify right now, but I bet it's the per-device cache we recently added (#3201). I wonder if you could compare the performance of #3201 vs that of #3200? The cache was implemented differently in the latter.

**Comment by leofang** [comment]
The other issue could be that having a cache (regardless of how it's done) could already add some overhead to it. If this is the case then reverting #3201 needs to be considered...

One question: How is the timing done? Did you take warm-up runs before starting timing?

cc: @emcastillo

**Comment by mnicely** [comment]
@leofang I'm trying the instructions you left at #3319 to checkout and apply the changes from #3200, but I'm getting the following error. 

I tried creating a new branch with
```bash
git checkout -b branch3200 master
```

```bash
(cusignal-dev) belt@orion:~/workStuff/rapids/cupy$ git am 3200.patch
Applying: make RawKernel/RawModule aware of CUDA context
error: patch failed: cupy/core/raw.pxd:4
error: cupy/core/raw.pxd: patch does not apply
error: patch failed: cupy/core/raw.pyx:1
error: cupy/core/raw.pyx: patch does not apply
error: patch failed: tests/cupy_tests/core_tests/test_raw.py:285
error: tests/cupy_tests/core_tests/test_raw.py: patch does not apply
Patch failed at 0001 make RawKernel/RawModule aware of CUDA context
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

I did testing with pytest-benchmarks. There are 10 warm-ups per call and garbage collection is disable. I'm syncing all CuPy raw kernels, so the benchmark runs a few thousand times and prints the statistics. Also, all CuPy raw kernels are precompiled before any benchmarks are run.

**Comment by mnicely** [comment]
Interestingly enough, the commands in #3319 work fine for that patch.

**Comment by emcastillo** [comment]
There is one PR we sent after release that further improves v8.0.0 cpu time when launching a kernel. #3298, unfortunately, it didn't pass the release cut :(

Can you try it and check if your numbers go back to where they were?

**Comment by leofang** [comment]
@mnicely Do you have a MWE (minimum working example) against which we can benchmark on our sides? I could try to take a look.

I think you could do `git fetch` from someone's branch so as to avoid resolving merge conflicts. In this case it's likely due to conflicts between master and #3200. IIRC `git fetch` would preserve the HEAD info, meaning it knows to which commit the remote changes are to be applied.

@emcastillo I wanted to bring up #3298, but is it part of the "merging elementwise" work that was left un-reverted? If it's not, then I am not sure why it could be the reason that v7.3.0 performs better than v8.0.0b2...?

**Comment by emcastillo** [comment]
This comes from an enhancement I did in the indexer for v8, that required accessing those properties. But I screwed it up, and fixed it later.
It is not related to the refactoring.

**Comment by mnicely** [comment]
Hi @leofang, all my code/tests are based on cuSignal. If you want, you can clone my remove_Numba branch that I'm testing. https://github.com/mnicely/cusignal/tree/remove_Numba

My environment is based on 
```yaml
name: cusignal
channels:
  - conda-forge
  - nvidia
  - defaults
  - numba
dependencies:
  - scipy
  - numpy
  - cudatoolkit>=9.2,<11
  - boost
  - matplotlib
  - numba
  - pytest
  - pytest-benchmark
  - cupy>=6.2.0   <--- REPLACE WITH 8.0
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - ipython
```

Once you get it setup, you can run 
`pytest -v --benchmark-only -k convolve2d_gpu`

**Comment by leofang** [comment]
Tried benchmarking a simple RawKernel against v7.4.0, v8.0.0b2, and master, and I think the CPU time does get increased a bit.

v7.4.0
```
test_multiply       :    CPU:    4.877 us   +/- 0.531 (min:    4.461 / max:   21.301) us     GPU:   27.901 us   +/- 0.859 (min:   24.576 / max:   49.088) us
```
v8.0.0b2
```
test_multiply       :    CPU:    5.416 us   +/- 0.705 (min:    5.032 / max:   51.297) us     GPU:   28.482 us   +/- 0.853 (min:   24.576 / max:   54.624) us
```
master
```
test_multiply       :    CPU:    5.433 us   +/- 1.039 (min:    5.061 / max:   90.184) us     GPU:   28.500 us   +/- 1.133 (min:   24.576 / max:  120.544) us
```

I also tried reverting the cache PR #3201 (by doing `git revert -m 1 ff18a56` on master), and it seems to help a bit, but is still slower than v7.4.0:
```
test_multiply       :    CPU:    5.113 us   +/- 0.587 (min:    4.726 / max:   21.754) us     GPU:   28.360 us   +/- 0.811 (min:   25.376 / max:   49.152) us
```
so there're other factors hitting the performance.

**Comment by emcastillo** [comment]
@leofang can you try reverting
https://github.com/cupy/cupy/pull/2940

**Comment by leofang** [comment]
I have a hard time reverting #2940 on master, but I was able to compare the performance with #2940. Below is the performance data listed in order.

v7.4.0:
```
test_multiply       :    CPU:    4.834 us   +/- 0.564 (min:    4.336 / max:   38.839) us     GPU:   93.135 us   +/- 0.800 (min:   90.112 / max:  125.888) us
```
Commit b9e49bc (right after #2940 was merged):
```
test_multiply       :    CPU:    4.933 us   +/- 0.391 (min:    4.536 / max:   36.597) us     GPU:   93.433 us   +/- 0.771 (min:   90.112 / max:  124.928) us
```
Commit ff18a56 (right after #3201 was merged):
```
test_multiply       :    CPU:    5.516 us   +/- 0.394 (min:    5.059 / max:   22.566) us     GPU:   93.902 us   +/- 0.680 (min:   89.920 / max:  110.592) us
```
v8.0.0b2:
```
test_multiply       :    CPU:    5.586 us   +/- 0.680 (min:    5.063 / max:   39.918) us     GPU:   93.940 us   +/- 0.767 (min:   90.112 / max:  127.040) us
```
master (the result fluctuates a lot):
```
test_multiply       :    CPU:    5.478 us   +/- 0.335 (min:    5.024 / max:   22.821) us     GPU:   94.062 us   +/- 0.627 (min:   90.112 / max:  112.640) us
```

Together with the result of reverting #3201, I feel the cache lookup is the main contribution (plus other factors).

**Comment by emcastillo** [comment]
Seems like #3201 was the main reason.
I can't remember the specific details but did you change something in the caching mechanism?
AFAIK the PR just cached the module or kernel per device instead of having a global one.

**Comment by leofang** [comment]
> AFAIK the PR just cached the module or kernel per device instead of having a global one.
> Maybe we can have a explicit dict ourselves? I don't know if it will lower exec time though ...

When a `RawKernel` is called, it used to be invoking the per-instance `Function` without looking up from the cache; the lookup only happened when the `RawKernel` instance does not hold any `Function`. 

In #3201, due to the need of supporting multiple devices, the `Function` is always looked up from the cache; `RawKernel` itself doesn't hold anything.

I guess each `RawKernel` should have its own cache so that it's faster to lookup.

**Comment by leofang** [comment]
I have a bit of concern with timings in https://github.com/cupy/cupy/issues/3326#issuecomment-627473681, as I found someone was running on my system that could impact benchmarks of small workloads. Let me try if I can find another idle system and redo it 😞

**Comment by mnicely** [comment]
> Thanks for looking into that! I would consider this a limitation or flaw in 8.0, especially if it's due to a bug fix. I just wanted to make sure you were seeing the same thing.

I wanted to correct a typo! 

I **wouldn't** consider this a limitation or flaw in 8.0

**Comment by leofang** [comment]
Continuing the benchmarking discussion in #3341, which was merged. Would be great to have a final confirmation that the performance regression is fully resolved so as to close this issue @mnicely.

**Comment by mnicely** [comment]
@leofang Sorry for the delayed response.

I've attached the latest results (sorted by mean).

As before, v8.0.0 (and patch 3341) performs much better than v7.4.0. 

v8.0.0 and v8.0.0:3341 seem to go back and forth, with 3341 performing better most of the time.

[pytest_740vs800vs3341.txt](https://github.com/cupy/cupy/files/4683891/pytest_740vs800vs3341.txt)

**Comment by leofang** [comment]
Thanks, @mnicely. I skimmed over the results, and it seems v7.4.0 wins in some cases. Also,
> v8.0.0 and v8.0.0:3341 seem to go back and forth

is a bit concerning. Sounds like we haven't fully resolved the issue... Did you benchmark v8.0.0b2 and the current master (after #3341 was merged)?

**Comment by mnicely** [comment]
@leofang Let me confirm. I have to teach today and tomorrow, but I'll rerun everything in my down time.

**Comment by mnicely** [comment]
@leofang Do you want me to test master + #3341 or v8.0.0b2 + #3341?

**Comment by mnicely** [comment]
I'm getting the following error when I try to install v8.0.0b2

```bash
(cusignal-dev) belt@orion:~/workStuff/rapids/cupy$ python -c 'import cupy; cupy.show_config()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/belt/workStuff/rapids/cupy/cupy/__init__.py", line 19, in <module>
    from cupy import core  # NOQA
  File "/home/belt/workStuff/rapids/cupy/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
    # distutils: language = c++
  File "/home/belt/workStuff/rapids/cupy/cupy/cuda/__init__.py", line 12, in <module>
    from cupy.cuda import pinned_memory  # NOQA
  File "cupy/cuda/pinned_memory.pyx", line 1, in init cupy.cuda.pinned_memory
    # distutils: language = c++
ValueError: cupy.core._carray.CIndexer size changed, may indicate binary incompatibility. Expected 440 from C header, got 432 from PyObject
```

Using commands
```bash
pip uninstall cupy
git checkout v8.0.0b2
pip install -e . -vvvv
```

**Comment by emcastillo** [comment]
please clean the temporaries with git clean -f X

**Comment by mnicely** [comment]
@leofang These results look much better! I compared v7.4.0, master, and v8.0.0b2

[pytest_740-master-v800b2.txt](https://github.com/cupy/cupy/files/4689402/pytest_740-master-v800b2.txt)

master seems to be superior in all but a few cases.

There are a few cases when v7.4.0 does better on functions with raw kernel, but no red flags. Everything is within a comfortable range.

There is one exception, `hilbert` and `hilbert2`. I need to drive into these when I have time to see if we are doing something wrong.

```bash
---------------------------------------------------------------------------------------------- benchmark 'Hilbert': 3 tests ---------------------------------------------------------------------------------------------
Name (time in us)                                Min                    Max                Mean              StdDev              Median               IQR            Outliers  OPS (Kops/s)            Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_hilbert_gpu[32768] (0001_cupy740)     461.8490 (1.01)        852.9310 (1.0)      469.3807 (1.0)       24.3024 (1.0)      465.2730 (1.01)     3.2723 (1.20)       38;213        2.1305 (1.0)        2141           1
bench_hilbert_gpu[32768] (0005_v800b2_)     472.7560 (1.04)      1,114.3070 (1.31)     480.0578 (1.02)      32.9084 (1.35)     476.1320 (1.04)     2.8895 (1.06)       24;188        2.0831 (0.98)       2087           1
bench_hilbert_gpu[32768] (0004_master_)     455.4660 (1.0)      35,872.5830 (42.06)    528.1544 (1.13)     978.7230 (40.27)    459.6540 (1.0)      2.7350 (1.0)        19;233        1.8934 (0.89)       2166           1
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------- benchmark 'Hilbert2': 3 tests ----------------------------------------------------------------------------------------------
Name (time in us)                               Min                    Max                  Mean                StdDev              Median                IQR            Outliers         OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
bench_hilbert2_gpu[256] (0005_v800b2_)     589.6920 (1.03)     85,497.1620 (1.84)       844.2809 (1.0)      2,932.9844 (1.12)     596.0590 (1.03)      7.3240 (1.0)        19;167  1,184.4399 (1.0)        1654           1
bench_hilbert2_gpu[256] (0004_master_)     574.2300 (1.0)      46,448.2780 (1.0)      1,010.0094 (1.20)     2,983.7577 (1.14)     580.4415 (1.0)      33.8660 (4.62)        10;34    990.0898 (0.84)        420           1
bench_hilbert2_gpu[256] (0001_cupy740)     766.0660 (1.33)     57,641.4990 (1.24)     1,077.4079 (1.28)     2,619.8909 (1.0)      776.8360 (1.34)     14.5298 (1.98)       22;230    928.1536 (0.78)       1283           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by leofang** [comment]
Thanks, Matt. 

> Do you want me to test master + #3341 or v8.0.0b2 + #3341?

I simply wanted to know what combinations you used in https://github.com/cupy/cupy/issues/3326#issuecomment-634164880. But I'd be interested in comparing v7.4.0, v8.0.0b2, and current master (just tagged v8.0.0b3, in which #3341 is included).

> please clean the temporaries with git clean -f X

Right, or `git clean -fdx`, or my lazy way: https://github.com/cupy/cupy/pull/3341#issuecomment-629462309 😇

**Comment by mnicely** [comment]
> Right, or `git clean -fdx`, or my lazy way: [#3341 (comment)](https://github.com/cupy/cupy/pull/3341#issuecomment-629462309)

I'll eventually get this Github figured out! Haha

**Comment by leofang** [comment]
Oh we replied at the same time! 🤝 

> These results look much better!

This looks great (and in line with what I expected), @mnicely! I think a very, very marginal slowdown of master (v8.0.0b3) compared to v7.4.0 is expected, because we need to call `cudaGetDevice` at every invocation of RawKernels. But we knew it's a very cheap API call so it's OK. The true benefit of #3341 is in long-running programs, in which the global, per-device cache could be too big to look up efficiently.

@emcastillo What do you think about Matt's latest test https://github.com/cupy/cupy/issues/3326#issuecomment-634707876? I suppose this issue can be marked as resolved?

**Comment by mnicely** [comment]
`hilbert` and `hilbert2` are pretty simple, mainly running `fftpack.fft(2)` and fftpack.ifft(2)`. Is there any reason those would be impacted with the latest changes?

**hilbert**
```python
x = asarray(x)
    if iscomplexobj(x):
        raise ValueError("x must be real.")
    if N is None:
        N = x.shape[axis]
    if N <= 0:
        raise ValueError("N must be positive.")

    Xf = fftpack.fft(x, N, axis=axis)
    h = zeros(N)
    if N % 2 == 0:
        h[0] = h[N // 2] = 1
        h[1 : N // 2] = 2
    else:
        h[0] = 1
        h[1 : (N + 1) // 2] = 2

    if x.ndim > 1:
        ind = [newaxis] * x.ndim
        ind[axis] = slice(None)
        h = h[tuple(ind)]
    x = fftpack.ifft(Xf * h, axis=axis)
    return x
```
**hilbert2**
```python
x = atleast_2d(x)
    if x.ndim > 2:
        raise ValueError("x must be 2-D.")
    if iscomplexobj(x):
        raise ValueError("x must be real.")
    if N is None:
        N = x.shape
    elif isinstance(N, int):
        if N <= 0:
            raise ValueError("N must be positive.")
        N = (N, N)
    elif len(N) != 2 or cp.any(cp.asarray(N) <= 0):
        raise ValueError(
            "When given as a tuple, N must hold exactly two positive integers"
        )

    Xf = fftpack.fft2(x, N, axes=(0, 1))
    h1 = zeros(N[0], "d")
    h2 = zeros(N[1], "d")
    for p in range(2):
        h = eval("h%d" % (p + 1))
        N1 = N[p]
        if N1 % 2 == 0:
            h[0] = h[N1 // 2] = 1
            h[1 : N1 // 2] = 2
        else:
            h[0] = 1
            h[1 : (N1 + 1) // 2] = 2
        exec("h%d = h" % (p + 1), globals(), locals())

    h = h1[:, newaxis] * h2[newaxis, :]
    k = x.ndim
    while k > 2:
        h = h[:, newaxis]
        k -= 1
    x = fftpack.ifft2(Xf * h, axes=(0, 1))
    return x
```

**Comment by leofang** [comment]
> `hilbert` and `hilbert2` are pretty simple, mainly running `fftpack.fft(2)` and fftpack.ifft(2)`. Is there any reason those would be impacted with the latest changes?

Not that I am aware of. The most recent change on FFT support is #3260, in which I fixed a minor multi-GPU issue. But it should be irrelevant to your code.

I looked at your `hilbert` and `hilbert2` statistics, and I found the timing fluctuated a lot -- the master wins in both min and max! Could it be possible the system was under stress during benchmarking?

**Comment by mnicely** [comment]
I'll re-benchmark them tomorrow. They shouldn't be affected too much because all tests are performed on an isolated GPU, but we'll see!

**Comment by leofang** [comment]
@mnicely I believe this is resolved?

**Comment by mnicely** [comment]
> @mnicely I believe this is resolved?

I actually kicked off some comparisons for cuSignal 0.14 vs. 0.15. https://github.com/rapidsai/cusignal/issues/183
I'll run 0.15 with the latest CuPy v8 and see what we get.

**Comment by mnicely** [comment]
I looks like okay to me. In the worst case some custom kernels are 10% slower (30us). I believe this is acceptable given the extra logic that was added for completeness. 

[cusignal_0-15_0-15v8_comparison.txt](https://github.com/cupy/cupy/files/5090513/cusignal_0-15_0-15v8_comparison.txt)

**Comment by leofang** [comment]
Is this still a concern @mnicely?

**Comment by mnicely** [comment]
It is not, thanks for checking.
