### ISSUE TITLE
cupy.percentile TypeError: data type not understood

### ISSUE THREAD

**Issue by sailfish009** [cupy/cupy#3388]
- CuPy version : 8.0.0b3
  - OS/Platform : ubuntu 20.04 64bit
  - CUDA version : 10.2

* Code to reproduce

```
import torch
import cupy
# import numpy as np

print('cupy version {}'.format(cupy.__version__))
x = torch.Tensor([1, 2, 3])
print(cupy.percentile(x, float(30))) # 30-th percentile of x
# print(cupy.percentile(x, 30)) # same error
# print(np.percentile(x, 30)) # 30-th percentile of x
# 1.6
```

* Error messages, stack traces, or logs

```
$ py test.py 
cupy version 8.0.0b3
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(cupy.percentile(x, float(30))) # 30-th percentile of x
  File "/usr/local/lib/python3.8/dist-packages/cupy-8.0.0b3-py3.8-linux-x86_64.egg/cupy/statistics/order.py", line 189, in percentile
    q = cupy.asarray(q, dtype=a.dtype)
  File "/usr/local/lib/python3.8/dist-packages/cupy-8.0.0b3-py3.8-linux-x86_64.egg/cupy/creation/from_data.py", line 68, in asarray
    return core.array(a, dtype, False, order)
  File "cupy/core/core.pyx", line 1975, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2052, in cupy.core.core.array
  File "cupy/core/core.pyx", line 2121, in cupy.core.core._send_object_to_gpu
TypeError: data type not understood
```

**Comment by sailfish009** [comment]
FYI, same error message with cupy version 7.5.0, ubuntu 18.04 64bit, CUDA 10.1.

**Comment by kmaehashi** [comment]
CuPy functions does not accept torch tensors. See https://docs-cupy.chainer.org/en/latest/reference/interoperability.html#dlpack for more information.

**Comment by sailfish009** [comment]
@kmaehashi thanks for the info!
