### ISSUE TITLE
numpy<1.13 do not have numpy.AxisError 

### ISSUE THREAD

**Issue by gwtnb** [cupy/cupy#342]
When using numpy 1.12.1:
```python
>>> import cupy
>>> cupy.cumprod
<function cumprod at 0x7f9a460b4c80>
>>> cupy.cumprod(cupy.ndarray(()), axis=-10000)                                                                                                                                                             
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/cupy/math/sumprod.py", line 206, in cumprod
    raise numpy.AxisError('axis(={}) out of bounds'.format(axis))
AttributeError: module 'numpy' has no attribute 'AxisError'
```

**Comment by gwtnb** [comment]
`numpy.AxisError` was introduced at https://github.com/cupy/cupy/pull/281.
