### ISSUE TITLE
sparse min/max for negative `axis`

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#3474]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
CuPy Version          : 8.0.0b3
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9000
CUDA Driver Version   : 9000
CUDA Runtime Version  : 9000
cuBLAS Version        : 9000
cuFFT Version         : 9000
cuRAND Version        : 9000
cuSOLVER Version      : (9, 0, 0)
cuSPARSE Version      : 9000
NVRTC Version         : (9, 0)
Thrust Version        : 100900
cuDNN Build Version   : 7300
cuDNN Version         : 7300
NCCL Build Version    : 2005
NCCL Runtime Version  : (unknown)
CUB Version           : None
cuTENSOR Version      : None
```

* Code to reproduce

```
cupyx.scipy.sparse.csc_matrix(cupy.arange(9).astype('f').reshape(3, 3) - 4).min(axis=-1)
```

* Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kataoka/cupy/cupyx/scipy/sparse/data.py", line 284, in min
    return self._min_or_max(axis, out, cupy.min, sum_duplicates, nonzero)
  File "/home/kataoka/cupy/cupyx/scipy/sparse/data.py", line 163, in _min_or_max
    raise ValueError("axis out of range")
ValueError: axis out of range
```
while scipy supports it:
```
>>> scipy.sparse.csc_matrix(np.arange(9).astype('f').reshape(3, 3) - 4).min(axis=-1)
<3x1 sparse matrix of type '<class 'numpy.float32'>'
	with 3 stored elements in COOrdinate format>
```

**Comment by toslunar** [comment]
There seems a bug around here.

https://github.com/cupy/cupy/blob/e9f8efcf36e4018cd92cf20c0bca666238d98203/cupyx/scipy/sparse/data.py#L159-L163
