### ISSUE TITLE
Sparse min/max does not support `axis=None`

### ISSUE THREAD

**Issue by takagi** [cupy/cupy#3506]
Rel #3474.

Sparse min/max does not support `axis=None`, which is the default value for the parameter.

```Python
>>> import cupy
>>> import cupyx
>>> m = cupy.random.rand(100).reshape(10, 10)
>>> m[m < 0.95] = 0
>>> m = cupyx.scipy.sparse.csr_matrix(m)
>>> m.min()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ext-mtakagi/cupy/cupyx/scipy/sparse/data.py", line 284, in min
    return self._min_or_max(axis, out, cupy.min, sum_duplicates, nonzero)
  File "/home/ext-mtakagi/cupy/cupyx/scipy/sparse/data.py", line 163, in _min_or_max
    axis, min_or_max, sum_duplicates, non_zero)
  File "/home/ext-mtakagi/cupy/cupyx/scipy/sparse/data.py", line 139, in _min_or_max_axis
    N = self.shape[axis]
TypeError: tuple indices must be integers or slices, not NoneType
```

**Comment by leofang** [comment]
Hi @takagi, If you're gonna fix this, could you create a fast path for `axis=None` utilizing the existing reduction kernel? Then, the CUB reduction kernels or any other reduction backends (like cuTENSOR, see #2939), when enabled, will automatically kick in. (For any other `axis != None`, I think we will need to rely on the existing implementation.)

**Comment by takagi** [comment]
Sure!
