### ISSUE TITLE
`cupy.array` raises `TypeError` for list of arrays of different dtypes

### ISSUE THREAD

**Issue by asi1024** [cupy/cupy#3576]
`numpy.array` seems to be called unexpectedly in `cupy.array` for such inputs.
```py
>>> cupy.array([cupy.zeros((2, 3), dtype='f'), cupy.zeros((2, 3), dtype='d')])
Traceback (most recent call last):
  ...
    return core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/core/core.pyx", line 1986, in cupy.core.core.array
    cpdef ndarray array(obj, dtype=None, bint copy=True, order='K',
  File "cupy/core/core.pyx", line 2065, in cupy.core.core.array
    return _send_object_to_gpu(obj, dtype, order, ndmin)
  File "cupy/core/core.pyx", line 2132, in cupy.core.core._send_object_to_gpu
    a_cpu = numpy.array(obj, dtype=dtype, copy=False, order=order,
  File "cupy/core/core.pyx", line 1171, in cupy.core.core.ndarray.__array__
    raise TypeError(
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

**Comment by yoshipon** [comment]
Thank you Imanishi-san for making this Issue.
Shouldn't the example use `cupy.array` function instead of `numpy.array` function?

```
cupy.array([cupy.zeros((2, 3), dtype='f'), cupy.zeros((2, 3), dtype='d')])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-2b780e71a55b> in <module>
----> 1 cupy.array([cupy.zeros((2, 3), dtype='f'), cupy.zeros((2, 3), dtype='d')])

~/research/dev-cupy/cupy/cupy/creation/from_data.py in array(obj, dtype, copy, order, subok, ndmin)
     41
     42     """
---> 43     return core.array(obj, dtype, copy, order, subok, ndmin)
     44
     45

~/research/dev-cupy/cupy/cupy/core/core.pyx in cupy.core.core.array()
   1983 # -----------------------------------------------------------------------------
   1984
-> 1985 cpdef ndarray array(obj, dtype=None, bint copy=True, order='K',
   1986                     bint subok=False, Py_ssize_t ndmin=0):
   1987     # TODO(beam2d): Support subok options

~/research/dev-cupy/cupy/cupy/core/core.pyx in cupy.core.core.array()
   2062     # fallback to numpy array and send it to GPU
   2063     # Note: dtype might not be numpy.dtype in this place
-> 2064     return _send_object_to_gpu(obj, dtype, order, ndmin)
   2065
   2066

~/research/dev-cupy/cupy/cupy/core/core.pyx in cupy.core.core._send_object_to_gpu()
   2129         else:
   2130             order = 'C'
-> 2131     a_cpu = numpy.array(obj, dtype=dtype, copy=False, order=order,
   2132                         ndmin=ndmin)
   2133     a_dtype = a_cpu.dtype  # converted to numpy.dtype

~/research/dev-cupy/cupy/cupy/core/core.pyx in cupy.core.core.ndarray.__array__()
   1169         # configure flag that allows implicit conversions to NumPy array.
   1170         # (See https://github.com/cupy/cupy/issues/589 for the detail.)
-> 1171         raise TypeError(
   1172             'Implicit conversion to a NumPy array is not allowed. '
   1173             'Please use `.get()` to construct a NumPy array explicitly.')

TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

**Comment by asi1024** [comment]
Sorry, I fixed the description. Raising `TypeError` for implicit device-to-host conversion: `numpy.array(cupy_arrays)` is intended behavior.
