### ISSUE TITLE
Array masking is surprisingly memory-inefficient

### ISSUE THREAD

**Issue by MrArsGravis** [cupy/cupy#3591]
Masking any type of array with a boolean array seems to use more memory than necessary.
On my system with 11156 MiB of VRAM according to `nvidia-smi`, entering the following in an interactive console:
```
a = cupy.random.random(int(50e7))
b = a > 0.5
```
leads to the following output:
```
>>> a.nbytes/1024**2
3814.697265625
>>> b.nbytes/1024**2
476.837158203125
```
i.e. we should be at roughly 38 % memory usage. However, upon requesting `a[b]`, I get an `OutOfMemoryError`:
```
>>> a[b]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1211, in cupy.core.core.ndarray.__getitem__
  File "cupy/core/_routines_indexing.pyx", line 37, in cupy.core._routines_indexing._ndarray_getitem
  File "cupy/core/_routines_indexing.pyx", line 616, in cupy.core._routines_indexing._getitem_mask_single
  File "cupy/core/_routines_indexing.pyx", line 582, in cupy.core._routines_indexing._prepare_mask_indexing_single
  File "cupy/core/_routines_math.pyx", line 398, in cupy.core._routines_math.scan
  File "cupy/core/core.pyx", line 3022, in cupy.core.core._ndarray_init
  File "cupy/core/core.pyx", line 149, in cupy.core.core.ndarray._init_fast
  File "cupy/cuda/memory.pyx", line 569, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1241, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1262, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 930, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 950, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1201, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 2,000,000,000 bytes (allocated so far: 10,100,000,256 bytes).
```
Even if the entire array `a` is copied during the masking operation, that should only occupy <73% of total RAM, i.e. there should still be a comfortable 3 GiB left over. Is this expected behavior? If so, is there a way to circumvent this? Unfortunately, I wasn't able to follow the chain of calls in the error message to check the source and see where the requested memory allocation came from.

output of `python -c 'import cupy; cupy.show_config()'`:
```
CuPy Version          : 8.0.0b4
CUDA Root             : /opt/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
Thrust Version        : 100907
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2604
NCCL Runtime Version  : 2604
CUB Version           : None
cuTENSOR Version      : None
```

**Comment by leofang** [comment]
Have you built CuPy from the latest master branch? I think `cupy.core._routines_math.scan` recently got a bit of improvement (#3540). I have no problem running your example, and `nvidia-smi` showed I used 8313MiB out of 11019MiB.

**Comment by MrArsGravis** [comment]
No, I was on a somewhat older version of v8.0.0b4 (whatever pip fed me a while ago). I'm building the latest version right now.

Oddly, after closing and relaunching python, I wasn't able to reliably reproduce the error with the example I gave above either, but I did observe 10177MiB / 11156MiB usage in `nvidia-smi`, so we'll see if the latest build brings improvements. However, this matches my experience in the actual code as well, which ran out of memory at somewhat random points as well despite being deterministic (i.e. should execute the same way every time).

**Comment by MrArsGravis** [comment]
(After unknowingly battling with a completely different issue ([#2157](https://github.com/cupy/cupy/issues/2157)) for far too long,) I can confirm that the latest build uses considerably (2 GiB) less VRAM less than the previous one: My example now results in 8273MiB / 11156MiB usage. Thanks for the hint!
