### ISSUE TITLE
Warn if nvcc found in PATH does not match with `$CUDA_PATH/bin/nvcc`

### ISSUE THREAD

**Issue by Char-Aznable** [cupy/cupy#3600]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version github repo 7f24cb5a5
  - OS/Platform CentOS 7.8.2003
  - CUDA version 11.0 
  - cuDNN/NCCL version (if applicable)
* Code to reproduce
```bash
export LC_ALL="en_US.UTF-8"
export CUDA_PATH=$LINUXBREWHOME/Cellar/cuda/11.0
export CC=$LINUXBREWHOME/opt/gcc@9/bin/gcc-9
export CXX=$LINUXBREWHOME/opt/gcc@9/bin/g++-9 
export LIBRARY_PATH="${CUDA_PATH}/lib"
export LD_LIBRARY_PATH="${CUDA_PATH}/lib:${LD_LIBRARY_PATH}"
export NVCC="nvcc --compiler-bindir $LINUXBREWHOME/opt/gcc@9/bin"
pip install . -vvvv
```
* Error messages, stack traces, or logs
```
    building 'cupy.cuda.nvtx' extension
    //home/aznb/.pyenv/versions/3.8.3/include/python3.8 -c cupy/cuda/nvtx.cpp -o build/temp.linux-x86_64-3.8/cupy/cuda/nvtx.o -fopenmp
    //home/aznb/.linuxbrew/Cellar/cuda/11.0/lib
    building 'cupy_backends.cuda.libs.cutensor' extension
    //home/aznb/.pyenv/versions/3.8.3/include/python3.8 -c cupy_backends/cuda/libs/cutensor.cpp -o build/temp.linux-x86_64-3.8/cupy_backends/cuda/libs/cutensor.o -fopenmp
    //home/aznb/.linuxbrew/Cellar/cuda/11.0/lib
    building 'cupy.cuda.cub' extension
    //home/aznb/.pyenv/versions/3.8.3/include/python3.8 -c cupy/cuda/cub.cpp -o build/temp.linux-x86_64-3.8/cupy/cuda/cub.o -fopenmp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/160405612.1.noble-long.q/pip-req-build-lj1opkee/setup.py", line 169, in <module>
        setup(
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/160405612.1.noble-long.q/pip-req-build-lj1opkee/cupy_setup_build.py", line 1012, in run
        build_ext.build_ext.run(self)
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "//home/aznb/.pyenv/versions/3.8.3/lib/python3.8/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/tmp/160405612.1.noble-long.q/pip-req-build-lj1opkee/cupy_setup_build.py", line 868, in _compile
        base_opts = build.get_compiler_base_options()
      File "/tmp/160405612.1.noble-long.q/pip-req-build-lj1opkee/install/build.py", line 232, in get_compiler_base_options
        _compiler_base_options = _get_compiler_base_options()
      File "/tmp/160405612.1.noble-long.q/pip-req-build-lj1opkee/install/build.py", line 270, in _get_compiler_base_options
        stderrdata.decode('utf8'))
    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 4-5: invalid continuation byte
    Running setup.py install for cupy: finished with status 'error'
ERROR: Command errored out with exit status 1: //home/aznb/.pyenv/versions/3.8.3/envs/loos/include/site/python3.8/cupy Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 827, in install
    success = install_legacy(
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 86, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 185, in wrapper
    return func(self, options, args)
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 398, in run
    installed = install_given_reqs(
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/req/__init__.py", line 67, in install_given_reqs
    requirement.install(
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 845, in install
    six.reraise(*exc.parent)
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 270, in runner
    call_subprocess(
  File "//home/aznb/.pyenv/versions/3.8.3/envs/loos/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: //home/aznb/.pyenv/versions/3.8.3/envs/loos/include/site/python3.8/cupy Check the logs for full command output.
Removed build tracker: '/tmp/160405612.1.noble-long.q/pip-req-tracker-rwqitlud'

```

**Comment by leofang** [comment]
I guess something is wrong in you nvcc, and then the error message got shadowed. Could you check your nvcc works by compiling something?

**Comment by Char-Aznable** [comment]
I have been working with same installation of CUDA 11 on the same machine in a lot of c++ applications. I haven't encountered any nvcc issues so far.

**Comment by leofang** [comment]
Could you try this: modify the source code here
https://github.com/cupy/cupy/blob/d99578753dd868a81d38cbd7f047a5eab92a0876/install/build.py#L267-L271
to not decode, and see if the (raw) error message can be printed out or not?

**Comment by Char-Aznable** [comment]
OK. Trying that now. Is there a way to speed up the build process? As far as I can tell, the build start from scratch rebuilding everything and it's doing it with 1 CPU core.

**Comment by Char-Aznable** [comment]
The error message is: `b'cc1plus: fatal error: cuda_runtime.h: No such file or directory\ncompilation terminated.\n'`

which is weird because earlier in the log, the cuda include path is set up correctly:
```
Include directories: ['/home/aznb/.linuxbrew/Cellar/cuda/11.0/include/cub', '/data/scratch/ssd/tmp/160441231.1.long.q/pip-req-build-tm1iq8f4/install/../cupy/core/include', '/home/aznb/.linuxbrew/Cellar/cuda/11.0/include']
```
and I can confirm that 
```
ls -lh /home/aznb/.linuxbrew/Cellar/cuda/11.0/include/cuda_runtime.h
-rw-r--r-- 1 aznb aznb 87K Jul  9 10:56 /home/aznb/.linuxbrew/Cellar/cuda/11.0/include/cuda_runtime.h
```
@leofang Is there a way to print out the exact nvcc command line from the build?

**Comment by leofang** [comment]
Could you try setting `CLFAGS` and `LDFLAGS`? On some OS this could help locate non-default CUDA installations. Putting `CUDA_PATH=...` right before `pip` might also help:
https://docs.cupy.dev/en/stable/install.html#working-with-custom-cuda-installation

**Comment by Char-Aznable** [comment]
setting CLFAGS LDFLAGS didn't work. I got the same error. `CUDA_PATH` is already exported in the build script. Putting it before calling pip didn't make a difference either. We need to see which `nvcc` command gives the error but I don't know how to find it out

**Comment by leofang** [comment]
We already by default output the full nvcc command, but I think the error happens right before that step, so you don't see that.

**Comment by kmaehashi** [comment]
Could you check `which nvcc` to see if nvcc under `$LINUXBREWHOME/Cellar/cuda/11.0` is used?

**Comment by leofang** [comment]
Another try: `export NVCC="nvcc --compiler-bindir $LINUXBREWHOME/opt/gcc@9/bin/gcc-9`.

**Comment by Char-Aznable** [comment]
What actually works `export NVCC="${CUDA_PATH}/bin/nvcc --compiler-bindir $LINUXBREWHOME/opt/gcc@9/bin"` which seems like a bug in the build config because `${CUDA_PATH}/bin` is actually in my `$PATH` and the build system should just look up `nvcc` in `${CUDA_PATH}/bin` anyway and should not risk allowing the user to set `$NVCC` to a different version of CUDA than ``${CUDA_PATH}`. Also, that `nvcc` is the only one I have on the system and I don't see how it would complain about missing header given all the path set up the way in the OP

**Comment by Char-Aznable** [comment]
As in the OP's setup: `nvcc = ['nvcc', '--compiler-bindir', '/home/aznb/.linuxbrew/opt/gcc@9/bin'] cuda = /home/aznb/.linuxbrew/Cellar/cuda/11.0`

**Comment by leofang** [comment]
My experience is setuptools usually has a bad interaction with `$PATH` and other env setups. In your case, if `$NVCC` is set then we just use it as is without expanding the full path to `nvcc`. Might be what happened to you. The easiest way to confirm this issue is to unset `$NVCC` while keeping other env setups intact, and see if it builds.

**Comment by Char-Aznable** [comment]
This won't work because I have to use `--compiler-bindir` to use gcc 9. Like a said, this `$NVCC` and `CUDA_PATH` setup is a bug to allow inconsistent `nvcc` and cuda library configured into the build. You could get silent errors in runtime that would be impossible to debug if the program is linked to the wrong cuda library. Without looking into the details of your setuptools code, the obvious solution would be to remove `$NVCC` setup,  ask the users to set only `CUDA_PATH`, look up `nvcc` in `CUDA_PATH` and set an `$NVCC_OPTIONS` to allow user to pass the compiler option like `--compiler-bindir` to `nvcc`

**Comment by Char-Aznable** [comment]
Also, more advanced build system like cmake and meson has their own way to detect cuda library without having to messing around with environment variables, which might be another way to go forward considering also that setuptool is so slow

**Comment by kmaehashi** [comment]
In current design, `CUDA_PATH` is automatically inferred from `nvcc` command found in `PATH`.
https://docs.cupy.dev/en/latest/install.html#working-with-custom-cuda-installation

`$NVCC` is mainly intended for use in conjunction with `ccache`, e.g., `export NVCC="ccache nvcc"`, so that's why we don't implement`$NVCC_OPTIONS`.

> Like I said, this `$NVCC` and `CUDA_PATH` setup is a bug to allow inconsistent `nvcc` and cuda library configured into the build.

I think it's reasonable to warn users if `$CUDA_PATH/bin/nvcc` != (`nvcc` found via `PATH`).

**Comment by leofang** [comment]
Sorry, I thought I replied...

> I think it's reasonable to warn users if `$CUDA_PATH/bin/nvcc` != (`nvcc` found via `PATH`).

We actually did this already: https://github.com/cupy/cupy/blob/dce046a8f3ccdb5688de89208d997ce987f05517/install/build.py#L64-L68
And in fact the op's `nvcc` *is* in `PATH`. The problem here is when setting `NVCC`, for some reason `subprocess` needs to know the full path to `nvcc`:
https://github.com/cupy/cupy/blob/dce046a8f3ccdb5688de89208d997ce987f05517/install/build.py#L246-L249

>> Like I said, this `$NVCC` and `CUDA_PATH` setup is a bug to allow inconsistent `nvcc` and cuda library configured into the build.

@Char-Aznable What if you only set `NVCC` but not `CUDA_PATH`?

>> Also, more advanced build system like cmake and meson has their own way to detect cuda library without having to messing around with environment variables, which might be another way to go forward considering also that setuptool is so slow

Unfortunately cmake is rarely used in mainstream Python projects. Unlike C/C++ projects, the entire Python ecosystem is built upon pip, setuptools, disutils, etc, and with all of our Cython codes floating around, I don't see how cmake could even work. 

I never heard of meson before, so I don't have enough knowledge to judge.

**Comment by leofang** [comment]
btw @kmaehashi the title should be `nvcc` not `nccl` 😁

**Comment by Char-Aznable** [comment]
Sorry I can't afford going back to testing only setting `CUDA_PATH` but not `NVCC` because it took too long to start the build to reach the point where the bug shows up. I can watch this in the future. 

BTW, there are ways to build c++/c code in a python project using cmake, e.g., `pytorch` does that, and there are a lot of examples in this regard. The major pain point here is that the setuptool only allow single-threaded compilation, which makes debugging and deploying code very slow.

**Comment by leofang** [comment]
> because it took too long to start the build to reach the point where the bug shows up

I wonder what's the hardware setup you're using. How long exactly are we talking here? To reach the point where `cupy.cuda.cub` is built isn't that long (less than 10 mins if building from scratch, single threaded). Unfortunately it seems you didn't build with the `-e` flag, otherwise I have a very dirty hack allowing you to reach to the failing point in 1 minute 😁

> there are ways to build c++/c code in a python project using cmake, e.g., `pytorch` does that, and there are a lot of examples in this regard.

OK, I know PyTorch uses cmake, but it's because their ATen tensor library, which is a huge portion of the whole repo, is all C++. In CuPy, we only have two modules (`thrust` and `cub`) that have some C++ codes. It simply makes little sense to migrate when our build system is already mature and has ways to further speed up (see below).

>  The major pain point here is that the setuptool only allow single-threaded compilation, which makes debugging and deploying code very slow.

Did you know you can do this?
```bash
python setup.py build -j 8
python setup.py install
```
This just works. On my system together with `export CUPY_NVCC_GENERATE_CODE="arch=compute_75,code=sm_75"` (to avoid building for other CCs that mismatch my local GPUs), it took less than two minutes to start building `cupy.cuda.cub` and 6.5 mins in total for an end-to-end build. I don't remember where I first learned this, but NumPy also recommends it: https://numpy.readthedocs.io/en/latest/user/building.html#parallel-builds. 

The `ccache` thing that @kmaehashi mentioned earlier will also accelerate it significantly for the second build onward.

**Comment by leofang** [comment]
btw, if the purpose of building from source is for debugging, you really should add the `-e` flag to build in place: `pip install -v -e .`

**Comment by Char-Aznable** [comment]
Problem with the parallel "-j" option is that the error message was mingled with other lines of report such that it is impossible to tell where the error shows up. This adding to the fact that the utf-8 decoding failure makes me think that some bug is going on in this setup.

**Comment by leofang** [comment]
> it is impossible to tell where the error shows up

The error shows up when building `cupy.cuda.cub`. If you could give it a shot I would be able to help address any potential issues.

**Comment by leofang** [comment]
Not sure if there's anything actionable given that we do already warn for potential mismatch (https://github.com/cupy/cupy/issues/3600#issuecomment-663677116), closing.
