### ISSUE TITLE
undefined symbol: cusparseScsrgemm

### ISSUE THREAD

**Issue by mnicely** [cupy/cupy#3619]
I discovered the following issue trying to build CuPy master with 
1. CUDA 11.0.194
2. Ubuntu 20.04
3. RTX Titan
4. R450.51.05

```bash
(cusignal-dev) belt@orion:~/workStuff/cupy$ python -c 'import cupy; cupy.show_config()'
Traceback (most recent call last):
  File "/home/belt/workStuff/cupy/cupy/__init__.py", line 19, in <module>
    from cupy import core  # NOQA
  File "/home/belt/workStuff/cupy/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
    # distutils: language = c++
  File "/home/belt/workStuff/cupy/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/belt/workStuff/cupy/cupy/cuda/compiler.py", line 10, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 10, in init cupy.cuda.device
    from cupy_backends.cuda.libs import cusparse
ImportError: /home/belt/workStuff/cupy/cupy_backends/cuda/libs/cusparse.cpython-38-x86_64-linux-gnu.so: undefined symbol: cusparseScsrgemm

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/belt/workStuff/cupy/cupy/__init__.py", line 40, in <module>
    raise ImportError(msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: /home/belt/workStuff/cupy/cupy_backends/cuda/libs/cusparse.cpython-38-x86_64-linux-gnu.so: undefined symbol: cusparseScsrgemm
```

Tried running
```bash
pip uninstall cupy
git clean -fdx
```
as well as
download a new cupy.

**Comment by anaruse** [comment]
It looks like you're importing old CUDA-build CuPy modules in the CUDA 11 environment.
Could you show us the following part of the log when you built CuPy?
```
************************************************************
* CuPy Configuration Summary                               *
************************************************************

Build Environment:
  Include directories: ['/usr/local/cuda-11.0.2/include/cub', '/home/anaruse/work/CUPY/cupy/install/../cupy/core/include', '/usr/local/cuda-11.0.2/include']
  Library directories: ['/usr/local/cuda-11.0.2/lib64']
  nvcc command       : ['/usr/local/cuda-11.0.2/bin/nvcc']

Environment Variables:
  CFLAGS          : (none)
  LDFLAGS         : (none)
  LIBRARY_PATH    : (none)
  CUDA_PATH       : /usr/local/cuda-11.0.2
  NVTOOLSEXT_PATH : (none)
  NVCC            : (none)
  ROCM_HOME       : (none)
  CUPY_CUB_PATH   : (none)

Modules:
  cuda      : Yes (version 11000)
  cusolver  : Yes
  cudnn     : No
    -> Include files not found: ['cudnn.h']
    -> Check your CFLAGS environment variable.
  nccl      : No
    -> Include files not found: ['nccl.h']
    -> Check your CFLAGS environment variable.
  nvtx      : Yes
  cutensor  : No
    -> Include files not found: ['cutensor.h']
    -> Check your CFLAGS environment variable.
  cub       : Yes (version 100909)
  thrust    : Yes (version 100909)
```

**Comment by kmaehashi** [comment]
Closing as it seems stale. Please feel free to reopen when needed.

**Comment by giangnguyen2412** [comment]
It seems you have a wrong version of cupy. It should be same with your cuda version. Run
```
import torch

print(torch.version.cuda)
```
to the version of CUDA. For exampe, mine was 11.3, then I install: ```pip install cupy-cuda113```. Please remember to uninstall any cupy versions you installed before. For example, I had to uninstall ```pip install cupy-cuda114``` before uninstall the correct one from my side. ```nvidia-smi``` seems to display the wrong version name.

**Comment by leofang** [comment]
> nvidia-smi seems to display the wrong version name.

It's a common pitfall. `nvidia-smi` does NOT display the CUDA Toolkit version installed on your system (there could be multiple versions!), instead it is saying "up to which CTK version it would definitely work without any caveat". This is also the version you'd get when you query [cudaDriverGetVersion](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html#group__CUDART____VERSION_1g8a06ee14a0551606b7c780084d5564ab).
