### ISSUE TITLE
Support Optuna v2

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#3686]
- [x] CI https://github.com/chainer/chainer-test/pull/599
- [x] Docs https://github.com/cupy/cupy/pull/3842

----

For some reason, doc build test is failing against Optuna v2 which is released today.

https://jenkins.preferred.jp/job/chainer/job/cupy_master/TEST=cupy-doc,label=mn1-p100/783/console

```
19:01:19 + make html
19:01:19 sphinx-build -b html -d build/doctrees  -W source build/html
19:01:19 Running Sphinx v2.0.1
19:01:19 
19:01:19 Configuration error:
19:01:19 There is a programmable error in your configuration file:
19:01:19 
19:01:19 Traceback (most recent call last):
19:01:19   File "/home/user/.local/lib/python3.5/site-packages/sphinx/config.py", line 361, in eval_config_file
19:01:19     execfile_(filename, namespace)
19:01:19   File "/home/user/.local/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
19:01:19     exec(code, _globals)
19:01:19   File "/work/cupy/docs/source/conf.py", line 42, in <module>
19:01:19     f.write(_comparison_generator.generate())
19:01:19   File "/work/cupy/docs/source/_comparison_generator.py", line 92, in generate
19:01:19     'numpy', 'cupy')
19:01:19   File "/work/cupy/docs/source/_comparison_generator.py", line 77, in _section
19:01:19     ) + [
19:01:19   File "/work/cupy/docs/source/_comparison_generator.py", line 30, in _generate_comparison_rst
19:01:19     cp_obj, cp_fmt = _import(cupy_mod, klass)
19:01:19   File "/work/cupy/docs/source/_comparison_generator.py", line 17, in _import
19:01:19     obj = importlib.import_module(mod)
19:01:19   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
19:01:19     return _bootstrap._gcd_import(name[level:], package, level)
19:01:19   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
19:01:19   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
19:01:19   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
19:01:19   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
19:01:19   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
19:01:19   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
19:01:19   File "/work/cupy/cupy/__init__.py", line 45, in <module>
19:01:19     import cupyx as _cupyx
19:01:19   File "/work/cupy/cupyx/__init__.py", line 11, in <module>
19:01:19     from cupyx import optimizing  # NOQA
19:01:19   File "/work/cupy/cupyx/optimizing/__init__.py", line 1, in <module>
19:01:19     from cupyx.optimizing._optimize import optimize  # NOQA
19:01:19   File "/work/cupy/cupyx/optimizing/_optimize.py", line 6, in <module>
19:01:19     import optuna
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/__init__.py", line 7, in <module>
19:01:19     from optuna import importance  # NOQA
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/importance/__init__.py", line 5, in <module>
19:01:19     from optuna.importance._base import BaseImportanceEvaluator
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/importance/_base.py", line 12, in <module>
19:01:19     from optuna.samplers import intersection_search_space
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/samplers/__init__.py", line 1, in <module>
19:01:19     from optuna.samplers._search_space import intersection_search_space  # NOQA
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/samplers/_search_space.py", line 8, in <module>
19:01:19     from optuna.study import BaseStudy
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/study.py", line 14, in <module>
19:01:19     from optuna._imports import try_import
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/_imports.py", line 7, in <module>
19:01:19     class _DeferredImportExceptionContextManager(object):
19:01:19   File "/usr/local/lib/python3.5/dist-packages/optuna/_imports.py", line 29, in _DeferredImportExceptionContextManager
19:01:19     exc_type: Optional[Type[Exception]],
19:01:19   File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
19:01:19     return Union[arg, type(None)]
19:01:19   File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
19:01:19     dict(self.__dict__), parameters, _root=True)
19:01:19   File "/usr/lib/python3.5/typing.py", line 512, in __new__
19:01:19     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
19:01:19   File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
19:01:19     for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
19:01:19   File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
19:01:19     if super().__subclasscheck__(cls):
19:01:19   File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
19:01:19     for scls in cls.__subclasses__():
19:01:19 TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```
Currently we tentatively use Optuna v1 but we need to resolve this issue in v8.
https://github.com/chainer/chainer-test/pull/592

**Comment by leofang** [comment]
@kmaehashi It seems to be a Python 3.5 issue:
- https://stackoverflow.com/a/56010650/2344149
- https://github.com/python/typing/issues/266#issuecomment-436812207

If we follow NEP 29 then this won't be a problem 😁

**Comment by kmaehashi** [comment]
Thanks, it seems that Optuna v2 does not support Python 3.5.2 or earlier.
