### ISSUE TITLE
Unable to install cupy-cuda110 via pip on Ubuntu

### ISSUE THREAD

**Issue by pranny** [cupy/cupy#3974]
I am unable to install cupy-cuda110 from pip. My CUDA version is 11.0, so I believe I need this to get going. The weird part is that pip search shows this package. I am on the latest version of setuptools.

```
$ python3 -m pip  search cupy-cuda110
cupy-cuda110 (7.8.0)                        - CuPy: NumPy-like API accelerated with CUDA
cupy (7.8.0)                                - CuPy: NumPy-like API accelerated with CUDA
  INSTALLED: 7.8.0 (latest)
cupy-cuda101 (7.8.0)                        - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda102 (7.8.0)                        - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda80 (7.8.0)                         - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda90 (7.8.0)                         - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda92 (7.8.0)                         - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda100 (7.8.0)                        - CuPy: NumPy-like API accelerated with CUDA
cupy-cuda91 (7.8.0)                         - CuPy: NumPy-like API accelerated with CUDA
cupy-ibmopt (4.0.0a3)                       - CuPy: NumPy-like API accelerated with CUDA (opbimized for POWER machines by IBM)
nvidia-dali-cuda110 (0.0.1.dev0)            - A fake package to warn the user he is not installing the correct package.
nvidia-dali-tf-plugin-cuda110 (0.0.1.dev0)  - A fake package to warn the user he is not installing the correct package.
clpy (0.0.0a0)                              - ClPy: OpenCL backend for CuPy
voltools (0.4.2)                            - CUDA-accelerated 3D affine transformations for NumPy and CuPy
pynvvl-cuda91 (0.0.3a2)                     - PyNVVL: A Python wrapper for NVIDIA Video Loader (NVVL) with CuPy
shinnosuke-gpu (0.7.1)                      - A keras-like API deep learning framework,realized by cupy
quantpycupy (0.0.1.dev1)                    - QuantPy Plugin using CuPy, that extends quantum Executor/Simulator.
pynvvl-cuda90 (0.0.3a2)                     - PyNVVL: A Python wrapper for NVIDIA Video Loader (NVVL) with CuPy
pynvvl-cuda80 (0.0.3a2)                     - PyNVVL: A Python wrapper for NVIDIA Video Loader (NVVL) with CuPy
pynvvl-cuda92 (0.0.3a2)                     - PyNVVL: A Python wrapper for NVIDIA Video Loader (NVVL) with CuPy
kde-gpu (0.1.0)                             - We implemented nadaraya waston kernel density and kernel conditional probability estimator using cuda through cupy. It is much
                                              faster than cpu version but it requires GPU with high memory.
```

Now when I install it, 

```
$ python3 -m pip install cupy-cuda110 -v
Using pip 20.2.3 from /home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip (python 3.6)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-olt147am
Created temporary directory: /tmp/pip-req-tracker-zcbiyep_
Initialized build tracking at /tmp/pip-req-tracker-zcbiyep_
Created build tracker: /tmp/pip-req-tracker-zcbiyep_
Entered build tracker: /tmp/pip-req-tracker-zcbiyep_
Created temporary directory: /tmp/pip-install-zr79gj6i
1 location(s) to search for versions of cupy-cuda110:
* https://pypi.org/simple/cupy-cuda110/
Fetching project page and analyzing links: https://pypi.org/simple/cupy-cuda110/
Getting page https://pypi.org/simple/cupy-cuda110/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/cupy-cuda110/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/cupy-cuda110/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: cp36-cp36m-win_amd64: https://files.pythonhosted.org/packages/63/ab/07a33802f63dd6987d3a9e6bde15dbb06f1bced82d367fe21387a9a2eb99/cupy_cuda110-7.8.0-cp36-cp36m-win_amd64.whl#sha256=363ba06e8d345b70d551268c88d059ac844cf38d2ea24ea3e8baa5c966c5ad62 (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
  Skipping link: none of the wheel's tags match: cp37-cp37m-win_amd64: https://files.pythonhosted.org/packages/c6/86/829bd3592633a1e67946aa6e8b19d1154d1f83c7bfdf6edb2e6fca9c5008/cupy_cuda110-7.8.0-cp37-cp37m-win_amd64.whl#sha256=631fd7a7c26f5c241c4c9bf8cf1d98767b64c342444efd5612d21ee4925e8153 (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://files.pythonhosted.org/packages/3f/00/4091510a6569e913c9a47f5368fbfbb5619c0930a9dc1a3d3a0a0f5a8386/cupy_cuda110-7.8.0-cp38-cp38-win_amd64.whl#sha256=587b263c08439b8b2fac4fa98d7d0acf673cb6a13f50d80005af665743b75461 (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
  Skipping link: none of the wheel's tags match: cp36-cp36m-win_amd64: https://files.pythonhosted.org/packages/83/86/ad0896ae8eff40d1737c0cbaa531dda5fd6be037f027ad42ddf001a3daae/cupy_cuda110-8.0.0rc1-cp36-cp36m-win_amd64.whl#sha256=ec66194c203832b7c27805b66f89e515f6bd841259c35f1888e28919e07baae6 (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
  Skipping link: none of the wheel's tags match: cp37-cp37m-win_amd64: https://files.pythonhosted.org/packages/e5/1d/50f2ded03fec64e9fb30981f33e6fa4c918b6ff6acaec16a8b0070afd786/cupy_cuda110-8.0.0rc1-cp37-cp37m-win_amd64.whl#sha256=e156771c1538f43439b6bb200d8ee893607e7262c42a0aa410a3449dd2c65668 (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
  Skipping link: none of the wheel's tags match: cp38-cp38-win_amd64: https://files.pythonhosted.org/packages/e4/cc/d79f999269abd9373e565b2378b4e383cebcc896198d4931ce8691ae7bd7/cupy_cuda110-8.0.0rc1-cp38-cp38-win_amd64.whl#sha256=5512e1487e0fa06958dbeef45ddc3e6e71b1c855c067794ad2c63525cb02db2d (from https://pypi.org/simple/cupy-cuda110/) (requires-python:>=3.5.0)
Given no hashes to check 0 links for project 'cupy-cuda110': discarding no candidates
ERROR: Could not find a version that satisfies the requirement cupy-cuda110 (from versions: none)
ERROR: No matching distribution found for cupy-cuda110
Exception information:
Traceback (most recent call last):
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/home/ppinazuredlvm1/.local/lib/python3.6/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for cupy-cuda110
Removed build tracker: '/tmp/pip-req-tracker-zcbiyep_'
```

My Python version is 3.6.9

```
$ python3 --version
Python 3.6.9

$ python3 -m pip list | grep setuptools
setuptools              50.3.0

$ python3 -m pip list | grep pip
pip                     20.2.3
```

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
$ python3 -c 'import cupy; cupy.show_config()'
CuPy Version          : 7.8.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 9010
CUDA Driver Version   : 11000
CUDA Runtime Version  : 9010
cuBLAS Version        : 9010
cuFFT Version         : 9010
cuRAND Version        : 9010
cuSOLVER Version      : (9, 1, 0)
cuSPARSE Version      : 9010
NVRTC Version         : (9, 1)
cuDNN Build Version   : None
cuDNN Version         : None
NCCL Build Version    : None
NCCL Runtime Version  : None
CUB Version           : None
cuTENSOR Version      : None
```

  - OS/Platform: Linux (ubuntu 18.04), x86_64, 
  - GPU Details

```
$ nvidia-smi
Wed Sep  9 18:39:13 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00007DEE:00:00.0 Off |                    0 |
| N/A   37C    P8    25W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ uname -a
Linux dlvm1 5.4.0-1025-azure #25~18.04.1-Ubuntu SMP Sat Sep 5 15:28:57 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I read in [some other thread](https://github.com/cupy/cupy/issues/2137#issuecomment-482532472) that 32 bit vs 64 bit Python might be the cause, so I used [this SO answer](https://stackoverflow.com/a/1406210/229341) to verify that my Python is 64 bit and matches with the OS

```
$ python3 -c 'import ctypes;print(ctypes.sizeof(ctypes.c_voidp))'
8
```

Thanks a lot in advance. Let me know if anything else is needed.

**Comment by leofang** [comment]
As far as I can tell, there is no Linux wheels for CUDA 11 on PyPI. The PyPI team has not responded the CuPy team's request for it, and you need to download the wheel in the Release Note (see also the explanation there): https://github.com/cupy/cupy/releases/tag/v7.8.0

**Comment by pranny** [comment]
Such an easy fix. Thanks for the super quick response.
