### ISSUE TITLE
cupy.cumsum unable to cast argument from list to cupy.ndarray in 8.0.0rc1

### ISSUE THREAD

**Issue by reikdas** [cupy/cupy#3984]
For cupy version 7.8.0, 

```
CuPy Version          : 7.8.0
CUDA Root             : /usr/local/cuda
CUDA Build Version    : 10020
CUDA Driver Version   : 10020
CUDA Runtime Version  : 10020
cuBLAS Version        : 10202
cuFFT Version         : 10102
cuRAND Version        : 10102
cuSOLVER Version      : (10, 3, 0)
cuSPARSE Version      : 10301
NVRTC Version         : (10, 2)
cuDNN Build Version   : 7605
cuDNN Version         : 7605
NCCL Build Version    : 2406
NCCL Runtime Version  : 2708
CUB Version           : None
cuTENSOR Version      : None
```

This works - 
```
>>> import cupy
>>> cupy.cumsum([3, 5, 5, 0, 2], out=cupy.empty(5))
array([ 3.,  8., 13., 13., 15.])
```

But for cupy 8.0.0rc1

```
CuPy Version          : 8.0.0rc1
CUDA Root             : /opt/cuda
CUDA Build Version    : 11000
CUDA Driver Version   : 11000
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : 8002
cuDNN Version         : 8002
NCCL Build Version    : None
NCCL Runtime Version  : None
cuTENSOR Version      : None
```

I get an error - 
```
>>> import cupy
>>> cupy.cumsum([3, 5, 5, 0, 2], out=cupy.empty(5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reik/.local/lib/python3.8/site-packages/cupy/math/sumprod.py", line 157, in cumsum
    return _math.scan_core(a, axis, _math.scan_op.SCAN_SUM, dtype, out)
TypeError: Argument 'a' has incorrect type (expected cupy.core.core.ndarray, got list)
```

I think `cupy.cumsum` is no longer able to cast Python lists to cupy.ndarrays implicitly from version 8.0.0rc1?

**Comment by leofang** [comment]
I think it was actually a mistake that we "accidentally" fixed in v8. (We meant to fix the slow performance for `cumsum`/`cumprod`: #2907). In general, CuPy's functions do not accept Python lists or NumPy arrays as input, except for the entry functions (i.e. array creation routines) and a few other cases, so we don't have test suites that cover this usage and didn't notice this support was gone at all, because it shouldn't be there in the first place. 

cc: @emcastillo
