### ISSUE TITLE
OutOfMemoryError: out of memory to allocate 

### ISSUE THREAD

**Issue by potato-patata** [cupy/cupy#4019]
I am working on layer wise relevance propagation tool for explainable project.
I am getting this error with large dataset.

I tried all the things mentioned in previous issues like

1. Tried converting variables to 'float32'
2. Tried Reduction Kernels
3.  Tried passing data in batches as well

As you can see, it runs for several iterations and then gives an error.
**Output Screen:**
15000 , 200 , 0.001 (15000 is number of iterations, 200 is batch size and 0.001 is learning rate)
Train: [129915 213708   3506 ... 173685  43567 199340] Validation: [  9207 209649 205105 ... 224967 101436 168717]
loading np-formatted data from teleco_ima_ch_2dense_15000_200_0.001_val_1.npy
loading np-formatted data from teleco_train_lab_ch_2dense_15000_200_0.001_val_1.npy
loading np-formatted data from teleco_test_ima_ch_2dense_15000_200_0.001_val_1.npy
loading np-formatted data from teleco_test_lab_ch_2dense_15000_200_0.001_val_1.npy
15000 , 200 , 0.001
batch# 25, lrate 0.001, l1-loss 0.6156
batch# 50, lrate 0.001, l1-loss 0.5528
batch# 75, lrate 0.001, l1-loss 0.5374
batch# 100, lrate 0.001, l1-loss 0.5519
batch# 125, lrate 0.001, l1-loss 0.5571
batch# 150, lrate 0.001, l1-loss 0.5503
batch# 175, lrate 0.001, l1-loss 0.5507
batch# 200, lrate 0.001, l1-loss 0.6165
batch# 225, lrate 0.001, l1-loss 0.5027
Accuracy after 250 iterations on validation set: 79.98444617264748% (l1-loss: 0.5433)
    New loss-optimal parameter set encountered. saving....
    Estimate time until current training ends : 0d 0h 10m 26s (1.67% done)
batch# 275, lrate 0.001, l1-loss 0.5504
batch# 300, lrate 0.001, l1-loss 0.5231
batch# 325, lrate 0.001, l1-loss 0.4971
batch# 350, lrate 0.001, l1-loss 0.5689
batch# 375, lrate 0.001, l1-loss 0.554
batch# 400, lrate 0.001, l1-loss 0.5686
batch# 425, lrate 0.001, l1-loss 0.5536
batch# 450, lrate 0.001, l1-loss 0.5038
batch# 475, lrate 0.001, l1-loss 0.5743
Using TensorFlow backend.
Accuracy after 500 iterations on validation set: 80.6954782801911% (l1-loss: 0.5402)
    New loss-optimal parameter set encountered. saving....
Traceback (most recent call last):
  File "/home/ICTDOMAIN/456095/virtual_gpu/xplainit/teleco_churn_28_CV_linear2000_2dense_test.py", line 455, in <module>
    lrate = z)
  File "/home/ICTDOMAIN/456095/virtual_gpu/xplainit/lrp_toolbox/python/modules/sequential.py", line 246, in train
    bestLayers = copy.deepcopy(self.modules)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/ICTDOMAIN/456095/virtual_gpu/lib/python3.5/copy.py", line 166, in deepcopy
    y = copier(memo)
  File "cupy/core/core.pyx", line 1124, in cupy.core.core.ndarray.__deepcopy__
  File "cupy/core/core.pyx", line 1125, in cupy.core.core.ndarray.__deepcopy__
  File "cupy/core/core.pyx", line 436, in cupy.core.core.ndarray.copy
  File "cupy/core/core.pyx", line 392, in cupy.core.core.ndarray.astype
  File "cupy/core/core.pyx", line 134, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 544, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1243, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1264, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1042, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1062, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 784, in cupy.cuda.memory._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 432,048,128 bytes (allocated so far: 11,236,023,808 bytes).

Can someone suggest the solution for the same?

**Comment by kmaehashi** [comment]
This means that there's no enough GPU memory left. GPU memory won't be freed if there is a reference to a `cupy.ndarray` instance.  Please make sure that everything is cleaned after each iteration.
See also: https://docs.cupy.dev/en/stable/reference/memory.html

**Comment by potato-patata** [comment]
@kmaehashi thank you for your time and reply.
But the machine I'm working on is a slurm server PowerEdge R730 running Ubuntu 16.04 with specs Two 4-core Intel Xeon Processors @ 2.8 GHz
512 GB Ram
Dual Tesla K40 GPU
4 TB Storage.

I will still try the cupy memory management as suggested by you.
