### ISSUE TITLE
`cupy.random.randint` does not support boolean dtype

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4238]
```
>>> numpy.random.randint(0, 2, dtype='bool')
True
>>> cupy.random.randint(0, 2, dtype='bool')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nishino/.local/lib/python3.6/site-packages/cupy/random/_sample.py", line 112, in randint
    return rs.randint(low, high, size, dtype)
  File "/home/nishino/.local/lib/python3.6/site-packages/cupy/random/_generator.py", line 1166, in randint
    if lo < cupy.iinfo(dtype).min:
  File "/home/nishino/.local/lib/python3.6/site-packages/numpy/core/getlimits.py", line 507, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'b'.
```

**Comment by aitikgupta** [comment]
The culprit is `cupy.iinfo(dtype)` where `dtype` is `bool`.
`iinfo()` is taken directly from Numpy, where:
```
>>> numpy.iinfo(numpy.bool)
...
ValueError: Invalid integer data type 'b'.
```
So `cupy.iinfo(cupy.bool)` raises the exact same error.
I guess the condition should check if dtype is _not_ bool here:
https://github.com/cupy/cupy/blob/f10c98d10757632d41f1b8c0dc9e6228cfbcec53/cupy/random/_generator.py#L1166-L1171

If this seems like a legit change, I can take this up. 👍🏼

**Comment by acosmicflamingo** [comment]
@aitikgupta it seems that even if the condition somehow is caught, there is currently no functionality that would truly generate random boolean values. Funny that the numpy documentation for `randint` has absolutely zero mentions of boolean support, and yet their implementation seems to have always supported boolean types since numpy's `mtrand.pyx` file's inception.
