### ISSUE TITLE
`cupy.linalg.inv` returns wrong value on integer input

### ISSUE THREAD

**Issue by toslunar** [cupy/cupy#4309]
```
>>> cupy.linalg.inv(cupy.array([[1, 2], [3, 4]]))
array([[-inf,  inf],
       [ inf, -inf]])
>>> numpy.linalg.inv(numpy.array([[1, 2], [3, 4]]))
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
>>> cupy.__version__
'9.0.0a1'
```

**Comment by toslunar** [comment]
CuPy v7 reproduced the wrong output.

**Comment by toslunar** [comment]
After #4293,

```
>>> cupy.linalg.inv(cupy.array([[1,2],[3,4]]))
array([[-2. ,  1. ],
       [ 1.5, -0.5]])
>>> cupy.linalg.inv(cupy.array([[[1,2],[3,4]]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../cupy/linalg/_solve.py", line 283, in inv
    return _batched_inv(a)
  File ".../cupy/linalg/_solve.py", line 322, in _batched_inv
    raise ValueError(msg)
ValueError: dtype must be float32, float64, complex64 or complex128 (actual: int64)
```
