### ISSUE TITLE
`tensordot_core` raises `CUDA_ERROR_INVALID_VALUE`

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#4387]
```py
>>> cp.outer(cp.arange(2**23), cp.arange(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kenichi/Development/cupy/cupy/linalg/_product.py", line 245, in outer
    return core.tensordot_core(a, b, None, n, m, 1, ret_shape)
  File "cupy/core/_routines_linalg.pyx", line 421, in cupy.core._routines_linalg.tensordot_core
    cpdef ndarray tensordot_core(
  File "cupy/core/_routines_linalg.pyx", line 493, in cupy.core._routines_linalg.tensordot_core
    return _integral_tensordot_core(b, a, out, m, n, k, dtype, ret_shape)
  File "cupy/core/_routines_linalg.pyx", line 320, in cupy.core._routines_linalg._integral_tensordot_core
    kern(grid, block, args=args, shared_mem=shared_mem)
  File "cupy/core/raw.pyx", line 89, in cupy.core.raw.RawKernel.__call__
    self.kernel(
  File "cupy/cuda/function.pyx", line 201, in cupy.cuda.function.Function.__call__
    _launch(
  File "cupy/cuda/function.pyx", line 183, in cupy.cuda.function._launch
    driver.launchKernel(
  File "cupy_backends/cuda/api/driver.pyx", line 299, in cupy_backends.cuda.api.driver.launchKernel
    check_status(status)
  File "cupy_backends/cuda/api/driver.pyx", line 124, in cupy_backends.cuda.api.driver.check_status
    raise CUDADriverError(status)
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
```

**Comment by emcastillo** [comment]
Seems like this comes from the matrix int kernel with a large grid size

**Comment by leofang** [comment]
Interestingly, this works fine on HIP (even without the fix #4512) but not on CUDA. Magic! 😂

**Comment by ashkspark** [comment]
I am getting a similar error when my array becomes large. I am using RTX 8000 . Here is the error:

cupy/core/_routines_linalg.pyx in cupy.core._routines_linalg.tensordot_core()

cupy/core/_routines_linalg.pyx in cupy.core._routines_linalg.tensordot_core()

cupy/core/_routines_linalg.pyx in cupy.core._routines_linalg._integral_tensordot_core()

cupy/core/raw.pyx in cupy.core.raw.RawKernel.__call__()

cupy/cuda/function.pyx in cupy.cuda.function.Function.__call__()

cupy/cuda/function.pyx in cupy.cuda.function._launch()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.launchKernel()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.check_status()

CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
