### ISSUE TITLE
CuPy Failed to Open nvrtc-builtins64_111.dll NVRTC_ERROR_BUILTIN_OPERATION_FAILURE (7)

### ISSUE THREAD

**Issue by EliteMinerZMC** [cupy/cupy#4396]
Failing to imprort nvrtc-builtins64_111.dll while running
Hoping this is not something with CuPy but with me as thats the easier fix
Was having issues with python version 3.7.9 so upgraded to 3.8.6 and now import worked (previously i couldnt get past importing cupy) now it seems after moving to a new venv and installing new python and cupy its failing here, far as i can tell the dll is present so i dont know where to go from here seems the cupy compiler is failing to open nvrtc-builtins

I may be wrong but 3090 uses compute 86? Cupy is using '-arch=compute_80'. First time using Cuda and Cupy but dont know if that difference would make it fail
**Tried forcing compute 86 and no joy**

Quite simply failing on cupy.ones((174,178))
OS                           : Windows-10-10.0.19041-SP0
CuPy Version                 : 8.2.0
NumPy Version                : 1.19.3
SciPy Version                : None
Cython Build Version         : 0.29.21
CUDA Root                    : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1
CUDA Build Version           : 11010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 11010
cuBLAS Version               : 11300
cuFFT Version                : 10300
cuRAND Version               : 10202
cuSOLVER Version             : (11, 0, 1)
cuSPARSE Version             : 11300
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
Device 0 Name                : GeForce RTX 3090
Device 0 Compute Capability  : 86

cupy.ones((174,178))
Traceback (most recent call last):
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\cuda\compiler.py", line 516, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 120, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_BUILTIN_OPERATION_FAILURE (7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/joshu/PycharmProjects/JakesProject/GoogleHost/SolaPar3_SA_Local.py", line 45, in <module>
    D_Az= cp.ones((alto_img,ancho_img)) # Azimut / Azimuth
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\_creation\basic.py", line 152, in ones
    a.fill(1)
  File "cupy\core\core.pyx", line 511, in cupy.core.core.ndarray.fill
  File "cupy\core\core.pyx", line 529, in cupy.core.core.ndarray.fill
  File "cupy\core\_kernel.pyx", line 821, in cupy.core._kernel.ElementwiseKernel.__call__
  File "cupy\core\_kernel.pyx", line 846, in cupy.core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy\_util.pyx", line 53, in cupy._util.memoize.decorator.ret
  File "cupy\core\_kernel.pyx", line 639, in cupy.core._kernel._get_elementwise_kernel
  File "cupy\core\_kernel.pyx", line 37, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy\core\_kernel.pyx", line 60, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy\core\core.pyx", line 1862, in cupy.core.core.compile_with_cache
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\cuda\compiler.py", line 335, in compile_with_cache
    return _compile_with_cache_cuda(
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\cuda\compiler.py", line 367, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\cuda\compiler.py", line 273, in _preprocess
    result, _ = prog.compile(options)
  File "C:\Users\joshu\PycharmProjects\JakesProject\GoogleHost\venv\lib\site-packages\cupy\cuda\compiler.py", line 527, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: nvrtc: error: failed to open nvrtc-builtins64_111.dll.
  Make sure that nvrtc-builtins64_111.dll is installed correctly.

Process finished with exit code 1

**Comment by EliteMinerZMC** [comment]
3rd reinstall of Cuda exactly thesame as the other previous installs fixed this issue asuming something transient was going on breaking the specific dll. Closing issue
