### ISSUE TITLE
Jitify/CUB compilation failure

### ISSUE THREAD

**Issue by grlee77** [cupy/cupy#4405]
Here is a case where a Jitify/CUB compilation error occurs. I came across it when I accidentally passed a complex-valued input to a function that calls sum with fixed dtype=cupy.float64. For example:

```Python
a = cupy.ones((8,), dtype=np.complex64)
a.sum(dtype=cupy.float64)
```
Indeed, it does not make sense to sum a complex array using a real dtype, so this does seem like a valid failure, I just wondered if we could detect this type of case and raise a simpler error message and/or bypass CUB/cuTENSOR in this case.

```

---------------------------------------------------
--- JIT compile log for /tmp/tmp04h8lhhn/495be8c6a63d5f0b2674719a4398fc8b_2.cubin.cu ---
---------------------------------------------------
cupy/complex/complex.h(94): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

cupy/complex/complex.h(101): warning: __device__ annotation is ignored on a function("complex") that is explicitly defaulted on its first declaration

specializations/block_reduce_raking_commutative_only.cuh(98): warning: declaration does not declare anything

cupy/cub/cub/block/block_load.cuh(118): error: no suitable conversion function from "const type_mid_in" to "_type_reduce" exists
          detected during:
            instantiation of "void cub::LoadDirectBlocked(int, InputIteratorT, InputT (&)[ITEMS_PER_THREAD], int) [with InputT=_type_reduce, ITEMS_PER_THREAD=4, InputIteratorT=const type_mid_in *]" 
(149): here
            instantiation of "void cub::LoadDirectBlocked(int, InputIteratorT, InputT (&)[ITEMS_PER_THREAD], int, DefaultT) [with InputT=_type_reduce, DefaultT=_type_reduce, ITEMS_PER_THREAD=4, InputIteratorT=const type_mid_in *]" 
(712): here
            instantiation of "void cub::BlockLoad<InputT, BLOCK_DIM_X, ITEMS_PER_THREAD, ALGORITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::LoadInternal<cub::BLOCK_LOAD_DIRECT, DUMMY>::Load(InputIteratorT, InputT (&)[ITEMS_PER_THREAD], int, DefaultT) [with InputT=_type_reduce, BLOCK_DIM_X=32, ITEMS_PER_THREAD=4, ALGORITHM=cub::BLOCK_LOAD_DIRECT, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, PTX_ARCH=610, DUMMY=0, InputIteratorT=const type_mid_in *, DefaultT=_type_reduce]" 
(1230): here
            instantiation of "void cub::BlockLoad<InputT, BLOCK_DIM_X, ITEMS_PER_THREAD, ALGORITHM, BLOCK_DIM_Y, BLOCK_DIM_Z, PTX_ARCH>::Load(InputIteratorT, InputT (&)[ITEMS_PER_THREAD], int, DefaultT) [with InputT=_type_reduce, BLOCK_DIM_X=32, ITEMS_PER_THREAD=4, ALGORITHM=cub::BLOCK_LOAD_DIRECT, BLOCK_DIM_Y=1, BLOCK_DIM_Z=1, PTX_ARCH=610, InputIteratorT=const type_mid_in *, DefaultT=_type_reduce]" 
/tmp/tmp04h8lhhn/495be8c6a63d5f0b2674719a4398fc8b_2.cubin.cu(104): here

1 error detected in the compilation of "/tmp/tmp04h8lhhn/495be8c6a63d5f0b2674719a4398fc8b_2.cubin.cu".

---------------------------------------------------
Traceback (most recent call last):

  File "<ipython-input-35-cc7d38537641>", line 1, in <module>
    a.sum(dtype=np.float64)

  File "cupy/core/core.pyx", line 860, in cupy.core.core.ndarray.sum

  File "cupy/core/core.pyx", line 868, in cupy.core.core.ndarray.sum

  File "cupy/core/_routines_math.pyx", line 120, in cupy.core._routines_math._ndarray_sum

  File "cupy/core/_reduction.pyx", line 560, in cupy.core._reduction._SimpleReductionKernel.__call__

  File "cupy/core/_reduction.pyx", line 346, in cupy.core._reduction._AbstractReductionKernel._call

  File "cupy/core/_cub_reduction.pyx", line 684, in cupy.core._cub_reduction._try_to_call_cub_reduction

  File "cupy/core/_cub_reduction.pyx", line 520, in cupy.core._cub_reduction._launch_cub

  File "cupy/core/_cub_reduction.pyx", line 455, in cupy.core._cub_reduction._cub_two_pass_launch

  File "cupy/_util.pyx", line 53, in cupy._util.memoize.decorator.ret

  File "cupy/core/_cub_reduction.pyx", line 227, in cupy.core._cub_reduction._SimpleCubReductionKernel_get_cached_function

  File "cupy/core/_cub_reduction.pyx", line 212, in cupy.core._cub_reduction._create_cub_reduction_function

  File "cupy/core/core.pyx", line 1883, in cupy.core.core.compile_with_cache

  File "/home/lee8rx/my_git/pyir/cupy/cupy/cuda/compiler.py", line 396, in compile_with_cache
    cache_in_memory, jitify)

  File "/home/lee8rx/my_git/pyir/cupy/cupy/cuda/compiler.py", line 474, in _compile_with_cache_cuda
    log_stream, cache_in_memory, jitify)

  File "/home/lee8rx/my_git/pyir/cupy/cupy/cuda/compiler.py", line 230, in compile_using_nvrtc
    name_expressions, log_stream, jitify)

  File "/home/lee8rx/my_git/pyir/cupy/cupy/cuda/compiler.py", line 206, in _compile
    source, options, cu_path)

  File "/home/lee8rx/my_git/pyir/cupy/cupy/cuda/compiler.py", line 188, in _jitify_prep
    raise JitifyException(str(cex))

JitifyException: Runtime compilation failed
```

For reference NumPy only raises a Warning and not an error:
```Python
np.ones((8,), dtype=np.complex128).sum(dtype=np.float64)
```
```
/miniconda3/envs/sp_dev/lib/python3.7/site-packages/numpy/core/_methods.py:47: ComplexWarning: Casting complex values to real discards the imaginary part
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
```

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
```
OS                           : Linux-4.15.0-124-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 9.0.0a3
NumPy Version                : 1.19.2
SciPy Version                : 1.6.0.dev0+ba8a861
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /usr/local/cuda
CUDA Build Version           : 11010
CUDA Driver Version          : 11010
CUDA Runtime Version         : 11010
cuBLAS Version               : 11300
cuFFT Version                : 10300
cuRAND Version               : 10202
cuSOLVER Version             : (11, 0, 1)
cuSPARSE Version             : 11300
NVRTC Version                : (11, 1)
Thrust Version               : 100910
CUB Build Version            : 100910
Jitify Build Version         : <unknown>
cuDNN Build Version          : 7605
cuDNN Version                : 7605
NCCL Build Version           : 2803
NCCL Runtime Version         : 2803
cuTENSOR Version             : 10201
Device 0 Name                : GeForce GTX 1080 Ti
Device 0 Compute Capability  : 61
```

**Comment by leofang** [comment]
This also happens when CUB/cuTENSOR is *not* in use, so it's a generic CuPy error. I guess we need to a way to detect and convert the dtypes internally, raise `ComplexWarning`, etc. How does NumPy achieve this?
```python
>>> import cupy as cp
>>> cp.ones((8,), dtype=cp.complex128).sum(dtype=cp.float64)
Traceback (most recent call last):
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 586, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 108, in cupy_backends.cuda.libs.nvrtc.compileProgram
    cpdef compileProgram(intptr_t prog, options):
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 120, in cupy_backends.cuda.libs.nvrtc.compileProgram
    check_status(status)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 58, in cupy_backends.cuda.libs.nvrtc.check_status
    raise NVRTCError(status)
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/core/_reduction.pyx", line 601, in cupy.core._reduction._SimpleReductionKernel._get_function
    return _SimpleReductionKernel_get_cached_function(
  File "cupy/_util.pyx", line 53, in cupy._util.memoize.decorator.ret
    result = f(*args, **kwargs)
  File "cupy/core/_reduction.pyx", line 614, in cupy.core._reduction._SimpleReductionKernel_get_cached_function
    return _create_reduction_function(
  File "cupy/core/_reduction.pyx", line 122, in cupy.core._reduction._create_reduction_function
    module = compile_with_cache(module_code, options)
  File "cupy/core/core.pyx", line 1883, in cupy.core.core.compile_with_cache
    return cuda.compile_with_cache(
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 396, in compile_with_cache
    cache_in_memory, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 474, in _compile_with_cache_cuda
    log_stream, cache_in_memory, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 230, in compile_using_nvrtc
    name_expressions, log_stream, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 213, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 598, in compile
    'nvrtc' if not runtime.is_hip else 'hiprtc')
cupy.cuda.compiler.CompileException: /tmp/tmpc91x0ufr/ddfd12c4936f2b662957e96d4589ee5e_2.cubin.cu(35): error: no suitable conversion function from "const type_in0_raw" to "_type_reduce" exists

1 error detected in the compilation of "/tmp/tmpc91x0ufr/ddfd12c4936f2b662957e96d4589ee5e_2.cubin.cu".

Exception ignored in: 'cupy.core._reduction._AbstractReductionKernel._launch'
Traceback (most recent call last):
  File "cupy/core/_reduction.pyx", line 601, in cupy.core._reduction._SimpleReductionKernel._get_function
    return _SimpleReductionKernel_get_cached_function(
  File "cupy/_util.pyx", line 53, in cupy._util.memoize.decorator.ret
    result = f(*args, **kwargs)
  File "cupy/core/_reduction.pyx", line 614, in cupy.core._reduction._SimpleReductionKernel_get_cached_function
    return _create_reduction_function(
  File "cupy/core/_reduction.pyx", line 122, in cupy.core._reduction._create_reduction_function
    module = compile_with_cache(module_code, options)
  File "cupy/core/core.pyx", line 1883, in cupy.core.core.compile_with_cache
    return cuda.compile_with_cache(
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 396, in compile_with_cache
    cache_in_memory, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 474, in _compile_with_cache_cuda
    log_stream, cache_in_memory, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 230, in compile_using_nvrtc
    name_expressions, log_stream, jitify)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 213, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "/home/leofang/dev/cupy_cuda10.2/cupy/cuda/compiler.py", line 598, in compile
    'nvrtc' if not runtime.is_hip else 'hiprtc')
cupy.cuda.compiler.CompileException: /tmp/tmpc91x0ufr/ddfd12c4936f2b662957e96d4589ee5e_2.cubin.cu(35): error: no suitable conversion function from "const type_in0_raw" to "_type_reduce" exists

1 error detected in the compilation of "/tmp/tmpc91x0ufr/ddfd12c4936f2b662957e96d4589ee5e_2.cubin.cu".

array(0.)
```
