### ISSUE TITLE
Import error with cupy-cuda101

### ISSUE THREAD

**Issue by briannghiem** [cupy/cupy#4429]
## Issue
I'm running into issues with importing CuPy after pip installing cupy-cuda101. I've ensured that I'm using the correct CUDA version available and that I only have one version of CuPy installed.

## Code
```python
import cupy
```

## Error
```python
Traceback (most recent call last):
  File "/home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy/cuda/__init__.py", line 5, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 10, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 10, in init cupy.cuda.device
ImportError: /home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy_backends/cuda/libs/cusparse.cpython-37m-x86_64-linux-gnu.so: symbol cusparseSpMatSetValues, version libcusparse.so.10 not defined in file libcusparse.so.10 with link time reference

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: /home/usr/.conda/envs/MY_ENV/lib/python3.7/site-packages/cupy_backends/cuda/libs/cusparse.cpython-37m-x86_64-linux-gnu.so: symbol cusparseSpMatSetValues, version libcusparse.so.10 not defined in file libcusparse.so.10 with link time reference
```

## Environment
- Linux (remote cluster)
- python=3.7.9
- cuda=10.1
- cupy-cuda101 = 8.2.0 (pip installation)

```bash
$ /usr/local/cuda/bin/nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by briannghiem** [comment]
Just found a related issue: #3918; I'll try upgrading to CUDA 10.1 update 2.

**Comment by briannghiem** [comment]
Downgrading to python v3.6.9 seemed to resolve import issues with cupy-cuda101=8.2.0 without need to upgrade CUDA 10.1
