### ISSUE TITLE
Import cupy leads to AttributeError?

### ISSUE THREAD

**Issue by JoPet123** [cupy/cupy#4455]
Hello! I've just installed CuPy through pip and when I try to import it, or use it CUDA with SpaCy, I get this error :  
>>> import cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python37\lib\site-packages\cupy\__init__.py", line 57, in <module>
    from cupy import fft  # NOQA
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python37\lib\site-packages\cupy\fft\__init__.py", line 1, in <module>
    from cupy.fft._fft import fft  # NOQA
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python37\lib\site-packages\cupy\fft\_fft.py", line 9, in <module>
    from cupy.fft import config
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python37\lib\site-packages\cupy\fft\config.py", line 13, in <module>
    from cupy.fft._callback import get_current_callback_manager  # NOQA
  File "cupy/fft/_callback.pyx", line 35, in init cupy.fft._callback
AttributeError: 'NoneType' object has no attribute 'split'

Do you guys know a fix for this? I can't seem to find anything on Google (I'm using CUDA 11.1)

**Comment by leofang** [comment]
Hi @JoPet123, this is a duplicate of #4352, which was just resolved recently (#4355). A couple of questions:
- Did you install cupy via `pip install cupy`?
- Are you on Windows?

The fix is to install the pre-built wheel, which in your case is `pip install cupy-cuda111`.

**Comment by JoPet123** [comment]
> Hi @JoPet123, this is a duplicate of #4352, which was just resolved recently (#4355). A couple of questions:
> 
> * Did you install cupy via `pip install cupy`?
> * Are you on Windows?
> 
> The fix is to install the pre-built wheel instead of building from source, which in your case is `pip install cupy-cuda111`.

Hello! 
Yes I am on Windows and I did install it with pip install cupy.
Should I run pip uninstall cupy before installing cupy-cuda111?
Thank you

**Comment by leofang** [comment]
Yes, uninstall it first, or there'd be bizarre conflicts.

**Comment by JoPet123** [comment]
Thank you, it seems to be working, I'll close the issue now :)
