### ISSUE TITLE
ROCm: TypeError: operand type(s) all returned NotImplemented from __array_ufunc__

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4515]
Previously all FFT tests passed on HIP, but it seems the recent change on `__array_ufunc__` (#4198) somehow breaks it...
```
$ pytest tests/cupy_tests/fft_tests/
(...similar error output omitted...)
__________________________________________________________ TestFftfreq.test_rfftfreq[_param_2_{d=2, n=100}] ___________________________________________________________

self = <<cupy_tests.fft_tests.test_fft.TestFftfreq object at 0x7f4144ceb090>  parameter: {'n': 100, 'd': 2}>
xp = <module 'cupy' from '/home/leofang/dev/cupy_rocm350/cupy/__init__.py'>, dtype = <class 'numpy.float64'>

    @testing.for_all_dtypes()
    @testing.numpy_cupy_allclose(rtol=1e-4, atol=1e-7, contiguous_check=False)
    def test_rfftfreq(self, xp, dtype):
>       out = xp.fft.rfftfreq(self.n, self.d)

tests/cupy_tests/fft_tests/test_fft.py:1258: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cupy/fft/_fft.py:1017: in rfftfreq
    return cupy.arange(0, n // 2 + 1, dtype=np.float64) / (n * d)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   return numpy.true_divide(x, y)
E   AssertionError: Only cupy raises error
E   
E   Traceback (most recent call last):
E     File "/home/leofang/dev/cupy_rocm350/cupy/testing/helper.py", line 47, in _call_func
E       result = impl(self, *args, **kw)
E     File "/home/leofang/dev/cupy_rocm350/tests/cupy_tests/fft_tests/test_fft.py", line 1258, in test_rfftfreq
E       out = xp.fft.rfftfreq(self.n, self.d)
E     File "/home/leofang/dev/cupy_rocm350/cupy/fft/_fft.py", line 1017, in rfftfreq
E       return cupy.arange(0, n // 2 + 1, dtype=np.float64) / (n * d)
E     File "cupy/core/core.pyx", line 1103, in cupy.core.core.ndarray.__truediv__
E       return numpy.true_divide(x, y)
E   TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'true_divide'>, '__call__', array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
E          13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
E          26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
E          39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]), 200): 'ndarray', 'int'

cupy/core/core.pyx:1103: AssertionError
------------------------------------------------------------------------ Captured stdout call -------------------------------------------------------------------------
dtype is <class 'numpy.float64'>
======================================================================= short test summary info =======================================================================
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_0_{n=None, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_1_{n=None, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_4_{n=5, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_5_{n=5, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_8_{n=10, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_9_{n=10, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_12_{n=15, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_hfft[_param_13_{n=15, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_0_{n=None, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_1_{n=None, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_2_{n=None, norm='ortho', shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_3_{n=None, norm='ortho', shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_4_{n=5, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_5_{n=5, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_6_{n=5, norm='ortho', shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_7_{n=5, norm='ortho', shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_8_{n=10, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_9_{n=10, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_10_{n=10, norm='ortho', shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_11_{n=10, norm='ortho', shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_12_{n=15, norm=None, shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_13_{n=15, norm=None, shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_14_{n=15, norm='ortho', shape=(10,)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestHfft::test_ihfft[_param_15_{n=15, norm='ortho', shape=(10, 10)}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_fftfreq[_param_0_{d=1, n=1}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_fftfreq[_param_1_{d=0.5, n=10}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_fftfreq[_param_2_{d=2, n=100}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_rfftfreq[_param_0_{d=1, n=1}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_rfftfreq[_param_1_{d=0.5, n=10}] - AssertionError: Only cupy raises error
FAILED tests/cupy_tests/fft_tests/test_fft.py::TestFftfreq::test_rfftfreq[_param_2_{d=2, n=100}] - AssertionError: Only cupy raises error
======================================================= 30 failed, 557 passed, 727 skipped in 103.58s (0:01:43) =======================================================
```

**Comment by leofang** [comment]
Minimal reproducer:
```python
>>> import cupy as cp
>>> a = cp.arange(10)
>>> a/10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1103, in cupy.core.core.ndarray.__truediv__
    return numpy.true_divide(x, y)
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'true_divide'>, '__call__', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 10): 'ndarray', 'int'
>>> a/10.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 1103, in cupy.core.core.ndarray.__truediv__
    return numpy.true_divide(x, y)
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'true_divide'>, '__call__', array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 10.0): 'ndarray', 'float'
>>> cp.show_config()
OS                           : Linux-5.4.0-52-generic-x86_64-with-debian-buster-sid
CuPy Version                 : 9.0.0b1
NumPy Version                : 1.19.4
SciPy Version                : 1.5.3
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /opt/rocm
CUDA Build Version           : 0
CUDA Driver Version          : 320400
CUDA Runtime Version         : 3204
cuBLAS Version               : 23000
cuFFT Version                : 10007941
cuRAND Version               : 201005
cuSOLVER Version             : (3, 9, 0)
cuSPARSE Version             : 21933
NVRTC Version                : (9, 0)
Thrust Version               : 100908
CUB Build Version            : 201005
Jitify Build Version         : None
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : Vega 20
Device 0 Compute Capability  : 90
```

**Comment by leofang** [comment]
I changed the issue title since it seems to have nothing to do with ROCm in particular.

**Comment by leofang** [comment]
> I changed the issue title since it seems to have nothing to do with ROCm in particular.

So it turns out this bug is only reproducible on HIP 😅 See #4524.
