### ISSUE TITLE
Catch incompatible CUDA version

### ISSUE THREAD

**Issue by sk1p** [cupy/cupy#4660]
CuPy version: 8.4
Platform: Debian Linux
CUDA: 11.2
Installed from source (`pip install cupy`)

It would be very nice if cupy could throw a clear (or more clear) error message if the installed CUDA version doesn't work with the selected GPU, or had an API to check compatibility. For example, I have an old K2000 in my desktop PC, for which support was dropped in CUDA 11.1, and this code:

```python
import cupy as cp
cp.array(cp.zeros((1,)))
```

Throws the following error:

```
~/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream)
    371             name_expressions, log_stream, cache_in_memory)
    372     else:
--> 373         return _compile_with_cache_cuda(
    374             source, options, arch, cache_dir, extra_source, backend,
    375             enable_cooperative_groups, name_expressions, log_stream,

~/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory)
    401     if base is None:
    402         # This is checking of NVRTC compiler internal version
--> 403         base = _preprocess('', options, arch, backend)
    404         _empty_file_preprocess_cache[env] = base
    405 

~/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py in _preprocess(source, options, arch, backend)
    309         prog = _NVRTCProgram(source, '')
    310         try:
--> 311             result, _ = prog.compile(options)
    312         except CompileException as e:
    313             dump = _get_bool_env_variable(

~/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile(self, options, log_stream)
    561         except nvrtc.NVRTCError:
    562             log = nvrtc.getProgramLog(self.ptr)
--> 563             raise CompileException(log, self.src, self.name, options,
    564                                    'nvrtc' if not runtime.is_hip else 'hiprtc')
    565 

CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
```

If I don't directly convert to a numpy array, the exception gets ignored and results in a sometimes-`NaN` array, for example this:

```python
cp.zeros((128, 128), dtype=cp.float32).sum()
```

Causes this exception:

```
Exception ignored in: 'cupy.core._reduction._AbstractReductionKernel._launch'
Traceback (most recent call last):
  File "cupy/core/_reduction.pyx", line 601, in cupy.core._reduction._SimpleReductionKernel._get_function
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/core/_reduction.pyx", line 614, in cupy.core._reduction._SimpleReductionKernel_get_cached_function
  File "cupy/core/_reduction.pyx", line 122, in cupy.core._reduction._create_reduction_function
  File "cupy/core/core.pyx", line 1889, in cupy.core.core.compile_with_cache
  File "/home/alex/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 373, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/alex/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 403, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "/home/alex/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 311, in _preprocess
    result, _ = prog.compile(options)
  File "/home/alex/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 563, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
```

And printing the result sometimes outputs 0, sometimes nan.

Btw: `cupy.show_config()` doesn't work for me, I get this traceback:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-23-dde3098f9bb5> in <module>
----> 1 cp.show_config()

~/.virtualenvs/libertem/lib/python3.8/site-packages/cupy/__init__.py in show_config()
    864 def show_config():
    865     """Prints the current runtime configuration to standard output."""
--> 866     _sys.stdout.write(str(_cupyx.get_runtime_info()))
    867     _sys.stdout.flush()

~/.virtualenvs/libertem/lib/python3.8/site-packages/cupyx/_runtime.py in __str__(self)
    223                 records += [
    224                     ('Device {} Name'.format(device_id),
--> 225                      props['name'].decode('utf-8')),
    226                     ('Device {} Compute Capability'.format(device_id),
    227                      device.compute_capability),

AttributeError: 'str' object has no attribute 'decode'
```

**Comment by leofang** [comment]
For the last `AttributeError`, it was caused by a combo of two bugs we recently found, one is fixed in #4594 but another is still ongoing (#4597). It turns out to be a sdist issue, so for the time being to actually "build from source" you should clone from GitHub; `pip install cupy` is currently not a good idea.

**Comment by sk1p** [comment]
> It turns out to be a sdist issue, so for the time being to actually "build from source" you should clone from GitHub; `pip install cupy` is currently not a good idea.

Okay, thanks for letting me know. Should I retry the original issue with the current development version?
