### ISSUE TITLE
Batched QR solver

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#4986]
This is for ~~both NumPy compatibility and also~~ the Python Array API standard (#4789, WIP proposal: data-apis/array-api#126).

Currently we have this check:
https://github.com/cupy/cupy/blob/07171d785422df01d2d0b41b41268c26d02d1331/cupy/linalg/_decomposition.py#L238-L240
so we can only support a 2D matrix, but we might be able to follow the approach of batched svd and pinv to support batched QR factorization. I can look into this later.

**Comment by leofang** [comment]
Oops, read it too quickly: NumPy does not support it currently, so this is just for Array API.
```python
>>> import numpy as np
>>> a = np.random.random((2,16,16))
>>> b = np.linalg.qr(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 6, in qr
  File "/home/leofang/miniconda3/envs/cupy_cuda112_dev/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 907, in qr
    _assert_2d(a)
  File "/home/leofang/miniconda3/envs/cupy_cuda112_dev/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 191, in _assert_2d
    'two-dimensional' % a.ndim)
numpy.linalg.LinAlgError: 3-dimensional array given. Array must be two-dimensional
```

**Comment by leofang** [comment]
Update: In the next NumPy release batched QR will be supported, see https://github.com/numpy/numpy/pull/19151. We should be prepared.
