### ISSUE TITLE
Sparse SVD fails if matrix rank is lower than the requested number of  singular values k

### ISSUE THREAD

**Issue by PavelStishenko** [cupy/cupy#5000]
* Conditions
CuPy Version                 : 9.0.0rc1
NumPy Version                : 1.20.1
SciPy Version                : 1.6.2
CUDA Build Version           : 11010
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11010

* Code to reproduce
```
import cupy as cp
from cupyx.scipy.sparse.linalg import svds

a = cp.random.random((10,10))
u,s,vt = svds(a, 5)
s[0] = 0.0
b = u @ cp.diag(s) @ vt
u,s,vt = svds(b, 5)	# TypeError: 'cupy.core.core.ndarray' object cannot be interpreted as an integer
```

* Error messages, stack traces, or logs
```
Traceback (most recent call last):
  File "/home/mazay/prg/regr/cupy_svds_bug.py", line 8, in <module>
    u,s,vt = svds(b, 5)	# TypeError: 'cupy.core.core.ndarray' object cannot be interpreted as an integer
  File "/home/mazay/prg/regr/ve/lib/python3.9/site-packages/cupyx/scipy/sparse/linalg/_eigen.py", line 363, in svds
    u = _augmented_orthnormal_cols(u, k - n_large)
  File "/home/mazay/prg/regr/ve/lib/python3.9/site-packages/cupyx/scipy/sparse/linalg/_eigen.py", line 373, in _augmented_orthnormal_cols
    y = cupy.empty((m, n + n_aug), dtype=x.dtype)
  File "/home/mazay/prg/regr/ve/lib/python3.9/site-packages/cupy/_creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 141, in cupy.core.core.ndarray.__init__
TypeError: 'cupy.core.core.ndarray' object cannot be interpreted as an integer
```

The problem is probably in `svds()` code with `n_large` variable. Currently it is not converted from `cupy`, so `k - n_large` is also a `cupy` number. If `n_large` is less than `k`, then the issue is triggered in `_augmented_orthnormal_cols`.

**Comment by Mazay0** [comment]
There is a similar issue #5001 , but I think it is another bug, with similar test conditions

**Comment by smarkesini** [comment]
Partly fixed, with the remainder tracked elsewhere:

- The `TypeError` reported here is fixed by the merged #5140 (`n_large` is converted to an int), so `svds` no longer raises on this input — verified on cupy 12.3 (A100).
- However, `svds` still returns **wrong** values on a rank-deficient matrix (the singular values overflow / include spurious entries). This is the underlying rank-deficiency bug — the Lanczos exhausts the Krylov space of the large null space of `A^H A` — which is the same root cause as #8009, addressed in #10098 (a β→0 lucky-breakdown guard). With that fix the rank-deficient case returns the correct top-k singular values.

So the crash here is resolved by #5140 and the correctness by #10098; once #10098 lands this can be closed.
