### ISSUE TITLE
IndexError when advanced-indexing zero-dim array

### ISSUE THREAD

**Issue by niboshi** [cupy/cupy#503]
CuPy version: latest master (83f8a07)

Code:
```
import numpy, cupy
shape = ()

for xp in (numpy, cupy):
    print("--", xp.__name__)

    a = xp.ones(shape, numpy.float32)
    print(a.shape)
    print((a < 0).shape)
    print(a[a < 0].shape)
```

Result:
```
-- numpy
()
()
(0,)
-- cupy
()
()
Traceback (most recent call last):
  File "test-zero.py", line 10, in <module>
    print(a[a < 0].shape)
  File "cupy/core/core.pyx", line 1386, in cupy.core.core.ndarray.__getitem__ (cupy/core/core.cpp:30591)
    raise IndexError('too many indices for array')
IndexError: too many indices for array

```

**Comment by yuyu2172** [comment]
I checked the behavior of zero-dim arrays in other cases.
It seems that boolean arrays are handled differently between NumPy and CuPy.

```python
import numpy
import cupy


for xp, name in zip((numpy, cupy), ('numpy', 'cupy')):
    print('')
    a = xp.ones((), dtype=numpy.float32)
    try: 
        a[0]
    except IndexError:
        print('{}: a[0] error'.format(name))

    try:
        a[[0]]
    except IndexError:
        print('{}: a[[0]] error'.format(name))

    try:
        a[numpy.array([0])]
    except IndexError:
        print('{}: a[numpy.arary([0]) error'.format(name))

    try:
        a[numpy.array(0)]
    except IndexError:
        print('{}: a[numpy.array(0)] error'.format(name))

    try:
        a[numpy.array([False])]
    except IndexError:
        print('{}: a[numpy.array([False])] error'.format(name))

    try:
        a[numpy.empty((), dtype=numpy.bool)]
    except IndexError:
        print('{}: a[numpy.empty((), dtype=numpy.bool)] error'.format(name))
```

Result:
```
numpy: a[0] error
numpy: a[[0]] error
numpy: a[numpy.arary([0]) error
numpy: a[numpy.array(0)] error
numpy: a[numpy.array([False])] error

cupy: a[0] error
cupy: a[[0]] error
cupy: a[numpy.arary([0]) error
cupy: a[numpy.array(0)] error
cupy: a[numpy.array([False])] error
cupy: a[numpy.empty((), dtype=numpy.bool)] error
```
