### ISSUE TITLE
cupy.sparse.csr_matrix.multiply behaves differently than scipy.sparse.csr_matrix.multiply for ndim>2

### ISSUE THREAD

**Issue by mfmullen** [cupy/cupy#5055]
Per the title, I am trying to replicate the result from Scipy when multiplying a csr_matrix with an nD array, n>2, specifically where one dimension being multiplied is intentionally a singleton. In scipy, the nD array is broadcast in the singleton dimension for the multiply, whereas cupy throws a ValueError (shown below). The array sizes are larger in practice than in this minimal working example.

_As an aside regarding numpy vs. scipy,_ this question came about as part of a workaround for matrix multiplication ```a@b``` when a is a csr_matrix and b is nD (not necessarily having any singleton dimensions). When a is not stored as a sparse array, numpy.matmul treats b as a stack of 2D arrays residing in the last two dimensions, and the matrix multiplication works great. If a is stored as a sparse array, the matrix multiplication does not work as is.

* Code to reproduce
```
import cupy as cp
from cupyx.scipy.sparse import csr_matrix as csr_gpu
from scipy.sparse import csr_matrix as csr_cpu
import numpy as np

x = np.random.randn(20,20,20)
y = np.eye(20)
ys = csr_cpu(y)

try:
    zs = ys.multiply(np.expand_dims(x,axis=2))
    print('Scipy threw no errors')
except ValueError:
    print('Error on scipy end')

x_gpu = cp.asarray(x)
ys_gpu = csr_gpu(ys)

try:
    zs_gpu = ys_gpu.multiply(cp.expand_dims(x_gpu,axis=2))
    print('No cupy errors')
except ValueError:
    print('Cupy error: ValueError: too many values to unpack (expected 2)')
```

* Error messages, stack traces, or logs
Traceback (most recent call last):

  File "/home/range6-raid2/from-buddy/buddy-raid1/username/Documents/Dual_Polarity_MPSSFP/untitled0.py", line 29, in <module>
    zs_gpu = cp.sum(ys_gpu.multiply(cp.expand_dims(x_gpu,axis=2)),axis=-1)

  File "/home/buddy-raid1/mmullen/anaconda3/envs/dual_pol_MRI/lib/python3.6/site-packages/cupyx/scipy/sparse/csr.py", line 314, in multiply
    return multiply_by_dense(self, other)

  File "/home/buddy-raid1/mmullen/anaconda3/envs/dual_pol_MRI/lib/python3.6/site-packages/cupyx/scipy/sparse/csr.py", line 581, in multiply_by_dense
    check_shape_for_pointwise_op(sp.shape, dn.shape)

  File "/home/buddy-raid1/mmullen/anaconda3/envs/dual_pol_MRI/lib/python3.6/site-packages/cupyx/scipy/sparse/csr.py", line 563, in check_shape_for_pointwise_op
    b_m, b_n = b_shape

ValueError: too many values to unpack (expected 2)

* Conditions
OS                           : Linux-3.10.0-1160.6.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
CuPy Version                 : 9.0.0b1
NumPy Version                : 1.19.2
SciPy Version                : 1.5.2
Cython Build Version         : 0.29.21
Cython Runtime Version       : 0.29.21
CUDA Root                    : /opt/local/cuda-10.1
CUDA Build Version           : 10010
CUDA Driver Version          : 11000
CUDA Runtime Version         : 10010
cuBLAS Version               : 10201
cuFFT Version                : 10101
cuRAND Version               : 10101
cuSOLVER Version             : (10, 2, 0)
cuSPARSE Version             : 10300
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 2708
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
Device 0 Name                : Tesla V100-PCIE-32GB
Device 0 Compute Capability  : 70
Device 1 Name                : Tesla V100-PCIE-32GB
Device 1 Compute Capability  : 70
Device 2 Name                : Tesla V100-PCIE-32GB
Device 2 Compute Capability  : 70
Device 3 Name                : Tesla V100-PCIE-32GB
Device 3 Compute Capability  : 70

**Comment by emcastillo** [comment]
Sorry, I am not really familiar with all the sparse code and scipy so I may be wrong here.
When ndim > 2 this is just a batched product, am I right?

I am not sure whether cuSPARSE supports batched products or not but as a last resort we can just throw a for loop inside.

**Comment by mfmullen** [comment]
Regarding the batched product, I believe you are correct. I am not even slightly familiar with cuSPARSE - hopefully someone who is sees this!
