### ISSUE TITLE
Using fft/ifft with large ndarray + managed allocator leads to "illegal memory access was encountered"

### ISSUE THREAD

**Issue by sevagh** [cupy/cupy#5134]
Hello. I'm trying to apply the `cupyx.scipy.fft.fft/ifft` routines to very large ndarrays. Here is the output of `cupy.print_config()`:
```
OS                           : Linux-5.11.14-100.fc32.x86_64-x86_64-with-glibc2.2.5
CuPy Version                 : 9.0.0
NumPy Version                : 1.20.2
SciPy Version                : 1.6.2
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /usr
CUDA Build Version           : 11020
CUDA Driver Version          : 11030
CUDA Runtime Version         : 11020
cuBLAS Version               : 11401
cuFFT Version                : 10400
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : 11400
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8101
cuDNN Version                : 8100
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2070 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:0A:00.0
```
My first problem was that a large ndarray (bigger than available GPU memory) could not be copied to my device (RTX 2070S) due to exceeding the available memory (which is expected/unsurprising). On Gitter, @leofang mentioned I could try using managed memory to handle such a case. During the experiment with the managed memory allocator, I encounter the error `CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered`.

Here is some code to minimally reproduce the issue (you may need to adjust the ndarray size appropriately for your vmem): https://gist.github.com/sevagh/3017d7c2393d3fd184b290e54dcae441. Copied inline for convenience:
```
import numpy as np
import scipy.fft
import cupyx
import cupy

# managed memory to stream large ndarrays to cuda
cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.memory.malloc_managed).malloc)


if __name__ == '__main__':
    # 10GB array, approx. won't fit in my 8GB gpu vmem
    big_array = np.random.standard_normal((1000, 1000000))

    print(f'size: {big_array.nbytes//1e9} GB')
    print(f'shape: {big_array.shape}')
    print(f'dtype: {big_array.dtype}')

    print(cupy.show_config())

    # perform giant 2D IFFT
    big_array = cupyx.scipy.fft.ifft2(cupy.array(big_array))
```
Errors:
1. To get the OOM behavior, you can comment out the `set_allocator` line: `cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 8,000,000,000 bytes (allocated so far: 0 bytes).` - this however isn't surprising but expected
2. To get the illegal access behavior, keep the `set_allocator` line.

What's interesting is that I tried a few different lines of code. Some succeed, some fail:
1. Apply fft2 (forward fft) is OK
2. Apply `cupy.asnumpy()` on the output of fft2 is not OK - leads to illegal memory access
3. Apply ifft2 (backward fft) is not OK - leads to illegal memory access

ifft2 stacktrace:
```
  File "test.py", line 22, in <module>
    big_array = cupyx.scipy.fft.ifft2(cupy.array(big_array))
  File "/home/sevagh/venvs/museval-optimization-2/lib/python3.8/site-packages/cupyx/scipy/fft/_fft.py", line 214, in ifft2
    return ifftn(x, s, axes, norm, overwrite_x, plan=plan)
  File "/home/sevagh/venvs/museval-optimization-2/lib/python3.8/site-packages/cupyx/scipy/fft/_fft.py", line 285, in ifftn
    return func(x, s, axes, norm, cufft.CUFFT_INVERSE, overwrite_x=overwrite_x,
  File "/home/sevagh/venvs/museval-optimization-2/lib/python3.8/site-packages/cupy/fft/_fft.py", line 614, in _fftn
    a = _exec_fftn(a, direction, value_type, norm=norm, axes=axes_sorted,
  File "/home/sevagh/venvs/museval-optimization-2/lib/python3.8/site-packages/cupy/fft/_fft.py", line 514, in _exec_fftn
    plan = _get_cufft_plan_nd(a.shape, fft_type, axes=axes, order=order,
  File "/home/sevagh/venvs/museval-optimization-2/lib/python3.8/site-packages/cupy/fft/_fft.py", line 456, in _get_cufft_plan_nd
    plan = cufft.PlanNd(*keys)
  File "cupy/cuda/cufft.pyx", line 790, in cupy.cuda.cufft.PlanNd.__init__
  File "cupy/cuda/cufft.pyx", line 169, in cupy.cuda.cufft.check_result
cupy.cuda.cufft.CuFFTError: CUFFT_INTERNAL_ERROR
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by leofang** [comment]
Thanks for the detailed report, @sevagh! Forgot to ask: How did you install CuPy?

**Comment by sevagh** [comment]
I ran `pip install cupy-cuda112` from my Python 3.8 virtualenv. CUDA 11.2 is installed on my Fedora computer through the Negativo17 `fedora-nvidia` repository.

**Comment by sevagh** [comment]
Another interesting thing is that by using the FFTPlanNd directly, we can avoid ifft2 errors, but still get the same illegal access when copying the array back to the host:
```
gpu_array = cupy.array(big_array)
plan = cupyx.scipy.fftpack.get_fft_plan(gpu_array)

# perform giant 2D FFT in-place - works with no illegal address
plan.fft(gpu_array, gpu_array, 1)

# perform giant 2D IFFT in-place - works with no illegal address
plan.fft(gpu_array, gpu_array, -1)

back_to_host = cupy.asnumpy(gpu_array) # illegal address
```

**Comment by sevagh** [comment]
I tried some more things with cuda-memcheck:
```
========= CUDA-MEMCHECK
========= Invalid __global__ read of size 16
=========     at 0x00000710 in void regular_fft<unsigned int=25, unsigned int=5, unsigned int=32, padding_t=1, twiddle_t=0, loa
dstore_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_t<unsigned int>)
=========     by thread (31,3,0) in block (239,0,0)
=========     Address 0x7fe6d253aff0 is out of bounds
=========     Device Frame:void regular_fft<unsigned int=25, unsigned int=5, unsigned int=32, padding_t=1, twiddle_t=0, loadsto
re_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_t<unsigned int>) (void regular_fft<unsigned int=25, unsigne
d int=5, unsigned int=32, padding_t=1, twiddle_t=0, loadstore_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_
t<unsigned int>) : 0x710)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib64/libcuda.so.1 [0x253eba]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0x2199c5]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0xdd108]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0xea7ad]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0xd8ffd]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0xe29f2]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0x476b4]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0x31c62]
=========     Host Frame:/usr/lib64/libcufft.so.10 [0x31dd0]
=========     Host Frame:/usr/lib64/libcufft.so.10 (cufftExecZ2Z + 0x69) [0x43469]
=========     Host Frame:/home/sevagh/thirdparty-repos/cupy/cupy/cuda/cufft.cpython-38-x86_64-linux-gnu.so [0x187ad]
=========     Host Frame:/home/sevagh/thirdparty-repos/cupy/cupy/cuda/cufft.cpython-38-x86_64-linux-gnu.so [0x206fb]
=========     Host Frame:/lib64/libpython3.8.so.1.0 [0x11a217]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (_PyEval_EvalFrameDefault + 0x81f) [0x10b5df]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (_PyEval_EvalCodeWithName + 0x314) [0x109cd4]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (PyEval_EvalCodeEx + 0x3d) [0x18651d]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (PyEval_EvalCode + 0x1f) [0x1864cf]
=========     Host Frame:/lib64/libpython3.8.so.1.0 [0x1a78f8]
=========     Host Frame:/lib64/libpython3.8.so.1.0 [0x1a7013]
=========     Host Frame:/lib64/libpython3.8.so.1.0 [0x90595]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (PyRun_SimpleFileExFlags + 0x367) [0x8f7f5]
=========     Host Frame:/lib64/libpython3.8.so.1.0 [0x86b07]
=========     Host Frame:/lib64/libpython3.8.so.1.0 (Py_BytesMain + 0x3d) [0x179e6d]
=========     Host Frame:/lib64/libc.so.6 (__libc_start_main + 0xf2) [0x27082]
=========     Host Frame:python (_start + 0x2e) [0x109e]
=========
========= Invalid __global__ read of size 16
=========     at 0x00000710 in void regular_fft<unsigned int=25, unsigned int=5, unsigned int=32, padding_t=1, twiddle_t=0, loa
dstore_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_t<unsigned int>)
=========     by thread (30,3,0) in block (239,0,0)
=========     Address 0x7fe6d253afe0 is out of bounds
=========     Device Frame:void regular_fft<unsigned int=25, unsigned int=5, unsigned int=32, padding_t=1, twiddle_t=0, loadsto
re_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_t<unsigned int>) (void regular_fft<unsigned int=25, unsigne
d int=5, unsigned int=32, padding_t=1, twiddle_t=0, loadstore_modifier_t=2, layout_t=1, unsigned int, double>(kernel_arguments_
t<unsigned int>) : 0x710)
=========     Saved host backtrace up to driver entry point at kernel launch time
```
I tried compiling cupy with `CUPY_CUDA_COMPILE_WITH_DEBUG=1` (which should add lineinfo and debug info) but I couldn't get more information than the above.

**Comment by sevagh** [comment]
Last thing I'll guess is that the cufft plan is too large to coexist with the large array being streamed by the managed malloc.

**Comment by leofang** [comment]
@sevagh Sorry for my long silence. It originally appeared to be a cuFFT bug to me, but I cannot reproduce the cuda-memcheck error that you saw, which is odd. Below I am documenting what's seen on my side (CuPy 9.0, CUDA 11.2, RTX 2080 Ti):
|    | [Python code](https://github.com/cupy/cupy/issues/5134#issue-865150552) | C code (see below)
| --- | --------- | -----
| `CUDA_ERROR_ILLEGAL_ADDRESS` seen? |  yes   | no
| `cuda-memcheck` clean? | yes* | yes

(* I still see the `CUDA_ERROR_ILLEGAL_ADDRESS` driver error raised, but `cuda-memcheck` says no error is detected.)

@sevagh One question: How much is the total system (CPU) memory that you have? I noticed your code actually requires at least 48 GB memory if everything were placed on host in the beginning.

Another thing: Could you try running this C code without and with `cuda-memcheck`, and report what you see?
```C
// nvcc -lcufft test_cufft_bug.cu -o test_cufft_bug
// to use cuda-memcheck: export CUDA_MEMCHECK_PATCH_MODULE=1

#include <cstdio>
#include <cufft.h>
#include <cassert>


int main() {
  cufftDoubleComplex *in_arr = NULL, *out_arr = NULL;
  int dimx = 1000;
  int dimy = 1000 * 1000;
  assert (0 == cudaMallocManaged(&in_arr, dimx * dimy * sizeof(cufftDoubleComplex)));
  assert (0 == cudaMallocManaged(&out_arr, dimx * dimy * sizeof(cufftDoubleComplex)));
  cufftDoubleComplex *out_arr_h = (cufftDoubleComplex*)malloc(dimx * dimy * sizeof(*out_arr_h));

  cufftHandle plan;
  assert (0 == cufftCreate(&plan));
  assert (0 == cufftSetAutoAllocation(plan, 0));
  int ndim = 2;
  int n[2] = {dimx, dimy};
  int inembed[2] = {dimx, dimy};
  int istride = 1, idist = 1;
  int onembed[2] = {dimx, dimy};
  int ostride = 1, odist = 1;
  int batch = 1;
  size_t worksize;
  assert (0 == cufftMakePlanMany(plan, ndim, n, inembed, istride, idist, onembed, ostride, odist, CUFFT_Z2Z, batch, &worksize));
  printf("work size: %lu\n", worksize);
  void* work_area;
  assert (0 == cudaMallocManaged(&work_area, worksize));
  assert (0 == cufftSetWorkArea(plan, work_area));

  // run ifft2 (out of place)
  assert (0 == cufftExecZ2Z(plan, in_arr, out_arr, CUFFT_INVERSE));

  // copy the data back (probably not needed?)
  assert (0 == cudaMemcpy(out_arr_h, out_arr, dimx * dimy * sizeof(cufftDoubleComplex), cudaMemcpyDeviceToHost));

  assert (0 == cudaFree(work_area));
  assert (0 == cudaFree(in_arr));
  assert (0 == cudaFree(out_arr));
  assert (0 == cufftDestroy(plan));
  free(out_arr_h);
  return 0;
}
```

**Comment by sevagh** [comment]
My system memory is 32GB. Maybe I had a typo in the numpy dimensions of my first example, but it was only using around 12-15 GB system memory.

I just tested your cuda code above, but adapted the dimension to be a bit smaller to fit my 32GB system memory: `int dimy = 750 * 500;`
Results are good:
```
sevagh:test-cupy-bug $ nvcc -lcufft test_cufft_bug.cu -o test_cufft_bug
sevagh:test-cupy-bug $ export CUDA_MEMCHECK_PATCH_MODULE=1
sevagh:test-cupy-bug $
sevagh:test-cupy-bug $ ./test_cufft_bug
work size: 6000000000
```

**Comment by leofang** [comment]
@sevagh so what's the array shape you used in Python that led to the memory corruption error? The fact that we run the C code fine seems to suggest something is wrong in CuPy.

**Comment by sevagh** [comment]
It's still the original shape. How did you calculate that it takes 48GB host memory?

Here's the same minimal bug reproduction I pasted in the original report. When I run the IFFT on the host, it works fine:
```
(cupy-bug) sevagh:cupy $ python bug.py
size: 8.0 GB
shape: (1000, 1000000)
dtype: float64
```
![mem-use](https://user-images.githubusercontent.com/8574092/117313274-be1ca900-ae53-11eb-892c-cfea429ff2b1.png)
My computer ends up using 26GB out of 32 when running a host-side ifft (using scipy, not cupy):
```
import numpy as np
import scipy.fft
import cupyx
import cupy

# managed memory to stream large ndarrays to cuda
cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.memory.malloc_managed).malloc)


if __name__ == '__main__':
    # 10GB array, approx. won't fit in my 8GB gpu vmem
    big_array = np.random.standard_normal((1000, 1000000))

    print(f'size: {big_array.nbytes//1e9} GB')
    print(f'shape: {big_array.shape}')
    print(f'dtype: {big_array.dtype}')

    # perform giant 2D IFFT on GPU
    #big_array = cupyx.scipy.fft.ifft2(cupy.array(big_array))

    # perform 2D IFFT on CPU
    big_array = scipy.fft.ifft2(big_array)
```
When I run the IFFT on the GPU, same bug report as before. So it seems the dimensions are fine.
```
(cupy-bug) sevagh:cupy $ python bug.py
size: 8.0 GB
shape: (1000, 1000000)
dtype: float64
Traceback (most recent call last):
  File "bug.py", line 21, in <module>
    big_array = cupyx.scipy.fft.ifft2(cupy.array(big_array))
  File "/home/sevagh/thirdparty-repos/cupy/cupyx/scipy/fft/_fft.py", line 215, in ifft2
    return ifftn(x, s, axes, norm, overwrite_x, plan=plan)
  File "/home/sevagh/thirdparty-repos/cupy/cupyx/scipy/fft/_fft.py", line 286, in ifftn
    return func(x, s, axes, norm, cufft.CUFFT_INVERSE, overwrite_x=overwrite_x,
  File "/home/sevagh/thirdparty-repos/cupy/cupy/fft/_fft.py", line 614, in _fftn
    a = _exec_fftn(a, direction, value_type, norm=norm, axes=axes_sorted,
  File "/home/sevagh/thirdparty-repos/cupy/cupy/fft/_fft.py", line 514, in _exec_fftn
    plan = _get_cufft_plan_nd(a.shape, fft_type, axes=axes, order=order,
  File "/home/sevagh/thirdparty-repos/cupy/cupy/fft/_fft.py", line 456, in _get_cufft_plan_nd
    plan = cufft.PlanNd(*keys)
  File "cupy/cuda/cufft.pyx", line 790, in cupy.cuda.cufft.PlanNd.__init__
    check_result(result)
  File "cupy/cuda/cufft.pyx", line 169, in cupy.cuda.cufft.check_result
    raise CuFFTError(result)
cupy.cuda.cufft.CuFFTError: CUFFT_INTERNAL_ERROR
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by leofang** [comment]
>> I noticed your code actually requires at least 48 GB memory if everything were placed on host in the beginning.
>
> It's still the original shape. How did you calculate that it takes 48GB host memory? The ndarray states it only takes 8GB

See my C code. So I forgot that initially your array was of dtype `float64`. My C code initialized with a `complex128` array. If everything were placed on host memory first (including those on managed memory, which can be migrated between host and device), then it takes 
- original input: 16 GB (of dtype `complex128`) or 8 GB (of dtype `float64`)
- internal copy for FFT input: 16 GB of dtype `complex128`
- FFT output: 16 GB of dtype `complex128`

In total: 40 GB or 48 GB. 

> My computer ends up using 26GB out of 32 when running a host-side ifft (using scipy, not cupy)

Yeah, SciPy might have its own decision on whether to make an internal copy or not. CuPy makes a copy for real inputs.

**Comment by leofang** [comment]
> I just tested your cuda code above, but adapted the dimension to be a bit smaller to fit my 32GB system memory: `int dimy = 750 * 500;`

@sevagh What happens if you use the same dimension matching the Python reproducer (i.e. those from my C code)?

**Comment by sevagh** [comment]
Python code with complex128 using scipy host-side FFT, works OK:
```
(cupy-bug) sevagh:cupy $ python bug.py
size: 16.0 GB
shape: (1000, 1000000)
dtype: complex128
```
My system memory gets almost maxed and swap starts increasing (as expected), but it still succeeds (I guess scipy fft does some manipulation to avoid going OOM).

If I run your original CUDA code with the original dimensons:
```
sevagh:test-cupy-bug $ ./test_cufft_bug
work size: 16000000000
test_cufft_bug: test_cufft_bug.cu:38: int main(): Assertion `0 == cudaMemcpy(out_arr_h, out_arr, dimx * dimy * sizeof(cufftDoubleComplex), cudaMemcpyDeviceToHost)' failed.
```
With CUDA memcheck:
```


========= Error: process didn't terminate successfully
========= Fatal UVM GPU fault of type invalid pde due to out of memory
=========     during write access to address 0x7f517aa00000
```
Aborted (core dumped)
```

**Comment by leofang** [comment]
Thanks for testing @sevagh. Could you try commenting out the line `cudaMemcpy` and rerun the CUDA code?

**Comment by sevagh** [comment]
```
sevagh:test-cupy-bug $ ./test_cufft_bug
work size: 16000000000
test_cufft_bug: test_cufft_bug.cu:40: int main(): Assertion `0 == cudaFree(work_area)' failed.
Aborted (core dumped)
```

**Comment by leofang** [comment]
Interesting....

**Comment by sevagh** [comment]
For what it's worth, I was able to work around the original issue by using smaller ndarrays (mono-channel audio instead of 2-channel), and not using the managed malloc. Instead, I play around with and clear the cupy FFT cache regularly:
```
mempool = cupy.get_default_memory_pool()

for item in items_to_process:
        ######
        do some expensive cupy fft here
        ######
        
        # cupy disable fft caching to free blocks
        fft_cache = get_plan_cache()
        fft_cache.set_size(0)
        
        mempool.free_all_blocks()
        
        # cupy reenable fft caching
        fft_cache.set_size(16)
        fft_cache.set_memsize(-1)
```
It looks like the plan cache can grow surprisingly large if we try to do FFTs on different and huge ndarrays.

**Comment by leofang** [comment]
@sevagh On the plan cache: yes, if your input arrays from `items_to_process` have all kinds of different shapes, it'd generate a plan for each input, and the plan cache would not help at all. I assume the "growing" of plan cache referred to the increasing usage of device memory, which is a correct observation as each plan has its own workarea allocated, and in the worst case (non-prime length input) the work area grows linearly w.r.t. the input size, which is huge (check out the CUDA code: it reports how large the work area was needed). In this case you could just set `cache.set_size(0)` to disable it entirely. May I ask what's the reason to reactivate it in your snippet?

I will continue to look into the memory corruption later this week...

**Comment by sevagh** [comment]
Yeah I removed too much info - the processing is very repetitive, such that the cache is desired and useful (it does ~30 FFT + IFFT of the same size) per different music track.

However, I run the analysis in the outer for loop for multiple diverse music tracks, so after each track it's necessary to clear the previous cache (or else run out of GPU memory).
