### ISSUE TITLE
conda install cupy installs wrong toolkit version with CUDA 11.0 on Windows

### ISSUE THREAD

**Issue by thomasaarholt** [cupy/cupy#5179]
`conda create --name cutest cupy` installs toolkit version 11.2 when I have CUDA 11.0 installed. This raises the error below.
`conda create --name cutest2 cupy cudatoolkit=11.0` works fine.

Ideally, conda would check which `cudatoolkit` version should be installed. Is this currently possible?
If not - would it be possible to check that the versions match on `import cupy`, and then raise a more useful error?

I check CUDA version by `nvcc --version`: version 11.0 is installed (using 11.0 for compatability reasons with other software)

Both `cp.linspace(0, 10, 10)` and `cp.show_config()` result in essentially the same error:

```python
$ python -c 'import cupy; cupy.show_config()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupy\__init__.py", line 860, in show_config
    _sys.stdout.write(str(_cupyx.get_runtime_info()))
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 277, in get_runtime_info
    return _RuntimeInfo()
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 156, in __init__
    self.cublas_version = _eval_or_error(
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 64, in _eval_or_error
    return func()
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 158, in <lambda>
    cupy.cuda.device.get_cublas_handle()),
  File "cupy\cuda\device.pyx", line 46, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 47, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 29, in cupy.cuda.device._get_device
  File "cupy_backends\cuda\api\runtime.pyx", line 289, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends\cuda\api\runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - The above call results in the same error.
  - CuPy version: 9.0.0
  - OS/Platform: Windows 10 v1909
  - CUDA version: 11.0

**Comment by leofang** [comment]
Hi @thomasaarholt Could you post the output of `conda list` for the failing environment?

Also, generally for the Conda-Forge installations and dependency issues it's preferably to open an issue in the corresponding feedstock (CuPy: https://github.com/conda-forge/cupy-feedstock), as the people behind the conda packaging and the main project may not be the same. (In CuPy's case it's the same, but it still helps us to triage faster 🙂)

**Comment by thomasaarholt** [comment]
Alright! I've posted conda-forge/cupy-feedstock#128 :)
