### ISSUE TITLE
cupy.cuda.compiler.CompileException: /tmp/tmpiatufk20/d1a46dada092a1d26c70ca560727a5db_2.cubin.cu(56): catastrophic error: cannot open source file "cuda_runtime.h"

### ISSUE THREAD

**Issue by 834799106** [cupy/cupy#5202]
>>> import cupy
>>> cupy.show_config()
OS                           : Linux-3.10.107-1-tlinux2_kvm_guest-0052-x86_64-with-glibc2.10
CuPy Version                 : 9.0.0
NumPy Version                : 1.20.1
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /data/home/v_lifengmei/cuda-10.2
CUDA Build Version           : 10020
CUDA Driver Version          : 10020
CUDA Runtime Version         : 10020
cuBLAS Version               : 10202
cuFFT Version                : 10102
cuRAND Version               : 10102
cuSOLVER Version             : (10, 3, 0)
cuSPARSE Version             : 10301
NVRTC Version                : (10, 2)
Thrust Version               : 100907
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8101
cuDNN Version                : 8200
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:00:09.0
Device 1 Name                : Tesla V100-SXM2-32GB
Device 1 Compute Capability  : 70
Device 1 PCI Bus ID          : 0000:00:0A.0

**Comment by kmaehashi** [comment]
This seems like an issue with your CUDA installation. Do you have `include/cuda_runtime.h` under your CUDA root (`/data/home/v_lifengmei/cuda-10.2`)?

**Comment by 834799106** [comment]
> This seems like an issue with your CUDA installation. Do you have `include/cuda_runtime.h` under your CUDA root (`/data/home/v_lifengmei/cuda-10.2`)?

yes i have checked include/cuda_runtime.h under /data/home/v_lifengmei/cuda-10.2

**Comment by kmaehashi** [comment]
Could you share the code to reprocue this?

**Comment by 834799106** [comment]
> Could you share the code to reproduce this?

https://github.com/sniklaus/3d-ken-burns
i can run it from colab but not my computer

**Comment by 834799106** [comment]
> Could you share the code to reproduce this?

Traceback (most recent call last):
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 623, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 133, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 145, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 64, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autozoom.py", line 85, in <module>
    objTo = process_autozoom({
  File "<string>", line 116, in process_autozoom
  File "<string>", line 352, in render_pointcloud
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "<string>", line 296, in launch_kernel
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 432, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 509, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 271, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 255, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "/data/home/v_lifengmei/anaconda3/envs/ken/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 635, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmppzxi3yv7/03e20ac1fb197c4434c893ed421f20dc_2.cubin.cu(56): catastrophic error: cannot open source file "cuda_runtime.h"

1 catastrophic error detected in the compilation of "/tmp/tmppzxi3yv7/03e20ac1fb197c4434c893ed421f20dc_2.cubin.cu".
Compilation terminated.

**Comment by leofang** [comment]
> > Could you share the code to reproduce this?
> 
> https://github.com/sniklaus/3d-ken-burns

@834799106 It is impossible for library maintainers to dig into every downstream project and debug for them. You either have to provide a *self-contained, minimal reproducer* (see [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) and [here](https://stackoverflow.com/help/minimal-reproducible-example) for what it means) in your bug report, or report first to the project you're using, as the project developer/maintainer must know their own code a lot better than we do.

**Comment by kmaehashi** [comment]
Closing as this issue is inactive recently. Feel free to reopen if there's anything we can help.
