### ISSUE TITLE
Unexpected error while assigning array element

### ISSUE THREAD

**Issue by insertinterestingnamehere** [cupy/cupy#5328]
With CuPy 8.6.0, 9.1.0, and master on Ubuntu 18.04 with Cuda 10.2 running the following code produces some kind of internal compiler error in cupy:
```
import cupy as cp
a = cp.zeros((66, 66, 66, 200, 32), 'f')
a[33, 33, 33, 80, 0] = 1.
```

The code that triggers this error was working several months ago, but I haven't found a working version to use yet.

I haven't pinned down exactly how big the array `a` needs to be to trigger this error yet, but does have to be large. Just setting the first item of a 2x2x2x2x2 array didn't hit the error. This example uses almost 8GB of VRAM.

The rather lengthy error is:
```
Traceback (most recent call last):
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 623, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 133, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 145, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 64, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1384, in cupy._core.core.ndarray.__setitem__
  File "cupy/_core/_routines_indexing.pyx", line 54, in cupy._core._routines_indexing._ndarray_setitem
  File "cupy/_core/_routines_indexing.pyx", line 955, in cupy._core._routines_indexing._scatter_op
  File "cupy/_core/core.pyx", line 588, in cupy._core.core.ndarray.fill
  File "cupy/_core/_kernel.pyx", line 841, in cupy._core._kernel.ElementwiseKernel.__call__
  File "cupy/_core/_kernel.pyx", line 866, in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/_util.pyx", line 59, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_kernel.pyx", line 653, in cupy._core._kernel._get_elementwise_kernel
  File "cupy/_core/_kernel.pyx", line 61, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/core.pyx", line 2001, in cupy._core.core.compile_with_cache
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 432, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 509, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 271, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 255, in _compile
    ptx, mapping = prog.compile(options, log_stream)
  File "/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 635, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/_core/include/cupy/carray.cuh(221): error: the size of an array must be greater than zero
          detected during instantiation of class "CArray<T, _ndim, _c_contiguous, _use_32bit_indexing> [with T=float, _ndim=0, _c_contiguous=true, _use_32bit_indexing=false]"
/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu(8): here

/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/_core/include/cupy/carray.cuh(222): error: the size of an array must be greater than zero
          detected during instantiation of class "CArray<T, _ndim, _c_contiguous, _use_32bit_indexing> [with T=float, _ndim=0, _c_contiguous=true, _use_32bit_indexing=false]"
/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu(8): here

/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/_core/include/cupy/carray.cuh(323): error: the size of an array must be greater than zero
          detected during instantiation of class "CArray<T, _ndim, _c_contiguous, _use_32bit_indexing> [with T=float, _ndim=0, _c_contiguous=true, _use_32bit_indexing=false]"
/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu(8): here

/org/centers/cdgc/ian/miniconda3/envs/cupy_dev/lib/python3.9/site-packages/cupy/_core/include/cupy/carray.cuh(328): error: the size of an array must be greater than zero
          detected during instantiation of class "CArray<T, _ndim, _c_contiguous, _use_32bit_indexing> [with T=float, _ndim=0, _c_contiguous=true, _use_32bit_indexing=false]"
/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu(8): here

/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu(12): error: no operator "[]" matches these operands
            operand types are: CArray<float, 0, true, false> [ const ptrdiff_t * ]

5 errors detected in the compilation of "/tmp/tmpkywqfpoy/51a0d81ea8dcaefc60d9e9a2fb3aa834_2.cubin.cu".
```

**Comment by insertinterestingnamehere** [comment]
Actually here's a slightly simpler example:
```
a = cp.zeros(536870913, 'f')
a[-1] = 1.
```
Given that it works if a is one element smaller, this probably has to do with a signed integer overflow somewhere.

**Comment by insertinterestingnamehere** [comment]
This also hits when accessing the first element. The key thing is that the array being indexed needs to have more than 2147483647 (signed int max) bytes.

**Comment by leofang** [comment]
Nice catch!
