### ISSUE TITLE
ROCm RawModule template kernel with complex

### ISSUE THREAD

**Issue by scarrazza** [cupy/cupy#5436]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version 9.1.0
  - OS/Platform AMD ROCm

* Code to reproduce

```python
import cupy

code = r'''
#include <cupy/complex.cuh>
template<typename T>
__global__ void func(T* in_arr) { /* do something */ }
'''

kers = ('func<int>', 'func<complex<double>>')
mod = cupy.RawModule(code=code, options=('--std=c++11',),
                         name_expressions=kers, translate_cucomplex=False)

ker_int = mod.get_function(kers[1])
```

* Error messages, stack traces, or logs

When calling `RawModule.get_function()` using kernels with template names

```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    ker_int = mod.get_function(kers[1])
  File "cupy/_core/raw.pyx", line 485, in cupy._core.raw.RawModule.get_function
  File "cupy/_core/raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy/_core/raw.pyx", line 117, in cupy._core.raw.RawKernel._kernel
  File "cupy/cuda/function.pyx", line 253, in cupy.cuda.function.Module.get_function
  File "cupy/cuda/function.pyx", line 194, in cupy.cuda.function.Function.__init__
  File "cupy_backends/cuda/api/driver.pyx", line 269, in cupy_backends.cuda.api.driver.moduleGetFunction
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: hipErrorNotFound: hipErrorNotFound
```

However if I do not use templates, the kernel runs fine. 
Is that feature not supported on ROCm?

**Comment by leofang** [comment]
On my cell, forgive my brevity: Could you try setting `backend='hipcc'` in `RawModule`? I seem to remember encountering similar issues with hipRTC (the default backend). I can look into it later.

**Comment by leofang** [comment]
Also, could you post the output of ` cupy.show_config()` please?

**Comment by scarrazza** [comment]
@leofang thanks.

The `backend='hipcc'` crashes with:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    mod = cupy.RawModule(code=code, options=('--std=c++11',),
  File "cupy/_core/raw.pyx", line 361, in cupy._core.raw.RawModule.__init__
ValueError: only nvrtc supports retrieving the mangled names for the given name expressions
```

Here the full show config:
<details>

```
OS                        : Linux-5.4.0-74-generic-x86_64-with-glibc2.29
Python Version            : 3.8.5
CuPy Version              : 9.1.0
CuPy Platform             : AMD ROCm
NumPy Version             : 1.19.5
SciPy Version             : 1.7.0rc2
Cython Build Version      : 0.29.22
Cython Runtime Version    : None
CUDA Root                 : /usr
hipcc PATH                : /usr/bin/hipcc
CUDA Build Version        : 400
CUDA Driver Version       : 327500
CUDA Runtime Version      : 3275
cuBLAS Version            : 23200
cuFFT Version             : 100
cuRAND Version            : 201009
cuSOLVER Version          : (3, 10, 0)
cuSPARSE Version          : 32593
NVRTC Version             : (9, 0)
Thrust Version            : 100908
CUB Build Version         : 201005
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 2708
NCCL Runtime Version      : 2804
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : Vega 20 [Radeon VII]
Device 0 Arch             : gfx906:sramecc-:xnack-
Device 0 PCI Bus ID       : 0000:43:00.0
```

</details>

**Comment by leofang** [comment]
Oh yes...I forgot 🤦🏻‍♂️ Let me check later.

**Comment by leofang** [comment]
@scarrazza I was right. This is a known hipRTC bug observed since as early as ROCm 3.5. Looks like it is still an issue on ROCm 4.0:
https://github.com/cupy/cupy/blob/ef422ca88182fad0a9544026d6104baf03d2a077/tests/cupy_tests/core_tests/test_raw.py#L812-L818
cc @amathews-amd: Any chance you could file a bug report internally for us please? 😇 I haven't tested it on ROCm 4.2, though, so maybe we need to test on 4.2 first.

**Comment by scarrazza** [comment]
@leofang thank you very much for checking.

**Comment by amathews-amd** [comment]
@leofang , 
I was creating a reproducer with `my_sqrt<complex<double>>`, when I got this error on CUDA 11.0. 
```
Error: 6
__nv_name_map(2): error: space required between adjacent ">" delimiters of nested template argument lists (">>" is the right shift operator)

__nv_name_map(2): error: Name expression cannot form address of a non-__global__ function. Input name expression was: " my_sqrt < complex < double >>"

2 errors detected in the compilation of "default_program".
```
So, I added a space to `my_sqrt<complex<double> >`.  With the same change in HIP version of the code, I get the lowered name. 
**HIP**
```
 Lowered Name for my_sqrt<int> is '_Z7my_sqrtIiEvPT_i'.
 Lowered Name for my_sqrt<float> is '_Z7my_sqrtIfEvPT_i'.
 Lowered Name for my_sqrt<complex<double> > is '_Z7my_sqrtI7complexIdEEvPT_i'.
```
**CUDA**
```
 Lowered Name for my_sqrt<int> is '_Z7my_sqrtIiEvPT_i'.
 Lowered Name for my_sqrt<float> is '_Z7my_sqrtIfEvPT_i'.
 Lowered Name for my_sqrt<complex<double> > is '_Z7my_sqrtI7complexIdEEvPT_i'.
```
________________________________________________________________
**HIP Program**
```
#include <stdio.h>
#include <iostream>
#include "hip/hiprtc.h"
#include <vector>

int main()
{

    hiprtcProgram prog;

    std::string code =
      "#include \"hip/hip_runtime.h\" \n"
        "    template <typename T>"
        "        struct complex {"
        "            public:"
        "                typedef T value_type;"
        "                inline __host__ __device__ complex(const T& re, const T& im);"
        "                __host__ __device__ inline complex<T>& operator*=(const complex<T> z);"
        "                __host__ __device__ inline T real() const volatile { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const volatile { return m_data[1]; }"
        "                __host__ __device__ inline T real() const { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const { return m_data[1]; }"
        "                __host__ __device__ inline void real(T re) volatile { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) volatile { m_data[1] = im; }"
        "                __host__ __device__ inline void real(T re) { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) { m_data[1] = im; }"
        "            private:"
        "                T m_data[2];"
        "        };"
        "    template <typename T>"
        "        inline __host__ __device__ complex<T>::complex(const T& re, const T& im) {"
        "            real(re);"
        "            imag(im);"
        "        }"
        "    template <typename T>"
        "        __host__ __device__ inline complex<T>& complex<T>::operator*=(const complex<T> z) {"
        "            *this = *this * z;"
        "            return *this;"
        "        }"
        "   template <typename T>"
        "       __host__ __device__ inline complex<T> operator*(const complex<T>& lhs,"
        "                                                const complex<T>& rhs) {"
        "           return complex<T>(lhs.real() * rhs.real() - lhs.imag() * rhs.imag(),lhs.real() * rhs.imag() + lhs.imag() * rhs.real());"
        "       }"
        " /* ------ DEVICE GLOBAL FUNCTION ------ */ "
        "template<typename T> "
        "__global__ void my_sqrt(T* input, int N) {"
        "  unsigned int x = blockIdx.x * blockDim.x + threadIdx.x;"
        "  if (x < N) {"
        "    input[x] *= input[x];"
        "  }"
        "}";

    // CREATE PROGRAM
    const char *headers[] = {""};
    const char *header_content[] = {"\n"};

    hiprtcResult result = hiprtcCreateProgram(&prog, code.c_str(), NULL, 0, header_content, headers);

    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

    std::vector<std::string> options;

    /* Tranfer options to a classic C array. */
    std::vector<const char *> opts(options.size());
    for (size_t i = 0; i < options.size(); i++) {
      opts[i] = options[i].c_str();
    }

    // ADD NAME EXPRESSION
    std::vector<std::string> name_expressions;
    name_expressions.push_back("my_sqrt<int>");
    name_expressions.push_back("my_sqrt<float>");
    name_expressions.push_back("my_sqrt<complex<double> >");

    for(size_t i = 0; i < name_expressions.size(); i++){
        result = hiprtcAddNameExpression(prog, name_expressions[i].c_str() );

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << "adding Name Expression " << name_expressions[i] << (int)result << std::endl; return 1; }
    }

    // COMPILE PROGRAM
    result = hiprtcCompileProgram(prog, options.size(), &opts[0]);

    if( result!= HIPRTC_SUCCESS ) {
        std::cout<<"Error: " << (int)result << std::endl;

        size_t log_size;
        hiprtcGetProgramLogSize(prog, &log_size);

        std::vector<char> log(log_size);
        hiprtcGetProgramLog(prog, &log[0]);
        fprintf(stderr, "%s\n", &log[0]);

      return 1;
    }

    // GET LOWERED NAME
    for(size_t i = 0; i < name_expressions.size(); i++){
        const char* mangled_instantiation_cstr;
        result = hiprtcGetLoweredName(prog, name_expressions[i].c_str(), &mangled_instantiation_cstr);

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

        std::cout << " Lowered Name for " << name_expressions[i] << " is '" << mangled_instantiation_cstr << "'." << std::endl;
    }

    // DESTROY PROGRAM
    result = hiprtcDestroyProgram(&prog);
    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

}
```

**CUDA Program**
```
#include <stdio.h>
#include <iostream>
#include "nvrtc.h"
#include <vector>

int main()
{

    nvrtcProgram prog;

    std::string code =
        "    template <typename T>"
        "        struct complex {"
        "            public:"
        "                typedef T value_type;"
        "                inline __host__ __device__ complex(const T& re, const T& im);"
        "                __host__ __device__ inline complex<T>& operator*=(const complex<T> z);"
        "                __host__ __device__ inline T real() const volatile { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const volatile { return m_data[1]; }"
        "                __host__ __device__ inline T real() const { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const { return m_data[1]; }"
        "                __host__ __device__ inline void real(T re) volatile { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) volatile { m_data[1] = im; }"
        "                __host__ __device__ inline void real(T re) { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) { m_data[1] = im; }"
        "            private:"
        "                T m_data[2];"
        "        };"
        "    template <typename T>"
        "        inline __host__ __device__ complex<T>::complex(const T& re, const T& im) {"
        "            real(re);"
        "            imag(im);"
        "        }"
        "    template <typename T>"
        "        __host__ __device__ inline complex<T>& complex<T>::operator*=(const complex<T> z) {"
        "            *this = *this * z;"
        "            return *this;"
        "        }"
        "   template <typename T>"
        "       __host__ __device__ inline complex<T> operator*(const complex<T>& lhs,"
        "                                                const complex<T>& rhs) {"
        "           return complex<T>(lhs.real() * rhs.real() - lhs.imag() * rhs.imag(),lhs.real() * rhs.imag() + lhs.imag() * rhs.real());"
        "       }"
        " /* ------ DEVICE GLOBAL FUNCTION ------ */ "
        "template<typename T> "
        "__global__ void my_sqrt(T* input, int N) {"
        "  unsigned int x = blockIdx.x * blockDim.x + threadIdx.x;"
        "  if (x < N) {"
        "    input[x] *= input[x];"
        "  }"
        "}";

    // CREATE PROGRAM
    const char *headers[] = {""};
    const char *header_content[] = {"\n"};

    nvrtcResult result = nvrtcCreateProgram(&prog, code.c_str(), NULL, 0, header_content, headers);

    if( result!= NVRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

    std::vector<std::string> options;

    /* Tranfer options to a classic C array. */
    std::vector<const char *> opts(options.size());
    for (size_t i = 0; i < options.size(); i++) {
      opts[i] = options[i].c_str();
    }

    // ADD NAME EXPRESSION
    std::vector<std::string> name_expressions;
    name_expressions.push_back("my_sqrt<int>");
    name_expressions.push_back("my_sqrt<float>");
    name_expressions.push_back("my_sqrt<complex<double> >");

    for(size_t i = 0; i < name_expressions.size(); i++){
        result = nvrtcAddNameExpression(prog, name_expressions[i].c_str() );

        if( result!= NVRTC_SUCCESS ) { std::cout<<"Error: " << "adding Name Expression " << name_expressions[i] << (int)result << std::endl; return 1; }
    }

    // COMPILE PROGRAM
    result = nvrtcCompileProgram(prog, options.size(), &opts[0]);

    if( result!= NVRTC_SUCCESS ) {
        std::cout<<"Error: " << (int)result << std::endl;

        size_t log_size;
        nvrtcGetProgramLogSize(prog, &log_size);

        std::vector<char> log(log_size);
        nvrtcGetProgramLog(prog, &log[0]);
        fprintf(stderr, "%s\n", &log[0]);

      return 1;
    }

    // GET LOWERED NAME
    for(size_t i = 0; i < name_expressions.size(); i++){
        const char* mangled_instantiation_cstr;
        result = nvrtcGetLoweredName(prog, name_expressions[i].c_str(), &mangled_instantiation_cstr);

        if( result!= NVRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

        std::cout << " Lowered Name for " << name_expressions[i] << " is '" << mangled_instantiation_cstr << "'." << std::endl;
    }

    // DESTROY PROGRAM
    result = nvrtcDestroyProgram(&prog);
    if( result!= NVRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

}
```

**Comment by leofang** [comment]
Hello @amathews-amd! Thanks for taking a look. I am slowly catching up things after a long long break...

The `__nv_name_map` error you got with NVRTC is because you didn't set `-std=c++11` or higher to NVRTC. Once you do that by replacing this line
```C++
std::vector<std::string> options;
```
with
```C++
std::vector<std::string> options = {"--std=c++11", };
```
The lower name of `my_sqrt<complex<double>>` (no spacing!) can be fetched correctly. 

However, this is not the case with hipRTC. With the above change, this is what I get (consistent with the current bug report and my earlier observation):
```
Lowered Name for my_sqrt<complex<double>> is ''.
```

**Comment by leofang** [comment]
> However, this is not the case with hipRTC. With the above change, this is what I get (consistent with the current bug report and my earlier observation):
> 
> ```
> Lowered Name for my_sqrt<complex<double>> is ''.
> ```

@amathews-amd btw I just checked that this still happens with ROCm 4.2.0.

**Comment by leofang** [comment]
@scarrazza FYI the best workaround for the time being is like what @amathews-amd showed above: add a space between the tailing bracket of your template specialization (ex: `func<complex<double> >`).

**Comment by scarrazza** [comment]
@leofang @amathews-amd thanks for this checks, however the workaround does not seem to work for me:

**Code**
```python
import cupy

code = r'''
#include <cupy/complex.cuh>
template<typename T>
__global__ void func(T* in_arr) { /* do something */ }
'''

kers = ('func<int>', 'func<complex<double> >')
mod = cupy.RawModule(code=code, options=('--std=c++11',),
                         name_expressions=kers)

ker_int = mod.get_function(kers[1])

```

**Crash**

<details>

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    ker_int = mod.get_function(kers[1])
  File "cupy/_core/raw.pyx", line 485, in cupy._core.raw.RawModule.get_function
  File "cupy/_core/raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy/_core/raw.pyx", line 117, in cupy._core.raw.RawKernel._kernel
  File "cupy/cuda/function.pyx", line 253, in cupy.cuda.function.Module.get_function
  File "cupy/cuda/function.pyx", line 194, in cupy.cuda.function.Function.__init__
  File "cupy_backends/cuda/api/driver.pyx", line 269, in cupy_backends.cuda.api.driver.moduleGetFunction
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: hipErrorNotFound: hipErrorNotFound
```

</details>

Does this code example works for you?

**Comment by leofang** [comment]
Thanks for testing, @scarrazza. I can reproduce it with both your snippet and a C++-equivalent reproducer (see below). 

@amathews-amd My wild guess is that your `complex` class is concise enough so that the workaround (with a space) works. For example, this works fine:

<details><summary>Code</summary>
<p>

```C++
#include <stdio.h>
#include <iostream>
#include "hip/hiprtc.h"
#include "hip/hip_runtime.h"
#include <vector>
#include <assert.h>

int main()
{

    hiprtcProgram prog;

    std::string code =
      "#include \"hip/hip_runtime.h\" \n"
        "    template <typename T>"
        "        struct complex {"
        "            public:"
        "                typedef T value_type;"
        "                inline __host__ __device__ complex(const T& re, const T& im);"
        "                __host__ __device__ inline complex<T>& operator*=(const complex<T> z);"
        "                __host__ __device__ inline T real() const volatile { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const volatile { return m_data[1]; }"
        "                __host__ __device__ inline T real() const { return m_data[0]; }"
        "                __host__ __device__ inline T imag() const { return m_data[1]; }"
        "                __host__ __device__ inline void real(T re) volatile { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) volatile { m_data[1] = im; }"
        "                __host__ __device__ inline void real(T re) { m_data[0] = re; }"
        "                __host__ __device__ inline void imag(T im) { m_data[1] = im; }"
        "            private:"
        "                T m_data[2];"
        "        };"
        "    template <typename T>"
        "        inline __host__ __device__ complex<T>::complex(const T& re, const T& im) {"
        "            real(re);"
        "            imag(im);"
        "        }"
        "    template <typename T>"
        "        __host__ __device__ inline complex<T>& complex<T>::operator*=(const complex<T> z) {"
        "            *this = *this * z;"
        "            return *this;"
        "        }"
        "   template <typename T>"
        "       __host__ __device__ inline complex<T> operator*(const complex<T>& lhs,"
        "                                                const complex<T>& rhs) {"
        "           return complex<T>(lhs.real() * rhs.real() - lhs.imag() * rhs.imag(),lhs.real() * rhs.imag() + lhs.imag() * rhs.real());"
        "       }"
        " /* ------ DEVICE GLOBAL FUNCTION ------ */ "
        "template<typename T> "
        "__global__ void my_sqrt(T* input, int N) {"
        "  unsigned int x = blockIdx.x * blockDim.x + threadIdx.x;"
        "  if (x < N) {"
        "    input[x] *= input[x];"
        "  }"
        "}";

    // CREATE PROGRAM
    const char *headers[] = {""};
    const char *header_content[] = {"\n"};

    hiprtcResult result = hiprtcCreateProgram(&prog, code.c_str(), NULL, 0, header_content, headers);

    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

    std::vector<std::string> options = {"--std=c++11", };

    /* Tranfer options to a classic C array. */
    std::vector<const char *> opts(options.size());
    for (size_t i = 0; i < options.size(); i++) {
      opts[i] = options[i].c_str();
    }

    // ADD NAME EXPRESSION
    std::vector<std::string> name_expressions;
    name_expressions.push_back("my_sqrt<int>");
    name_expressions.push_back("my_sqrt<float>");
    name_expressions.push_back("my_sqrt<complex<double> >");

    for(size_t i = 0; i < name_expressions.size(); i++){
        result = hiprtcAddNameExpression(prog, name_expressions[i].c_str() );

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << "adding Name Expression " << name_expressions[i] << (int)result << std::endl; return 1; }
    }

    // COMPILE PROGRAM
    result = hiprtcCompileProgram(prog, options.size(), &opts[0]);

    if( result!= HIPRTC_SUCCESS ) {
        std::cout<<"Error: " << (int)result << std::endl;

        size_t log_size;
        hiprtcGetProgramLogSize(prog, &log_size);

        std::vector<char> log(log_size);
        hiprtcGetProgramLog(prog, &log[0]);
        fprintf(stderr, "%s\n", &log[0]);

      return 1;
    }

    // Obtain Code from the program.
    size_t ptxSize;
    result = hiprtcGetCodeSize(prog, &ptxSize);
    if( result != HIPRTC_SUCCESS ) { std::cout << "Error:" << result << std::endl; return 1; }
    char *ptx = new char[ptxSize];
    result = hiprtcGetCode(prog, ptx);
    if( result != HIPRTC_SUCCESS ) { std::cout << "Error:" << result << std::endl; return 1; }

    // Load the generated Code
    hipError_t err;
    int dev;
    err = hipSetDevice(0);
    if (err != hipSuccess) {
        std::cout << "device error:" << hipGetErrorName(err) << std::endl;
        return 1;
    }
    hipModule_t module;
    err = hipModuleLoadData(&module, ptx);
    if (err != hipSuccess) {
        std::cout << "module load error:" << hipGetErrorName(err) << std::endl;
        return 1;
    }

    // GET LOWERED NAME & KERNEL
    for(size_t i = 0; i < name_expressions.size(); i++){
        const char* mangled_instantiation_cstr;
        result = hiprtcGetLoweredName(prog, name_expressions[i].c_str(), &mangled_instantiation_cstr);

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

        std::cout << " Lowered Name for " << name_expressions[i] << " is '" << mangled_instantiation_cstr << "'." << std::endl;

        hipFunction_t func;
        err = hipModuleGetFunction(&func, module, mangled_instantiation_cstr);
        if (err != hipSuccess) {
            std::cout << "function load error:" << hipGetErrorName(err) << std::endl;
            return 1;
        } else {
            std::cout << "got kernel" << std::endl;
        }
    }

    // DESTROY PROGRAM
    result = hiprtcDestroyProgram(&prog);
    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

}
```

</p>
</details>

Output:
```
 Lowered Name for my_sqrt<int> is '_Z7my_sqrtIiEvPT_i'.
got kernel
 Lowered Name for my_sqrt<float> is '_Z7my_sqrtIfEvPT_i'.
got kernel
 Lowered Name for my_sqrt<complex<double> > is '_Z7my_sqrtI7complexIdEEvPT_i'.
got kernel
```

However, when using a real-world `complex` class (from CuPy, which is in turn taken from Thrust) it fails:

<details><summary>Code</summary>
<p>

```C++
// assuming this file is placed in CuPy's source root (see the "-I" option below)

#include <stdio.h>
#include <iostream>
#include "hip/hiprtc.h"
#include "hip/hip_runtime.h"
#include <vector>
#include <assert.h>

int main()
{

    hiprtcProgram prog;

    std::string code =
        "#include \"hip/hip_runtime.h\" \n"
        "#include <cupy/complex.cuh>\n"
        "template<typename T> "
        "__global__ void my_sqrt(T* input, int N) {"
        "  unsigned int x = blockIdx.x * blockDim.x + threadIdx.x;"
        "  if (x < N) {"
        "    input[x] *= input[x];"
        "  }"
        "}";

    std::cout << "code is:" << std::endl << code << std::endl;

    // CREATE PROGRAM
    const char *headers[] = {""};
    const char *header_content[] = {"\n"};

    hiprtcResult result = hiprtcCreateProgram(&prog, code.c_str(), NULL, 0, header_content, headers);

    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

    std::vector<std::string> options = {"--std=c++11", "-I./cupy/_core/include"};

    /* Tranfer options to a classic C array. */
    std::vector<const char *> opts(options.size());
    for (size_t i = 0; i < options.size(); i++) {
      opts[i] = options[i].c_str();
    }

    // ADD NAME EXPRESSION
    std::vector<std::string> name_expressions;
    name_expressions.push_back("my_sqrt<int>");
    name_expressions.push_back("my_sqrt<float>");
    name_expressions.push_back("my_sqrt<complex<double> >");

    for(size_t i = 0; i < name_expressions.size(); i++){
        result = hiprtcAddNameExpression(prog, name_expressions[i].c_str() );

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << "adding Name Expression " << name_expressions[i] << (int)result << std::endl; return 1; }
    }

    // COMPILE PROGRAM
    result = hiprtcCompileProgram(prog, options.size(), &opts[0]);

    if( result!= HIPRTC_SUCCESS ) {
        std::cout<<"Error: " << (int)result << std::endl;

        size_t log_size;
        hiprtcGetProgramLogSize(prog, &log_size);

        std::vector<char> log(log_size);
        hiprtcGetProgramLog(prog, &log[0]);
        fprintf(stderr, "%s\n", &log[0]);

      return 1;
    }

    // Obtain Code from the program.
    size_t ptxSize;
    result = hiprtcGetCodeSize(prog, &ptxSize);
    if( result != HIPRTC_SUCCESS ) { std::cout << "Error:" << result << std::endl; return 1; }
    char *ptx = new char[ptxSize];
    result = hiprtcGetCode(prog, ptx);
    if( result != HIPRTC_SUCCESS ) { std::cout << "Error:" << result << std::endl; return 1; }

    // Load the generated Code
    hipError_t err;
    int dev;
    err = hipSetDevice(0);
    if (err != hipSuccess) {
        std::cout << "device error:" << hipGetErrorName(err) << std::endl;
        return 1;
    }
    hipModule_t module;
    err = hipModuleLoadData(&module, ptx);
    if (err != hipSuccess) {
        std::cout << "module load error:" << hipGetErrorName(err) << std::endl;
        return 1;
    }

    // GET LOWERED NAME & KERNEL
    for(size_t i = 0; i < name_expressions.size(); i++){
        const char* mangled_instantiation_cstr;
        result = hiprtcGetLoweredName(prog, name_expressions[i].c_str(), &mangled_instantiation_cstr);

        if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

        std::cout << " Lowered Name for " << name_expressions[i] << " is '" << mangled_instantiation_cstr << "'." << std::endl;

        hipFunction_t func;
        err = hipModuleGetFunction(&func, module, mangled_instantiation_cstr);
        if (err != hipSuccess) {
            std::cout << "function load error:" << hipGetErrorName(err) << std::endl;
            return 1;
        } else {
            std::cout << "got kernel" << std::endl;
        }
    }

    // DESTROY PROGRAM
    result = hiprtcDestroyProgram(&prog);
    if( result!= HIPRTC_SUCCESS ) { std::cout<<"Error: " << (int)result << std::endl; return 1; }

}
```

</p>
</details>

Output:
```
 Lowered Name for my_sqrt<int> is '_Z7my_sqrtIiEvPT_i'.
got kernel
 Lowered Name for my_sqrt<float> is '_Z7my_sqrtIfEvPT_i'.
got kernel
 Lowered Name for my_sqrt<complex<double> > is ''.
function load error:hipErrorNotFound
```
btw the 2nd C++ reproducer above can only be compiled in ROCm 4.2+, which fixed the bug of `-I` not being accepted (https://github.com/ROCm-Developer-Tools/HIP/issues/2182). For ROCm < 4.2 CuPy works by recursively unrolling all internal headers.

**Comment by amathews-amd** [comment]
Hi @leofang , @scarrazza ,
It seems to be a namespace issue. 
```
root@rocm-framework-9:~/cupy/tests# git diff cupy_tests/core_tests/test_raw.py
diff --git a/tests/cupy_tests/core_tests/test_raw.py b/tests/cupy_tests/core_tests/test_raw.py
index d6ae670a5..359ee3f02 100644
--- a/tests/cupy_tests/core_tests/test_raw.py
+++ b/tests/cupy_tests/core_tests/test_raw.py
@@ -801,7 +801,7 @@ class TestRaw(unittest.TestCase):

         # compile code
         name_expressions = ['my_sqrt<int>', 'my_sqrt<float>',
-                            'my_sqrt<complex<double>>', 'my_func']
+                            "my_sqrt<thrust::complex<double> >", 'my_func']
         mod = cupy.RawModule(code=test_cxx_template,
                              options=('--std=c++11',),
                              name_expressions=name_expressions,
@@ -814,8 +814,9 @@ class TestRaw(unittest.TestCase):
                 # TODO(leofang): investigate why getLoweredName has no error
                 # but returns an empty string for my_sqrt<complex<double>>
                 mangled_name = mod.module.mapping.get(ker_T)
-                if mangled_name == '':
-                    continue
+            #    if mangled_name == '':
+            #        continue
+            print(ker_T, dtype, mangled_name)
             ker = mod.get_function(ker_T)

             # prepare inputs & expected outputs
```
seems to work. If it works for you, you can use it as a workaround. 

I will look at filing a bug. 

Thanks,
Aswin.

**Comment by scarrazza** [comment]
@amathews-amd thanks, this workaround seems to work for me.

**Comment by leofang** [comment]
> It seems to be a namespace issue.

Thanks, @amathews-amd! This is a very interesting (and nontrivial) finding. How did you figure out?

Just wanna make sure: Neither hipRTC nor hipcc would secretly include any actual Thrust (or rocThrust for that matter) headers, so we are sure it's CuPy's headers being used, right?

> I will look at filing a bug.

Sounds great, thanks Aswin! Please keep us posted on this 👍

**Comment by amathews-amd** [comment]
Hi @leofang , I was just trying to see what the differences are between the scaled down implementation of complex, and the full implementation of thrust::complex. Regarding whether hipRTC/hipcc may be using different thrust implementations, I am not entirely sure. We may need to test it out.

**Comment by amathews-amd** [comment]
Internal ticket: https://ontrack-internal.amd.com/browse/SWDEV-294764

**Comment by yxsamliu** [comment]
We studied the CUDA documentation and examples about nvrtcAddNameExpression and nvrtcGetLoweredName at  https://docs.nvidia.com/cuda/nvrtc/index.html#accessing-lowered-names.

CUDA does not specify whether non-fully-qualified names can be used with nvrtcGetLoweredName. Based on the examples provided, the intention seems to be that fully qualified names should be used with nvrtcGetLoweredName.

Another drawback of supporting non-fully-qualified names with nvrtcGetLoweredName is that it introduces context dependency and ambiguity for the code using such names since such names are valid only in specific contexts.

Since supporting of getting lowered name of non-fully-qualified names is not clearly documented, CUDA could drop its support in the future. On the other hand, to work around this issue, users can use fully-qualified names instead of non-fully-qualified names with nvrtcGetLoweredName, which should work for both CUDA and HIP, with benefits of context-free names and clarity.

Therefore our suggestion is not to support getting lowered names for non-fully-qualified names in HIP.

**Comment by leofang** [comment]
Thanks for the update, @yxsamliu. It's confusing, though. In the failing case, we do expose the `thrust::complex` class to the global context:
https://github.com/cupy/cupy/blob/24d4d683807e5afdf16139c250e4c63b8d1fd5b4/cupy/_core/include/cupy/complex.cuh#L5
So why wouldn't `complex<float>` be a fully qualified name and we have to still use `thrust::complex<float>`?

**Comment by amathews-amd** [comment]
@yxsamliu is the expert here, but this is my understanding (it may be wrong). 

In https://docs.nvidia.com/cuda/nvrtc/index.html#accessing-lowered-names, it is mentioned "NVRTC will parse the name expression string as a C++ constant expression at the end of the user program". If the name expression string is parsed in the context of the program scope, it should get the `using` directive as you mentioned. But if the name expression string is parsed outside the context of the program scope, you will have to use fully qualified names.
 
This might be the source of the confusion. Since the NV documentation does not make it clear, it might be better to be conservative and support the usage that provides context-free naming and clarity.

**Comment by leofang** [comment]
Hi @amathews-amd I have two comments:
1. If the scoping thing is for real (which I doubt), `thrust::complex<float>` would not be a fully-qualified name either. You'd need to use `::thrust::complex<float>`.
2. Whether or not the NV documentation is clear is subjective IMHO, but the actual behavior has remained intact across multiple CUDA versions for as long as I am aware. In this case not being fully compatible could be a foot gun for ROCm if code portability is a top concern, unless it's really too hard to fix on the compiler side.
