### ISSUE TITLE
IndexError when convolving with float scalar

### ISSUE THREAD

**Issue by FranzForstmayr** [cupy/cupy#5568]
# My setup
```
OS                           : Linux-5.4.0-80-generic-x86_64-with-glibc2.31
Python Version               : 3.9.5
CuPy Version                 : 9.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.0
SciPy Version                : 1.7.0
Cython Build Version         : 0.29.23
Cython Runtime Version       : 0.29.23
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11000
CUDA Driver Version          : 11020
CUDA Runtime Version         : 11000
cuBLAS Version               : (available)
cuFFT Version                : 10200
cuRAND Version               : 10201
cuSOLVER Version             : (10, 5, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 0)
Thrust Version               : 100909
CUB Build Version            : 100909
Jitify Build Version         : <unknown>
cuDNN Build Version          : 7605
cuDNN Version                : 7605
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : GeForce GTX 1060 6GB
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0
```

Cupy throws Index error when convolving an array with only one value, if the dtype is not an integer.
See the following reproducer:

```python
import cupy as cp
import cupyx.scipy.signal as csig
import scipy.signal as sig

a = cp.arange(10)
b = cp.ones(1)

print("This works - scipy")
print(sig.convolve(a.get(),b.get(), mode='full'))


print("This works as well - cupy")
print(csig.convolve(a, b, mode='full'))

print("Now with float values - scipy")
print(sig.convolve(a.get() * 1.0, b.get() * 1.0, mode='full'))

print("Now with float values - scipy")
print(csig.convolve(a * 1.0, b * 1.0, mode='full'))
```

Outputs at my machine:

```
This works - scipy
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
This works as well - cupy
[0 1 2 3 4 5 6 7 8 9]
Now with float values - scipy
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
Now with float values - scipy
Traceback (most recent call last):
  File "/home/franz/homeofffice/homeoffice/master/fecsim/testcupy.py", line 19, in <module>
    print(csig.convolve(a * 1.0, b * 1.0, mode='full'))
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupyx/scipy/signal/signaltools.py", line 55, in convolve
    return _correlate(in1, in2, mode, method, True)
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupyx/scipy/signal/signaltools.py", line 125, in _correlate
    out = fftconvolve(in1, in2, mode)
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupyx/scipy/signal/signaltools.py", line 180, in fftconvolve
    out = _st_core._freq_domain_conv(in1, in2, axes, shape, calc_fast_len=True)
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupyx/scipy/signal/_signaltools_core.py", line 148, in _freq_domain_conv
    sp1 = fftn(in1, fshape, axes=axes)
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupyx/scipy/fft/_fft.py", line 465, in rfftn
    return func(x, s, axes, norm, cufft.CUFFT_FORWARD, 'R2C',
  File "/home/franz/homeofffice/homeoffice/master/fecsim/.venv/lib/python3.9/site-packages/cupy/fft/_fft.py", line 229, in _fft
    raise IndexError('list index out of range')
IndexError: list index out of range
```
Before anyone is asking - I know there's a more obvious way to get the result, but the length of the second array is configurable so 1 is possible too.

**Comment by toslunar** [comment]
A workaround seems `method='direct'`.

```
>>> csig.choose_conv_method(a, b)
'direct'
>>> csig.choose_conv_method(a * 1.0, b)
'fft'
>>> print(csig.convolve(a * 1.0, b * 1.0, mode='full', method='direct'))
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
```

**Comment by FranzForstmayr** [comment]
Great! Thank you!
