### ISSUE TITLE
Release 9.3 does not have back-port of fix for CUDA enhanced compatibility 

### ISSUE THREAD

**Issue by dantegd** [cupy/cupy#5610]
PR #5097 was not backported to v9 so it was not included in release 9.3. 

cc @rlratzel @pentschev 

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - CuPy version: 9.3
  - OS/Platform: Ubuntu 20.04
  - CUDA version: 11.4

* Code to reproduce

Create a CuPy array with CuPy for CUDA 11.4, with driver < 470. 

* Error messages, stack traces, or logs

With driver < 470:

```python
(base) ➜  ~ nvidia-smi
Wed Aug  4 13:24:56 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
...
(rapids) root@71740761bae2:/workspace/cuml/python
Python 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy as cp
>>> cp.ones(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cupy/_creation/basic.py", line 154, in ones
    a.fill(1)
  File "cupy/_core/core.pyx", line 570, in cupy._core.core.ndarray.fill
...
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_UNSUPPORTED_PTX_VERSION: the provided PTX was compiled with an unsupported toolchain.
>>>
```

**Comment by emcastillo** [comment]
Sorry about this, we just backported it and it will be available in the next release, scheduled by the end of August.

**Comment by kmaehashi** [comment]
Backported in v9.4. #5611 Thanks again for reporting!
