### ISSUE TITLE
[Bug!] abnormal memory error in cupyx.scipy.sparse.linalg.cg

### ISSUE THREAD

**Issue by phylars** [cupy/cupy#5666]
Hi cupy team,

I got a strange bug when using the function cupyx.scipy.sparse.linalg.cg

In my code, A is a cupyx coo sparse matrix of size (16000000, 16000000), with 3686022 data points inside, b is a cupy array of 16000000. When I load A and b to my 1070 GPU (8G memory), it says only 1.9G is used, which is normal and expected. Next, when I run this code: 

result_gpu = cupyx.scipy.sparse.linalg.cg(A=A, b=b)

It got this error: 

Traceback (most recent call last):
  File "<ipython-input-125-214f01c4dd1d>", line 1, in <module>
    result_gpu = cupyx.scipy.sparse.linalg.cg(A=A, b=b)
  File "C:\Users\user\anaconda3\lib\site-packages\cupyx\scipy\sparse\linalg\_iterative.py", line 47, in cg
    A, M, x, b = _make_system(A, M, x0, b)
  File "C:\Users\user\anaconda3\lib\site-packages\cupyx\scipy\sparse\linalg\_iterative.py", line 238, in _make_system
    x = cupy.zeros((n,), dtype=A.dtype)
  File "C:\Users\user\anaconda3\lib\site-packages\cupy\_creation\basic.py", line 209, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy\_core\core.pyx", line 163, in cupy._core.core.ndarray.__init__
  File "cupy\cuda\memory.pyx", line 718, in cupy.cuda.memory.alloc
  File "cupy\cuda\memory.pyx", line 1395, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 1416, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 1096, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy\cuda\memory.pyx", line 1117, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy\cuda\memory.pyx", line 1355, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
OutOfMemoryError: Out of memory allocating 128,000,000 bytes (allocated so far: 7,721,392,640 bytes).

Obviously, suddenly all of the GPU memory is used up so it cannot run. An additional problem is that the memory cannot be freed, even if both A and b are deleted. So these 7.7G memory is allocated to something uncontrolable in the background. 

However, with the same data, if I run cg function with scipy by CPU it just works without any problem. Also, if I use the same data to run CUDA based cg function in MATLAB (I assume these are the same thing), it also run very well. 

Therefore I don't know what's wrong. Is there any way I can use your cg function, and also, clean the memory? If you need my data, I can send you.

My environment:
  - CuPy version: 9.3.0
  - OS/Platform: windows 10, anaconda, python 3.8
  - CUDA version: 11.4
  - cuDNN/NCCL version (if applicable)
* Code to reproduce: as described 
* Error messages, stack traces, or logs: as described

**Comment by emcastillo** [comment]
Hi and thanks for the report!
there is a bunch of vectors allocation and cusparse setting that is probably eating all your memory.
Can you try using managed memory?

```
import cupy

# Use managed memory
cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.malloc_managed).malloc)
```

https://docs.cupy.dev/en/stable/user_guide/memory.html

**Comment by phylars** [comment]
@emcastillo @kmaehashi 
Hi. I tried what you said and it still cannot work. The only thing changed is how much GPU memory it think I have. Here is the process.

Let's say I already have got A, a scipy coo matrix, and b, a numpy 1-D array. I process:

import cupy 
import cupyx
mempool = cupy.get_default_memory_pool()
pinned_mempool = cupy.get_default_pinned_memory_pool()
mempool.free_all_blocks()
pinned_mempool.free_all_blocks()
print(mempool.used_bytes())              
print(mempool.total_bytes())             
print(pinned_mempool.n_free_blocks())   

Here I see:
0
0
0
This looks normal. Next:

A_GPU = cupyx.scipy.sparse.coo_matrix(A)
b_GPU = cupy.asarray(b)
result = cupyx.scipy.sparse.linalg.cg(A,b)

I got:
....
OutOfMemoryError: Out of memory allocating 442,560,000 bytes (allocated so far: 7,593,393,664 bytes).
Then I checked momory:
print(mempool.used_bytes())              
print(mempool.total_bytes())             
print(pinned_mempool.n_free_blocks())
I got:
7464960512
7465393152
3   
Above is When I do not use managed memory. If I free memory, the numbers do not change.


Next, I add managed memory 
cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.malloc_managed).malloc)
result = cupyx.scipy.sparse.linalg.cg(A,b)
OutOfMemoryError: Out of memory allocating 128,000,000 bytes (allocated so far: 256,000,000 bytes).

Next, I cleared my python IDE to run everything from the begining:
...
import cupy 
import cupyx
cupy.cuda.set_allocator(cupy.cuda.MemoryPool(cupy.cuda.malloc_managed).malloc)
A_GPU = cupyx.scipy.sparse.coo_matrix(A)
b_GPU = cupy.asarray(b)
result = cupyx.scipy.sparse.linalg.cg(A,b)
Out of memory allocating 885,120,000 bytes (allocated so far: 5,694,720,512 bytes).

The only thing changed is how much memory the system thinks I have. By all means it seems not "enough". But I really know this is not true because the same data runs perfectly well in the cg function of MATLAB, which I think use only ~5G GPU memory.

So is there a bug and how to solve it?

**Comment by emcastillo** [comment]
We will try to reproduce and check where the memory consumption is sharply increasing.

**Comment by phylars** [comment]
@emcastillo Hi, did get a change to see what's happened over there?

**Comment by kmaehashi** [comment]
Let me close as this is inactive for a long time. Leave a comment if anyone still encounter this problem.
