### ISSUE TITLE
CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

### ISSUE THREAD

**Issue by llodds** [cupy/cupy#5668]
* Conditions
```
CuPy Version          : 8.0.0
CUDA Root             : /hpc/apps/RHEL/3.10/x86_64/cuda/11.0
CUDA Build Version    : 11000
CUDA Driver Version   : 11020
CUDA Runtime Version  : 11000
cuBLAS Version        : 11200
cuFFT Version         : 10201
cuRAND Version        : 10201
cuSOLVER Version      : (10, 6, 0)
cuSPARSE Version      : 11101
NVRTC Version         : (11, 0)
Thrust Version        : 100909
CUB Build Version     : 100909
cuDNN Build Version   : 8000
cuDNN Version         : 8000
NCCL Build Version    : 2708
NCCL Runtime Version  : 2708
cuTENSOR Version      : None
```
* Code to reproduce
```python
import numpy as np
X = np.random.random_sample((600, 128, 128, 128))
Y = np.random.random_sample((600, 128, 128, 128))

import cupy as cp
# conversion functions between tensorflow and cupy
def tf2cp(x):
    dlcapsule = tf.experimental.dlpack.to_dlpack(x)
    return cp.fromDlpack(dlcapsule)
def cp2tf(x):
    dlcapsule = x.toDlpack()
    return tf.experimental.dlpack.from_dlpack(dlcapsule)

import tensorflow as tf
dataset = tf.data.Dataset.from_tensor_slices((X, Y))
train_dst = dataset.shuffle(500, reshuffle_each_iteration=True)
train_dst = dataset.batch(10, drop_remainder=True).prefetch(tf.data.AUTOTUNE)

for X, Y in dataset.take(10):
    print(X.shape)
    X2 = tf2cp(X)
    X3 = cp.copy(X2)
    X3[...,:] = X2[...,::-1]
    X = cp2tf(X3)
```
* Error messages, stack traces, or logs
```
---------------------------------------------------------------------------
CUDADriverError                           Traceback (most recent call last)
<ipython-input-3-678fbfef46a0> in <module>
      3     X2 = tf2cp(X)
      4     X3 = cp.copy(X2)
----> 5     X3[...,:] = X2[...,::-1]
      6     X = cp2tf(X3)

cupy/core/core.pyx in cupy.core.core.ndarray.__setitem__()

cupy/core/_routines_indexing.pyx in cupy.core._routines_indexing._ndarray_setitem()

cupy/core/_routines_indexing.pyx in cupy.core._routines_indexing._scatter_op()

cupy/core/_kernel.pyx in cupy.core._kernel.ufunc.__call__()

cupy/core/_kernel.pyx in cupy.core._kernel.ufunc._get_ufunc_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_ufunc_kernel()

cupy/core/_kernel.pyx in cupy.core._kernel._get_simple_elementwise_kernel()

cupy/core/core.pyx in cupy.core.core.compile_with_cache()

/hpc/apps/pyhpc/dist/conda/x86_64/envs/cuda-11.0/lib/python3.8/site-packages/cupy/cuda/compiler.py in compile_with_cache(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream)
    333             name_expressions, log_stream, cache_in_memory)
    334     else:
--> 335         return _compile_with_cache_cuda(
    336             source, options, arch, cache_dir, extra_source, backend,
    337             enable_cooperative_groups, name_expressions, log_stream,

/hpc/apps/pyhpc/dist/conda/x86_64/envs/cuda-11.0/lib/python3.8/site-packages/cupy/cuda/compiler.py in _compile_with_cache_cuda(source, options, arch, cache_dir, extra_source, backend, enable_cooperative_groups, name_expressions, log_stream, cache_in_memory)
    391                 cubin_hash = hashlib.md5(cubin).hexdigest().encode('ascii')
    392                 if hash == cubin_hash:
--> 393                     mod.load(cubin)
    394                     return mod
    395     else:

cupy/cuda/function.pyx in cupy.cuda.function.Module.load()

cupy/cuda/function.pyx in cupy.cuda.function.Module.load()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.moduleLoadData()

cupy_backends/cuda/api/driver.pyx in cupy_backends.cuda.api.driver.check_status()

CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

**Comment by llodds** [comment]
Update: if I take out `train_dst = dataset.shuffle(500, reshuffle_each_iteration=True)`, the code will work... 

Do I have to configure something related to the memory?

**Comment by llodds** [comment]
I figured out an alternative solution:
If I do the following to manually copy TF tensor to a CuPy device array in advance, then the code will work, however I don't know why the earlier code doesn't work. 

```python
X2 = cp.empty((10, 128, 128, 128)) # create a CuPy array in advance
for X, Y in dataset.take(10):
    print(X.shape)
    X2[:] = tf2cp(X) # note the ":", to manually copy results to a CuPy device array
    X3 = cp.copy(X2)
    X3[...,:] = X2[...,::-1]
    X = cp2tf(X3)
```

**Comment by emcastillo** [comment]
The only thing I can guess from this is some issue with the strides of the original tensor in TensorFlow and cupy.

**Comment by lxop** [comment]
I'm also getting this error, but from a completely different operation. My MRE looks like this:
```python
import cupy as np
np.cuda.set_allocator(np.cuda.malloc_managed)

gigs = 8  # <== if this is 7 or greater, I get the error
x = np.random.random((gigs*1024*1024*256,), dtype=np.float32)
m = np.median(x)
print(m)
```

As noted in the code, the error only occurs for large data sizes. The error I get looks like
```
/(user home)/.venvs/bh_script/bin/python /(user home)/.config/JetBrains/PyCharmCE2022.2/scratches/scratch_5.py
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.memory.ManagedMemory.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.memory.ManagedMemory.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "/(user home)/.config/JetBrains/PyCharmCE2022.2/scratches/scratch_5.py", line 8, in <module>
    m = np.median(x)
  File "/(user home)/.venvs/bh_script/lib/python3.9/site-packages/cupy/_statistics/meanvar.py", line 34, in median
    return _statistics._median(a, axis, out, overwrite_input, keepdims)
  File "cupy/_core/_routines_statistics.pyx", line 389, in cupy._core._routines_statistics._median
  File "cupy/_core/_routines_statistics.pyx", line 428, in cupy._core._routines_statistics._median
  File "cupy/_core/core.pyx", line 922, in cupy._core.core._ndarray_base.partition
  File "cupy/_core/_routines_sorting.pyx", line 174, in cupy._core._routines_sorting._ndarray_partition
  File "cupy/_core/core.pyx", line 885, in cupy._core.core._ndarray_base.sort
  File "cupy/_core/_routines_sorting.pyx", line 44, in cupy._core._routines_sorting._ndarray_sort
  File "cupy/cuda/thrust.pyx", line 75, in cupy.cuda.thrust.sort
RuntimeError: smart_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.memory.ManagedMemory.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/runtime.pyx", line 550, in cupy_backends.cuda.api.runtime.free
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Error in sys.excepthook:

Original exception was:

Process finished with exit code 1
```
(I haven't truncated the above output - nothing is printed after "Original exception was:")

**Comment by kmaehashi** [comment]
When using managed memory, `cudaErrorIllegalAddress` often indicates out-of-memory on host.

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
