### ISSUE TITLE
CuPy and NumPy raise different exceptions for indexing with multiple ellipsis

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5714]
CuPy raises `ValueError` while NumPy raises `IndexError`:
```python
>>> import cupy as cp
>>> a = cp.random.random((3, 3,3))
>>> a[..., ..., 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 1380, in cupy._core.core.ndarray.__getitem__
    return _indexing._ndarray_getitem(self, slices)
  File "cupy/_core/_routines_indexing.pyx", line 36, in cupy._core._routines_indexing._ndarray_getitem
    slice_list, advanced, mask_exists = _prepare_slice_list(
  File "cupy/_core/_routines_indexing.pyx", line 249, in cupy._core._routines_indexing._prepare_slice_list
    slice_list, n_newaxes = internal.complete_slice_list(slice_list, ndim)
  File "cupy/_core/internal.pyx", line 251, in cupy._core.internal.complete_slice_list
    raise ValueError('Only one Ellipsis is allowed in index')
ValueError: Only one Ellipsis is allowed in index
>>> 
>>> import numpy as np
>>> a = np.random.random((3, 3, 3))
>>> a[..., ..., 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: an index can only have a single ellipsis ('...')
```

**Comment by leofang** [comment]
Note: this relates to the `test_indexing.py` failure seen in https://github.com/cupy/cupy/pull/5698#issuecomment-913406882.
