### ISSUE TITLE
Segfault when copying a non-contiguous CuPy array to host

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#5721]
```python
>>> import cupy as cp
>>>
>>> ptr = cp.cuda.alloc(2**27 * 8)
>>> a = cp.ndarray(shape=(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2),\
...                strides=(128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608, 16777216, 33554432, 67108864, 134217728, 536870912, 268435456, 8, 16, 32, 64),\
...                memptr=ptr)
>>> 
>>> b = cp.asnumpy(a)
Segmentation fault (core dumped)
```

It either segfaults hard, or causes `CUDA_ERROR_MISALIGNED_ADDRESS` in a real workload:
```python
Traceback (most recent call last):
  File "<string>", line 23, in <module>
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/cupy/__init__.py", line 773, in asnumpy
    return a.get(stream=stream, order=order)
  File "cupy/_core/core.pyx", line 1567, in cupy._core.core.ndarray.get
  File "cupy/_core/core.pyx", line 1623, in cupy._core.core.ndarray.get
  File "cupy/_core/core.pyx", line 1625, in cupy._core.core.ndarray.get
  File "cupy/_core/core.pyx", line 2404, in cupy._core.core._internal_ascontiguousarray
  File "cupy/_core/_kernel.pyx", line 1185, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 1212, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 952, in cupy._core._kernel._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 62, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/core.pyx", line 2030, in cupy._core.core.compile_with_cache
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 460, in compile_with_cache
    return _compile_with_cache_cuda(
  File "/home/leof/miniforge3/envs/opt_einsum_dev/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 529, in _compile_with_cache_cuda
    mod.load(cubin)
  File "cupy/cuda/function.pyx", line 241, in cupy.cuda.function.Module.load
  File "cupy/cuda/function.pyx", line 243, in cupy.cuda.function.Module.load
  File "cupy_backends/cuda/api/driver.pyx", line 253, in cupy_backends.cuda.api.driver.moduleLoadData
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_MISALIGNED_ADDRESS: misaligned address
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
(... repeat the above traceback N times ...)
``` 

By the way, technically this array is illegal in CuPy (`a.ndim=27` > `MAX_NDIM=25`, see #4193), but I am not sure if this is relevant.

**Comment by leofang** [comment]
```
OS                           : Linux-5.8.0-53-generic-x86_64-with-glibc2.10
Python Version               : 3.8.10
CuPy Version                 : 9.4.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.3
SciPy Version                : 1.7.1
Cython Build Version         : 0.29.22
Cython Runtime Version       : None
CUDA Root                    : /usr
nvcc PATH                    : /usr/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 3)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : 60e9e72
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10301
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A6000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:21:00.0
Device 1 Name                : NVIDIA RTX A6000
Device 1 Compute Capability  : 86
Device 1 PCI Bus ID          : 0000:22:00.0
Device 2 Name                : NVIDIA RTX A6000
Device 2 Compute Capability  : 86
Device 2 PCI Bus ID          : 0000:41:00.0
Device 3 Name                : NVIDIA RTX A6000
Device 3 Compute Capability  : 86
Device 3 PCI Bus ID          : 0000:43:00.0
```

**Comment by leofang** [comment]
Looks like this is a duplicate of https://github.com/cupy/cupy/issues/4193 indeed.

**Comment by emcastillo** [comment]
Since this seems to be a duplicate, let's close this one.
Feel free to reopen if you think it is not :)

**Comment by leofang** [comment]
Hi @emcastillo, could you reopen and assign this issue to me (as I can't reopen)? I'd like to add a safe check so that we don't accidentally compile a copy kernel that can't do its job correctly.

**Comment by leofang** [comment]
hmmm I missed to catch this...
```python
>>> a = cp.ndarray(shape=[2 for i in range(33)], dtype=cp.int8)
>>> a.shape
(2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
>>> a.ndim
33
>>>
>>> a = np.ndarray(shape=[2 for i in range(33)], dtype=cp.int8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum supported dimension for an ndarray is 32, found 33
```
