### ISSUE TITLE
cupy fails on device with computing capability 3.0

### ISSUE THREAD

**Issue by ululi1970** [cupy/cupy#5847]
* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
 OS                           : Linux-5.4.0-87-generic-x86_64-with-Ubuntu-18.04-bionic
Python Version               : 3.6.9
CuPy Version                 : 9.5.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.19.5
SciPy Version                : 1.5.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.24
CUDA Root                    : /usr
nvcc PATH                    : /usr/bin/nvcc
CUDA Build Version           : 11040
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11040
cuBLAS Version               : (available)
cuFFT Version                : 10502
cuRAND Version               : 10205
cuSOLVER Version             : (11, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 4)
Thrust Version               : 101201
CUB Build Version            : 101201
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA TITAN V
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:01:00.0
Device 1 Name                : NVIDIA GeForce GTX 680
Device 1 Compute Capability  : 30
Device 1 PCI Bus ID          : 0000:02:00.0

* Code to reproduce
import cupy
cupy.cuda.runtime.setDevice(1)
a=cupy.arange(1000)

* Error messages, stack traces, or logs
Traceback (most recent call last):
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 653, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 133, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 145, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 64, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_INVALID_OPTION (5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/_creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/_core/_kernel.pyx", line 1185, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 1212, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 952, in cupy._core._kernel._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 62, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/core.pyx", line 2042, in cupy._core.core.compile_with_cache
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 463, in compile_with_cache
    cache_in_memory, jitify)
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 503, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 401, in _preprocess
    result, _ = prog.compile(options)
  File "/home/alberto/.local/lib/python3.6/site-packages/cupy/cuda/compiler.py", line 671, in compile
    'nvrtc' if not runtime.is_hip else 'hiprtc')
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)

I was under the impression that cupy 4.0+ still supports devices with computing capability of 3.0

**Comment by leofang** [comment]
It's not abut CuPy. You're on CUDA 11.4 and CC 3.0 has been dropped since 11.0:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-cuda-libraries
