### ISSUE TITLE
cupy ufuncs don't accept array-like objects

### ISSUE THREAD

**Issue by kohr-h** [cupy/cupy#594]
The code
```python
>>> x = cupy.array([1, 2, 3])
>>> cupy.add(x, [2, 1, -1])
```
raises an error:
```
Traceback (most recent call last):
  File "[...]/cupy/core/fusion.py", line 701, in __call__
    return self._cupy_op(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 765, in cupy.core.core.ufunc.__call__
  File "cupy/core/elementwise.pxi", line 133, in cupy.core.core._preprocess_args
TypeError: Unsupported type <class 'list'>
```
Casting to `cupy.array` would solve the issue nicely I think (including broadcasting).

**Comment by kohr-h** [comment]
I guess this has the same constraints regarding unwanted copies as #589

**Comment by kmaehashi** [comment]
Let me close this as a duplicate of #1206.
