### ISSUE TITLE
CI: add `make linkcheck` to CI to detect dead-links in docs

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#5969]
Current results:

```
(reference/generated/cupy.cuda.malloc_managed: line   13) broken    https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#axzz4qygc1Ry1 - Anchor 'axzz4qygc1Ry1' not found
( reference/scipy: line    5) broken    https://docs.scipy.org/doc/scipy/reference/#api-reference - Anchor 'api-reference' not found
(         upgrade: line  239) broken    https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements - Anchor 'requirements' not found
(         install: line  378) broken    https://github.com/RadeonOpenCompute/ROCm#Hardware-and-Software-Support - Anchor 'Hardware-and-Software-Support' not found
```

Maybe run it once a week as it generates many requests.

**Comment by kmaehashi** [comment]
Thanks @laysauchoa! The sphinx build itself is already in https://github.com/cupy/cupy/blob/master/.github/workflows/pretest.yml so it would be nice if the check can be integrated without adding a new workflow file.

**Comment by laysauchoa** [comment]
I can add there, np! Unfortunately, when I try to run local following the instructions:

```
pip install -r requirements.txt
make html
```
My output is like this:
```
cupy/docs git:add-linkcheck*  
(new) ❯ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v5.0.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/laysa.uchoa/.pyenv/versions/new/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/Users/laysa.uchoa/Documents/cupy/docs/source/conf.py", line 20, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

make: *** [html] Error 2
```

Would be possible to help me with some guidance, I am not sure what I am missing.
