### ISSUE TITLE
Unable to convert some constants in cupy.jit

### ISSUE THREAD

**Issue by HighCWu** [cupy/cupy#6207]
### Description

My code shouldn't raise Exception but I got:
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    relu_inplace_forward[128, 1024](x, size)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cupyx/jit/_interface.py", line 123, in <lambda>
    return lambda *args, **kwargs: self(grid, block, args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cupyx/jit/_interface.py", line 97, in __call__
    _cuda_types.void,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cupyx/jit/_compile.py", line 87, in transpile
    source=source
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cupyx/jit/_compile.py", line 175, in _transpile_function
    exc.reraise(source)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/cupyx/jit/_compile.py", line 42, in reraise
    raise self.error_type(self.mes + '\n\n' + pycode)
AttributeError: 'Constant' object has no attribute 'ctype'

  @jit.rawkernel()
  def relu_inplace_forward(x, size):
      tid = jit.blockIdx.x * jit.blockDim.x + jit.threadIdx.x
      ntid = jit.gridDim.x * jit.blockDim.x
      for i in range(tid, size, ntid):
          if x[i] < 0.:
>             x[i] = 0.
```

If I modify the function to:
```python
@jit.rawkernel()
def relu_inplace_forward(x, size):
    tid = jit.blockIdx.x * jit.blockDim.x + jit.threadIdx.x
    ntid = jit.gridDim.x * jit.blockDim.x
    for i in range(tid, size, ntid):
        x[i] = x[i] if x[i] > 0. else 0.
```
it wouldn't raise Exception and get the right result.

### To Reproduce

`test.py`:
```py
import cupy as cp
from cupyx import jit

@jit.rawkernel()
def relu_inplace_forward(x, size):
    tid = jit.blockIdx.x * jit.blockDim.x + jit.threadIdx.x
    ntid = jit.gridDim.x * jit.blockDim.x
    for i in range(tid, size, ntid):
        if x[i] < 0.:
            x[i] = 0.

size = cp.uint32(2 ** 22)
x = cp.random.normal(size=(size,), dtype=cp.float32)
print(x)

relu_inplace_forward[128, 1024](x, size)
print(x)

```

run `python test.py` to reproduce.

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-4.4.0-150-generic-x86_64-with-debian-stretch-sid
Python Version               : 3.7.4
CuPy Version                 : 9.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.3
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.22
Cython Runtime Version       : 0.29
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 10010
CUDA Driver Version          : 10010
CUDA Runtime Version         : 10010
cuBLAS Version               : (available)
cuFFT Version                : 10101
cuRAND Version               : 10101
cuSOLVER Version             : (10, 2, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (10, 1)
Thrust Version               : 100906
CUB Build Version            : 100800
Jitify Build Version         : 60e9e72
cuDNN Build Version          : 8005
cuDNN Version                : 8000
NCCL Build Version           : 2803
NCCL Runtime Version         : 2708
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Tesla V100-SXM2-32GB
Device 0 Compute Capability  : 70
Device 0 PCI Bus ID          : 0000:07:00.0
```

### Additional Information

```python
if x[i] < 0.:
    x[i] = 0.
```
got error while 

```python
x[i] = x[i] if x[i] > 0. else 0.
```

passed in @jit.rawkernel()

**Comment by kmaehashi** [comment]
Thanks for reporting! Can you take a look @asi1024?

**Comment by asi1024** [comment]
This bug seems to be already fixed in https://github.com/cupy/cupy/pull/5319/commits/123c9f7d659e5e395dda1ab040f684fd54825c3b.

**Comment by HighCWu** [comment]
OK, I will try the new version of cupy
