### ISSUE TITLE
ufunc should accept `out=None` as a positional argument

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6393]
### Description

Discovered by @khushi-411 in https://github.com/cupy/cupy/pull/6089#discussion_r789687065:

```py
>>> import numpy as xp
>>> a =  xp.arange(10)
>>> xp.logical_and(a, a, None)
array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])
```

```py
>>> import cupy as xp
>>> a = xp.arange(10)
>>> xp.logical_and(a, a, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/_kernel.pyx", line 1147, in cupy._core._kernel.ufunc.__call__
    arg_list = _preprocess_args(dev_id, args, False)
  File "cupy/_core/_kernel.pyx", line 130, in cupy._core._kernel._preprocess_args
    raise TypeError('Unsupported type %s' % type(arg))
TypeError: Unsupported type <class 'NoneType'>
```

**Comment by khushi-411** [comment]
Thanks for the mention, @kmaehashi! :)
