### ISSUE TITLE
Cupy installation for NVIDIA AGX (AARCH64)

### ISSUE THREAD

**Issue by sivashankar28** [cupy/cupy#6462]
Hi I have some code that works very well on my linux-based laptop and I am trying to get it to run on an NVIDIA AGX. 
The error that I am encountering when I run the code (see below)
I know the code itself is fine as it works on other devices so I believe its due to the cupy and cuda installation. Maybe its the wrong version but I dont understand whats going on.
Cupy version 8.3.0 installed from source
CUDA version 10.2
There is no straight pip install cupy-cuda102 that is compatible with the NVIDIA AGX to my knowledge so I am not sure what I am doing wrong here.

ERROR:root:Error!
Traceback (most recent call last):
  File "/home/mebot/polylidar-realsense-wheelchair/surfacedetector/curblinedetection.py", line 424, in capture
    planes, obstacles, geometric_planes, timings = get_polygon(depth_image, config, ll_objects, **meta)
  File "/home/mebot/polylidar-realsense-wheelchair/surfacedetector/curblinedetection.py", line 300, in get_polygon
    mesh, timings = create_meshes_cuda(opc, **config['mesh']['filter'])
  File "/home/mebot/polylidar-realsense-wheelchair/surfacedetector/utility/helper_mesh.py", line 471, in create_meshes_cuda
    smooth_opc, opc_normals, timings = laplacian_then_bilateral_opc_cuda(opc, **kwargs)
  File "/home/mebot/polylidar-realsense-wheelchair/surfacedetector/utility/helper_mesh.py", line 371, in laplacian_then_bilateral_opc_cuda
    sigma_length=sigma_length, sigma_angle=sigma_angle)
  File "/home/mebot/polylidar-realsense-wheelchair/surfacedetector/utility/helper_mesh.py", line 281, in bilateral_opc_cuda
    normals_opc, centroids_opc, loops=loops, sigma_length=sigma_length, sigma_angle=sigma_angle)
  File "/home/mebot/OrganizedPointFilters/cmake-build/lib/python_package/organizedpointfilters/cuda/kernel.py", line 203, in bilateral_K3_cuda
    normals_float_out = cp.asnumpy(normals_float_gpu_b) if use_b else cp.asnumpy(normals_float_gpu_a)
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 773, in asnumpy
    return a.get(stream=stream, order=order)
  File "cupy/_core/core.pyx", line 1542, in cupy._core.core.ndarray.get
  File "cupy/_core/core.pyx", line 1611, in cupy._core.core.ndarray.get
  File "cupy/_core/core.pyx", line 1617, in cupy._core.core.ndarray.get
  File "cupy/cuda/memory.pyx", line 531, in cupy.cuda.memory.MemoryPointer.copy_to_host
  File "cupy_backends/cuda/api/runtime.pyx", line 672, in cupy_backends.cuda.api.runtime.memcpy
  File "cupy_backends/cuda/api/runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
INFO:root:Out of frames
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 55, in apport_excepthook
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
TypeError: 'NoneType' object is not callable
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 260, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 125, in cupy_backends.cuda.api.driver.check_status
TypeError: 'NoneType' object is not callable
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:

**Comment by sivashankar28** [comment]
I have tried  Cupy 9.2.0 and still have the same issue. What do you mean by reproducer? Do you know of a simpler code that will check to ensure that the cuda and cupy libraries work as it should?

**Comment by emcastillo** [comment]
I mean some code that will cause the error and we can see what is going on.

```
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
INFO:root:Out of frames
```

Sorry but this does not give enough information, I can only think of you trying to use a large array and since AGX memory is shared between GPU & CPU this can cause issues.

**Comment by sivashankar28** [comment]
The above outputs are from a code that I am running. Its quite extensive to recreate on another machine. I have it working on a laptop but not sure what I am doing wrong here. I think I need to purge all version of cupy off my system and install the correct version for cuda 10.2. Do you know of the commands to purge all versions of cupy and a version of cupy I should install that is older than 8.3.0 (compatible for cuda 10.2)

**Comment by emcastillo** [comment]
If you installed it from source `pip uninstall cupy` should clean it. Also, starting CuPy v10 we distribute aarch64 [wheels](https://pypi.org/project/cupy-cuda102/#files).
you can just install cupy-cuda102 and it should detect it. However, these are compiled with NVidia jetpack SDK and may not be compatible with your env?

But again, without seeing the code we don't know if this is an application issue, device issue, or a CuPy bug.
I would say the problem is with the application itself due to using a lot of memory and the AGX being limited.
If you are dealing with images, try to lower the image resolution.

If you can't provide a simple code that shows the same error I am afraid we can't easily debug this.

**Comment by kmaehashi** [comment]
> There is no straight pip install cupy-cuda102 that is compatible with the NVIDIA AGX to my knowledge so I am not sure what I am doing wrong here.

CuPy v10 does not support Python 3.6 and that is the reason why `pip install cupy-cuda102` does not work.

**Comment by sivashankar28** [comment]
Yup I'm using python 3.6.9
If I upgrade my python to 3.7 will this solve the issue and I can install cuda-cupy102 or is there a way to install on python 3.6.9 from source.
It's hard to find clear instructions on this

**Comment by emcastillo** [comment]
> Is there a way of installing cupy for python 3.6 (aarch64)?

No, we use python features that requires python to be at least 3.7
You can easily install a newer python version using pyenv

**Comment by sivashankar28** [comment]
Okay even after installing a python environment in version 3.7 and installing all the appropriate drivers. Successful cupy installation .... I still have the same issue. Theoretically, I need cudatoolkit=10.2 but I am assuming that cudatoolkit is already built on the system with the jetpack? If not, how do I install cudatoolkit=10.2 on the conda python3.7 environment.

**Comment by emcastillo** [comment]
The error is the same as before, so CuPy is likely to be working fine.

Probably this is an issue of running a tool that is not prepared for the jetson hardware limits. Try to reduce the memory footprint and it may work. But I don't believe this is a CuPy issue per-se.

If we don't get a very simple script that can reproduce this error we can't debug this.

**Comment by kmaehashi** [comment]
> File "cupy_backends/cuda/api/runtime.pyx", line 552, in cupy_backends.cuda.api.runtime.memcpy
> File "cupy_backends/cuda/api/runtime.pyx", line 132, in cupy_backends.cuda.api.runtime.check_status
> cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered

I guess the error is coming from the previous kernel execution. Try running your code with `export CUDA_LAUNCH_BLOCKING=1` specified, or under `cuda-gdb`.

**Comment by kmaehashi** [comment]
Closing as inactive for a while. Please feel free to reopen if you still need help.
