### ISSUE TITLE
`cupy.linalg.eigh` returns `nan` for zero matrix

### ISSUE THREAD

**Issue by stavros11** [cupy/cupy#6539]
### Description

The eigenvalues and eigenvectors of a zero matrix are `nan`. Is this the expected behavior?

### To Reproduce

```py
import cupy as cp
x = cp.zeros((2, 2))
print(cp.linalg.eigh(x))
```
gives
```
(array([nan, nan]), array([[nan, nan],
       [nan, nan]]))
```

The equivalent in numpy:
```py
import numpy as np
x = np.zeros((2, 2))
print(np.linalg.eigh(x))
```
gives 
```
(array([0., 0.]), array([[1., 0.],
       [0., 1.]]))
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-5.13.0-30-generic-x86_64-with-glibc2.17
Python Version               : 3.8.12
CuPy Version                 : 10.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.28
Cython Runtime Version       : None
CUDA Root                    : /home/stavros/anaconda3/envs/testcupy
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11060
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 0ea2960
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10400
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1650 with Max-Q Design
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

There are a few other cases for which the output of `cupy.linalg.eigh` does not agree with numpy. For example:
```py
import numpy as np
import cupy as cp


m1 = np.array([[0, 0, 0, 1],
               [0, 0, 0, 0],
               [0, 0, 0, 1],
               [1, 0, 1, 0]])
m2 = cp.asarray(m1)

eigvals1, eigvecs1 = np.linalg.eigh(m1)
eigvals2, eigvecs2 = cp.linalg.eigh(m2)
eigvals2, eigvecs2 = eigvals2.get(), eigvecs2.get()

print(eigvals1)
print(eigvals2)
print()
print()
print(eigvecs1)
print()
print(eigvecs2)
```
gives
```
[-1.41421356e+00 -6.07153217e-18  0.00000000e+00  1.41421356e+00]
[-1.41421356e+00  0.00000000e+00  7.54604712e-17  1.41421356e+00]


[[-5.00000000e-01 -7.07106781e-01  0.00000000e+00  5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.00000000e+00  0.00000000e+00]
 [-5.00000000e-01  7.07106781e-01  0.00000000e+00  5.00000000e-01]
 [ 7.07106781e-01  4.85722573e-17  0.00000000e+00  7.07106781e-01]]

[[-5.00000000e-01  0.00000000e+00  7.07106781e-01 -5.00000000e-01]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.00000000e-01  0.00000000e+00 -7.07106781e-01 -5.00000000e-01]
 [ 7.07106781e-01  0.00000000e+00  6.92100090e-17 -7.07106781e-01]]
```
In this case both results are mathematically correct, it is just that the degenerate eigenvectors are returned in different order and some signs are different. I am not sure if this is expected behavior.

**Comment by emcastillo** [comment]
Can you try with CUDA < 11.6?
Cuda 11.6 changed the way that eigh works https://github.com/cupy/cupy/pull/6347

**Comment by emcastillo** [comment]
This works with cuda 11.2

```
>>> import cupy as cp
>>> x = cp.zeros((2, 2))

>>> print(cp.linalg.eigh(x))
(array([0., 0.]), array([[1., 0.],
       [0., 1.]]))
```

cc @anaruse @leofang

**Comment by kmaehashi** [comment]
Also got the same result as @emcastillo in CUDA 11.5.

cuSOLVER in CUDA 11.6+ now raises an error:

```
>>> cupyx.seterr(linalg='raise')
{'divide': None, 'over': None, 'under': None, 'invalid': None, 'linalg': 'ignore', 'fallback_mode': 'ignore'}
>>> print(cp.linalg.eigh(x))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/vol21/maehashi/Development/cupy/cupy/linalg/_eigenvalue.py", line 146, in eigh
    return _syevd(a, UPLO, True)
  File "/mnt/vol21/maehashi/Development/cupy/cupy/linalg/_eigenvalue.py", line 66, in _syevd
    cupy.linalg._util._check_cusolver_dev_info_if_synchronization_allowed(
  File "/mnt/vol21/maehashi/Development/cupy/cupy/linalg/_util.py", line 126, in _check_cusolver_dev_info_if_synchronization_allowed
    raise linalg.LinAlgError(
numpy.linalg.LinAlgError: Error reported by xsyevd in cuSOLVER. devInfo = 1. Please refer to the cuSOLVER documentation.
```

**Comment by stavros11** [comment]
Thank you for the responses. Indeed, I get
```
>>> import cupy as cp
>>> x = cp.zeros((2, 2))
>>> cp.linalg.eigh(x)
(array([0., 0.]), array([[1., 0.],
       [0., 1.]]))
```
 with CUDA 11.5. Note that is the cudatoolkit version that matters. In a machine with CUDA 11.5 I still get `nan` if I use cudatoolkit-11.6.0 in the conda environment where I install cupy. Here are the two configs that work/return `nan`:

<details>
<summary>config that works</summary>

```
OS                           : Linux-5.4.0-100-generic-x86_64-with-glibc2.17
Python Version               : 3.8.12
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.27
Cython Runtime Version       : None
CUDA Root                    : /home/stavros/anaconda3/envs/cuda115
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11050
CUDA Runtime Version         : 11050
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10206
cuSOLVER Version             : (11, 2, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 5)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 6dbba68
cuDNN Build Version          : 8201
cuDNN Version                : 8302
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10400
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A6000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:C5:00.0
```

</details>
<details>
<summary>config that returns nan</summary>

```
OS                           : Linux-5.4.0-100-generic-x86_64-with-glibc2.17
Python Version               : 3.8.12
CuPy Version                 : 10.1.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.8.0
Cython Build Version         : 0.29.27
Cython Runtime Version       : None
CUDA Root                    : /home/stavros/anaconda3/envs/qibojit38
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 11050
CUDA Runtime Version         : 11060
cuBLAS Version               : (available)
cuFFT Version                : 10600
cuRAND Version               : 10209
cuSOLVER Version             : (11, 3, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 6)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 6dbba68
cuDNN Build Version          : 8201
cuDNN Version                : 8302
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10400
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX A6000
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:C5:00.0
```

</details>

The other example about the order of eigenvectors differing from numpy behaves the same for cudatoolkit-11.5 and 11.6.

**Comment by emcastillo** [comment]
Yeah, this is a cuda issue, stick to an older toolkit version meanwhile :)

**Comment by leofang** [comment]
It's a known issue (nvbugs 3496875) expected to be fixed in CUDA 11.7.
