### ISSUE TITLE
cupy.is_available() raises CUDARuntimeError

### ISSUE THREAD

**Issue by dmargala** [cupy/cupy#6702]
### Description

We've encountered an unexpected error while attempting to run cpu-only unit tests on a shared server that does not have GPUs. The code uses something like the following to decide it should run tests that require cupy + GPUs:

```python
is_cupy_available = False
try:
    import cupy
    is_cupy_available = cupy.is_available()
except ImportError:
    pass
```

However, `cupy.is_available()` is unexpectedly raising a CUDARuntimeError:

```
(cupy-test) dmargala@cori06:~> python -c "import cupy; print(cupy.is_available())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/global/homes/d/dmargala/.conda/envs/cupy-test/lib/python3.10/site-packages/cupy/__init__.py", line 36, in is_available
    return cuda.is_available()
  File "/global/homes/d/dmargala/.conda/envs/cupy-test/lib/python3.10/site-packages/cupy/cuda/__init__.py", line 84, in is_available
    _available = runtime.getDeviceCount() > 0
  File "cupy_backends/cuda/api/runtime.pyx", line 357, in cupy_backends.cuda.api.runtime.getDeviceCount
  File "cupy_backends/cuda/api/runtime.pyx", line 360, in cupy_backends.cuda.api.runtime.getDeviceCount
  File "cupy_backends/cuda/api/runtime.pyx", line 142, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorMpsConnectionFailed: MPS client failed to connect to the MPS control daemon or the MPS server
```

Some other user on the system left a CUDA MPS daemon running (why they have CUDA MPS running on a server without GPUs is another question):

```
(cupy-test) dmargala@cori06:~> ps aux | grep cuda-mps | grep -v grep
xxxxx  22343  0.0  0.0  10676  1508 ?        Ss   May02   0:08 nvidia-cuda-mps-control -d
```

It seems like `numba.cuda.is_available()` can handle this so I was wondering if `cupy.is_available()` could catch the CUDARuntimeError for us?

```
(cupy-test) dmargala@cori06:~> python -c "import numba.cuda; print(numba.cuda.is_available())"
False
```

Redirecting the default CUDA MPS pipe directory prevents an uncaught exception from occuring:

```
(cupy-test) dmargala@cori06:~> CUDA_MPS_PIPE_DIRECTORY=(mktemp -d) python -c "import cupy; print(cupy.is_available())"
False
```

If you have any other recommendations to protect against this, please let me know.

### To Reproduce

Start a CUDA MPS daemon as user_a on the system. Then, as user_b, try to run:

```bash
python -c "import cupy; print(cupy.is_available())"
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
/global/homes/d/dmargala/.conda/envs/cupy-test/lib/python3.10/site-packages/cupyx/_runtime.py:279: UserWarning: Failed to detect number of GPUs: cudaErrorMpsConnectionFailed: MPS client failed to connect to the MPS control daemon or the MPS server
  warnings.warn(f'Failed to detect number of GPUs: {e}')
OS                        : Linux-5.3.18-24.96-default-x86_64-with-glibc2.26
Python Version            : 3.10.4
CuPy Version              : 10.4.0
CuPy Platform             : NVIDIA CUDA
NumPy Version             : 1.21.6
SciPy Version             : None
Cython Build Version      : 0.29.24
Cython Runtime Version    : None
CUDA Root                 : None
nvcc PATH                 : None
CUDA Build Version        : 11050
CUDA Driver Version       : 11040
CUDA Runtime Version      : CUDARuntimeError('cudaErrorMpsConnectionFailed: MPS client failed to connect to the MPS control daemon or the MPS server')
cuBLAS Version            : (available)
cuFFT Version             : 10600
cuRAND Version            : 10207
cuSOLVER Version          : (11, 3, 2)
cuSPARSE Version          : (available)
NVRTC Version             : (11, 5)
Thrust Version            : 101301
CUB Build Version         : 101301
Jitify Build Version      : 4a37de0
cuDNN Build Version       : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version             : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version        : None
NCCL Runtime Version      : None
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
```

**Comment by leofang** [comment]
This is interesting 😂
> Some other user on the system left a CUDA MPS daemon running (why they have CUDA MPS running on a server without GPUs is another question)

Sounds like a one-off event to me that the system admin can fix (by not allowing users to launch the daemon)?

It's unclear to me if we should swallow `CUDARuntimeError` unconditionally. Maybe in [this case](https://docs.nvidia.com/deploy/mps/index.html#topic_3_3_5_1) (reaching MPS connection limit) we still wanna raise it?

**Comment by dmargala** [comment]
I agree that this is a rare circumstance and we can get the system admins involved. 

I'd advocate that `cupy.is_available()` is more helpful to users if it returned `False` instead of allowing the exception through. 

For what it's worth, both `numba.cuda.is_avaialble()` and `torch.cuda.is_available()` returned `False` in this case.

**Comment by leofang** [comment]
I see, looks like Torch explicitly guarantees no throw indeed:
https://github.com/pytorch/pytorch/blob/d5210a4269e289f1d15d3044f16c0d3926803ceb/torch/cuda/__init__.py#L80-L82

**Comment by kmaehashi** [comment]
Thanks for reporting, @dmargala!

> I'd advocate that `cupy.is_available()` is more helpful to users if it returned `False` instead of allowing the exception through.

I agree this makes sense.

**Comment by duboism** [comment]
Hello,

I recently faced a similar issue using Google Colab (see googlecolab/colabtools#5166) and we came to the same conclusion. Note that @metrizable dug into the code and found the explanation.

I think the API changed a bit compared to when this issue was opened but I think it's an interesting improvement.

**Comment by leofang** [comment]
PR is welcomed! Though the colab situation is a bit suspicious. It seems the colab cpu mode still has a very old CUDA driver installed and/or a gpu attached, causing a different error code from what's expected.

**Comment by duboism** [comment]
I gave it a shoot but I have problems installing the current `main` on the system I have access to. I think it's related to #8215. I'm not an expert on cuda so it's a bit hard for me.

**Comment by leofang** [comment]
> I think it's related to [#8215](https://github.com/cupy/cupy/issues/8215). I'm not an expert on cuda so it's a bit hard for me.

Yes, if you're building CuPy from source on a machine that has cuDNN 9 in the system include/search path, a build failure could happen and it bites me every time 😛 I recommend commenting out this line and proceed:
https://github.com/cupy/cupy/blob/34e2daa7c36c44bd34a2732d5343619f9850c96c/install/cupy_builder/_features.py#L430
