### ISSUE TITLE
eigh() on float32 matrix leads to cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by asmeurer** [cupy/cupy#6789]
### Description

Calling eigh() on the matrix

```
a = cupy.asarray([[ 2.0000100e+00,  0.0000000e+00,  0.0000000e+00, 
             1.0000000e+07,  0.0000000e+00], 
           [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, 
            -2.0000100e+00,  3.4028235e+38], 
           [ 0.0000000e+00,  0.0000000e+00, -5.0000000e-01, 
            -2.2098796e+16, -1.9000000e+00], 
           [ 1.0000000e+07, -2.0000100e+00, -2.2098796e+16, 
            -1.1754944e-38, -4.2423595e+16], 
           [ 0.0000000e+00,  3.4028235e+38, -1.9000000e+00, 
            -4.2423595e+16, -2.6436685e+16]], dtype=cupy.float32) 
```

leads to 

```
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

### To Reproduce

```py
>>> import cupy
>>> a = cupy.asarray([[ 2.0000100e+00,  0.0000000e+00,  0.0000000e+00,
...              1.0000000e+07,  0.0000000e+00],
...            [ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
...             -2.0000100e+00,  3.4028235e+38],
...            [ 0.0000000e+00,  0.0000000e+00, -5.0000000e-01,
...             -2.2098796e+16, -1.9000000e+00],
...            [ 1.0000000e+07, -2.0000100e+00, -2.2098796e+16,
...             -1.1754944e-38, -4.2423595e+16],
...            [ 0.0000000e+00,  3.4028235e+38, -1.9000000e+00,
...             -4.2423595e+16, -2.6436685e+16]], dtype=cupy.float32)
>>> cupy.linalg.eigh(a)
Traceback (most recent call last):
  File "cupy/_core/core.pyx", line 1704, in cupy._core.core._ndarray_base.__repr__
    return repr(self.get())
  File "cupy/_core/core.pyx", line 1818, in cupy._core.core._ndarray_base.get
    a_gpu.data.copy_to_host(ptr, a_gpu.nbytes)
  File "cupy/cuda/memory.pyx", line 557, in cupy.cuda.memory.MemoryPointer.copy_to_host
    and runtime.streamIsCapturing(stream_ptr)
  File "cupy_backends/cuda/api/runtime.pyx", line 965, in cupy_backends.cuda.api.runtime.streamIsCapturing
    check_status(status)  # cudaErrorStreamCaptureImplicit could be raised here
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
    raise CUDARuntimeError(status)
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

after this, all further operations give the same error. The same matrix with float64 does not give the error.

### Installation

Built from GitHub source

### Environment

```
>>> cupy.show_config()
OS                           : Linux-5.13.0-51-generic-x86_64-with-glibc2.34
Python Version               : 3.9.7
CuPy Version                 : 11.0.0b3
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.20.3
SciPy Version                : 1.7.1
Cython Build Version         : 0.29.24
Cython Runtime Version       : 0.29.24
CUDA Root                    : /home/aaronmeurer/anaconda3
nvcc PATH                    : /home/aaronmeurer/anaconda3/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101500
CUB Build Version            : 101500
Jitify Build Version         : 4a37de0
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2080
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

### Additional Information

I tested this with the CuPy git source (commit 7df760a0186ddf609e30d1a176349e56ad114050).

**Comment by kmaehashi** [comment]
Thanks for reporting, I could reproduce this. CuPy just calls cuSOLVER routine for `eigh`, so I suspect this is not a CuPy issue. The first error observed by `cuda-memcheck` suggests there is an out of bounds read in cuSOLVER:

```
========= Invalid __shared__ read of size 4
=========     at 0x00003920 in void steqr_ker<stedc_params_<float, int=8, int=16>, float, int=0>(int, floatdata_type*, floatdata_type*, int=8*, long, int*, int*, int, int, floatdata_typ
e, floatdata_type, int*)
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0xfffffffc is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x2182ec]
=========     Host Frame:/usr/local/cuda-11.7.0/lib64/libcusolver.so.11 [0x74cbcb]
=========     Host Frame:/usr/local/cuda-11.7.0/lib64/libcusolver.so.11 [0x7a8368]
=========     Host Frame:/usr/local/cuda-11.7.0/lib64/libcusolver.so.11 [0x3fe479]
=========     Host Frame:/usr/local/cuda-11.7.0/lib64/libcusolver.so.11 [0x3e0f35]
=========     Host Frame:/usr/local/cuda-11.7.0/lib64/libcusolver.so.11 (cusolverDnXsyevd + 0x35c) [0x4966fc]
=========     Host Frame:/home/maehashi/Development/cupy/cupy_backends/cuda/libs/cusolver.cpython-38-x86_64-linux-gnu.so [0x25d0d]
...
```

cc/ @anaruse @leofang

**Comment by leofang** [comment]
Any chance we know the earliest offending CUDA version here? Are there any special properties about the offending matrix?
