### ISSUE TITLE
c_nnz overflowing

### ISSUE THREAD

**Issue by jainmilan** [cupy/cupy#6864]
Trying to multiply two sparse matrix using cupy.cusparse.csr2gemm that results in 2563136096 non-zero elements. During debugging, I found that the array that keeps track of the non-zero elements of the output array (c_nnz - check the snippet below) has a data type of `int32` which has a maximum limit of 2147483647. 

https://github.com/cupy/cupy/blob/770ff2d295637ef6791b8f90c487749f586cc38a/cupy/cusparse.py#L727-L739

This results in an overflow and throws the following error. I tried changing it to `int64` everywhere in the function, however, since it has multiple dependencies, it leads to illegal memory access error. 

> Traceback (most recent call last):
  File "runSparseDNNchallenge.py", line 103, in <module>
    scores = inferenceReLUvec(layers, bias, featureVectors);  
  File "reference_implementation/SparseDNN/python/cupy/inferenceReLUvec.py", line 23, in inferenceReLUvec
    Y = Y @ W[i]
  File ".conda/envs/horovod/lib/python3.8/site-packages/cupyx/scipy/sparse/base.py", line 126, in __matmul__
    return self.__mul__(other)
  File ".conda/envs/horovod/lib/python3.8/site-packages/cupyx/scipy/sparse/csr.py", line 156, in __mul__
    return cusparse.csrgemm2(self, other)
  File ".conda/envs/horovod/lib/python3.8/site-packages/cupy/cusparse.py", line 751, in csrgemm2
    c_indices = _cupy.empty(int(c_nnz), _numpy.int64)
  File ".conda/envs/horovod/lib/python3.8/site-packages/cupy/_creation/basic.py", line 22, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/_core/core.pyx", line 150, in cupy._core.core.ndarray.__init__
ValueError: Negative dimensions are not allowed

**Comment by kmaehashi** [comment]
Sorry for the inconvenience, but currently sparse matrices have 32-bit limit. These routines are written using [deprecated cuSPARSE APIs](https://docs.nvidia.com/cuda/cusparse/index.html#csrgemm2) (which have 32-bit limit) and need to be rewritten using generic APIs introduced in CUDA 11.0. (#3513)

**Comment by kmaehashi** [comment]
We're going to work on this targeting v12 release. #3513
