### ISSUE TITLE
`cupy.clip` behave differently from NumPy

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#6901]
### Description

The behavior is different from NumPy when

* only `a_max` or `a_min` is given
* `a_max` < `a_min`

### To Reproduce

CuPy:
```py
>>> import cupy as cp
>>> cp.clip(cp.arange(8), a_min=3, a_max=6)
array([3, 3, 3, 3, 4, 5, 6, 6])
>>> cp.clip(cp.arange(8), a_min=3)
array([3, 3, 3, 3, 4, 5, 6, 7])
>>> cp.clip(cp.arange(8), a_max=3)
array([0, 1, 2, 3, 3, 3, 3, 3])
>>> cp.clip(cp.arange(8), a_min=6, a_max=3)
array([6, 6, 6, 6, 6, 6, 3, 3])
```

NumPy:
```py
>>> import numpy as np
>>> np.clip(np.arange(8), a_min=3, a_max=6)
array([3, 3, 3, 3, 4, 5, 6, 6])
>>> np.clip(np.arange(8), a_min=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 179, in clip
TypeError: _clip_dispatcher() missing 1 required positional argument: 'a_max'
>>> np.clip(np.arange(8), a_max=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 179, in clip
TypeError: _clip_dispatcher() missing 1 required positional argument: 'a_min'
>>> np.clip(np.arange(8), a_min=6, a_max=3)
array([3, 3, 3, 3, 3, 3, 3, 3])
```

**Comment by pri1311** [comment]
Will take this up.
