### ISSUE TITLE
Failed to import CuPy

### ISSUE THREAD

**Issue by ssconquer** [cupy/cupy#7002]
### Description

I installed cupy and cudatoolkit with conda-forge. But failed to import cupy.

My conda list is 
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
cupy                      11.0.0          py310h9216885_0    conda-forge

The output is the same with the environment configuration of cupy.

### To Reproduce

```py
# Write the code here
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
Traceback (most recent call last):
  File "/njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 14, in <module>
    from cupy.cuda import function
  File "cupy/cuda/function.pyx", line 1, in init cupy.cuda.function
  File "cupy/_core/_carray.pyx", line 1, in init cupy._core._carray
  File "cupy/_core/internal.pyx", line 1, in init cupy._core.internal
  File "cupy/cuda/memory.pyx", line 1, in init cupy.cuda.memory
ImportError: /njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy_backends/cuda/api/driver.cpython-310-x86_64-linux-gnu.so: undefined symbol: cuDevicePrimaryCtxRelease_v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: /njcam_share/lxl/anaconda3/envs/FAME/lib/python3.10/site-packages/cupy_backends/cuda/api/driver.cpython-310-x86_64-linux-gnu.so: undefined symbol: cuDevicePrimaryCtxRelease_v2
================================================================

```

**Comment by emcastillo** [comment]
Is it possible that you have another CUDA installation in that system?

**Comment by ssconquer** [comment]
> Is it possible that you have another CUDA installation in that system? or that your CUDA driver is too old to support 11.7

Thanks! It is exactly what you said!
