### ISSUE TITLE
dtrsm segmentation fault

### ISSUE THREAD

**Issue by nicelhc13** [cupy/cupy#7011]
### Description

cublas.dtrsm() got segmentation fault on the latest cupy version, 11.0, and 9.2 version, which worked well on 8.6 version.
(We have used 8.6 version for a long time and recently updated to the newer versions. 9.2 was an attempt to check when this bug started).

Is there anything that I am missing here? 
The below is gdb's stack tracing:
```
Program received signal SIGSEGV, Segmentation fault.
0x00002aaac0940958 in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64
(gdb) where
#0  0x00002aaac0940958 in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#1  0x00002aaac09413fc in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#2  0x00002aaac0940a14 in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#3  0x00002aaac09413fc in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#4  0x00002aaac0942ca1 in ?? () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#5  0x00002aaac093aa8d in cublasDtrsm_v2 () from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.11
#6  0x00002aaac0218924 in __pyx_f_13cupy_backends_4cuda_4libs_6cublas_dtrsm(long, int, int, int, int, int, int, unsigned long, unsigned long, int, unsigned long, int, int) ()
   from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/cublas.cpython-38-x86_64-linux-gnu.so
#7  0x00002aaac0218bbd in __pyx_pw_13cupy_backends_4cuda_4libs_6cublas_131dtrsm(_object*, _object*, _object*) ()
   from /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/lib/python3.8/site-packages/cupy_backends/cuda/libs/cublas.cpython-38-x86_64-linux-gnu.so
#8  0x000055555567fb94 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x2aaabfed0770)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Objects/call.c:773
#9  PyCFunction_Call () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Objects/call.c:773
#10 0x000055555568ef2e in _PyObject_MakeTpCall () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/errors.c:219
#11 0x0000555555725fae in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x555555e29910, callable=0x2aaabfed0770)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Include/cpython/abstract.h:125
#12 _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x555555e29910, callable=0x2aaabfed0770)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Include/cpython/abstract.h:115
#13 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x55555591c950)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:4963
#14 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:3500
#15 0x0000555555703f06 in PyEval_EvalFrameEx (throwflag=0, f=0x555555e29750) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:738
#16 function_code_fastcall (globals=<optimized out>, nargs=<optimized out>, args=<optimized out>, co=<optimized out>)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Objects/call.c:284
#17 _PyFunction_Vectorcall () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Objects/call.c:411
#18 0x00005555557218cf in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x2aaaaabac5b0, callable=0x2aaaaab92550)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Include/cpython/abstract.h:115
#19 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x55555591c950)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:4963
#20 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:3500
#21 0x0000555555702cf3 in PyEval_EvalFrameEx (throwflag=0, f=0x2aaaaabac440) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:4298
#22 _PyEval_EvalCodeWithName () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:4298
#23 0x0000555555703d59 in PyEval_EvalCodeEx () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:4327
#24 0x00005555557a8b5b in PyEval_EvalCode (co=co@entry=0x2aaaaabeb0e0, globals=globals@entry=0x2aaaaab68e40, locals=locals@entry=0x2aaaaab68e40)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/ceval.c:718
#25 0x00005555557a8bf3 in run_eval_code_obj () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:1166
#26 0x00005555557c25b3 in run_mod () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:1188
#27 0x00005555557c75d2 in pyrun_file (fp=fp@entry=0x555555db6060, filename=filename@entry=0x2aaab212f470, start=start@entry=257, globals=globals@entry=0x2aaaaab68e40, 
    locals=locals@entry=0x2aaaaab68e40, closeit=closeit@entry=1, flags=0x7fffffffa5a8) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:1085
#28 0x00005555557c77b2 in pyrun_simple_file (flags=0x7fffffffa5a8, closeit=1, filename=0x2aaab212f470, fp=0x555555db6060)
    at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:439
#29 PyRun_SimpleFileExFlags () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:472
#30 0x00005555557c79bb in PyRun_AnyFileExFlags () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pythonrun.c:90
#31 0x00005555557c7d2d in pymain_run_file (cf=0x7fffffffa5a8, config=0x55555591b550) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Modules/main.c:391
#32 pymain_run_python (exitcode=0x7fffffffa5a0) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Modules/main.c:616
#33 Py_RunMain () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Modules/main.c:695
#34 0x00005555557c7e7b in pymain_main () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Modules/main.c:1103
#35 0x00005555557c7ee9 in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Modules/main.c:1127
#36 0x00002aaaab81e555 in __libc_start_main () from /lib64/libc.so.6
#37 0x000055555573b989 in _start () at /home/conda/feedstock_root/build_artifacts/python-split_1643583808657/work/Python/pyarena.c:124
```

### To Reproduce

```py
# Write the code here
import cupy as cp
import numpy as np
from cupy.cuda import cublas
from cupy.cuda import device

def cupy_trsm_wrapper():
    cublas_handle = device.get_cublas_handle()
    trsm = cublas.dtrsm
    uplo = cublas.CUBLAS_FILL_MODE_LOWER
    a = cp.array([[1.57297875, 1.0279683, 0, 0],[1.6328578, 0.1439442, 0.42486692, 0],[1.36113799, 0.54304009, 0.39802999, 0.65366583]] , dtype=np.float64, order='F')
    b = cp.array([[1.718675, 1.37716661, 1.66625853, 1.68687542],[2.28286534, 2.28809639, 2.43368819, 2.54181435],[1.81073068, 1.39893788, 1.95708066, 1.93265258],[2.53843618, 2.2738666, 2.83373146, 2.94323057]], dtype=np.float64, order='F')

    trans = cublas.CUBLAS_OP_T
    side = cublas.CUBLAS_SIDE_RIGHT
    diag = cublas.CUBLAS_DIAG_NON_UNIT
    m, n = (b.side, 1) if b.ndim == 1 else b.shape
    print("m:", m, "n:", n)
    print(a, " and ", b)
    trsm(cublas_handle, side, uplo, trans, diag, m, n, 1.0, a.data.ptr, m, b.data.ptr, m)

cupy_trsm_wrapper()
```

### Environment

```
# Paste the output here

 for 9.2 version 
OS                           : Linux-3.10.0-1127.13.1.el7.x86_64-x86_64-with-glibc2.10
Python Version               : 3.8.12
CuPy Version                 : 9.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.2
SciPy Version                : 1.6.3
Cython Build Version         : 0.29.23
Cython Runtime Version       : 0.29.28
CUDA Root                    : /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla
nvcc PATH                    : /work2/06398/hochan/frontera/workspace/miniconda3/envs/parla/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11030
cuBLAS Version               : (available)
cuFFT Version                : 10402
cuRAND Version               : 10204
cuSOLVER Version             : (11, 1, 2)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 3)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8200
cuDNN Version                : 8201
NCCL Build Version           : 20909
NCCL Runtime Version         : 21212
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro RTX 5000
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:02:00.0
Device 1 Name                : Quadro RTX 5000
Device 1 Compute Capability  : 75
Device 1 PCI Bus ID          : 0000:03:00.0
Device 2 Name                : Quadro RTX 5000
Device 2 Compute Capability  : 75
Device 2 PCI Bus ID          : 0000:82:00.0
Device 3 Name                : Quadro RTX 5000
Device 3 Compute Capability  : 75
Device 3 PCI Bus ID          : 0000:83:00.0

for version 11
OS                           : Linux-5.4.0-124-generic-x86_64-with-glibc2.10
Python Version               : 3.8.13
CuPy Version                 : 11.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.9.0
Cython Build Version         : 0.29.30
Cython Runtime Version       : 0.29.32
CUDA Root                    : /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla
nvcc PATH                    : /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 3, 5)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 3c4a4ba
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21212
NCCL Runtime Version         : 20908
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1080
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:06:00.0
Device 1 Name                : NVIDIA GeForce GTX 1080
Device 1 Compute Capability  : 61
Device 1 PCI Bus ID          : 0000:81:00.0
Device 2 Name                : Tesla K80
Device 2 Compute Capability  : 37
Device 2 PCI Bus ID          : 0000:04:00.0
Device 3 Name                : Tesla K80
Device 3 Compute Capability  : 37
Device 3 PCI Bus ID          : 0000:05:00.0
Device 4 Name                : Tesla K80
Device 4 Compute Capability  : 37
Device 4 PCI Bus ID          : 0000:84:00.0
Device 5 Name                : Tesla K80
Device 5 Compute Capability  : 37
Device 5 PCI Bus ID          : 0000:85:00.0
```

**Comment by emcastillo** [comment]
Can you try with CUDA 10.2?
I suspect this may be a cublas internal bug instead of CuPy

**Comment by nicelhc13** [comment]
Hi, @emcastillo  thank you for your suggestion. I reinstalled 10.2 cuda toolkit and retried to run. But I still got the same segmentation fault. The below is the topmost stack tracing from gdb. I am confused since the above example is using very simple matrices as operands. Is there a possibility that it is compatibility issue between cupy and cublas, and if it is, how could I check the compatibility? Is there any description that I am missing?
Thank you.

```(gdb) where                                                                 
#0  0x00007ffe5f4ad496 in ?? () from /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla-debug/lib/python3.10/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.10
#1  0x00007ffe5f4ace31 in ?? () from /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla-debug/lib/python3.10/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.10
#2  0x00007ffe5f4ace31 in ?? () from /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla-debug/lib/python3.10/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.10
#3  0x00007ffe5f4b575d in ?? () from /net/ohm/export/cdgc/hlee/workspace/miniconda3/envs/parla-debug/lib/python3.10/site-packages/cupy_backends/cuda/libs/../../../../../libcublas.so.10
```

**Comment by anaruse** [comment]
This is because the wrapping method of the cublas APIs has changed since CuPy v9, and pointers are now exposed as pointers, even if they are coefficients.

https://github.com/cupy/cupy/issues/4200
https://github.com/cupy/cupy/pull/4263

Please change the source code as follows.

```python

import cupy as cp
import numpy as np
from cupy.cuda import cublas
from cupy.cuda import device


def cupy_trsm_wrapper():
    cublas_handle = device.get_cublas_handle()
    trsm = cublas.dtrsm
    uplo = cublas.CUBLAS_FILL_MODE_LOWER
    a = cp.array([[1.0, 0, 0, 0],
                  [1.57297875, 1.0279683, 0, 0],
                  [1.6328578, 0.1439442, 0.42486692, 0],
                  [1.36113799, 0.54304009, 0.39802999, 0.65366583]],
                 dtype=np.float64, order='F')
    b = cp.array([[1.718675, 1.37716661, 1.66625853, 1.68687542],
                  [2.28286534, 2.28809639, 2.43368819, 2.54181435],
                  [1.81073068, 1.39893788, 1.95708066, 1.93265258],
                  [2.53843618, 2.2738666, 2.83373146, 2.94323057]],
                 dtype=np.float64, order='F')

    trans = cublas.CUBLAS_OP_T
    side = cublas.CUBLAS_SIDE_RIGHT
    diag = cublas.CUBLAS_DIAG_NON_UNIT
    m, n = (b.side, 1) if b.ndim == 1 else b.shape
    print("m:", m, "n:", n)
    print('a:\n{}'.format(a))
    print('b:\n{}'.format(b))
    alpha = np.array(1.0, dtype=np.float64)
    trsm(cublas_handle, side, uplo, trans, diag, m, n, alpha.ctypes.data,
         a.data.ptr, m, b.data.ptr, m)
    print('b (after trsm):\n{}'.format(b))

cupy_trsm_wrapper()
```

```
m: 4 n: 4
a:
[[1.         0.         0.         0.        ]
 [1.57297875 1.0279683  0.         0.        ]
 [1.6328578  0.1439442  0.42486692 0.        ]
 [1.36113799 0.54304009 0.39802999 0.65366583]]
b:
[[1.718675   1.37716661 1.66625853 1.68687542]
 [2.28286534 2.28809639 2.43368819 2.54181435]
 [1.81073068 1.39893788 1.95708066 1.93265258]
 [2.53843618 2.2738666  2.83373146 2.94323057]]
b (after trsm):
[[ 1.718675   -1.29018827 -2.24629922  1.44147048]
 [ 2.28286534 -1.26735647 -2.61606075  1.78075029]
 [ 1.81073068 -1.4098713  -1.8750395   1.4991404 ]
 [ 2.53843618 -1.67226905 -2.51951935  2.14027104]]
```

**Comment by nicelhc13** [comment]
@anaruse Thank you very much. It worked well.
