### ISSUE TITLE
"ImportError: libcudart.so.7.5" only on the v2.0.0 (not on the v1.0.3)

### ISSUE THREAD

**Issue by lynn-hong** [cupy/cupy#714]
Hello, I installed `cupy 2.0.0` but got the error below.
My environment was like this.
```
python 3.5.2
cuda 8.0
nvidia-driver 384.66
$ export LD_LIBRARY_PATH=/usr/local/cuda/lib64
```
The error was solved when I installed `v1.0.3`... Is there anyone know about this error?

```Python 3.5.2 (default, Sep 14 2017, 22:51:06) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cupy/__init__.py", line 9, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/__init__.py", line 3, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy/cuda/runtime.pxd", line 5, in init cupy.cuda.device
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cupy/__init__.py", line 20, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/cupy/__init__.py", line 9, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/__init__.py", line 3, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/usr/local/lib/python3.5/dist-packages/cupy/cuda/compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy/cuda/runtime.pxd", line 5, in init cupy.cuda.device
ImportError: CuPy is not correctly installed. Please check your environment, uninstall CuPy and reinstall it with `pip install cupy --no-cache-dir -vvvv`.

original error: libcudart.so.7.5: cannot open shared object file: No such file or directory```

**Comment by kmaehashi** [comment]
Have you tried uninstalling and reinstalling CuPy as the error message says?

```
pip uninstall cupy
pip install cupy --no-cache-dir -vvvv
```

**Comment by lynn-hong** [comment]
Oh, many thanks!
When I tried the command `pip install cupy --no-cache-dir -vvvv`, I thought something's wrong and stopped the installation because of so many warnings@_@!
Let me close the issue thank you!!
