### ISSUE TITLE
Typo in raise from einsum

### ISSUE THREAD

**Issue by jjmortensen** [cupy/cupy#7198]
### Description

In this line:

https://github.com/cupy/cupy/blob/master/cupy/linalg/_einsum.py#L511

einsum() tries to raise an error:

```py
raise TypeError('Did not understand the following kwargs: %s'
                        % list(kwargs.keys))
```

but I believe it should be `list(kwargs.keys())` or simply `list(kwargs)`.

### To Reproduce

```py
>>> cp.einsum('i', cp.ones(7), asdf=42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/camp/jensj/venv/lib64/python3.9/site-packages/cupy/linalg/_einsum.py", line 512, in einsum
    % list(kwargs.keys))
TypeError: 'builtin_function_or_method' object is not iterable
```

### Environment

```
OS                           : Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Python Version               : 3.9.13
CuPy Version                 : 11.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.9.3
Cython Build Version         : 0.29.32
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 11080
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro RTX 4000
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:21:00.0
```

**Comment by takagi** [comment]
Thanks! Do you have interest in posting a pull request to fix this?

**Comment by jjmortensen** [comment]
I'll do that.

**Comment by jjmortensen** [comment]
Done.
