### ISSUE TITLE
Using CuPy with memory pool from multi-threaded application

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#72]
When using CuPy with memory pool from multi-threaded app, sometimes it fails to launch a kernel (``CUDADriverError: CUDA_ERROR_INVALID_CONTEXT: invalid device context``).  I think this is because CUDA Driver API (to launch kernel) is called without establishing context on the host thread.

Here is a simple code to reproduce:

```py
import chainer  # Enable memory pool; without this line the issue does not reproduce.
import cupy
import threading

def run(size):
    # Uncomment the following line to explicitly establish CUDA context
    # on the current host thread:
    #cupy.cuda.runtime.free(0)
    print(cupy.arange(size, dtype=int))

size = 1024

# Run in main thread; this is OK.
# CuPy mallocs memory via Runtime API, then launches kernel with Driver API.
run(size)

# Run in another thread; this fails.
# The executed thread tries to launch kernel without establishing context,
# as Runtime API is not used (memory block acquired in the previous run is
# reused from pool.)
t = threading.Thread(target=run, args=(size,))
t.start()
t.join()
```

As commented in the above code, I could workaround the problem by calling harmless Runtime API, e.g., ``cupy.cuda.runtime.free(0)`` to explicitly establish context on the host thread.

It would be great if CuPy could take care of such use case, but documenting the behavior may be enough.

**Comment by okuta** [comment]
Thank you for your reporting,

The solution to this error is a bit difficult.
Do you have any good ideas?

**Comment by kmaehashi** [comment]
How about this?

1. Add a boolean flag (thread local storage) indicating that the thread has a context to memory pool.
1. On malloc, if the flag is false, call `cuCtxGetCurrent`.  If it fails create a context.
1. Set the flag to true.

**Comment by okuta** [comment]
OK, make sense.
Cloud you make a PR?

**Comment by kmaehashi** [comment]
I'll try.

**Comment by okuta** [comment]
I found error case.
```python
import chainer  # Enable memory pool; without this line the issue does not reproduce.
import cupy
import threading

size = 1024
a = cupy.arange(size, dtype=int)

def run(a):
    # Uncomment the following line to explicitly establish CUDA context
    # on the current host thread:
    #cupy.cuda.runtime.free(0)
    a += 1


# Run in main thread; this is OK.
# CuPy mallocs memory via Runtime API, then launches kernel with Driver API.
run(a)

# Run in another thread; this fails.
# The executed thread tries to launch kernel without establishing context,
# as Runtime API is not used (memory block acquired in the previous run is
# reused from pool.)
t = threading.Thread(target=run, args=(a,))
t.start()
t.join()
```

I got following error.
```
/home/okuta/env/chainer/cupy/cupy/core/fusion.py:659: FutureWarning: cupy.core.fusion is experimental. The interface can change in the future.
  util.experimental('cupy.core.fusion')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/okuta/.pythonz/pythons/CPython-2.7.13/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/okuta/.pythonz/pythons/CPython-2.7.13/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../thread_test.py", line 12, in run
    a += 1
  File "cupy/core/core.pyx", line 1285, in cupy.core.core.ndarray.__iadd__
    return add(self, other, self)
  File "cupy/core/elementwise.pxi", line 827, in cupy.core.core.ufunc.__call__
    kern.linear_launch(indexer.size, inout_args)
  File "cupy/cuda/function.pyx", line 158, in cupy.cuda.function.Function.linear_launch
    _launch(self.ptr,
  File "cupy/cuda/function.pyx", line 127, in cupy.cuda.function._launch
    driver.launchKernel(
  File "cupy/cuda/driver.pyx", line 184, in cupy.cuda.driver.launchKernel
    check_status(status)
  File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
    raise CUDADriverError(status)
CUDADriverError: CUDA_ERROR_INVALID_CONTEXT: invalid device context
```

**Comment by kmaehashi** [comment]
For record: I noticed that CUDA recommends setting current device after spawning a new thread.
https://devblogs.nvidia.com/cuda-pro-tip-always-set-current-device-avoid-multithreading-bugs/
If you follow this best practice, you won't see this error in any case.
