### ISSUE TITLE
Installation with pip results in broken installation

### ISSUE THREAD

**Issue by uellue** [cupy/cupy#7253]
### Description

When installing with pip from source or binary packages `cupy-cuda111`  resp. `cupy-cuda11x`, importing cupy results in an import error:

```
(cupytest310) C:\Users\weber>python -c "import cupy"
Traceback (most recent call last):
  File "C:\Users\weber\miniconda3\envs\cupytest310\lib\site-packages\cupy\__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "C:\Users\weber\miniconda3\envs\cupytest310\lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "C:\Users\weber\miniconda3\envs\cupytest310\lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Users\weber\miniconda3\envs\cupytest310\lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\weber\miniconda3\envs\cupytest310\lib\site-packages\cupy\__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================
```

This happens with Python 3.7 and Python 3.10. I've tried CUDA 11.1 and CUDA 11.8. I've also installed the latest driver for my GPU. Operating system is Windows 11. I'm installing in Conda environments with their own Python. CUDA_PATH is set to the correct CUDA installation.

Installation from conda-forge works. On Python 3.10 it installs cudatoolkit 11.1, which is why I have tried that in addition to CUDA 11.8.

See also on StackOverflow where someone else seems to experience the same issue: https://stackoverflow.com/questions/73961872/cupy-cuda-failed-to-import-cupy

### To Reproduce

```bash
pip install cupy
```

```py
import cupy
```

### Installation

Source (`pip install cupy`)

### Environment

Not possible since import fails.

**Comment by kmaehashi** [comment]
Could you try running the following code and see what line generates an error?

```py
import cupy_backends.cuda.api.driver
import cupy_backends.cuda.api.runtime
import cupy_backends.cuda.libs.profiler
import cupy_backends.cuda.libs.nvrtc
import cupy_backends.cuda.libs.cublas
import cupy_backends.cuda.libs.curand
import cupy_backends.cuda.libs.cusparse
import cupy_backends.cuda.libs.cusolver
import cupy_backends.cuda.libs.nvtx
```

**Comment by uellue** [comment]
Sure! This is Python 3.10, CUDA 11.8 and `pip install cupy-cuda11x`.

```python
import cupy_backends.cuda.api.driver  # OK

import cupy_backends.cuda.api.runtime
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing runtime: The specified module could not be found.

import cupy_backends.cuda.libs.profiler
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing profiler: The specified module could not be found.

import cupy_backends.cuda.libs.nvrtc
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing nvrtc: The specified module could not be found.

import cupy_backends.cuda.libs.cublas
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing cublas: The specified module could not be found.

import cupy_backends.cuda.libs.curand
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing curand: The specified module could not be found.

import cupy_backends.cuda.libs.cusparse
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing cusparse: The specified module could not be found.

import cupy_backends.cuda.libs.cusolver
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing cusolver: The specified module could not be found.

import cupy_backends.cuda.libs.nvtx
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
# ImportError: DLL load failed while importing nvtx: The specified module could not be found.

**Comment by uellue** [comment]
Same result with `pip install cupy`.

**Comment by uellue** [comment]
> Could you be more specific on this? What did you set exactly?
> 
> > CUDA_PATH is set to the correct CUDA installation.

When I check environment variables with `SET`, it shows something like this:

```
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
```

When I install different versions, this variable changes to whatever I installed last. Also, it always uses the verion of the NVIDIA build tools that I installed last when I `pip install cupy`.

**Comment by leofang** [comment]
OK. In the case of using a local copy of CUDA Toolkit + pip wheels, you should not have `cudatoolkit` from conda-forge. The linker takes precedence for anything inside `$CONDA_PREFIX/lib`. I suspect the output of this command on your system is not empty, could you check?
```
conda list cu  # yes, just cu, it'd show all packages starting with "cu" 
```

**Comment by uellue** [comment]
@leofang Happy New Year! There's no `cudatoolkit` installed in the environment that reproduces the issue:

```
(cupytest310) C:\Users\weber>conda list cu
# packages in environment at C:\Users\weber\miniconda3\envs\cupytest310:
#
# Name                    Version                   Build  Channel
cupy                      11.4.0                   pypi_0    pypi
```

**Comment by Adam-L-Huerta** [comment]
Any updates on this? I'm having the same exact issue. Tried importing the list above and got the same output.

**Comment by kmaehashi** [comment]
Please try this with the latest `cupy-cuda12x` and open another issue along with the `python -c "import cupy; cupy.show_config()"` output if you still have issues.
