### ISSUE TITLE
Compilation error cupy-rocm with Radeon Mobile Graphics (AMD)

### ISSUE THREAD

**Issue by danielsz** [cupy/cupy#7504]
### Description

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 686, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 154, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 166, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 84, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: HIPRTC_ERROR_COMPILATION (6)
```

### To Reproduce

```py
python autozoom.py --in ./images/doublestrike.jpg --out ./autozoom.mp4
```
From https://github.com/sniklaus/3d-ken-burns

### Installation

None

### Environment

```
OS                        : Linux-6.2.9-arch1-1-x86_64-with-glibc2.37
Python Version            : 3.10.10
CuPy Version              : 11.3.0
CuPy Platform             : AMD ROCm
NumPy Version             : 1.24.2
SciPy Version             : 1.10.1
Cython Build Version      : 0.29.33
Cython Runtime Version    : 0.29.33
CUDA Root                 : /opt/rocm
hipcc PATH                : /opt/rocm/bin/hipcc
CUDA Build Version        : 50422804
CUDA Driver Version       : 50422804
CUDA Runtime Version      : 50422804
cuBLAS Version            : (available)
cuFFT Version             : 10021
cuRAND Version            : 201009
cuSOLVER Version          : (3, 20, 0)
cuSPARSE Version          : (available)
NVRTC Version             : (9, 0)
Thrust Version            : 101600
CUB Build Version         : 201012
Jitify Build Version      : None
cuDNN Build Version       : None
cuDNN Version             : None
NCCL Build Version        : 21304
NCCL Runtime Version      : 21304
cuTENSOR Version          : None
cuSPARSELt Build Version  : None
Device 0 Name             : AMD Radeon Graphics
Device 0 Arch             : gfx90c:xnack-
Device 0 PCI Bus ID       : 0000:07:00.0
```

### Additional Information

I've installed python-cupy-rocm in Arch linux.
I am overriding the version of the graphics card with HSA_OVERRIDE_GFX_VERSION=9.0.0 because it seems that the integrated GPU on laptops are not officially supported.

**Comment by emcastillo** [comment]
@amathews-amd 
Do you have any clue about this? :) 
Thanks!

**Comment by amathews-amd** [comment]
See https://github.com/RadeonOpenCompute/ROCm/issues/1714#issuecomment-1128327143 

If the gpu is not officially supported, the ROCm stack is not build up, or tested on this GPU. While some non-supported hardware sometimes just tends to work, continued functionality is not guaranteed, and there is no mechanism to request for help. 
cc: @AdrianAbeyta
