### ISSUE TITLE
Raw Kernels with Arrays greater 8GB

### ISSUE THREAD

**Issue by Intron7** [cupy/cupy#7539]
### Description

Dear Cupy-Team, 

I have been really enjoying using `cp.RawKernel`.  However I found some very weird behavior for Arrays > 8 GB. I have tested this on a 3090 and an A100. So Vram itself should not be the issue. What confuses me is that the "normal" cupy  works while my raw kernels break. Is this a known limit? How can I adjust my code so that these Kernels run even with the lager array sizes.

### To Reproduce

```py
import cupy as cp
import math

_add_one_kernel_row_wise = cp.RawKernel(r'''
    extern "C" __global__
    void add_one(float * residuals, const int x_dim, const int y_dim) {
        int x = blockDim.x * blockIdx.x + threadIdx.x;
        if(x >= x_dim){
            return;
        }


        for(int y = 0; y < y_dim; y++){
            residuals[x*y_dim+y] += 1;
        }
    }
    ''',"add_one")

_add_one_kernel_block = cp.RawKernel(r'''
    extern "C" __global__
    void add_one_block(float * residuals, const int x_dim, const int y_dim) {
        int x = blockDim.x * blockIdx.x + threadIdx.x;
        int y = blockDim.y * blockIdx.y + threadIdx.y;
        if(x >= x_dim||y >= y_dim){
            return;
        }      
        residuals[x*y_dim+y] += 1;
       
    }
    ''',"add_one_block")

#CUPY
residuals = cp.zeros((429498, 5000), dtype=cp.float32)
#429497 works for rowwise and 429496 for block. 429498 and Greater works fine for CUPY
residuals = residuals+1
print(residuals)

bytes_size =residuals.nbytes
size_gb = bytes_size / (1024**3)
print(f"Size in GB: {size_gb}")

#Row Wise
block = (32,)
grid = (int(math.ceil(residuals.shape[0] / block[0])),)
print(grid)
_add_one_kernel_row_wise(grid,block,(residuals,residuals.shape[0],residuals.shape[1]))
cp.cuda.Stream.null.synchronize()
print(residuals)

## Block
block = (16,16)
grid = (int(math.ceil(residuals.shape[0] / block[0])),int(math.ceil(residuals.shape[1] / block[1])))
print(grid)
_add_one_kernel_block(grid,block,(residuals,residuals.shape[0],residuals.shape[1]))
cp.cuda.Stream.null.synchronize()
print(residuals)
bytes_size =residuals.nbytes
size_gb = bytes_size / (1024**3)
print(f"Size in GB: {size_gb}")
```

### Installation

Conda-Forge (`conda install ...`)

## 429498
```
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Size in GB: 8.000023663043976
(13422,)
Traceback (most recent call last):
  File "/home/sdicks/git/rapids_singlecell_tester/notebooks/raw_test_random.py", line 46, in <module>
    cp.cuda.Stream.null.synchronize()
  File "cupy/cuda/stream.pyx", line 252, in cupy.cuda.stream._BaseStream.synchronize
  File "cupy_backends/cuda/api/runtime.pyx", line 851, in cupy_backends.cuda.api.runtime.streamSynchronize
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```
## 429497
```
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Size in GB: 8.000005036592484
(13422,)
[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
(26844, 313)
Traceback (most recent call last):
  File "/home/sdicks/git/rapids_singlecell_tester/notebooks/raw_test_random.py", line 54, in <module>
    cp.cuda.Stream.null.synchronize()
  File "cupy/cuda/stream.pyx", line 252, in cupy.cuda.stream._BaseStream.synchronize
  File "cupy_backends/cuda/api/runtime.pyx", line 851, in cupy_backends.cuda.api.runtime.streamSynchronize
  File "cupy_backends/cuda/api/runtime.pyx", line 143, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
Exception ignored in: 'cupy.cuda.function.Module.__dealloc__'
Traceback (most recent call last):
  File "cupy_backends/cuda/api/driver.pyx", line 217, in cupy_backends.cuda.api.driver.moduleUnload
  File "cupy_backends/cuda/api/driver.pyx", line 60, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```
## 429496
```
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Size in GB: 7.999986410140991
(13422,)
[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
(26844, 313)
[[3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]]
Size in GB: 7.999986410140991
```

#### 3090
```
OS                           : Linux-5.19.0-41-generic-x86_64-with-glibc2.35
Python Version               : 3.10.10
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.22.4
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.33
Cython Runtime Version       : None
CUDA Root                    : /home/sdicks/miniconda3/envs/rapids-23.04
nvcc PATH                    : /home/sdicks/miniconda3/envs/rapids-23.04/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 12010
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : f670b37
cuDNN Build Version          : 8401
cuDNN Version                : 8800
NCCL Build Version           : 21403
NCCL Runtime Version         : 21505
cuTENSOR Version             : 10700
cuSPARSELt Build Version     : 200
Device 0 Name                : NVIDIA GeForce RTX 3090
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:0B:00.0
```
#### A100
```
OS                           : Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
Python Version               : 3.10.10
CuPy Version                 : 11.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.10.1
Cython Build Version         : 0.29.33
Cython Runtime Version       : None
CUDA Root                    : /home/sedi10/conda/envs/rapids-23.04
nvcc PATH                    : /home/sedi10/conda/envs/rapids-23.04/bin/nvcc
CUDA Build Version           : 11020
CUDA Driver Version          : 11040
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : f670b37
cuDNN Build Version          : 8401
cuDNN Version                : 8800
NCCL Build Version           : 21403
NCCL Runtime Version         : 21505
cuTENSOR Version             : 10700
cuSPARSELt Build Version     : 200
Device 0 Name                : NVIDIA A100 80GB PCIe
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:21:00.0
```

### Additional Information

Same behavior on A100 and RTX 3090

**Comment by Intron7** [comment]
Ok thank you. Casting the index into long long fixed the code.
