### ISSUE TITLE
Failed to import CuPy

### ISSUE THREAD

**Issue by lyysl** [cupy/cupy#7565]
### Description

I updated my nvidia driver
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0`

And I used `pip install cupy-cuda12x`

But I get the error
```
Traceback (most recent call last):
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: @": cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./src/colorisation.py", line 18, in <module>
    import cupy as cp
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/__init__.py", line 27, in <module>
    ''') from exc
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: @": cannot open shared object file: No such file or directory
================================================================
```

Thank you.

**Comment by kmaehashi** [comment]
Could you share the output of this command? 
`python -c 'import cupy; cupy.show_config()'`

**Comment by liyingyinsimon** [comment]
```
Traceback (most recent call last):
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: @": cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/simon/miniconda3/lib/python3.7/site-packages/cupy/__init__.py", line 27, in <module>
    ''') from exc
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: @": cannot open shared object file: No such file or directory
================================================================
```

Thank you.

**Comment by twmht** [comment]
@kmaehashi 

Same error, my driver version is  550.54.14.

**Comment by kmaehashi** [comment]
I'm closing this one as it's inactive for a while. If feel free to request reopening if anyone still seeing this problem.
