### ISSUE TITLE
cupy v12.0.0 cuda11x failing to import

### ISSUE THREAD

**Issue by aaronluong** [cupy/cupy#7573]
### Description

Seems like cupy is looking for libnvJitLink.so.12, which I'm assuming is a file that only exists on cuda 12 despite having installed cupy-cuda11x. pip freeze | grep cupy only shows cupy-cuda11x==12.0.0. 

### To Reproduce

```py
import cupy
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
Traceback (most recent call last):
  File "/home/aaronluong/anaconda3/lib/python3.9/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "/home/aaronluong/anaconda3/lib/python3.9/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/aaronluong/anaconda3/lib/python3.9/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/aaronluong/anaconda3/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 9, in init cupy.cuda.device
ImportError: libnvJitLink.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aaronluong/anaconda3/lib/python3.9/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libnvJitLink.so.12: cannot open shared object file: No such file or directory
================================================================
```

**Comment by kmaehashi** [comment]
I guess you have both CUDA 11 and 12 on your computer, and for some reason CUDA 12 is preferred over CUDA 11 on your library discovery path (e.g. `LD_LIBRARY_PATH`).

`libnvJitLink.so.12` is actually a dependency of cuSOLVER bundled with CUDA 12. Note that cuSOLVER bundled with CUDA 11 does not require `libnvJitLink`, although they have the same file name `libcusolver.so.11`.


```
/usr/local/cuda-11.6.0/targets/x86_64-linux/lib/libcusolver.so.11:
	linux-vdso.so.1 (0x00007ffcb4feb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0d1f888000)
	libcublas.so.11 => /usr/local/cuda-11.6.0/lib64/libcublas.so.11 (0x00007f0d05600000)
	libcublasLt.so.11 => /usr/local/cuda-11.6.0/lib64/libcublasLt.so.11 (0x00007f0cf0000000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0d1f883000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0d1f87e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0d1f795000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d1f775000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0cefdd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0d1f8a8000)
/usr/local/cuda-12.1.0/targets/x86_64-linux/lib/libcusolver.so.11:
	linux-vdso.so.1 (0x00007fff00710000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1769f19000)
	libnvJitLink.so.12 => /usr/local/cuda-12.1.0/lib64/libnvJitLink.so.12 (0x00007f1754800000)
	libcublas.so.12 => /usr/local/cuda-12.1.0/lib64/libcublas.so.12 (0x00007f174de00000)
	libcublasLt.so.12 => /usr/local/cuda-12.1.0/lib64/libcublasLt.so.12 (0x00007f172ce00000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1769f14000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1769f0d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1757919000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1769eed000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f172cbd8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1769f39000)
```

**Comment by ZeliangM** [comment]
> 

I meet the same problem.However,I don't use Pycharm such as jupyter lab,there is nor error.I don't understand the reason.

**Comment by kmaehashi** [comment]
Closing as inactive. Feel free to open another case if you still need help.
