### ISSUE TITLE
PooledMemory object as no attribute ptr

### ISSUE THREAD

**Issue by mratsim** [cupy/cupy#765]
I'm trying to get spaCy working with CUDA backend, not too sure if it's an issue in Cupy or spaCy's Thinc backend:

Error points to: https://github.com/cupy/cupy/blob/bad41820a4247a4bf9871b58eda662c24f5b60cf/cupy/cuda/memory.pyx#L481

cupy, spacy and thinc build from master on Nov 17.

Traceback:
```
Created blank 'en' model
Loading IMDB data...
Using 2000 examples (1600 training, 400 evaluation)
Exception ignored in: <bound method PooledMemory.free of <cupy.cuda.memory.PooledMemory object at 0x7f363dd2d128>>
Traceback (most recent call last):
  File "cupy/cuda/memory.pyx", line 481, in cupy.cuda.memory.PooledMemory.free
AttributeError: 'PooledMemory' object has no attribute 'ptr'
Traceback (most recent call last):
  File "cupy/cuda/driver.pyx", line 72, in cupy.cuda.driver.check_status
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "spacy_imdb_classification_gpu.py", line 132, in <module>
    plac.call(main)
  File "/usr/lib/python3.6/site-packages/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/usr/lib/python3.6/site-packages/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "spacy_imdb_classification_gpu.py", line 57, in main
    optimizer = nlp.begin_training(device=0) # GPU / Cuda training
  File "/usr/lib/python3.6/site-packages/spacy/language.py", line 456, in begin_training
    sgd=self._optimizer)
  File "pipeline.pyx", line 859, in spacy.pipeline.TextCategorizer.begin_training
  File "pipeline.pyx", line 778, in spacy.pipeline.TextCategorizer.Model
  File "/usr/lib/python3.6/site-packages/spacy/_ml.py", line 527, in build_text_classifier
    >> zero_init(Affine(nr_class, width, drop_factor=0.0))
  File "/usr/lib/python3.6/site-packages/thinc/api.py", line 296, in with_flatten
    model = layerize(begin_update, predict=predict)
  File "/usr/lib/python3.6/site-packages/thinc/api.py", line 74, in layerize
    return FunctionLayer(begin_update, predict=predict, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/thinc/api.py", line 22, in __init__
    Model.__init__(self)
  File "/usr/lib/python3.6/site-packages/thinc/neural/_classes/model.py", line 83, in __init__
    self._mem = Memory(self.ops)
  File "/usr/lib/python3.6/site-packages/thinc/neural/mem.py", line 13, in __init__
    self._mem = self.ops.allocate((2, size))
  File "ops.pyx", line 158, in thinc.neural.ops.Ops.allocate
  File "/usr/lib/python3.6/site-packages/cupy/creation/basic.py", line 146, in zeros
    a = cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 95, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 441, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 915, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 936, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 693, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 759, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
SystemError: <class 'cupy.cuda.memory.PooledMemory'> returned a result with an error set
```

The test file is spaCy IMDB example modified for CuPy backend, i.e. https://github.com/explosion/spaCy/blob/c3051e95f718c4ff5983197e0bdaea691cd67ea2/examples/training/train_textcat.py#L58 changed from:
`optimizer = nlp.begin_training()` to `optimizer = nlp.begin_training(device=0)` according to https://github.com/explosion/spaCy/issues/1530

**Comment by kmaehashi** [comment]
I'm sorry that we failed to respond :bow: As the issue seems out-dated, let me close this issue. Please feel free to reopen if needed. Thank you.
