### ISSUE TITLE
KeyError: 11 in cupy_backends.cuda.libs.cusparse.spGEMM_compute

### ISSUE THREAD

**Issue by sambaPython24** [cupy/cupy#7677]
### Description

A better error description would be great for the following error: 

```python 
Exception ignored in: 'cupy_backends.cuda.libs.cusparse.spGEMM_compute'
Traceback (most recent call last):
  File "cupy_backends/cuda/libs/cusparse.pyx", line 1544, in cupy_backends.cuda.libs.cusparse.check_status
  File "cupy_backends/cuda/libs/cusparse.pyx", line 1534, in cupy_backends.cuda.libs.cusparse.CuSparseError.__init__
KeyError: 11
```

For me, the error is raised but does not crash the script. Also, it appeared suddenly, without a change in cupy or cuda.

### Idea or request for content

I don't know where this error is coming from.

**Comment by kmaehashi** [comment]
Hi @sambaPython24, thanks for reporting! I'll work on fix for this case.
