### ISSUE TITLE
Versioning error? 

### ISSUE THREAD

**Issue by zohimchandani** [cupy/cupy#7772]
### Description

import cupy yields an error 

### To Reproduce

`nvidia-smi` shows cuda version is 12.0 hence I install cupy via `pip install cupy-cuda12x`

`import cupy` yields the error:

```
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/cupy/__init__.py:17
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

File ~/.local/lib/python3.10/site-packages/cupy/_core/__init__.py:3
      1 # mypy: ignore-errors
----> 3 from cupy._core import core  # NOQA
      4 from cupy._core import fusion  # NOQA

ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import cupy

File ~/.local/lib/python3.10/site-packages/cupy/__init__.py:19
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
...

Original error:
  ImportError: libcudart.so.12: cannot open shared object file: No such file or directory 
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
Traceback (most recent call last):
  File "/home/cudaq/.local/lib/python3.10/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
  File "/home/cudaq/.local/lib/python3.10/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cudaq/.local/lib/python3.10/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
================================================================
```

**Comment by leofang** [comment]
Hey Zohim 😄 As indicated in the error message, `libcudart.so.12` is not found. It's likely that you haven't added your local CTK installation to `LD_LIBRARY_PATH` so the dynamic linker could not find it.

> nvidia-smi shows cuda version is 12.0 hence I install cupy via pip install cupy-cuda12x

`nvidia-smi` only tells you up to what CTK version your driver is fully compatible with. It is different from what CTK is actually available to local processes.

**Comment by leofang** [comment]
Discussed with Zohim offline, this can be closed now.
