### ISSUE TITLE
`ndarray` constructor behavior mismatches when `strides` is given

### ISSUE THREAD

**Issue by leofang** [cupy/cupy#7818]
### Description

As title.

### To Reproduce

```py
>>> import numpy as np
>>> a = np.ndarray((1,), strides=(8,), dtype=np.float64)  # this works
>>>
>>> import cupy as cp
>>> a = cp.ndarray((1,), strides=(8,), dtype=cp.float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/core.pyx", line 136, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 213, in cupy._core.core._ndarray_base._init
ValueError: memptr is required if strides is given.
```

### Installation

Source (`pip install cupy`)

**Comment by leofang** [comment]
Maybe NumPy no longer raises in recent releases, so the old comment https://github.com/cupy/cupy/pull/1611#discussion_r218683200 is no longer applicable?

**Comment by leofang** [comment]
@seberg would you mind triaging this issue?

**Comment by seberg** [comment]
Seems like a very strange feature that I doubt is used.  But allowing this isn't much more than changing the order things so probably might as well change it.

NumPy does check that the memory bounds fit into the allocation if passed, which CuPy is currently not.  We could add that for the Python side constructor (the Cython/internal code paths don't need to verify).
