### ISSUE TITLE
erro on generate a exe

### ISSUE THREAD

**Issue by Allmight0000** [cupy/cupy#7852]
### Description

torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
torch\_jit_internal.py:853: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000020D8FF01000>.
  warnings.warn(
torch\_jit_internal.py:853: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x0000020D8FF032E0>.
  warnings.warn(
Traceback (most recent call last):
  File "cupy\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cupy\_core\__init__.py", line 3, in <module>
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cupy\cuda\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cupy\cuda\compiler.py", line 13, in <module>
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
  File "cupy_backends\cuda\api\runtime.pyx", line 110, in init cupy_backends.cuda.api.runtime
  File "cupy_backends\cuda\api\runtime.pyx", line 103, in cupy_backends.cuda.api.runtime._export_enum
ModuleNotFoundError: No module named 'cupy_backends.cuda.api._runtime_enum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "TENSORRTFORGAMING.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "cupy\__init__.py", line 19, in <module>
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ModuleNotFoundError: No module named 'cupy_backends.cuda.api._runtime_enum'
================================================================

[8544] Failed to execute script 'TENSORRTFORGAMING' due to unhandled exception!

### To Reproduce

```py
# Write the code here
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
# Paste the output here
```

### Additional Information

.

**Comment by kmaehashi** [comment]
Closing as duplicate #5090. You need to define hiddenimports for libraries with C-extension.
