### ISSUE TITLE
Error when using multiprocessing and Multi-gpu

### ISSUE THREAD

**Issue by miguelcarcamov** [cupy/cupy#7879]
### Description

I'm trying to use multiprocessing to use 2 or more GPUs in parallel. I'm getting the error regardless if I use 'spawn' and 'fork' when setting the start method for the threads.

In particular, this is the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/miguel.carcamo/test_multigpu/test_2.py", line 20, in <module>
    p = ctx.Pool(4)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
/home/miguel.carcamo/anaconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
I attach two minimum viable codes that I'm currently using to test.

### To Reproduce

```py
import cupy as cp
from multiprocessing import Pool, current_process, set_start_method, get_context

def run(ndevices, data):
    process = current_process()
    pid = process.pid
    gpu_id = pid % ndevices
    # data = list_gpu[gpu_id]
    with cp.cuda.Device(gpu_id):
        data *= 0.5
        print("Process {0} using GPU {1}".format(pid, gpu_id), data)

ctx = get_context('spawn')
#pool = ctx.Pool(4)
# set_start_method('spawn', force=True)

list_multi_gpu = []

ndevices = 3

for i in range(ndevices):
    with cp.cuda.Device(i):
        list_multi_gpu.append(cp.ones((2,2)))

with ctx.Pool(processes=3) as pool:
    pool.map(run, [(ndevices, list_multi_gpu), (ndevices, list_multi_gpu)])
```

```py
import cupy
import numpy as np
import multiprocessing
from multiprocessing import pool


def f(x):
    return cupy.asnumpy(2*cupy.array(x))


ctx = multiprocessing.get_context('spawn')

input = np.array([1,2,3,4])
print(cupy.asnumpy(cupy.array(input)))


print(np.array(list(map(f, input))))


p = ctx.Pool(4)
output = p.map(f, input)
p.close()
p.join()
print(output)
```

### Installation

None

### Environment

```
OS                           : Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Python Version               : 3.9.12
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.21.5
SciPy Version                : 1.7.3
Cython Build Version         : 0.29.28
Cython Runtime Version       : 0.29.28
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 11080
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100 80GB PCIe
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:81:00.0
Device 1 Name                : NVIDIA A100 80GB PCIe
Device 1 Compute Capability  : 80
Device 1 PCI Bus ID          : 0000:C1:00.0
Device 2 Name                : NVIDIA A100 80GB PCIe
Device 2 Compute Capability  : 80
Device 2 PCI Bus ID          : 0000:C2:00.0
```

**Comment by emcastillo** [comment]
This is a python issue with multiprocessing rather than a CuPy error.

If you put your code into a `main` function then it works as expected (note that you have other errors)

```ctx = get_context('spawn')
#pool = ctx.Pool(4)
# set_start_method('spawn', force=True)

def main():
    list_multi_gpu = []

    ndevices = 3

    for i in range(ndevices):
        with cp.cuda.Device(i):
            list_multi_gpu.append(cp.ones((2,2)))

    with ctx.Pool(processes=3) as pool:
        pool.map(run, [(ndevices, list_multi_gpu), (ndevices, list_multi_gpu)])


if __name__ == "__main__":
    main()
```

**Comment by miguelcarcamov** [comment]
Hi @emcastillo, I have been testing your code, but now I've got to more questions and issues.

I'm using the following MVC to test:

```python
import cupy as cp
from multiprocessing import Pool, current_process, set_start_method, get_context

def run(ndevices, list_data):
    process = current_process()
    pid = process.pid
    gpu_id = pid % ndevices
    data = list_data[gpu_id]
    with cp.cuda.Device(gpu_id):
        data *= 0.5
        print("Process {0} using GPU {1}, and data is on GPU {2}".format(pid, gpu_id, data.device), data)

ctx = get_context('spawn')
#pool = ctx.Pool(4)
# set_start_method('spawn', force=True)

def func():
    list_multi_gpu = []

    ndevices = 3

    for i in range(ndevices):
        with cp.cuda.Device(i):
            list_multi_gpu.append(cp.ones((2,2)))

    print("Checking GPU arrays on list")
    for i, data in enumerate(list_multi_gpu):
        print("Data from GPU {0} is on GPU {1}".format(i, data.device))

    with ctx.Pool(processes=3) as pool:
        pool.starmap(run, [(ndevices, list_multi_gpu), (ndevices, list_multi_gpu), (ndevices, list_multi_gpu)])

if __name__ == "__main__":
    func()
```

This results on:

```
Checking GPU arrays on list
Data from GPU 0 is on GPU <CUDA Device 0>
Data from GPU 1 is on GPU <CUDA Device 1>
Data from GPU 2 is on GPU <CUDA Device 2>
Process 1893744 using GPU 0, and data is on GPU <CUDA Device 0> [[0.5 0.5]
 [0.5 0.5]]
/home/miguel.carcamo/test_multigpu/test_3.py:10: PerformanceWarning: The device where the array resides (0) is different from the current device (2). Peer access has been activated automatically.
  data *= 0.5
/home/miguel.carcamo/test_multigpu/test_3.py:10: PerformanceWarning: The device where the array resides (0) is different from the current device (1). Peer access has been activated automatically.
  data *= 0.5
Process 1893743 using GPU 2, and data is on GPU <CUDA Device 0> [[0.5 0.5]
 [0.5 0.5]]
Process 1893745 using GPU 1, and data is on GPU <CUDA Device 0> [[1. 1.]
 [1. 1.]]
```

- Why data appears on GPU 0 even if the data was accessed using the correct GPU id on the list and on `cp.cuda.Device()`?
- Why data does not change to 0.5 on this case?
```
Process 1893745 using GPU 1, and data is on GPU <CUDA Device 0> [[1. 1.]
 [1. 1.]]
```

**Comment by kmaehashi** [comment]
Let me close as this is inactive for a long time. Please feel free to request reopening if anyone is still seeing this problem.
