### ISSUE TITLE
Reduction with complex accumulator not working with float16

### ISSUE THREAD

**Issue by kohr-h** [cupy/cupy#795]
The following code gives a compile exception (similar with `prod`):
```python
>>> a = cupy.ones(3, dtype='float16')
>>> cupy.sum(a, dtype=complex)
Traceback (most recent call last):

  File "<ipython-input-11-8ad163707fe2>", line 1, in <module>
    cupy.sum(a, dtype=complex)

  File "[...]/cupy/core/fusion.py", line 821, in __call__
    return self._cupy_op(*args, **kwargs)

  File "[...]/cupy/math/sumprod.py", line 25, in sum
    return a.sum(axis, dtype, out, keepdims)

  File "cupy/core/core.pyx", line 1016, in cupy.core.core.ndarray.sum

  File "cupy/core/core.pyx", line 1024, in cupy.core.core.ndarray.sum

  File "cupy/core/reduction.pxi", line 254, in cupy.core.core.simple_reduction_function.__call__

  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret

  File "cupy/core/reduction.pxi", line 178, in cupy.core.core._get_simple_reduction_function

  File "cupy/core/reduction.pxi", line 105, in cupy.core.core._get_simple_reduction_kernel

  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache

  File "[...]/cupy/cuda/compiler.py", line 149, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)

  File "[...]/cupy/cuda/compiler.py", line 70, in compile_using_nvrtc
    ptx = prog.compile(options)

  File "[...]/cupy/cuda/compiler.py", line 230, in compile
    raise CompileException(log, self.src, self.name, options)

CompileException: [...]/cupy/core/include/cupy/carray.cuh(394): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmp3y9uraiv/kern.cu(29): here

/tmp/tmp3y9uraiv/kern.cu(31): error: no suitable user-defined conversion from "const type_in0_raw" to "_type_reduce" exists

1 error detected in the compilation of "/tmp/tmp3y9uraiv/kern.cu".
```
Here's the kernel source:
```C++
#include <cupy/complex.cuh>
#include <cupy/carray.cuh>

    typedef float16 type_in0_raw; typedef complex<double> type_out0_raw;
    
    #define REDUCE(a, b) (a + b)
    #define POST_MAP(a) (out0 = type_out0_raw(a))
    #define _REDUCE(_offset) if (_tid < _offset) {       _type_reduce _a = _sdata[_tid], _b = _sdata[(_tid + _offset)];       _sdata[_tid] = REDUCE(_a, _b);     }

    typedef complex<double> _type_reduce;
    extern "C" __global__ void cupy_sum(CArray<float16, 1> _raw_in0, CArray<complex<double>, 0> _raw_out0, CIndexer<1> _in_ind, CIndexer<0> _out_ind, int _block_stride) {
      extern __shared__ _type_reduce _sdata_raw[];
      _type_reduce *_sdata = _sdata_raw;
      unsigned int _tid = threadIdx.x;

      int _J_offset = _tid / _block_stride;
      int _j_offset = _J_offset * _out_ind.size();
      int _J_stride = 512;
      long long _j_stride = 512LL * _out_ind.size();

      for (int _i_base = blockIdx.x * _block_stride;
           _i_base < _out_ind.size();
           _i_base += gridDim.x * _block_stride) {
        _type_reduce _s = _type_reduce(0);
        int _i = _i_base + _tid % _block_stride;
        int _J = _J_offset;
        for (long long _j = _i + _j_offset; _j < _in_ind.size();
             _j += _j_stride, _J += _J_stride) {
          _in_ind.set(_j);
          const type_in0_raw in0 = _raw_in0[_in_ind.get()];
          _type_reduce _a = in0;
          _s = REDUCE(_s, _a);
        }
        if (_block_stride < 512) {
          _sdata[_tid] = _s;
          __syncthreads();
          if (_block_stride <= 256) {
            _REDUCE(256);
            __syncthreads();
            if (_block_stride <= 128) {
              _REDUCE(128);
              __syncthreads();
              if (_block_stride <= 64) {
                _REDUCE(64);
                __syncthreads();
                if (_block_stride <= 32) {
                  _REDUCE(32);
                  if (_block_stride <= 16) {
                    _REDUCE(16);
                    if (_block_stride <= 8) {
                      _REDUCE(8);
                      if (_block_stride <= 4) {
                        _REDUCE(4);
                        if (_block_stride <= 2) {
                          _REDUCE(2);
                          if (_block_stride <= 1) {
                            _REDUCE(1);
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          _s = _sdata[_tid];
          __syncthreads();
        }
        if (_J_offset == 0 && _i < _out_ind.size()) {
          _out_ind.set(_i);
          type_out0_raw &out0 = _raw_out0[_out_ind.get()];
          POST_MAP(_s);
        }
      }
    }
```

**Comment by leofang** [comment]
I think this has been resolved for a while.
