### ISSUE TITLE
NVRTCError: NVRTC_ERROR_COMPILATION (6)

### ISSUE THREAD

**Issue by Grasszhenzhen** [cupy/cupy#7972]
### Description

Could you please assist me in troubleshooting an error I'm facing with CuPy in the im2col function within Pyinn? Your help would be greatly appreciated.

### To Reproduce

Traceback (most recent call last):
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 685, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 141, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 153, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 69, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CNNtest\GNNStyletransfer_cpu\test_demo.py", line 179, in <module>
    yc_patch, y_padding = im2patch(ys_patch, patchsize=5, stride=1, padding=None, returnpadding=True)
  File "D:\CNNtest\GNNStyletransfer_cpu\test_demo.py", line 120, in im2patch
    x2col = pyinn.im2col(xpad, [patchsize]*2, [stride]*2, [0,0])
  File "D:\CNNtest\GNNStyletransfer_cpu\pyinn\im2col.py", line 253, in im2col
    return im2col_c.forward(input)
  File "D:\CNNtest\GNNStyletransfer_cpu\pyinn\im2col.py", line 215, in forward
    return im2col_batch(input, self.kernel_size, self.stride, self.padding)
  File "D:\CNNtest\GNNStyletransfer_cpu\pyinn\im2col.py", line 191, in im2col_batch
    _im2col(x, kernel_size, stride, padding, out=o)
  File "D:\CNNtest\GNNStyletransfer_cpu\pyinn\im2col.py", line 122, in _im2col
    f(block=(CUDA_NUM_THREADS,1,1),
  File "cupy\_core\raw.pyx", line 89, in cupy._core.raw.RawKernel.__call__
  File "cupy\_core\raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 113, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 547, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2081, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2141, in cupy._core.core.compile_with_cache
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 492, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 570, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 321, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 305, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "D:\Anaconda3\envs\styletransferGNN\lib\site-packages\cupy\cuda\compiler.py", line 704, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: C:\Users\masha\AppData\Local\Temp\tmpkxm4w02p\b5e3bff97e6984901871bfb79b050768bf553b82.cubin.cu(7): error: identifier "None" is undefined

C:\Users\masha\AppData\Local\Temp\tmpkxm4w02p\b5e3bff97e6984901871bfb79b050768bf553b82.cubin.cu(7): error: identifier "None" is undefined

2 errors detected in the compilation of "C:\Users\masha\AppData\Local\Temp\tmpkxm4w02p\b5e3bff97e6984901871bfb79b050768bf553b82.cubin.cu".

进程已结束,退出代码1

### Installation

Conda-Forge (`conda install ...`)

### Environment

OS                           : Windows-10-10.0.22621-SP0
Python Version               : 3.9.18
CuPy Version                 : 10.6.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.11.3
Cython Build Version         : 0.29.30
Cython Runtime Version       : 3.0.4
CUDA Root                    : D:\NVIDIA\CUDA
nvcc PATH                    : D:\NVIDIA\CUDA\bin\nvcc.EXE
CUDA Build Version           : 11020
CUDA Driver Version          : 12010
CUDA Runtime Version         : 11020
cuBLAS Version               : (available)
cuFFT Version                : 10401
cuRAND Version               : 10203
cuSOLVER Version             : (11, 1, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 2)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4060 Laptop GPU
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0

**Comment by leofang** [comment]
You need to report this issue to whoever provides the kernel. The kernel is not from CuPy.
