### ISSUE TITLE
Can not find cutensor by installing cupy from source code

### ISSUE THREAD

**Issue by beimojiguang** [cupy/cupy#7991]
### Description

Hi,
By following the document, I install cupy from source code.

```
git clone --recursive https://github.com/cupy/cupy.git
cd cupy
pip install -e .
```

After that I install cutensor by using `python -m cupyx.tools.install_library --cuda 11.x --library cutensor`

but fail to load cutensor it in python:
`from cupy import cutensor`

cutensor/lib has already been added into LD_LIBRARY_PATH

### To Reproduce

```py
import cupy
from cupy import cutensor
```
The output
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/tiger/cupy/cupy/cutensor.py", line 3, in <module>
    from cupyx.cutensor import *  # NOQA
ModuleNotFoundError: No module named 'cupyx.cutensor'
```

### Installation

Built from GitHub source

### Environment

```
OS                           : Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Python Version               : 3.9.2
CuPy Version                 : 13.0.0b1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.2
SciPy Version                : 1.11.4
Cython Build Version         : 0.29.33
Cython Runtime Version       : 0.29.33
CUDA Root                    : /usr/local/cuda-11.7
nvcc PATH                    : /usr/local/cuda-11.7/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 4, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : b1e3f19e5
cuDNN Build Version          : 8500
cuDNN Version                : 8500
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-SXM4-80GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:71:00.0
```

**Comment by leofang** [comment]
If you're building from source, you need to set the env var `CUTENSOR_PATH`:
https://docs.cupy.dev/en/stable/reference/environment.html#envvar-CUTENSOR_PATH

**Comment by beimojiguang** [comment]
Thank you for your answer!

But the problem still exists.

I tried to use pip to get `cutensor` package:

```
pip install cutensor-cu11 --target=/to/my/workdir
```

then set the CUTENSOR_PATH and install :
```
export CUTENSOR_PATH=/to/my/workdir/cutensor
cd cupy
pip install -e .
```

Here is the output of ` python3 -c "import cupy; cupy.show_config()"`
```
OS                           : Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
Python Version               : 3.9.2
CuPy Version                 : 13.0.0b1
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.2
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11070
CUDA Driver Version          : 11070
CUDA Runtime Version         : 11070
cuBLAS Version               : (available)
cuFFT Version                : 10702
cuRAND Version               : 10210
cuSOLVER Version             : (11, 4, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 7)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : ff9b39bb1
cuDNN Build Version          : 8500
cuDNN Version                : 8500
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-SXM4-80GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:4E:00.0
```

Really expect your reply~!

**Comment by leofang** [comment]
Like all NVIDIA wheels, using the cuTENSOR wheel at build time requires additional effort, and CuPy is not prepared for that. Please download and use cuTENSOR in other forms (conda, tarball, apt, yum, ...) from the [official download page](https://developer.nvidia.com/cutensor-downloads).

Also, note that cuTENSOR 2.0 just came out, and CuPy's support is still being updated (#7984), so make sure you're using the older (1.7) version in the interim.

**Comment by beimojiguang** [comment]
Finally fix this problem!
Thank you so so much!
