### ISSUE TITLE
Allow using CUDA libraries installed from pip wheels

### ISSUE THREAD

**Issue by FlorinAndrei** [cupy/cupy#8013]
### Description

JAX, PyTorch and TensorFlow all can use CUDA libraries installed as Python modules. For example, if you install JAX with the pip version of CUDA...

```
pip install --upgrade --user "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

...that will also install the relevant CUDA libraries as Python modules:

```
nvidia-cublas-cu11                11.11.3.6
nvidia-cuda-cupti-cu11            11.8.87
nvidia-cuda-nvcc-cu11             11.8.89
nvidia-cuda-nvrtc-cu11            11.8.89
nvidia-cuda-runtime-cu11          11.8.89
nvidia-cudnn-cu11                 8.9.6.50
nvidia-cufft-cu11                 10.9.0.58
nvidia-cusolver-cu11              11.4.1.48
nvidia-cusparse-cu11              11.7.5.86
nvidia-nccl-cu11                  2.19.3
```

Then you can install TensorFlow as well...

```
pip install --upgrade --user tensorflow=2.14.1
```

...and then PyTorch...

```
pip install --upgrade --user torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
```

...and they all work perfectly without needing a separate CUDA install.

However, if you install `cupy-cuda11x` and try to run it, it claims it cannot find CUDA. It only works if you give it a completely separate installation of CUDA, in `/usr/local` or something.

Having CUDA installed via pip is easier and more convenient, and may save some storage.

### Additional Information

I'm using Ubuntu 22.04 with an RTX 3090.

**Comment by kmaehashi** [comment]
Hi @FlorinAndrei, thanks for feedback! This is definitely what we want. I'll start investigating changes required to support these PyPI distributed CUDA Toolkit.

**Comment by HelloCard** [comment]
Still not working, still relying on NVIDIA CUDA suite instead of Python components.
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/cupy/__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/root/miniconda3/lib/python3.11/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 9, in init cupy.cuda.device
ImportError: libcusolver.so.11: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.11/site-packages/vllm/model_executor/parallel_utils/cupy_utils.py", line 16, in <module>
    import cupy
  File "/root/miniconda3/lib/python3.11/site-packages/cupy/__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.
```
I have already installed it: nvidia-cusolver-cu12      11.4.5.107
\\wsl.localhost\Ubuntu-22.04\root\miniconda3\lib\python3.11\site-packages\nvidia\cusolver\lib\libcusolver.so.11
It exists here, but cupy cannot find it.

**Comment by kmaehashi** [comment]
I've checked how PyTorch achieves this:

https://github.com/pytorch/pytorch/blob/0e1e289033554f7293da70a45c9d38c17517b5dc/torch/__init__.py#L281-L317

So only thing we have to do is to find `nvidia/${library_name}/lib/${filename}.so` from `sys.path` and `open` with `RTLD_GLOBAL.`

**Comment by leofang** [comment]
@kmaehashi More or less, yes. nvmath-python already does this and it's coming public soon. I suggest that we start evaluating making it a dependency and let nvmath handle the loading for CuPy.

btw would you mind changing the issue title to, say, ""Allow using CUDA libraries installed from pip wheels"? The current title is hard to search 😅

**Comment by kmaehashi** [comment]
Thanks Leo, I'll wait for `nvmath-python`. Just curious, does it cover libnvrtc as well?

> btw would you mind changing the issue title to, say, ""Allow using CUDA libraries installed from pip wheels"? The current title is hard to search 😅

Makes sense, updated the title.

**Comment by leofang** [comment]
> Just curious, does it cover libnvrtc as well?

This is supposed to be handled in CUDA Python (https://github.com/NVIDIA/cuda-python/issues/62), but, yes, nvmath-python covers it too due to other reasons (supporting CuPy being one) 🙂

**Comment by martinResearch** [comment]
Hi, is any work planned on this?

**Comment by leofang** [comment]
Yes, we have discussed a rough plan for this, but the actual work has not happened yet.

**Comment by leofang** [comment]
In a recent meeting we discussed and decided that we want to decouple this work from #9237 and instead use [`cuda-pathfinder`](https://nvidia.github.io/cuda-python/cuda-pathfinder/latest/index.html) directly. I will drive this transition.
