### ISSUE TITLE
Fusing a function with min/max results in compilation error

### ISSUE THREAD

**Issue by keichi** [cupy/cupy#8040]
### Description

Fusing a function with min or max reduction fails with a runtime compilation error.

```
Traceback (most recent call last):
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 689, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 159, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 171, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 89, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cupy/_core/_reduction.pyx", line 863, in cupy._core._reduction.ReductionKernel._get_function
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_reduction.pyx", line 906, in cupy._core._reduction._ReductionKernel_get_cached_function
  File "cupy/_core/_reduction.pyx", line 125, in cupy._core._reduction._create_reduction_function_from_code
  File "cupy/_core/core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 574, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 322, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 306, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 708, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu(101): error: identifier "type_in0_raw" is undefined
          __device__ double _postmap_cast(min_max_st<type_in0_raw> a) {
                                                     ^

/tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu(117): error: identifier "type_in0_raw" is undefined
  typedef min_max_st<type_in0_raw> _type_reduce;
                     ^

2 errors detected in the compilation of "/tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu".

Exception ignored in: 'cupy._core._reduction._AbstractReductionKernel._launch'
Traceback (most recent call last):
  File "cupy/_core/_reduction.pyx", line 863, in cupy._core._reduction.ReductionKernel._get_function
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_reduction.pyx", line 906, in cupy._core._reduction._ReductionKernel_get_cached_function
  File "cupy/_core/_reduction.pyx", line 125, in cupy._core._reduction._create_reduction_function_from_code
  File "cupy/_core/core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 574, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 322, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 306, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 708, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu(101): error: identifier "type_in0_raw" is undefined
          __device__ double _postmap_cast(min_max_st<type_in0_raw> a) {
                                                     ^

/tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu(117): error: identifier "type_in0_raw" is undefined
  typedef min_max_st<type_in0_raw> _type_reduce;
                     ^

2 errors detected in the compilation of "/tmp/tmpo_0a8iip/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu".
```

### To Reproduce

```py
import cupy as cp

@cp.fuse
def foo(x):
    return cp.min(x)

foo(cp.zeros(10))
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
Python Version               : 3.10.13
CuPy Version                 : 12.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.2
SciPy Version                : 1.11.4
Cython Build Version         : 0.29.36
Cython Runtime Version       : 3.0.6
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : None
CUDA Build Version           : 12020
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12010
cuBLAS Version               : (available)
cuFFT Version                : 11002
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 1)
Thrust Version               : 200101
CUB Build Version            : 200101
Jitify Build Version         : <unknown>
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : 10700
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100 80GB PCIe
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:E1:00.0
```

### Additional Information

The generated kernel source code obtained using `CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1` looks like the following. As you can see `type_in0_raw` is not defined.

```
Name: /tmp/tmps0lscbzr/3eee2ea138ee98f6a1c04378682e4d4f19199624.cubin.cu
Options: -I/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/_core/include -I/home/gp.sc.cc.tohoku.ac.jp/keichi/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cupy/_core/include/cupy/_cuda/cuda-12 -I/usr/local/cuda/include -ftz=true --device-as-default-execution-space -arch=sm_80
CUDA source:
001 #include <cupy/complex.cuh>
002 #include <cupy/carray.cuh>
003 #include <cupy/atomics.cuh>
004 #include <cupy/math_constants.h>
005
006
007
008 template <typename T>
009 struct min_max_st{
010     T value;
011     int index;
012     __device__ min_max_st() : index(-1) { }
013     __device__ min_max_st(T v) : value(v), index(0) { }
014     __device__ min_max_st(T v, int i) : value(v), index(i) { }
015 };
016
017 template <typename T>
018 __device__ min_max_st<T> my_min(
019         const min_max_st<T>& a, const min_max_st<T>& b) {
020     if (a.index == -1) return b;
021     if (b.index == -1) return a;
022     return min_max_st<T>(min(a.value, b.value));
023 }
024 template <typename T>
025 __device__ min_max_st<T> my_min_float(
026         const min_max_st<T>& a, const min_max_st<T>& b) {
027     if (a.index == -1) return b;
028     if (b.index == -1) return a;
029     if (isnan(a.value)) return a;
030     if (isnan(b.value)) return b;
031     return min_max_st<T>(min(a.value, b.value));
032 }
033
034 template <typename T>
035 __device__ min_max_st<T> my_max(
036         const min_max_st<T>& a, const min_max_st<T>& b) {
037     if (a.index == -1) return b;
038     if (b.index == -1) return a;
039     return min_max_st<T>(max(a.value, b.value));
040 }
041 template <typename T>
042 __device__ min_max_st<T> my_max_float(
043         const min_max_st<T>& a, const min_max_st<T>& b) {
044     if (a.index == -1) return b;
045     if (b.index == -1) return a;
046     if (isnan(a.value)) return a;
047     if (isnan(b.value)) return b;
048     return min_max_st<T>(max(a.value, b.value));
049 }
050
051 template <typename T>
052 __device__ min_max_st<T> my_argmin(
053         const min_max_st<T>& a, const min_max_st<T>& b) {
054     if (a.index == -1) return b;
055     if (b.index == -1) return a;
056     if (a.value == b.value)
057         return min_max_st<T>(a.value, min(a.index, b.index));
058     return (a.value <= b.value) ? a : b;
059 }
060 template <typename T>
061 __device__ min_max_st<T> my_argmin_float(
062         const min_max_st<T>& a, const min_max_st<T>& b) {
063     if (a.index == -1) return b;
064     if (b.index == -1) return a;
065     if (a.value == b.value)
066         return min_max_st<T>(a.value, min(a.index, b.index));
067     if (isnan(a.value)) return a;
068     if (isnan(b.value)) return b;
069     return (a.value <= b.value) ? a : b;
070 }
071
072 template <typename T>
073 __device__ min_max_st<T> my_argmax(
074         const min_max_st<T>& a, const min_max_st<T>& b) {
075     if (a.index == -1) return b;
076     if (b.index == -1) return a;
077     if (a.value == b.value)
078         return min_max_st<T>(a.value, min(a.index, b.index));
079     return (a.value >= b.value) ? a : b;
080 }
081 template <typename T>
082 __device__ min_max_st<T> my_argmax_float(
083         const min_max_st<T>& a, const min_max_st<T>& b) {
084     if (a.index == -1) return b;
085     if (b.index == -1) return a;
086     if (a.value == b.value)
087         return min_max_st<T>(a.value, min(a.index, b.index));
088     if (isnan(a.value)) return a;
089     if (isnan(b.value)) return b;
090     return (a.value >= b.value) ? a : b;
091 }
092
093
094         __device__ double _pre_map(double v0) {
095         // 0 operations
096 ;
097         return v0;
098         }
099         typedef double type_out0_raw;
100
101         __device__ double _postmap_cast(min_max_st<type_in0_raw> a) {
102         double out0;
103         out0 = a.value;
104         return out0;
105         }
106
107         __device__ void _post_map(double in, double &v2) {
108         double v1 = in;
109         // 0 operations
110 v2 = v1;;
111         }
112
113 #define REDUCE(a, b) (my_min_float(a, b))
114 #define POST_MAP(a) (_post_map(_postmap_cast(a), v2))
115 #define _REDUCE(_offset) if (_tid < _offset) {   _type_reduce _a = _sdata[_tid], _b = _sdata[(_tid + _offset)];   _sdata[_tid] = REDUCE(_a, _b); }
116
117 typedef min_max_st<type_in0_raw> _type_reduce;
118 extern "C" __global__ void foo(const CArray<double, 1, 1, 1> _raw_v0, CArray<double, 0, 1, 1> _raw_v2, CIndexer<1, 1> _in_ind, CIndexer<0, 1> _out_ind, const int _block_stride) {
119   __shared__ char _sdata_raw[512 * sizeof(_type_reduce)];
120   _type_reduce *_sdata = reinterpret_cast<_type_reduce*>(_sdata_raw);
121   unsigned int _tid = threadIdx.x;
122
123   int _J_offset = _tid >> __popc(_block_stride - 1);  // _tid / _block_stride
124   ptrdiff_t _j_offset = (ptrdiff_t)_J_offset * _out_ind.size();
125   int _J_stride = 512 >> __popc(_block_stride - 1);
126   ptrdiff_t _j_stride = (ptrdiff_t)_J_stride * _out_ind.size();
127
128   for (ptrdiff_t _i_base = (ptrdiff_t)blockIdx.x * _block_stride;
129        _i_base < _out_ind.size();
130        _i_base += (ptrdiff_t)gridDim.x * _block_stride) {
131     _type_reduce _s = _type_reduce();
132     ptrdiff_t _i =
133         _i_base + (_tid & (_block_stride - 1));  // _tid % _block_stride
134     int _J = _J_offset;
135     for (ptrdiff_t _j = _i + _j_offset; _j < _in_ind.size();
136          _j += _j_stride, _J += _J_stride) {
137       _in_ind.set(_j);
138       const double v0 = _raw_v0[_in_ind.get()];
139       _type_reduce _a = static_cast<_type_reduce>(_pre_map(v0));
140       _s = REDUCE(_s, _a);
141     }
142     _sdata[_tid] = _s;
143     __syncthreads();
144     for (unsigned int _block = 512 / 2;
145          _block >= _block_stride; _block >>= 1) {
146       if (_tid < _block) {
147         _REDUCE(_block);
148       }
149       __syncthreads();
150     }
151     if (_tid < _block_stride) {
152       _s = _sdata[_tid];
153     }
154     if (_tid < _block_stride && _i < _out_ind.size()) {
155       _out_ind.set(static_cast<ptrdiff_t>(_i));
156       double &v2 = _raw_v2[_out_ind.get()];
157       POST_MAP(_s);
158     }
159   }
160 }
```

**Comment by codereport** [comment]
@keichi @asi1024  I just tested this in `cupy-cuda12x version13.3.0` and it works so I think this issue can be closed.

**Comment by keichi** [comment]
Yes, I just tested it too and it works now! Thanks.
