### ISSUE TITLE
from_dlpack on an object not implementing DLPack protocol throws irrelevant error message

### ISSUE THREAD

**Issue by pearu** [cupy/cupy#8070]
### Description

As in the title.

### To Reproduce

```py
>>> import cupy
>>> cupy.from_dlpack(object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/dlpack.pyx", line 344, in cupy._core.dlpack.from_dlpack
  File "cupy/_core/dlpack.pyx", line 378, in cupy._core.dlpack.from_dlpack
  File "cupy/_core/dlpack.pyx", line 268, in cupy._core.dlpack._dlpack_to_cupy_array
  File "cupy/_core/dlpack.pyx", line 174, in cupy._core.dlpack.DLPackMemory.__init__
ValueError: A DLPack tensor object cannot be consumed multiple times
```

An expected behavior would be an exception with a message "object does not appear to implement DLPack protocol" or similar.

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
>>> import cupy; cupy.show_config()
OS                           : Linux-5.4.0-153-generic-x86_64-with-glibc2.31
Python Version               : 3.11.7
CuPy Version                 : 12.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.2
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /tmp/arrayviews-tests/envs/arrayviews-tests_cupy-numba-cuda_19d0dab9
nvcc PATH                    : None
CUDA Build Version           : 11080
CUDA Driver Version          : 12010
CUDA Runtime Version         : 11080
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 101501
CUB Build Version            : 101501
Jitify Build Version         : 6fc36c7
cuDNN Build Version          : 8800
cuDNN Version                : 8907
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2060 SUPER
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:17:00.0
Device 1 Name                : NVIDIA GeForce RTX 2060 SUPER
Device 1 Compute Capability  : 75
Device 1 PCI Bus ID          : 0000:65:00.0
```

**Comment by pearu** [comment]
PyTorch from_dlpack throws the following error message:
```
RuntimeError: from_dlpack received an invalid capsule. Note that DLTensor capsules can be consumed only once, so you might have already constructed a tensor from it once.
```

**Comment by leofang** [comment]
Hold on. `cupy.from_dlpack(object())` is not a valid use case anyway, due to lack of `__dlpack_device__` and `__dlpack__`. We don't even need to use `PyCapsule_CheckExact`, just checking whether both attributes exist is enough, similar to what we did in mpi4py: https://github.com/mpi4py/mpi4py/blob/9eb98e11e069ada0eb665ff2a3701d52cb4e5384/src/mpi4py/MPI/asdlpack.pxi#L201-L205


@kmaehashi I think the `if` branch at line 375 is causing confusion and should just be removed? Now that we've updated instructions (#7988) and the new interface has been there for a few releases, I suggest we at least add a deprecation warning in v13 and remove it in v14.

**Comment by pearu** [comment]
I also agree that the branch at line 375 is the cause of the confusion: the lack of `__dlpack_device__` is  misinterpreted as the legacy interface where the object ought to be a capsule object while the object just does not support the dlpack interface.

To detect the legacy interface (if the plan is to support it for BC), one should check if the object is a capsule object.

To detect if the object supports the dlpack protocol, one should try to access `__dlpack__` or `__dlpack_device__` (or equivalently, call `hasattr` that implements the access operation). Btw, this is how numpy implements it.

**Comment by yanweiqin** [comment]
how to deal with this problem?

**Comment by pearu** [comment]
> how to deal with this problem?

As a first instance, `from_dlpack` should not be called on an object that does not implement DLPack protocol. This issue is about raising a better exception that would hint an user what is true cause of the failure.

What is your use case?
