### ISSUE TITLE
Hardcoded lib path in build script causes error

### ISSUE THREAD

**Issue by muslll** [cupy/cupy#8124]
### Description

Library path on setup_build is [hardcoded](https://github.com/cupy/cupy/blob/f215deeb7a2f3cfd046a3f3f80c59cfb4499f8b6/install/cupy_builder/cupy_setup_build.py#L263). Some systems, such as Debian, do not install nvidia libraries to /usr/lib64/ when installing `nvidia-cuda-dev` and `nvidia-cuda-toolkit` through apt:

```
$ find /usrt/ -name libcudart_static*
/usr/lib/x86_64-linux-gnu/libcudart_static.a
```

I solved this issue by doing a symlink:

```
ln -s /usr/lib/x86_64-linux-gnu/libcuda* /usr/lib64/
```

However, the correct solution for this issue would be to not hardcode paths or add conditions to it.

### To Reproduce

```
poetry add cupy
```
On Debian:
```
$ uname -a
Linux anon 6.6.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.9-1 (2024-01-01) x86_64 GNU/Linux
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-6.6.9-amd64-x86_64-with-glibc2.37
Python Version               : 3.11.7
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.3
SciPy Version                : 1.11.4
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr
nvcc PATH                    : /usr/bin/nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12000
CUDA Runtime Version         : 12020 (linked to CuPy) / 12000 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11001
cuRAND Version               : 10301
cuSOLVER Version             : (11, 4, 3)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 0)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1050
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:08:00.0
```

**Comment by leofang** [comment]
Just curious, was building against distro packages ever work for CuPy? i.e. did CuPy v12 and earlier work with this setup, but v13 does not?

**Comment by kmaehashi** [comment]
Maybe I should have let the linker find static libraries by specifying `-lcudart_static`, instead of discovering a file path on our own?

**Comment by leofang** [comment]
Not sure, would that work on Windows too?

**Comment by leofang** [comment]
My question is more about the distro package layout. If we have libs and headers scattered (e.g. `/usr/lib/x86_64-linux-gnu/`, `/usr/include`, ...) I suppose the old `CUDA_PATH` based logic never worked?

**Comment by leofang** [comment]
> Maybe I should have let the linker find static libraries by specifying `-lcudart_static`

I guess it'd work.

**Comment by kmaehashi** [comment]
@muslll, we've just merged the fix #8134. Could you try with the latest main branch?

@leofang

> My question is more about the distro package layout. If we have libs and headers scattered (e.g. `/usr/lib/x86_64-linux-gnu/`, `/usr/include`, ...) I suppose the old `CUDA_PATH` based logic never worked?

I guess these distro-default paths are on the compiler/linker search path by default?

**Comment by muslll** [comment]
Thanks @kmaehashi :+1:

**Comment by larsoner** [comment]
I am on Ubuntu 25.10 and latest `main` and get this error when using `apt`-based packages:

<details>
<summary>Traceback</summary>

```
$ pip install --no-build-isolation -ve .
Using pip 26.0.1 from /home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/pip (python 3.13)
Obtaining file:///home/larsoner/python/cupy
  Running command Checking if build backend supports build_editable
  Checking if build backend supports build_editable ... done
  Running command Preparing editable metadata (pyproject.toml)
  Generating CUPY_CACHE_KEY from header files...
  CUPY_CACHE_KEY (2006 files matching /home/larsoner/python/cupy/cupy/_core/include/**): bb0abd009e32cb3266dc9bbd435ee72bc24f9575

  -------- Configuring Module: cuda --------

  -------- Configuring Module: cusolver --------

  -------- Configuring Module: nccl --------

  -------- Configuring Module: nvtx --------

  -------- Configuring Module: cutensor --------
  /tmp/tmp7v9vfx2w/a.cpp:1:10: fatal error: cutensor.h: No such file or directory
      1 | #include <cutensor.h>
        |          ^~~~~~~~~~~~
  compilation terminated.
  command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

  -------- Configuring Module: cub --------

  -------- Configuring Module: jitify --------

  -------- Configuring Module: random --------

  -------- Configuring Module: thrust --------

  -------- Configuring Module: cusparselt --------
  /tmp/tmpf8bvknbi/a.cpp:1:10: fatal error: cusparseLt.h: No such file or directory
      1 | #include <cusparseLt.h>
        |          ^~~~~~~~~~~~~~
  compilation terminated.
  command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

  -------- Configuring Module: dlpack --------

  ************************************************************
  * CuPy Configuration Summary                               *
  ************************************************************

  Build Environment:
    Include directories: ['/home/larsoner/python/cupy/cupy/_core/include/cupy/_cccl/libcudacxx', '/home/larsoner/python/cupy/cupy/_core/include/cupy/_cccl/thrust', '/home/larsoner/python/cupy/cupy/_core/include/cupy/_cccl/cub', '/home/larsoner/python/cupy/cupy/_core/include', '/usr/include', '/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/numpy/_core/include']
    Library directories: ['/usr/lib64', '/usr/lib']
    nvcc command       : ['/usr/bin/nvcc']
    hipcc command      : (not found)

  Environment Variables:
    CFLAGS          : (none)
    LDFLAGS         : (none)
    LIBRARY_PATH    : (none)
    CUDA_PATH       : (none)
    NVCC            : (none)
    HIPCC           : (none)
    ROCM_HOME       : (none)

  Modules:
    cuda      : Yes (version 12040)
    cusolver  : Yes
    nccl      : Yes (version 22203)
    nvtx      : Yes
    cutensor  : No
      -> Include files not found: ['cutensor.h']
      -> Check your CFLAGS environment variable.
    cub       : Yes (version 300102)
    jitify    : Yes (version 1a0ca0e)
    random    : Yes
    thrust    : Yes (version 300102)
    cusparselt: No
      -> Include files not found: ['cusparseLt.h']
      -> Check your CFLAGS environment variable.
    dlpack    : Yes

  WARNING: Some modules could not be configured.
  CuPy will be installed without these modules.
  Please refer to the Installation Guide for details:
  https://docs.cupy.dev/en/stable/install.html

  ************************************************************

  Traceback (most recent call last):
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 209, in prepare_metadata_for_build_editable
      return hook(metadata_directory, config_settings)
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/setuptools/build_meta.py", line 478, in prepare_metadata_for_build_editable
      return self.prepare_metadata_for_build_wheel(
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
          metadata_directory, config_settings
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      )
      ^
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/setuptools/build_meta.py", line 374, in prepare_metadata_for_build_wheel
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "/home/larsoner/python/virtualenvs/base/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 56, in <module>
    File "/home/larsoner/python/cupy/install/cupy_builder/cupy_setup_build.py", line 560, in get_ext_modules
      extensions = make_extensions(ctx, compiler, use_cython)
    File "/home/larsoner/python/cupy/install/cupy_builder/cupy_setup_build.py", line 428, in make_extensions
      _find_static_library(name) for name in module.static_libraries
      ~~~~~~~~~~~~~~~~~~~~^^^^^^
    File "/home/larsoner/python/cupy/install/cupy_builder/cupy_setup_build.py", line 295, in _find_static_library
      raise Exception(f'Could not find {filename}: {path} does not exist')
  Exception: Could not find libcudart_static.a: /usr/lib/libcudart_static.a does not exist
  error: subprocess-exited-with-error
```

</details>

I then checked out [5d5ef64](https://github.com/cupy/cupy/commit/5d5ef648d1b1b3af4c969e2b7a47b0d63f8b57b0) (which closed this issue) and things were fine! So I suspected a regression. `git bisect start --first-parent` says there was a regression introduced by #7603. I tried reverting on `main` but it wasn't trivial to test due to multiple commits and newer changes to the affected files.
