### ISSUE TITLE
Incomplete type when compiling a `wmma::fragment` type with jitify

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8155]
I'm not sure whether this is an issue with CuPy, but I am running into another problem. It works when `jitify=False`. But as it is, I'm just getting an incomplete type error. Compiling just the kernel code for the following does work with NVCC even though the Intellisense is messed up when loaded in Visual Studio.

```py
import cupy as cp

kernel_code = r'''
#include <mma.h>
using namespace nvcuda;
extern "C" __global__ void mykernel() {
    wmma::fragment<wmma::accumulator, 16, 16, 8, float> v16;
    return ;
}
'''
module = cp.RawModule(code=kernel_code, backend='nvrtc', jitify=True, enable_cooperative_groups=True)
module.get_function('mykernel')((1,),(1,),())
```
```
PS D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests>  d:; cd 'd:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests'; & 'C:\Users\mrakg\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\mrakg\.vscode\extensions\ms-python.python-2023.22.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '53548' '--' 'D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py' 
---------------------------------------------------
--- JIT compile log for C:\Users\mrakg\AppData\Local\Temp\tmpu7gc6bb7\2983982998ae8febc0583032d61861b2579068a4.cubin.cu ---
---------------------------------------------------
C:\Users\mrakg\AppData\Local\Temp\tmpu7gc6bb7\2983982998ae8febc0583032d61861b2579068a4.cubin.cu(7): error: incomplete type is not allowed
      wmma::fragment<wmma::accumulator, 16, 16, 8, float> v16;
                                                          ^

1 error detected in the compilation of "C:\Users\mrakg\AppData\Local\Temp\tmpu7gc6bb7\2983982998ae8febc0583032d61861b2579068a4.cubin.cu".

---------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 250, in _jitify_prep
    name, options, headers, include_names = jitify.jitify(source, options)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\cuda\jitify.pyx", line 240, in cupy.cuda.jitify.jitify
  File "cupy\cuda\jitify.pyx", line 264, in cupy.cuda.jitify.jitify
RuntimeError: Runtime compilation failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\Marko\Source\Repos\The Spiral Language\Spiral Compilation Tests\cuda_experiments\tensor1\bug_mma.py", line 12, in <module>
    module.get_function('mykernel')((1,),(1,),())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\raw.pyx", line 487, in cupy._core.raw.RawModule.get_function
  File "cupy\_core\raw.pyx", line 100, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 117, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 538, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2236, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
                                      ^^^^^^^^^^^^^
  File "C:\Users\mrakg\AppData\Local\Programs\Python\Python311\Lib\site-packages\cupy\cuda\compiler.py", line 257, in _jitify_prep
    raise JitifyException(str(cex)) from e
cupy.cuda.compiler.JitifyException: Runtime compilation failed
```

_Originally posted by @mrakgr in https://github.com/cupy/cupy/issues/8146#issuecomment-1918986468_

**Comment by leofang** [comment]
This is a result of two quite subtle bugs compounded with the `mma.h` header internal detail! 

It turns out that when we call `_jitify_prep`, we didn't pass the `-arch` option to Jitify, so it tries to detect it for us ([here](https://github.com/NVIDIA/jitify/blob/1a0ca0e837405506f3b8f7883bacb71c20d86d96/jitify.hpp#L2893)). But because we're using Jitify 1 and it's been kinda outdated, on my machine [this logic](https://github.com/NVIDIA/jitify/blob/1a0ca0e837405506f3b8f7883bacb71c20d86d96/jitify.hpp#L2581) would pass `-arch=compute_75` to NVRTC. And because the wmma instructions don't support Turing and below, all types become undefined, leading to the incomplete type error.

@mrakgr If you make this change locally, your snippet should work:
```diff
diff --git a/cupy/cuda/compiler.py b/cupy/cuda/compiler.py
index 13b8f6af5..d3967302a 100644
--- a/cupy/cuda/compiler.py
+++ b/cupy/cuda/compiler.py
@@ -280,6 +280,12 @@ def compile_using_nvrtc(source, options=(), arch=None, filename='kern.cu',
     def _compile(
             source, options, cu_path, name_expressions, log_stream, jitify):
 
+        if not runtime.is_hip:
+            arch_opt, method = _get_arch_for_options_for_nvrtc(arch)
+            options += (arch_opt,)
+        else:
+            method = 'ptx'
+
         if jitify:
             options, headers, include_names = _jitify_prep(
                 source, options, cu_path)
@@ -291,12 +297,6 @@ def compile_using_nvrtc(source, options=(), arch=None, filename='kern.cu',
                 # tests cause an error if the following option is not included.
                 options += ('--device-as-default-execution-space',)
 
-        if not runtime.is_hip:
-            arch_opt, method = _get_arch_for_options_for_nvrtc(arch)
-            options += (arch_opt,)
-        else:
-            method = 'ptx'
-
         prog = _NVRTCProgram(source, cu_path, headers, include_names,
                              name_expressions=name_expressions, method=method)
         try:
```

On CuPy's side, we need to apply this patch to unconditionally add `-arch=...` to `options`, regardless if it's a prep call for Jitify or not.

On Jitify's side, they need to handle `-arch` better. Jitify 1 is certainly buggy, and I see that even with Jitify 2 there could be issues.
