### ISSUE TITLE
I installed the CuPy, but it still report that it hasn't be installed!

### ISSUE THREAD

**Issue by LumenScope** [cupy/cupy#8159]
### Description

I installed the CuPy, but it still report that it hasn't be installed!

### To Reproduce

```py
from functools import partial
import torch
import torch.nn as nn
import torch.nn.functional as F
from timm.models.layers import trunc_normal_
from timm.models.registry import register_model
from timm.models.vision_transformer import _cfg
from spikingjelly.clock_driven.neuron import (
    MultiStepLIFNode,
    MultiStepParametricLIFNode,
)
from sps import *
from ms_conv import *


class SpikeDrivenTransformer(nn.Module):
    def __init__(
        self,
        img_size_h=128,
        img_size_w=128,
        patch_size=16,
        in_channels=2,
        num_classes=11,
        embed_dims=512,
        num_heads=8,
        mlp_ratios=4,
        qkv_bias=False,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.0,
        norm_layer=nn.LayerNorm,
        depths=[6, 8, 6],
        sr_ratios=[8, 4, 2],
        T=4,
        pooling_stat="1111",
        attn_mode="direct_xor",
        spike_mode="lif",
        get_embed=False,
        dvs_mode=False,
        TET=False,
        cml=False,
        pretrained=False,
        pretrained_cfg=None,
    ):
        super().__init__()
        self.num_classes = num_classes
        self.depths = depths

        self.T = T
        self.TET = TET
        self.dvs = dvs_mode

        # dpr = [
        #     x.item() for x in torch.linspace(0, drop_path_rate, depths)
        # ]  # stochastic depth decay rule
        total_depth = sum(depths)  # 计算所有解码器层的深度总和
        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, total_depth)]

        patch_embed = MS_SPS(
            img_size_h=img_size_h,
            img_size_w=img_size_w,
            patch_size=patch_size,
            in_channels=in_channels,
            embed_dims=embed_dims,
            pooling_stat=pooling_stat,
            spike_mode=spike_mode,
        )

        blocks = nn.ModuleList(
            [
                MS_Block_Conv(
                    dim=embed_dims,
                    num_heads=num_heads,
                    mlp_ratio=mlp_ratios,
                    qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate,
                    attn_drop=attn_drop_rate,
                    drop_path=dpr[j],
                    norm_layer=norm_layer,
                    sr_ratio=sr_ratios,
                    attn_mode=attn_mode,
                    spike_mode=spike_mode,
                    dvs=dvs_mode,
                    layer=j,
                )
                for j in range(depths)
            ]
        )

        setattr(self, f"patch_embed", patch_embed)
        setattr(self, f"block", blocks)

        # classification head
        if spike_mode in ["lif", "alif", "blif"]:
            self.head_lif = MultiStepLIFNode(tau=2.0, detach_reset=True, backend="cupy")
        elif spike_mode == "plif":
            self.head_lif = MultiStepParametricLIFNode(
                init_tau=2.0, detach_reset=True, backend="cupy"
            )
        self.head = (
            nn.Linear(embed_dims, num_classes) if num_classes > 0 else nn.Identity()
        )
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Conv2d):
            trunc_normal_(m.weight, std=0.02)
            if m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.BatchNorm2d):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)

    def forward_features(self, x, hook=None):
        block = getattr(self, f"block")
        patch_embed = getattr(self, f"patch_embed")

        x, _, hook = patch_embed(x, hook=hook)
        for blk in block:
            x, _, hook = blk(x, hook=hook)

        x = x.flatten(3).mean(3)
        return x, hook

    def forward(self, x, hook=None):
        if len(x.shape) < 5:
            x = (x.unsqueeze(0)).repeat(self.T, 1, 1, 1, 1)
        else:
            x = x.transpose(0, 1).contiguous()

        x, hook = self.forward_features(x, hook=hook)
        x = self.head_lif(x)
        if hook is not None:
            hook["head_lif"] = x.detach()

        x = self.head(x)
        if not self.TET:
            x = x.mean(0)
        return x, hook


@register_model
def sdt(**kwargs):
    model = SpikeDrivenTransformer(
        **kwargs,
    )
    model.default_cfg = _cfg()
    return model

# 创建模型实例
model = SpikeDrivenTransformer()

# 打印模型
print(model)
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
(sllama2) (base) root@9c83119027b1:/home/SLLaMA# pip list
Package                Version
---------------------- ------------
accelerate             0.21.0
aiohttp                3.9.3
aiosignal              1.3.1
appdirs                1.4.4
async-timeout          4.0.3
attrs                  23.2.0
bitsandbytes           0.40.2
certifi                2024.2.2
charset-normalizer     3.3.2
click                  8.1.7
contourpy              1.1.1
cupy-cuda11x           12.3.0
cycler                 0.12.1
datasets               2.16.1
dill                   0.3.7
docker-pycreds         0.4.0
fastrlock              0.8.2
filelock               3.13.1
fonttools              4.47.2
frozenlist             1.4.1
fsspec                 2023.10.0
gitdb                  4.0.11
GitPython              3.1.41
huggingface-hub        0.20.3
idna                   3.6
importlib-resources    6.1.1
kiwisolver             1.4.5
matplotlib             3.7.4
multidict              6.0.5
multiprocess           0.70.15
numpy                  1.24.4
opencv-python          4.9.0.80
opencv-python-headless 4.9.0.80
packaging              23.2
pandas                 2.0.3
peft                   0.4.0
pillow                 10.2.0
pip                    24.0
protobuf               4.25.2
psutil                 5.9.8
pyarrow                15.0.0
pyarrow-hotfix         0.6
pyparsing              3.1.1
python-dateutil        2.8.2
pytz                   2024.1
PyYAML                 6.0.1
regex                  2023.12.25
requests               2.31.0
safetensors            0.4.2
scipy                  1.10.1
sentencepiece          0.1.99
sentry-sdk             1.40.0
setproctitle           1.3.3
setuptools             69.0.3
six                    1.16.0
smmap                  5.0.1
spikingjelly           0.0.0.0.12
timm                   0.6.12
tokenizers             0.13.3
torch                  1.13.1+cu117
torchaudio             0.13.1+cu117
torchinfo              1.8.0
torchvision            0.14.1+cu117
tqdm                   4.66.1
transformers           4.31.0
trl                    0.4.7
typing_extensions      4.9.0
tzdata                 2023.4
urllib3                2.2.0
wandb                  0.16.2
wheel                  0.41.2
xxhash                 3.4.1
yarl                   1.9.4
zipp                   3.17.0
```

### Additional Information

```
(sllama2) (base) root@9c83119027b1:/home/SLLaMA# /root/miniconda3/envs/sllama/bin/python /home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py
Traceback (most recent call last):
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py", line 153, in <module>
    model = SpikeDrivenTransformer()
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/spikeformer.py", line 60, in __init__
    patch_embed = MS_SPS(
  File "/home/SLLaMA/Spike-Driven-Transformer_原版/model/sps.py", line 38, in __init__
    self.proj_lif = MultiStepLIFNode(tau=2.0, detach_reset=True, backend="cupy")
  File "/root/miniconda3/envs/sllama/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron.py", line 823, in __init__
    check_backend(backend)
  File "/root/miniconda3/envs/sllama/lib/python3.8/site-packages/spikingjelly/clock_driven/neuron.py", line 30, in check_backend
    assert cupy is not None, 'CuPy is not installed! You can install it from "https://github.com/cupy/cupy".'
AssertionError: CuPy is not installed! You can install it from "https://github.com/cupy/cupy".
(sllama2) (base) root@9c83119027b1:/home/SLLaMA# pip list
Package                Version
---------------------- ------------
accelerate             0.21.0
aiohttp                3.9.3
aiosignal              1.3.1
appdirs                1.4.4
async-timeout          4.0.3
attrs                  23.2.0
bitsandbytes           0.40.2
certifi                2024.2.2
charset-normalizer     3.3.2
click                  8.1.7
contourpy              1.1.1
cupy-cuda11x           12.3.0
cycler                 0.12.1
datasets               2.16.1
dill                   0.3.7
docker-pycreds         0.4.0
fastrlock              0.8.2
filelock               3.13.1
fonttools              4.47.2
frozenlist             1.4.1
fsspec                 2023.10.0
gitdb                  4.0.11
GitPython              3.1.41
huggingface-hub        0.20.3
idna                   3.6
importlib-resources    6.1.1
kiwisolver             1.4.5
matplotlib             3.7.4
multidict              6.0.5
multiprocess           0.70.15
numpy                  1.24.4
opencv-python          4.9.0.80
opencv-python-headless 4.9.0.80
packaging              23.2
pandas                 2.0.3
peft                   0.4.0
pillow                 10.2.0
pip                    24.0
protobuf               4.25.2
psutil                 5.9.8
pyarrow                15.0.0
pyarrow-hotfix         0.6
pyparsing              3.1.1
python-dateutil        2.8.2
pytz                   2024.1
PyYAML                 6.0.1
regex                  2023.12.25
requests               2.31.0
safetensors            0.4.2
scipy                  1.10.1
sentencepiece          0.1.99
sentry-sdk             1.40.0
setproctitle           1.3.3
setuptools             69.0.3
six                    1.16.0
smmap                  5.0.1
spikingjelly           0.0.0.0.12
timm                   0.6.12
tokenizers             0.13.3
torch                  1.13.1+cu117
torchaudio             0.13.1+cu117
torchinfo              1.8.0
torchvision            0.14.1+cu117
tqdm                   4.66.1
transformers           4.31.0
trl                    0.4.7
typing_extensions      4.9.0
tzdata                 2023.4
urllib3                2.2.0
wandb                  0.16.2
wheel                  0.41.2
xxhash                 3.4.1
yarl                   1.9.4
zipp                   3.17.0
```

**Comment by LumenScope** [comment]
> Looks like you are running the code in the `sllama` venv but installing cupy in the `sllama2` venv

None of this bussiness, the conda environmets nees xformer

**Comment by LumenScope** [comment]
> Looks like you are running the code in the `sllama` venv but installing cupy in the `sllama2` venv

My mistake , It's  tensorboardX

**Comment by Kiwiwiki** [comment]
Met the same problem. You solved it?

**Comment by kmaehashi** [comment]
Closing as inactive, feel free to open another case if you still need help.
