### ISSUE TITLE
Seemingly redundant malloc in broadcasted `matmul` causing OoM

### ISSUE THREAD

**Issue by tianrluo** [cupy/cupy#8193]
### Description

Hi devs

I was using `cupy.matmul` and got out-of-memory errors when using generic ubuntu.

The same code strangely works on ubuntu WSL2, with a GPU that has the same amount of memory.

Also, although on WSL2 that both `matmul` calls would work, the 2nd way (`ab_bad = cp.matmul(a_bad, b_bad)`) is a lot slower than the 1st way (`ab_ok = cp.matmul(a_ok, b_ok)`).
I guess the time different might makes sense for they were possibly executed differently, but on the other hand the two ways are essentially doing the same thing here...

thank you for looking into this!

the error message i got
```
Traceback (most recent call last):
  File "/home/tmp.py", line 18, in <module>
    ab_bad = cp.matmul(a_bad, b_bad)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/lib/python3.11/site-packages/cupy/_core/_gufuncs.py", line 683, in __call__
    self._apply_func_to_inputs(
  File "/home/conda/lib/python3.11/site-packages/cupy/_core/_gufuncs.py", line 397, in _apply_func_to_inputs
    func(*args, out=outs)
  File "cupy/_core/_routines_linalg.pyx", line 809, in cupy._core._routines_linalg.matmul
  File "cupy/_core/_routines_linalg.pyx", line 891, in cupy._core._routines_linalg.matmul
  File "cupy/_core/core.pyx", line 2731, in cupy._core.core.ascontiguousarray
  File "cupy/_core/core.pyx", line 132, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 220, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File"cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 5,440,000,000 bytes (allocated so far: 2,315,200,512 bytes).
```

### To Reproduce
(please play with `s0, s1, s2, s3` if your setup has a lot of memory, my configs are quite limited to 4GB of VRAM)
```py
import cupy as cp

s0, s1, s2, s3 = 500, 80, 3400, 5
dtype = cp.complex64

# ok
a_ok = cp.ones((s0, s1, s2), dtype=dtype)
b_ok = cp.ones((s0, s2, s3), dtype=dtype)

ab_ok = cp.matmul(a_ok, b_ok)

print(f'{a_ok.shape, b_ok.shape, ab_ok.shape}')

# fail
a_bad = cp.ones((s0, 1, s3, s2), dtype=dtype)
b_bad = cp.ones((s0, s1, s2, 1), dtype=dtype)

ab_bad = cp.matmul(a_bad, b_bad)

print(f'{a_bad.shape, b_bad.shape, ab_bad.shape}')
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

ubuntu, failed, generic
```
OS                           : Linux-5.15.0-67-generic-x86_64-with-glibc2.35
Python Version               : 3.11.5
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.3
SciPy Version                : None
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12000
CUDA Driver Version          : 12030
CUDA Runtime Version         : 12000 (linked to CuPy) / 12030 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11012
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200001
CUB Build Version            : 200200
Jitify Build Version         : c08b8c6
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 1050 Ti
Device 0 Compute Capability  : 61
Device 0 PCI Bus ID          : 0000:01:00.0
```

ubuntu, works, WSL2
```
OS                           : Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Python Version               : 3.9.16
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.23.5
SciPy Version                : 1.10.0
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12030
CUDA Runtime Version         : 11080 (linked to CuPy) / 11080 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro T2000 with Max-Q Design
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by takagi** [comment]
Seems that the shape `(500, 1, 5, 3400)` is reshaped here to `(500, 80, 5, 3400)` then ascontiguousarray is called. I wonder why it runs on WSL2 machine without the same OoM.

**Comment by tianrluo** [comment]
The behavior on WSL2 was also quite strange.

I tried follow the error message stack and set a breakpoint in `cupy._core._gufuncs`. (I use vscode for breakpoint)
WSL2 will also hit the out-of-memory error if the breakpoint in `cupy` is active,
and if I deactivate the breakpoint, the code works again (in WSL2).

**Comment by leofang** [comment]
This is not just same system running two different OSs, but two different systems with different drivers, CUDA Toolkits, and even GPUs. I am not sure what's the point of comparison?

**Comment by tianrluo** [comment]
Ah, sry i wasn't aware of that.
I tried different cuda and driver versions on generic ubuntu and they are failed.
(Combinations of: OS 18.04, 22.04; cuda 11.8, 12.1, 12.3; drivers 520, 530, 545)

Essentially i was hoping `ab_bad = cp.matmul(a_bad, b_bad)` would also work on generic Ubuntu.
The command worked on WSL2 ubuntu, so I thought maybe something could be done.

**Comment by tianrluo** [comment]
To me, the main issue here is the somewhat ridiculous memory footprint of `cupy.matmul` in cases where unnecessary mallocates could have been avoided if the axes of operands were ordered properly.

Here's a helper function covers up the issue with some automatic `transpose` and `reshape`.
(Probably not bug-free).
I guess such array-massaging should ideally be inside `matmul` or somewhere else in `cupy`, but I lack the expertise to directly patch for it...
```py
import cupy as cp


def matmul_helper(
    a: cp.ndarray,
    b: cp.ndarray,
) -> cp.ndarray:
    ## preprocessing
    orig_a_shape, orig_b_shape = a.shape, b.shape
    length = a.shape[-1]

    # match ndim
    ndim_diff = a.ndim - b.ndim
    ndim = max(a.ndim, b.ndim)

    if ndim_diff > 0:
        b = b.reshape(ndim_diff*(1,)+b.shape)
    elif ndim_diff < 0:
        a = a.reshape(-ndim_diff*(1,)+a.shape)

    a_shape, b_shape = a.shape, b.shape

    # broadcastable?
    broadcastable = all(
        ((sa == sb) or sa == 1 or sb == 1) for (sa, sb) in
        zip(a_shape[:-2], b_shape[:-2])
    )
    if (not broadcastable) or (a_shape[-1] != b_shape[-2]):
        raise ValueError(f'Imcompatible shapes: {orig_a_shape, orig_b_shape}')

    # transpose
    dims_shared = tuple(_ for _ in range(ndim-2) if a_shape[_] == b_shape[_])
    dims_matmul = tuple(_ for _ in range(ndim-2) if a_shape[_] != b_shape[_])
    ndim_shared = len(dims_shared)
    ndim_matmul = len(dims_matmul)

    old2new_axes_order = dims_shared + dims_matmul + (ndim-2, ndim-1)
    new2old_axes_order = tuple(
        i[0] for i in sorted(enumerate(old2new_axes_order), key=lambda x:x[1])
    )  # `cupy.argsort` can't handle `tuple` input

    a = a.transpose(old2new_axes_order)
    b = b.transpose(dims_shared + (ndim-2,) + dims_matmul + (ndim-1,))

    shared_shape = a.shape[:ndim_shared]
    a_unique_shape = a.shape[ndim_shared:-1]
    b_unique_shape = b.shape[ndim_shared+1:]

    ab = cp.matmul(
        a.reshape(shared_shape + (-1, length)),
        b.reshape(shared_shape + (length, -1)),
    ).reshape(shared_shape + a_unique_shape + b_unique_shape)

    # Move all size-1 dim to the end, notice that either `_a == 1` or `_b == 1`
    # for `(_a, _b) in zip(a_unique_shape[:-1], b_unique_shape[:-1])`.
    choose_a = tuple(
        _a > _b for (_a, _b) in zip(a_unique_shape[:-1], b_unique_shape[:-1])
    )

    offset_a = ndim_shared
    offset_b = offset_a + ndim_matmul + 1
    ndim_ab = ab.ndim

    a_range = range(offset_a, offset_a + ndim_matmul + 1)
    b_range = range(offset_b, offset_b + ndim_matmul + 1)

    shared_axes = tuple(range(ndim_shared))
    axes_left = tuple(
        _a if _ else _b for (_, _a, _b) in zip(choose_a, a_range, b_range)
    )
    axes_right = tuple(
        _b if _ else _a for (_, _a, _b) in zip(choose_a, a_range, b_range)
    )
    ab_axes = shared_axes + axes_left + (offset_b-1, ndim_ab-1) + axes_right

    ab = ab.transpose(ab_axes).squeeze(axis=tuple(range(offset_b+1, ndim_ab)))

    ab = ab.transpose(new2old_axes_order)
    return ab


if __name__ == '__main__':
    s0, s1, s2, s3 = 2, 3, 5, 4
    a = cp.random.rand(s0, 1, s3, s2)
    b = cp.random.rand(s0, s1, s2, 1)

    ab_ref = cp.matmul(a, b)
    ab = matmul_helper(a, b)
    print(f'a, b, ab_ref, ab: {a.shape, b.shape, ab_ref.shape, ab.shape}')
    print(f'(ab - ab_ref).(max, min): {(ab-ab_ref).max(), (ab-ab_ref).min()}')

```

**Comment by tianrluo** [comment]
Closing this.
Latest cupy `14.2.0` seems to have removed the unnecessary allocations in `matmul`.
It might have been fixed in some earlier version, but I haven't kept testing it, and don't know which version it exactly was.

**Comment by tianrluo** [comment]
sry, i said that too soon, it was not fully fixed...
the seemingly redundant malloc is still there when i try broadcasted matrix multiplication `(s0, s1, 1, s2, s3) × (s0, 1, s4, s3, 1)` calling `matmul`, throwing OoM.
(in my test, `s0, s1, s2, s3, s4 = 259, 76, 94, 36, 24`)

edit:
this was embarrassing, but i should have double checked my codes.
there was a type-promotion in my usages that i didn't notice, and have triggered the malloc.

thx to you folks in cupy community fixing the issue.
