### ISSUE TITLE
Error when calling shares_memory

### ISSUE THREAD

**Issue by NaderAlAwar** [cupy/cupy#8249]
### Description

Calling `shares_memory()` on two cupy arrays results in a JIT related error, similar to the one in #8171:

```
---------------------------------------------------
--- JIT compile log for cupy_jitify_exercise ---
---------------------------------------------------
cub/util_cpp_dialect.cuh(143): warning #161-D: unrecognized #pragma
       CUB_COMPILER_DEPRECATION_SOFT(C++14, C++11);
       ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

cooperative_groups/details/helpers.h(454): error: identifier "cudaCGGetIntrinsicHandle" is undefined
              return (cudaCGGetIntrinsicHandle(cudaCGScopeMultiGrid));
                      ^

cooperative_groups/details/helpers.h(459): error: identifier "cudaCGSynchronize" is undefined
              cudaError_t err = cudaCGSynchronize(handle, 0);
                                ^

cooperative_groups/details/helpers.h(465): error: identifier "cudaCGGetSize" is undefined
              cudaCGGetSize(&numThreads, NULL, handle);
              ^

cooperative_groups/details/helpers.h(472): error: identifier "cudaCGGetRank" is undefined
              cudaCGGetRank(&threadRank, NULL, handle);
              ^

cooperative_groups/details/helpers.h(479): error: identifier "cudaCGGetRank" is undefined
              cudaCGGetRank(NULL, &gridRank, handle);
              ^

cooperative_groups/details/helpers.h(486): error: identifier "cudaCGGetSize" is undefined
              cudaCGGetSize(NULL, &numGrids, handle);
              ^

6 errors detected in the compilation of "cupy_jitify_exercise".

---------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PATH_TO_CUPY/cupy/_misc/memory_ranges.py", line 42, in shares_memory
    return bool((x != y).any())
                ^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 1173, in cupy._core.core._ndarray_base.any
  File "cupy/_core/core.pyx", line 1175, in cupy._core.core._ndarray_base.any
  File "cupy/_core/_routines_logic.pyx", line 12, in cupy._core._routines_logic._ndarray_any
  File "cupy/_core/_reduction.pyx", line 618, in cupy._core._reduction._SimpleReductionKernel.__call__
  File "cupy/_core/_reduction.pyx", line 370, in cupy._core._reduction._AbstractReductionKernel._call
  File "cupy/_core/_cub_reduction.pyx", line 689, in cupy._core._cub_reduction._try_to_call_cub_reduction
  File "cupy/_core/_cub_reduction.pyx", line 526, in cupy._core._cub_reduction._launch_cub
  File "cupy/_core/_cub_reduction.pyx", line 461, in cupy._core._cub_reduction._cub_two_pass_launch
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_cub_reduction.pyx", line 240, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function
  File "cupy/_core/_cub_reduction.pyx", line 223, in cupy._core._cub_reduction._create_cub_reduction_function
  File "cupy/_core/core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "PATH_TO_CUPY/cupy/cuda/compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH_TO_CUPY/cupy/cuda/compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "PATH_TO_CUPY/cupy/cuda/compiler.py", line 319, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH_TO_CUPY/cupy/cuda/compiler.py", line 284, in _compile
    options, headers, include_names = _jitify_prep(
                                      ^^^^^^^^^^^^^
  File "PATH_TO_CUPY/cupy/cuda/compiler.py", line 233, in _jitify_prep
    jitify._init_module()
  File "cupy/cuda/jitify.pyx", line 212, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 233, in cupy.cuda.jitify._init_module
  File "cupy/cuda/jitify.pyx", line 209, in cupy.cuda.jitify._init_cupy_headers
  File "cupy/cuda/jitify.pyx", line 192, in cupy.cuda.jitify._init_cupy_headers_from_scratch
  File "cupy/cuda/jitify.pyx", line 264, in cupy.cuda.jitify.jitify
RuntimeError: Runtime compilation failed
```

### To Reproduce

```py
import cupy as cp

a = cp.zeros((5,))
b = cp.zeros((5,))
print(cp.shares_memory(a, b))
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
OS                           : Linux-4.18.0-372.26.1.el8_6.x86_64-x86_64-with-glibc2.28
Python Version               : 3.11.8
CuPy Version                 : 13.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.11.4
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /opt/apps/cuda/12.0
nvcc PATH                    : /opt/apps/cuda/12.0/bin/nvcc
CUDA Build Version           : 12000
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12000 (linked to CuPy) / 12000 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11200
cuRAND Version               : 10305
cuSOLVER Version             : (11, 6, 0)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 4)
Thrust Version               : 200001
CUB Build Version            : 200200
Jitify Build Version         : c08b8c6
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA A100-PCIE-40GB
Device 0 Compute Capability  : 80
Device 0 PCI Bus ID          : 0000:06:00.0
```

**Comment by leofang** [comment]
Hey Nader! I was never able to reproduce this error, could you try setting the env var `CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1`, rerun your reproducer, and share the full output?

**Comment by NaderAlAwar** [comment]
I tried setting `CUPY_DUMP_CUDA_SOURCE_ON_ERROR` but it seems that the output is the same? I'm not seeing any CUDA sources.

**Comment by leofang** [comment]
Hmmm... How did you install CuPy?

**Comment by NaderAlAwar** [comment]
It was a while ago, I think it was just `conda install -c conda-forge cupy`

**Comment by leofang** [comment]
```
NVRTC Version                : (12, 4)
```
This just caught my attention, as I was assuming you are using CUDA 12.0? If you installed CuPy from conda-forge (I am not sure), could you share the output of `conda list`?

**Comment by NaderAlAwar** [comment]
This is `conda list`:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
blas                      1.0                    openblas  
bzip2                     1.0.8                h5eee18b_5  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.3.11            h06a4308_0  
cmake                     3.26.4               h96355d8_0  
cuda-nvrtc                12.4.99              hd3aeb46_0    conda-forge
cuda-version              12.4                 h3060b56_3    conda-forge
cupy                      13.0.0          py311h8a5e998_3    conda-forge
cupy-core                 13.0.0          py311h84cfafc_3    conda-forge
distro                    1.8.0           py311h06a4308_0  
expat                     2.5.0                h6a678d5_0  
fastrlock                 0.8.2           py311hb755f60_2    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46306  
krb5                      1.20.1               h143b758_1  
ld_impl_linux-64          2.38                 h1181459_1  
libcublas                 12.4.2.65            hd3aeb46_0    conda-forge
libcufft                  11.2.0.44            hd3aeb46_0    conda-forge
libcurand                 10.3.5.119           hd3aeb46_0    conda-forge
libcurl                   8.5.0                h251f7ec_0  
libcusolver               11.6.0.99            hd3aeb46_0    conda-forge
libcusparse               12.3.0.142           hd3aeb46_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   13.2.0               h807b86a_5    conda-forge
libllvm14                 14.0.6               hdb19cb5_3  
libnghttp2                1.57.0               h2d74bed_0  
libnvjitlink              12.4.99              hd3aeb46_0    conda-forge
libopenblas               0.3.21               h043d6bf_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libuuid                   1.41.5               h5eee18b_0  
libuv                     1.44.2               h5eee18b_0  
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               18.1.1               h4dfa4b3_0    conda-forge
llvmlite                  0.42.0          py311h6a678d5_0  
lz4-c                     1.9.4                h6a678d5_0  
make                      4.2.1                h1bed415_1  
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mkl-service               2.4.0           py311h5eee18b_1  
mkl_fft                   1.3.8           py311hf18274c_1    conda-forge
mkl_random                1.2.5           py311hc1a02e1_1    conda-forge
ncurses                   6.4                  h6a678d5_0  
numba                     0.59.0          py311h96b013e_1    conda-forge
numpy                     1.26.4          py311h24aa872_0  
numpy-base                1.26.4          py311hbfb1bba_0  
openssl                   3.2.1                hd590300_0    conda-forge
packaging                 23.1            py311h06a4308_0  
patchelf                  0.17.2               h58526e2_0    conda-forge
pip                       23.3.1          py311h06a4308_0  
pybind11                  2.11.1          py311h9547e67_2    conda-forge
pybind11-global           2.11.1          py311h9547e67_2    conda-forge
pykokkos-base             0.0.7                    pypi_0    pypi
python                    3.11.8               h955ad1f_0  
python_abi                3.11                    2_cp311    conda-forge
readline                  8.2                  h5eee18b_0  
rhash                     1.4.3                hdbd6064_0  
scikit-build              0.15.0          py311h6a678d5_0  
scipy                     1.11.4          py311h24aa872_0  
setuptools                68.2.2          py311h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
tbb                       2021.8.0             hdb19cb5_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2024a                h04d1e81_0  
wheel                     0.41.2          py311h06a4308_0  
xz                        5.4.6                h5eee18b_0  
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hc292b87_0  
```

**Comment by leofang** [comment]
@NaderAlAwar any chance you can try the following?
- If you have set `CUDA_PATH` env var, unset it
- If you have `nvcc` in your `PATH`, remove it
- Retry the reproducer

The first two steps can be confirmed this way: The following two lines should become `None`:
```
CUDA Root                    : /opt/apps/cuda/12.0
nvcc PATH                    : /opt/apps/cuda/12.0/bin/nvcc
```

**Comment by NaderAlAwar** [comment]
That seems to fix it, I'm not getting that error anymore

**Comment by leofang** [comment]
Nice, thanks for confirming. 

I am 90% sure we're running into a compiler issue here. Starting CUDA 12.3 NVRTC bundles some CUDA headers and this is a result of version conflicts (between the runtime env, in this case CCCL headers vendored in CuPy, and the compiler, in this case the cooperative group headers). Since CuPy does not yet have 12.3/12.4 CI/CD (#7950, cc: @kmaehashi), this issue was not caught in testing.

The reason I couldn't reproduce it was because I developed locally with CUDA 12.2, and based on this runtime check
https://github.com/cupy/cupy/blob/028889eef3ba110829d677726348aa0f75aadb4e/cupy/_core/_cub_reduction.pyx#L338-L341
I did have `nvcc` in my `PATH` and I'd already trigger the Jitify path, but because I had compatible versions, everything worked. As soon as I switch to a local CUDA 12.3+ env, I can reproduce.

Known workarounds (either should work):
1. Do not set `CUDA_PATH` & do not add `nvcc` location to `PATH` (as you already checked)
   - This would avoid triggering the Jitify path in your reproducer, but might still run into issues elsewhere
2. Downgrade local CTK to CUDA 12.0-12.2
   - This would ensure Jiitfy to work fine

I'll need to discuss a proper fix plan with internal folks.

**Comment by leofang** [comment]
(fixed/expanded the workarounds listed above)

**Comment by leofang** [comment]
Pure C reproducer:
```C++
// compile this code with
//
//   nvcc -std=c++11 test_nvrtc_bug.cu -lnvrtc -o test_nvrtc_bug
//
// and just run it: ./test_nvrtc_bug. Note that libnvrtc should be in LD_LIBRARY_PATH.

#include <iostream>
#include <nvrtc.h>


const char code[] = "                                 \n \
#include <cooperative_groups.h>                       \n \
#include <cooperative_groups/memcpy_async.h>          \n \
                                                      \n \
extern \"C\" __global__ void jitify_exercise() { }";


int main() {
    nvrtcProgram prog;
    nvrtcCreateProgram(&prog,         // prog
                       code,          // buffer
                       "debug.cu",    // name
                       0,             // numHeaders
                       NULL,          // headers
                       NULL);         // includeNames
    const char *opts[] = {
        "--std=c++11",
        "-I/usr/local/cuda-12.0.0/include",
        "-arch=sm_89",
    };

    nvrtcResult compileResult = nvrtcCompileProgram(prog,  // prog
                                                    3,     // numOptions
                                                    opts); // options

    // Obtain compilation log from the program.
    size_t logSize;
    (nvrtcGetProgramLogSize(prog, &logSize));
    char *log = new char[logSize];
    (nvrtcGetProgramLog(prog, log));
    if (logSize > 1)
        std::cout << log << '\n';
    delete[] log;
    if (compileResult != NVRTC_SUCCESS) {
       exit(1);
    } else {
       std::cout << "ok!" << std::endl;
    }

    return 0;
}
```
Output with NVRTC from CUDA 12.0:
```
ok!
```
Output with NVRTC from CUDA 12.3:
```
/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(453): error: identifier "cudaCGGetIntrinsicHandle" is undefined
              return (cudaCGGetIntrinsicHandle(cudaCGScopeMultiGrid));
                      ^

/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(458): error: identifier "cudaCGSynchronize" is undefined
              cudaError_t err = cudaCGSynchronize(handle, 0);
                                ^

/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(464): error: identifier "cudaCGGetSize" is undefined
              cudaCGGetSize(&numThreads, NULL, handle);
              ^

/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(471): error: identifier "cudaCGGetRank" is undefined
              cudaCGGetRank(&threadRank, NULL, handle);
              ^

/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(478): error: identifier "cudaCGGetRank" is undefined
              cudaCGGetRank(NULL, &gridRank, handle);
              ^

/usr/local/cuda-12.0.0/include/cooperative_groups/details/helpers.h(485): error: identifier "cudaCGGetSize" is undefined
              cudaCGGetSize(NULL, &numGrids, handle);
              ^

6 errors detected in the compilation of "debug.cu".
```
