### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by AlgoOy** [cupy/cupy#8251]
### Description

I installed cupy using conda install cupy, and then found that Cuda ToolKit needs to be installed. After configuring the environment variables, the following problem still exists. The reason is that numpy no longer has bool attributes. It seems that no one has encountered the same problem as me. I am curious, does cupy have requirements for the numpy version?

```
C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\_index.py:22: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
Traceback (most recent call last):
  File "xxx\main.py", line 1, in <module>
    import dezero
  File "xxx\__init__.py", line 13, in <module>
    from dezero.core import Variable
  File "xxx\core.py", line 6, in <module>
    import cupy as cp
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupy\__init__.py", line 46, in <module>
    import cupyx as _cupyx
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\__init__.py", line 8, in <module>
    from cupyx import linalg  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\__init__.py", line 2, in <module>
    from cupyx.linalg import sparse  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\sparse\__init__.py", line 3, in <module>
    from cupyx.linalg.sparse._solve import lschol  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\sparse\_solve.py", line 7, in <module>
    from cupyx.scipy import sparse
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.base import spmatrix as _spmatrix
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.coo import coo_matrix  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\coo.py", line 12, in <module>
    from cupyx.scipy.sparse import csc
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\csc.py", line 11, in <module>
    from cupyx.scipy.sparse import compressed
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\compressed.py", line 22, in <module>
    from cupyx.scipy.sparse import _index
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\_index.py", line 22, in <module>
    _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Process finished with exit code 1
```

### To Reproduce

```py
# Write the code here
```

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
# Paste the output here
C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\_index.py:22: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupy\__init__.py", line 46, in <module>
    import cupyx as _cupyx
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\__init__.py", line 8, in <module>
    from cupyx import linalg  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\__init__.py", line 2, in <module>
    from cupyx.linalg import sparse  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\sparse\__init__.py", line 3, in <module>
    from cupyx.linalg.sparse._solve import lschol  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\linalg\sparse\_solve.py", line 7, in <module>
    from cupyx.scipy import sparse
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.base import spmatrix as _spmatrix
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\__init__.py", line 4, in <module>
    from cupyx.scipy.sparse.coo import coo_matrix  # NOQA
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\coo.py", line 12, in <module>
    from cupyx.scipy.sparse import csc
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\csc.py", line 11, in <module>
    from cupyx.scipy.sparse import compressed
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\compressed.py", line 22, in <module>
    from cupyx.scipy.sparse import _index
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\cupyx\scipy\sparse\_index.py", line 22, in <module>
    _bool_scalar_types = (bool, numpy.bool, numpy.bool_)
  File "C:\Users\xxx\miniconda3\envs\dlf\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by AlgoOy** [comment]
In fact, when I modify this part of the code as follows, it can run normally. I wonder if I need to submit a PR?
https://github.com/cupy/cupy/blob/028889eef3ba110829d677726348aa0f75aadb4e/cupyx/scipy/sparse/_index.py#L22

`_bool_scalar_types = (bool, numpy.bool_)`

**Comment by takagi** [comment]
Would you paste the result of `python -c "import cupy; cupy.show_config()`? I guess you're using older cupy and updating it may resolve the issue.

**Comment by kmaehashi** [comment]
I guess you are installing outdated CuPy packages from [anaconda](https://anaconda.org/anaconda/cupy) channel. Currently CuPy's releases are published through conda-forge. Please see https://github.com/cupy/cupy?tab=readme-ov-file#conda.
