### ISSUE TITLE
matmul does not validate if arguments are on the current GPU

### ISSUE THREAD

**Issue by kmaehashi** [cupy/cupy#828]
Code:

```py
import cupy as cp

with cp.cuda.Device(0):
    x = cp.arange(1, dtype=cp.float32)

with cp.cuda.Device(2):
    print(x @ x)
```

What I get:

```
Traceback (most recent call last):
  File "matmul.py", line 7, in <module>
    print(x @ x)
  File "cupy/core/core.pyx", line 1658, in cupy.core.core.ndarray.__str__
    return str(self.get())
  File "cupy/core/core.pyx", line 1705, in cupy.core.core.ndarray.get
    a_gpu.data.copy_to_host(ptr, a_gpu.nbytes)
  File "cupy/cuda/memory.pyx", line 345, in cupy.cuda.memory.MemoryPointer.copy_to_host
    runtime.memcpy(mem.value, self.ptr, size,
  File "cupy/cuda/runtime.pyx", line 257, in cupy.cuda.runtime.memcpy
    check_status(status)
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
    raise CUDARuntimeError(status)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorIllegalAddress: an illegal memory access was encountered
```

What I expect:

```
ValueError: Array device must be same as the current device: array device = 0 while current = 2
```

**Comment by kmaehashi** [comment]
Merged to #1389
