### ISSUE TITLE
cupy do not suport two axis operation?

### ISSUE THREAD

**Issue by leslielee619** [cupy/cupy#8342]
### Description

A is a $m\times n\times n$ tensor     
when i run `np.all(np.isnan(A), axis=(1, 2))` or `cp.all(cp.isnan(A), axis=1)`, there has no error.
but when i run `A1 = cp.all(cp.isnan(A), axis=1); A2 = cp.all(cp.isnan(A1), axis=1)` or `A2 = cp.all(cp.isnan(A), axis=(1,2))`, the error happens.

i add cl.exe `D:\Software\VS2019IDE\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64` to windows system path, but it still doesnt work.

### To Reproduce

```py
D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py:103: UserWarning: Failed to auto-detect cl.exe path: <class 'distutils.errors.DistutilsPlatformError'>: No Microsoft Visual C++ version found
  warnings.warn(f'Failed to auto-detect cl.exe path: {type(e)}: {e}')
Traceback (most recent call last):
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 64, in _run_cc
    log = subprocess.check_output(cmd, cwd=cwd, env=env,
  File "D:\Software\Python3.9_20231208\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\Software\Python3.9_20231208\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['D:\\Software\\CUDA12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_50,code=sm_50', '--ptx', '--std=c++11', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-ID:\\Software\\CUDA12.3\\include', '-ftz=true', 'C:\\Users\\14682\\AppData\\Local\\Temp\\tmp8mzyyiow\\preprocess.cu']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 366, in compile_using_nvcc
    _run_cc(cmd, root_dir, 'nvcc', log_stream)
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 80, in _run_cc
    raise NVCCException(msg)
cupy.cuda.compiler.NVCCException: `nvcc` command returns non-zero exit status. 
command: ['D:\\Software\\CUDA12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_50,code=sm_50', '--ptx', '--std=c++11', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-ID:\\Software\\CUDA12.3\\include', '-ftz=true', 'C:\\Users\\14682\\AppData\\Local\\Temp\\tmp8mzyyiow\\preprocess.cu']
return-code: 1
stdout/stderr: 
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xxx", line 49, in <module>
    vivek(detector_num_y, detector_num_z,
  File "xxx", line 537, in xxx
    t2 = cp.all(t1, axis=1)
  File "D:\CTRec_Cupy\lib\site-packages\cupy\_logic\truth.py", line 50, in all
    return a.all(axis=axis, out=out, keepdims=keepdims)
  File "cupy\_core\core.pyx", line 1169, in cupy._core.core._ndarray_base.all
  File "cupy\_core\core.pyx", line 1171, in cupy._core.core._ndarray_base.all
  File "cupy\_core\_routines_logic.pyx", line 8, in cupy._core._routines_logic._ndarray_all
  File "cupy\_core\_reduction.pyx", line 608, in cupy._core._reduction._SimpleReductionKernel.__call__
  File "cupy\_core\_reduction.pyx", line 364, in cupy._core._reduction._AbstractReductionKernel._call
  File "cupy\_core\_cub_reduction.pyx", line 701, in cupy._core._cub_reduction._try_to_call_cub_reduction
  File "cupy\_core\_cub_reduction.pyx", line 552, in cupy._core._cub_reduction._launch_cub
  File "cupy\_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy\_core\_cub_reduction.pyx", line 246, in cupy._core._cub_reduction._SimpleCubReductionKernel_get_cached_function
  File "cupy\_core\_cub_reduction.pyx", line 231, in cupy._core._cub_reduction._create_cub_reduction_function
  File "cupy\_core\core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 539, in _compile_with_cache_cuda
    base = _preprocess('', options, arch, backend)
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 434, in _preprocess
    result = compile_using_nvcc(source, options, arch, 'preprocess.cu',
  File "D:\CTRec_Cupy\lib\site-packages\cupy\cuda\compiler.py", line 376, in compile_using_nvcc
    raise cex
cupy.cuda.compiler.CompileException: `nvcc` command returns non-zero exit status. 
command: ['D:\\Software\\CUDA12.3\\bin\\nvcc.EXE', '-gencode=arch=compute_50,code=sm_50', '--ptx', '--std=c++11', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include', '-ID:\\CTRec_Cupy\\lib\\site-packages\\cupy\\_core\\include\\cupy\\_cuda\\cuda-12', '-ID:\\Software\\CUDA12.3\\include', '-ftz=true', 'C:\\Users\\14682\\AppData\\Local\\Temp\\tmp8mzyyiow\\preprocess.cu']
return-code: 1
stdout/stderr: 
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
```

### Installation

Source (`pip install cupy`)

### Environment

```
nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:51:05_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```

```
python -c "import cupy; cupy.show_config()"

OS                           : Windows-10-10.0.19045-SP0        
Python Version               : 3.9.10                           
CuPy Version                 : 12.3.0                           
CuPy Platform                : NVIDIA CUDA                      
NumPy Version                : 1.26.2                           
SciPy Version                : 1.11.4                           
Cython Build Version         : 0.29.36                          
Cython Runtime Version       : None                             
CUDA Root                    : D:\Software\CUDA12.3             
nvcc PATH                    : D:\Software\CUDA12.3\bin\nvcc.EXE
CUDA Build Version           : 12020                            
CUDA Driver Version          : 12030                            
CUDA Runtime Version         : 12030                            
cuBLAS Version               : (available)                      
cuFFT Version                : 11012                            
cuRAND Version               : 10304
cuSOLVER Version             : (11, 5, 4)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 3)
Thrust Version               : 200101
CUB Build Version            : 200101
Jitify Build Version         : 4a37de0
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce GTX 950M
Device 0 Compute Capability  : 50
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by leslielee619** [comment]
okay, my bad, i add cl.exe to system path, and restart pycharm, then it works.
but i confused why this will happen? and i use cupy and numba.cuda well before.

**Comment by leofang** [comment]
Hmmm @kmaehashi has MSVC been a run-time requirement on Windows?

**Comment by kmaehashi** [comment]
> Hmmm @kmaehashi has MSVC been a run-time requirement on Windows?

It's no longer the case in CuPy v13 (#7869). The author looks using CuPy v12:

> CuPy Version                 : 12.3.0                           

It's unclear why cl.exe detection failed, though.

**Comment by leofang** [comment]
> The author looks using CuPy v12:
> 
> > CuPy Version                 : 12.3.0

Good catch! @leslielee619 plz try to update your CuPy version to v13 and see if you still hit issues.
