### ISSUE TITLE
ndimage.distance_transform_edt does not accept cupy arrays for indices

### ISSUE THREAD

**Issue by ev-br** [cupy/cupy#8397]
### Description

`cupyx.scipy.ndimage.distance_transform_edt` accepts numpy arrays as indices; For a cupy array it raises

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/ev-br/.conda/envs/scipy-dev/lib/python3.11/site-packages/cupyx/scipy/ndimage/_pba_2d.py(257)_check_indices()
-> raise RuntimeError("indices array has wrong shape")
(Pdb) u
> /home/ev-br/.conda/envs/scipy-dev/lib/python3.11/site-packages/cupyx/scipy/ndimage/_pba_2d.py(497)_pba_2d()
-> _check_indices(indices, (arr.ndim,) + arr.shape, x.dtype.itemsize)
```

### To Reproduce

```py
# Write the code here
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

This works:

```
(Pdb) from cupyx.scipy import ndimage as cx_ndimage
(Pdb) data
array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)
(Pdb) ft = np.indices(data.shape, dtype=np.int32)
(Pdb) cx_ndimage.distance_transform_edt(data, return_distances=False, return_indices=True, indices=ft)
array([[[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 1, 1, 2, 2, 2],
        [3, 3, 3, 2, 1, 2, 2, 3, 3],
        [4, 4, 4, 4, 6, 4, 4, 4, 4],
        [5, 5, 5, 6, 7, 6, 6, 5, 5],
        [6, 6, 6, 6, 7, 7, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 2, 4, 5, 6, 7, 8],
        [0, 1, 1, 2, 4, 6, 6, 7, 8],
        [0, 1, 1, 1, 2, 7, 7, 7, 8],
        [0, 1, 1, 2, 4, 6, 6, 7, 8],
        [0, 1, 2, 2, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]]], dtype=int16)
```

Wrapping `np.indices` into a cupy arrays raises:

```
(Pdb) cx_ndimage.distance_transform_edt(data, return_distances=False, return_indices=True, indices=cupy.asarray(ft))
*** RuntimeError: indices array has wrong shape
```

**Comment by takagi** [comment]
Thanks, let me have its stack trace for record.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mtakagi/cupy/cupyx/scipy/ndimage/_distance_transform.py", line 161, in distance_transform_edt
    vals = pba_func(
  File "/home/mtakagi/cupy/cupyx/scipy/ndimage/_pba_2d.py", line 497, in _pba_2d
    _check_indices(indices, (arr.ndim,) + arr.shape, x.dtype.itemsize)
  File "/home/mtakagi/cupy/cupyx/scipy/ndimage/_pba_2d.py", line 257, in _check_indices
    raise RuntimeError("indices array has wrong shape")
```
