### ISSUE TITLE
cupyx.scipy.signal.upfirdn failing on 2D inputs

### ISSUE THREAD

**Issue by bmerry** [cupy/cupy#8448]
### Description

Using cupyx.scipy.signal.upfirdn is failing CUDADriverError for some combinations of parameters when the input signal is 2D. It seems to depend on both the types and the up/down factors.

### To Reproduce

```py
#!/usr/bin/env python3

import cupy as cp
import cupyx.scipy.signal
import numpy as np
import scipy.signal

h = np.zeros(101, np.float32)
x = np.zeros((8, 500), np.complex64)
print(scipy.signal.upfirdn(h, x, 3, 2))

h = cp.asarray(h)
x = cp.asarray(x)
cupyx.scipy.signal.upfirdn(h, x, 3, 2)
```

Output:
```
/home/bmerry/.pyenv/versions/env/lib/python3.12/site-packages/cupyx/jit/_interface.py:173: FutureWarning: cupyx.jit.rawkernel is experimental. The interface can change in the future.
  cupy._util.experimental('cupyx.jit.rawkernel')
[[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]
Traceback (most recent call last):
  File "/home/bmerry/work/bugs/cupy-upfirdn/./upfirdn2d.py", line 14, in <module>
    cupyx.scipy.signal.upfirdn(h, x, 3, 2)
  File "/home/bmerry/.pyenv/versions/env/lib/python3.12/site-packages/cupyx/scipy/signal/_upfirdn.py", line 500, in upfirdn
    return ufd.apply_filter(x, axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bmerry/.pyenv/versions/env/lib/python3.12/site-packages/cupyx/scipy/signal/_upfirdn.py", line 417, in apply_filter
    kernel(threadsperblock, blockspergrid,
  File "cupy/_core/raw.pyx", line 93, in cupy._core.raw.RawKernel.__call__
  File "cupy/cuda/function.pyx", line 223, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 205, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 273, in cupy_backends.cuda.api.driver.launchKernel
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-6.8.0-39-generic-x86_64-with-glibc2.39
Python Version               : 3.12.3
CuPy Version                 : 13.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.14.0
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12050
CUDA Driver Version          : 12050
CUDA Runtime Version         : 12050 (linked to CuPy) / 12050 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 11203
cuRAND Version               : 10306
cuSOLVER Version             : (11, 6, 3)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 5)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4070 Laptop GPU
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by leofang** [comment]
cc: @ev-br for vis
