### ISSUE TITLE
When use rocm6.0 ,can not import cupy  

### ISSUE THREAD

**Issue by tianlinliang** [cupy/cupy#8589]
### Description

I try to install  the cupy-rocm 5.0 and i check it in my conda environments .but i can not imporrt this . i try to removr it and reinstall the cupy-rocm 5.0 but it still not work for me . i want to replenishment that   is i use rocm 6.0 and my python is 3.9.18 .

### To Reproduce

i can not import cupy , even when i try make a new environment for testing import Cupy using "python -c "import cupy; cupy.show_config()" it still can not work . 

### Installation

Wheel (`pip install cupy-***`)

### Environment

 python -c "import cupy; print(cupy.__version__)"
Traceback (most recent call last):
  File "/home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy/__init__.py", line 16, in <module>
    from cupy import _core  # NOQA
  File "/home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy/cuda/__init__.py", line 9, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 1, in init cupy.cuda.device
ImportError: /home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy_backends/cuda/api/runtime.cpython-39-x86_64-linux-gnu.so: undefined symbol: _Z23hipDestroySurfaceObjecty, version hip_4.2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yang/miniconda3/envs/test/lib/python3.9/site-packages/cupy/__init__.py", line 18, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

**Comment by tianlinliang** [comment]
> ROCm 6 支持目前正在进行中#8319.
Thank you for your support very much! but i try to use you give me the sulution , it still have another problem  likes follows, and i haved try to find my libroctx64.so , the file is exist in my rocm folders ：find /opt/rocm/ -name "libroctx64.so"
/opt/rocm/lib/libroctx64.so
-------- Configuring Module: cuda --------
/home/yang/miniconda3/compiler_compat/ld: cannot find -lroctx64: 没有那个文件或目录
collect2: error: ld returned 1 exit status
Cannot build a stub file.
Original error: command '/usr/bin/g++' failed with exit code 1
-------------------------------------------------------------------
can you have something  idea for this? it is important to me ,thanks!

**Comment by tianlinliang** [comment]
> ROCm 6 support is currently ongoing at #8319.
Thank you for your support very much! but i try to use you give me the sulution , it still have another problem  likes follows, and i haved try to find my libroctx64.so , the file is exist in my rocm folders ：find /opt/rocm/ -name "libroctx64.so"
/opt/rocm/lib/libroctx64.so
-------- Configuring Module: cuda --------
/home/yang/miniconda3/compiler_compat/ld: cannot find -lroctx64: 没有那个文件或目录
collect2: error: ld returned 1 exit status
Cannot build a stub file.
Original error: command '/usr/bin/g++' failed with exit code 1

if you have any idea for this problem.please tell me ,it is important for me ,Thank you very much!
