### ISSUE TITLE
cupy multiprocessing issue

### ISSUE THREAD

**Issue by tori-hotaru** [cupy/cupy#8592]
### Description

I try to use torch.multiprocessing to accelerate my model code. In previous conda enviroment, I successfully run my code with multiprocessing. However, when I create a new conda enviroment which is same as my previous enviroment and run my code. It reports error.
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 692, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 125, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 138, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 53, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/model.py", line 77, in _process_image
    return self.nsctDec(image)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/model.py", line 108, in nsctDec
    [Insp, Insct] = myNSCTd(x, self.levels, self.pfilt, self.dfilt, self.type)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/nsct_gpu.py", line 23, in myNSCTd
    [dh1, dh2] = dfilters(dfiltername, 'd')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/nsct_gpu.py", line 96, in dfilters
    [h0, h1] = ld2quin(beta)
               ^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/nsct_gpu.py", line 125, in ld2quin
    h1 = -1 * convolve2d(h,h0)
              ^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupyx/scipy/signal/_signaltools.py", line 352, in convolve2d
    return _correlate2d(in1, in2, mode, boundary, fillvalue, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupyx/scipy/signal/_signaltools.py", line 418, in _correlate2d
    return _st_core._direct_correlate(in1, in2, mode, in1.dtype, convolution,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupyx/scipy/signal/_signaltools_core.py", line 88, in _direct_correlate
    kernel(in1, in2, output)
  File "cupy/_core/_kernel.pyx", line 920, in cupy._core._kernel.ElementwiseKernel.__call__
  File "cupy/_core/_kernel.pyx", line 945, in cupy._core._kernel.ElementwiseKernel._get_elementwise_kernel
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/_kernel.pyx", line 728, in cupy._core._kernel._get_elementwise_kernel
  File "cupy/_core/_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
  File "cupy/_core/core.pyx", line 2283, in cupy._core.core.compile_with_cache
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 498, in _compile_module_with_cache
    return _compile_with_cache_cuda(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 577, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 333, in compile_using_nvrtc
    return _compile(source, options, cu_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 317, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/cupy/cuda/compiler.py", line 711, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /usr/local/cuda/include/cuda_bf16.hpp(575): error: no instance of overloaded function "__half::__half" matches the specified type

1 error detected in the compilation of "/tmp/tmpl3hmrvp9/f6dea56492c78b04104c6cfdcaed0f5ffd616a0b.cubin.cu".

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shizhe/New_project/nsct_github/model.py", line 454, in <module>
    output = model(input)
             ^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/model.py", line 373, in forward
    x1_1 = block(x1_1)
           ^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/model.py", line 143, in forward
    x_trans = self.CT(x2)
              ^^^^^^^^^^^
  File "/home/shizhe/New_project/nsct_github/model.py", line 67, in CT
    transformed_list = pool.starmap(self._process_image, [(image[b, c].detach(),) for b in range(B) for c in range(C)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shizhe/anaconda3/envs/openmmlab/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
cupy.cuda.compiler.CompileException: /usr/local/cuda/include/cuda_bf16.hpp(575): error: no instance of overloaded function "__half::__half" matches the specified type

1 error detected in the compilation of "/tmp/tmpl3hmrvp9/f6dea56492c78b04104c6cfdcaed0f5ffd616a0b.cubin.cu".
```

### To Reproduce

```py
import torch.multiprocessing as mp
import cupy as cp

mp.set_start_method('spawn', force=True)
......
with mp.Pool(processes=mp.cpu_count()) as pool:
       transformed_list = pool.starmap(self._process_image, [(image[b, c].detach(),) for b in range(B) for c in range(C)])
      # the _process_image function is written by cupy 
......
```

### Installation

Source (`pip install cupy`)

### Environment

```
OS                           : Linux-5.15.0-118-generic-x86_64-with-glibc2.35
Python Version               : 3.11.9
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.3
SciPy Version                : None
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12020
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12020 (linked to CuPy) / 12000 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : (available)
cuFFT Version                : 11001
cuRAND Version               : 10301
cuSOLVER Version             : (11, 4, 3)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 0)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA RTX 6000 Ada Generation
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : NVIDIA RTX 6000 Ada Generation
Device 1 Compute Capability  : 89
Device 1 PCI Bus ID          : 0000:51:00.0
```

### Additional Information

Actually, when I run my code on another linux systerm, the code run perfectly. 
Also when I fully copy my previous conda enviroment(copy everything), the error didn't exist. 
I think this issue maybe connect with other CUDA library(Maybe like cudnn?).

**Comment by kmaehashi** [comment]
> ### Installation
> Source (`pip install cupy`)

```
CUDA Runtime Version         : 12020 (linked to CuPy) / 12000 (locally installed)
```

It seems you are building CuPy with CUDA 12.2 but your CUDA environment is CUDA 12.0. If you don't have a specific reasons to build from source, could you try removing the source installation and use conda-forge distribution instead? https://github.com/cupy/cupy?tab=readme-ov-file#conda

**Comment by kmaehashi** [comment]
Closing as inactive. Feel free to reopen in case you still need help.
