### ISSUE TITLE
cupy fails to locate `vector_types.h` on Debian 6.1

### ISSUE THREAD

**Issue by dagardner-nv** [cupy/cupy#8654]
I believe the issue is that `platform.processor()` returns an empty string on some systems (https://docs.python.org/3.10/library/platform.html#platform.processor), and as such on my machine in a Conda env the `cupy._environment._get_include_dir_from_conda_or_wheel` method returns an invalid path:
```
>>> from cupy import _environment
>>> _environment._get_include_dir_from_conda_or_wheel(12, 5)
['/home/dagardner/work/conda/envs/morpheus/targets/-linux/include', '/home/dagardner/work/conda/envs/morpheus/include']
```

One possible work-around would be to call `platform.machine()` on systems that return an empty string:
```
>>> import platform
>>> platform.processor()
''
>>> platform.machine()
'x86_64'
```

Repro:
```
import cupy as cp
cp.array(cp.zeros((1,)))
```

Error:
```
Traceback (most recent call last):
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 692, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 125, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 138, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 53, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/_creation/from_data.py", line 53, in array
    return _core.array(obj, dtype, copy, order, subok, ndmin, blocking)
  File "cupy/_core/core.pyx", line 2408, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2418, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2449, in cupy._core.core._array_from_cupy_ndarray
  File "cupy/_core/core.pyx", line 518, in cupy._core.core._ndarray_base.astype
  File "cupy/_core/core.pyx", line 586, in cupy._core.core._ndarray_base.astype
  File "cupy/_core/_kernel.pyx", line 1375, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 1402, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 1082, in cupy._core._kernel._get_ufunc_kernel
  File "cupy/_core/_kernel.pyx", line 94, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy/_core/_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
  File "cupy/_core/core.pyx", line 2283, in cupy._core.core.compile_with_cache
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 498, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 577, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 333, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 317, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 711, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /home/dagardner/work/conda/envs/morpheus/lib/python3.10/site-packages/cupy/_core/include/cupy/_cuda/cuda-12.5/cuda_fp16.h(129): catastrophic error: cannot open source file "vector_types.h"
  #include "vector_types.h"
                           ^

1 catastrophic error detected in the compilation of "/tmp/tmpraot9sgg/462dc71896a6e18044ab9cb305c270d49e3e4e90.cubin.cu".
Compilation terminated.
```

**Comment by leofang** [comment]
Interesting, thanks for reporting! Would you be able to submit a patch based on what you found?

cc @jakirkham for vis

**Comment by dagardner-nv** [comment]
@leofang sure https://github.com/cupy/cupy/pull/8655

**Comment by jakirkham** [comment]
Think this is already fixed with PR ( https://github.com/cupy/cupy/pull/8519 ). We are just waiting on the backport PR ( https://github.com/cupy/cupy/pull/8652 )
