### ISSUE TITLE
The argpartition function has a small difference in behaviour between NumPy and CuPy

### ISSUE THREAD

**Issue by dbolser** [cupy/cupy#8659]
### Description

Not sure if this behaviour is expected... I'm trying to use `np.argpartition` interchangeably with `cp.argpartition` and I'm hitting a minor issue.

```txt
test_cupy.py
Traceback (most recent call last):
  File "/home/danbolser/Work/nomaly-post-stuff/test_cupy.py", line 202, in <module>
    demo_bug()
  File "/home/danbolser/Work/nomaly-post-stuff/test_cupy.py", line 197, in demo_bug
    _ = cp.argpartition(random_data_cp, kth=tcp, axis=1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/danbolser/Work/nomaly-post-stuff/.venv/lib/python3.12/site-packages/cupy/_sorting/sort.py", line 217, in argpartition
    return a.argpartition(kth, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 917, in cupy._core.core._ndarray_base.argpartition
  File "cupy/_core/core.pyx", line 936, in cupy._core.core._ndarray_base.argpartition
  File "cupy/_core/_routines_sorting.pyx", line 246, in cupy._core._routines_sorting._ndarray_argpartition
TypeError: 'ndarray' object cannot be interpreted as an integer
```

### To Reproduce

```py

def demo_bug():

    xsize = 1000  # Samples
    ysize = 2000  # Conditions

    # Generate random case / control data for testing (real data goes here)
    mnp = np.random.rand(ysize, xsize) < 0.01
    mcp = cp.random.rand(ysize, xsize) < 0.01

    tnp = mnp.sum(axis=1)  # Number of 'affected' samples for each condition
    tcp = mcp.sum(axis=1)

    # tcp = tnp  # Mitigation!

    # Trying to use random data to efficiently get permutations of the case /
    # control status via argpartition (probably stupid, but vectorized!)
    random_data_np = np.random.rand(ysize, xsize).astype(np.float32)
    random_data_cp = cp.random.rand(ysize, xsize).astype(cp.float32)

    # Get the indexes of the kth smallest values in each row
    _ = np.argpartition(random_data_np, kth=tnp, axis=1)
    _ = cp.argpartition(random_data_cp, kth=tcp, axis=1)

    # Would proceed to get a mask for looking up the permutation statistic...
    pass
```

### Installation

None

### Environment

```
OS                           : Linux-6.8.0-45-generic-x86_64-with-glibc2.39
Python Version               : 3.12.3
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.1
SciPy Version                : 1.14.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : None
nvcc PATH                    : None
CUDA Build Version           : 12060
CUDA Driver Version          : 12020
CUDA Runtime Version         : 12060 (linked to CuPy) / 12000 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : (available)
cuFFT Version                : 11001
cuRAND Version               : 10301
cuSOLVER Version             : (11, 4, 3)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 0)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : (not loaded; try `import cupy.cuda.cudnn` first)
cuDNN Version                : (not loaded; try `import cupy.cuda.cudnn` first)
NCCL Build Version           : (not loaded; try `import cupy.cuda.nccl` first)
NCCL Runtime Version         : (not loaded; try `import cupy.cuda.nccl` first)
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : Quadro K620
Device 0 Compute Capability  : 50
Device 0 PCI Bus ID          : 0000:B4:00.0
```

### Additional Information

I think my 'mitigation' is also slowing things down a lot.

**Comment by kmaehashi** [comment]
Thanks for the feedback. Currently this behavior is as intended. `kth` must be a sequence on CPU, not `cupy.ndarray, because we need to raise exception for out-of-bounds index, like NumPy does. https://github.com/cupy/cupy/blob/678add80cdd82e89f2b751f1722035c53997ad03/cupy/_core/_routines_sorting.pyx#L153-L154

**Comment by dbolser** [comment]
Does that mean that my current fix, `tcp = tnp  # Mitigation!` is the correct way to handle the situation?

In reality I'm calling argpartition to avoid argsort, but under the hood cp.argpartition *is* actually sorting 😅, which is probably why I thought it was slower due to me passing in a numpy array instead of keeping it all cupy.

**Comment by kmaehashi** [comment]
`tcp = tnp` or `tcp = tcp.get()` (convert CuPy ndarray to NumPy) are both valid mitigation in your case. In general keeping everything on GPU (cupy.ndarray) performs better, as you suggested. I agree this behavior is not intuitive for users, so may possibly be changed in the future. I've cross-linked this issue at https://github.com/cupy/cupy/issues/4831#issuecomment-896990298.
