### ISSUE TITLE
`rint` not following numpy API

### ISSUE THREAD

**Issue by fedemengo** [cupy/cupy#8672]
### Description

`numpy.rint` returns either a ndarray or scalar from: https://numpy.org/doc/stable/reference/generated/numpy.rint.html#numpy.rint
but cupy returns a `cupy.ndarray`, is this expected?

```shell
> python test.py
<class 'numpy.int64'>
<class 'cupy.ndarray'>
[1647 8534 1848 ... 3270 1723  957]
Traceback (most recent call last):
  File "/home/fedemengo/workspace/test/test.py", line 16, in <module>
    xp_ii = xp.random.choice(xp_a, size, replace=False)
  File "/home/fedemengo/workspace/test/venv/lib/python3.10/site-packages/cupy/random/_sample.py", line 190, in choice
    return rs.choice(a, size, replace, p)
  File "/home/fedemengo/workspace/test/venv/lib/python3.10/site-packages/cupy/random/_generator.py", line 1091, in choice
    raise NotImplementedError
NotImplementedError
```

### To Reproduce

```py
> cat test.py
import numpy as np
import cupy as xp

a = 9128
size = 8256

nn_a = np.rint(a).astype(int)
xp_a = xp.rint(a).astype(int)

print(type(nn_a))
print(type(xp_a))

np_ii = np.random.choice(nn_a, size, replace=False)
print(np_ii)

xp_ii = xp.random.choice(xp_a, size, replace=False)
print(xp_ii)
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
> python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.15.0-122-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.2
SciPy Version                : None
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12060 (linked to CuPy) / 12060 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : (available)
cuFFT Version                : 11300
cuRAND Version               : 10307
cuSOLVER Version             : (11, 7, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 6)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4090
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:0B:00.0
```

**Comment by kmaehashi** [comment]
This is as expected. CuPy returns scalar values as 0-dim ndarray to avoid the overhead of GPU-to-CPU transfer.

**Comment by fedemengo** [comment]
got it, thanks
