### ISSUE TITLE
Confusing `nccl` import

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8710]
### Description

When I execute:

```
from cupy.cuda import nccl
print(nccl)
```

I get:

```
<module 'cupy.cuda.nccl' from '/home/ceti/miniconda3/envs/inference-servers/lib/python3.12/site-packages/cupy/cuda/nccl.py'>
```

When I do:

```
import cupy
print(cupy.cuda.nccl)
```

I get:

```
Traceback (most recent call last):
  File "/home/ceti/inference-servers/nccl/init.py", line 5, in <module>
    print(cupy.cuda.nccl)
          ^^^^^^^^^^^^^^
  File "/home/ceti/miniconda3/envs/inference-servers/lib/python3.12/site-packages/cupy/cuda/__init__.py", line 84, in __getattr__
    raise AttributeError(
AttributeError: module 'cupy.cuda' has no attribute 'nccl'
```

This really tripped me up, I was under the impression that the `nccl` library wasn't installed the whole time. Hell, one of the chatbots gave me the following code to check whether `nccl` is available and it's completely wrong:

```
import cupy as cp

# Check if NCCL is available
try:
    nccl = cp.cuda.nccl
    print("NCCL is enabled in CuPy.")
except AttributeError:
    print("NCCL is not enabled in CuPy.")
```

I thought the two imports were supposed to be the same in Python, but I guess they aren't.

### Installation

Conda-Forge (`conda install ...`)

### Environment

(inference-servers) ceti@ceti16:~$ python -c "import cupy; cupy.show_config()"
OS                           : Linux-5.15.0-124-generic-x86_64-with-glibc2.35
Python Version               : 3.12.7
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.2
SciPy Version                : 1.14.1
Cython Build Version         : 0.29.37
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-12.6
nvcc PATH                    : /usr/local/cuda-12.6/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12060
CUDA Runtime Version         : 12060 (linked to CuPy) / 12060 (locally installed)
CUDA Extra Include Dirs      : ['/home/ceti/miniconda3/envs/inference-servers/targets/x86_64-linux/include', '/home/ceti/miniconda3/envs/inference-servers/include']
cuBLAS Version               : (available)
cuFFT Version                : 11300
cuRAND Version               : 10307
cuSOLVER Version             : (11, 7, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (12, 6)
Thrust Version               : 200500
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 22304
NCCL Runtime Version         : 22304
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA H100 80GB HBM3
Device 0 Compute Capability  : 90
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : NVIDIA H100 80GB HBM3
Device 1 Compute Capability  : 90
Device 1 PCI Bus ID          : 0000:2A:00.0
Device 2 Name                : NVIDIA H100 80GB HBM3
Device 2 Compute Capability  : 90
Device 2 PCI Bus ID          : 0000:3A:00.0
Device 3 Name                : NVIDIA H100 80GB HBM3
Device 3 Compute Capability  : 90
Device 3 PCI Bus ID          : 0000:5D:00.0
Device 4 Name                : NVIDIA H100 80GB HBM3
Device 4 Compute Capability  : 90
Device 4 PCI Bus ID          : 0000:84:00.0
Device 5 Name                : NVIDIA H100 80GB HBM3
Device 5 Compute Capability  : 90
Device 5 PCI Bus ID          : 0000:8B:00.0
Device 6 Name                : NVIDIA H100 80GB HBM3
Device 6 Compute Capability  : 90
Device 6 PCI Bus ID          : 0000:91:00.0
Device 7 Name                : NVIDIA H100 80GB HBM3
Device 7 Compute Capability  : 90
Device 7 PCI Bus ID          : 0000:E4:00.0

**Comment by mrakgr** [comment]
```python
import cupy
import cupy.cuda.nccl
print(cupy.cuda.nccl)
```

I figured out that due to them being separate packages, I'd need to import them separately, and once I did that it fixed the issue. I guess the misunderstanding was on my end.
