### ISSUE TITLE
cupyx.scipy.signal.resample_poly fails for 2D arrays

### ISSUE THREAD

**Issue by naperman** [cupy/cupy#8716]
### Description

For 2D input arrays, `cupyx.scipy.signal.resample_poly` works for small upsampling rates (see Example 1), but fails for large upsampling rates( see Example 2).

### To Reproduce

```py
# Example 1 (works)
import cupy as cp
from cupyx.scipy.signal import resample, resample_poly

x = cp.linspace(0, 10, 32, endpoint=False)
z = cp.cos(-x**2/6.0) + 1j*cp.sin(-x**2/6.0)
y = cp.concatenate((z[cp.newaxis,...], z[cp.newaxis,...]))
print(f"y.shape = {y.shape}")

f_fft = resample(y, 96, axis=1)
f_poly = resample_poly(y, 3, 1, axis=1)
xnew = cp.linspace(0, 10, 96, endpoint=False)

plt.plot(cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_fft[0,:])), 'b.-', cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_poly[0,:])), 'r.-')
plt.plot(cp.asnumpy(x), cp.asnumpy(cp.squeeze(y[0,:])), 'ko-')
plt.plot(10, cp.asnumpy(y[0,0]), 'bo', 10, 0., 'ro')  # boundaries
plt.legend(['resample', 'resamp_poly', 'data'], loc='best')
plt.grid(True)
plt.show()

plt.plot(cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_fft[1,:])), 'b.-', cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_poly[1,:])), 'r.-')
plt.plot(cp.asnumpy(x), cp.asnumpy(cp.squeeze(y[1,:])), 'ko-')
plt.plot(10, cp.asnumpy(y[1,0]), 'bo', 10, 0., 'ro')  # boundaries
plt.legend(['resample', 'resamp_poly', 'data'], loc='best')
plt.grid(True)
plt.show()

```

```py
# Example 2 (does not work)
import cupy as cp
from cupyx.scipy.signal import resample, resample_poly

x = cp.linspace(0, 10, 32, endpoint=False)
A = cp.zeros([8, 32], dtype=cp.complex64)

A[:,...] = cp.cos(-x**2/6.0) + 1j*cp.sin(-x**2/6.0)

print(f"A.shape = {A.shape}")

inp_samples = A.shape[-1]
osf = 960  # oversampling factor
req_samples = inp_samples * osf
f_fft = resample(A, req_samples, axis=1)
f_poly = resample_poly(A, osf, 1, axis=1)

print(f"f_fft.shape = {f_fft.shape}")
print(f"f_poly.shape = {f_poly.shape}")

xnew = cp.linspace(0, 10, req_samples, endpoint=False)

plt.plot(cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_fft.real)), 'b.-', cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_poly.real)), 'r.-')
plt.plot(cp.asnumpy(x), cp.asnumpy(cp.squeeze(A.real)), 'ko-')
plt.plot(10, cp.asnumpy(z[0].real), 'bo', 10, 0., 'ro')  # boundaries
plt.legend(['resample', 'resamp_poly', 'data'], loc='best')
plt.title('Real')
plt.grid(True)
plt.show()

plt.plot(cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_fft.imag)), 'b.-', cp.asnumpy(xnew), cp.asnumpy(cp.squeeze(f_poly.imag)), 'r.-')
plt.plot(cp.asnumpy(x), cp.asnumpy(cp.squeeze(A.imag)), 'ko-')
plt.plot(10, cp.asnumpy(A[0].imag), 'bo', 10, 0., 'ro')  # boundaries
plt.legend(['resample', 'resamp_poly', 'data'], loc='best')
plt.title('Imag')
plt.grid(True)
plt.show()

```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.15.0-124-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.3
SciPy Version                : 1.14.0
Cython Build Version         : 0.29.36
Cython Runtime Version       : 3.0.11
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 11080
CUDA Driver Version          : 12020
CUDA Runtime Version         : 11080 (linked to CuPy) / 11080 (locally installed)
cuBLAS Version               : (available)
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : (available)
NVRTC Version                : (11, 8)
Thrust Version               : 200200
CUB Build Version            : 200200
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8801
cuDNN Version                : 8906
NCCL Build Version           : 21602
NCCL Runtime Version         : 21505
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3090
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:C1:00.0

```

**Comment by kmaehashi** [comment]
Thanks for the report @naperman, this reproduced on my end as well.

**Comment by dundermain** [comment]
@kmaehashi and @naperman Let me know if I can work on this issue

**Comment by naperman** [comment]
@dundermain I'd say please do, but I think @kmaehashi seems to be the only one in this thread who can authorize merge requests.

**Comment by naperman** [comment]
I'd also add the being able to use resample_poly on arrays of any dimension would be very useful. Currently, it supports only 2 dimensional arrays whereas resample support any dimension.

**Comment by kmaehashi** [comment]
Here is the error I get when running `Example 2` code:
```pycon
>>> f_poly = resample_poly(A, osf, 1, axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maehashi/Development/cupy/cupyx/scipy/signal/_resample.py", line 552, in resample_poly
    y = upfirdn(h, x, up, down, axis)
  File "/home/maehashi/Development/cupy/cupyx/scipy/signal/_upfirdn.py", line 502, in upfirdn
    return ufd.apply_filter(x, axis)
  File "/home/maehashi/Development/cupy/cupyx/scipy/signal/_upfirdn.py", line 417, in apply_filter
    kernel(threadsperblock, blockspergrid,
  File "cupy/_core/raw.pyx", line 93, in cupy._core.raw.RawKernel.__call__
  File "cupy/cuda/function.pyx", line 223, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 205, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 273, in cupy_backends.cuda.api.driver.launchKernel
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
```

**Comment by Harishjitu** [comment]
This appears to be fixed by PR #9352, which corrected the kernel launch argument order in the 2D case.

I've implemented N-D array support for upfirdn as suggested in the comments by @naperman . The implementation reshapes N-D arrays to 2D, applies the existing kernel, and reshapes back. Will open a PR shortly.
