### ISSUE TITLE
cudaErrorOperatingSystem when trying to pin memory

### ISSUE THREAD

**Issue by cpeter153** [cupy/cupy#8733]
Hello, I'm having an issue with cupy giving  cudaErrorOperatingSystem error when I try to allocate any memory that exceeds the GPU memory. 
```
import cupy
mem = cupy.cuda.pinned_memory._malloc(30 * 1e9 * 8)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/cuda/pinned_memory.pyx", line 180, in cupy.cuda.pinned_memory._malloc
  File "cupy/cuda/pinned_memory.pyx", line 181, in cupy.cuda.pinned_memory._malloc
  File "cupy/cuda/pinned_memory.pyx", line 30, in cupy.cuda.pinned_memory.PinnedMemory.__init__
  File "cupy_backends/cuda/api/runtime.pyx", line 554, in cupy_backends.cuda.api.runtime.hostAlloc
  File "cupy_backends/cuda/api/runtime.pyx", line 146, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorOperatingSystem: OS call failed or operation not supported on this OS
```
The server that I'm testing this on has around ~700Gb of ram memory and a H100 NVL, (Driver: 535.104.05, cuda12.2). The OS is Ubuntu 18.04 with kernel 4.15.0-213-generic. I'm confused because I am able to run the same command on a different server with the same OS config, similar system specs, but different cuda (12.0) and driver (525.147.05).

Any memory allocation that exceeds the GPU memory will result in this error. When I monitor the memory usage of the system, I can see that the memory usage is going up, but then right before reaching the target memory usage, the process stops and gives the cuda error. 

Any help/insight would be much appreciated.

**Comment by cpeter153** [comment]
Sorry just realized that cuda 12.2 in general is probably incompatible with ubuntu 18.04...
