### ISSUE TITLE
Bug Report: `cupy.repeat` triggers an error with `()`-shape array

### ISSUE THREAD

**Issue by AnonymousPlayer2000** [cupy/cupy#8756]
### Description

Hi! I use `cupy.repeat` function but trigger an error with `()`-shape array. `numpy.repeat` runs without errors. This issue is similar with a previous one about [`cupy.prod`](https://github.com/cupy/cupy/issues/8748)

### To Reproduce

```shell
>>> import numpy as np
>>> import cupy as cp
>>> np.repeat(np.array(1), 1, axis=0)
array([1])
>>> cp.repeat(cp.array(1), 1, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.12/site-packages/cupy/_manipulation/tiling.py", line 70, in repeat
    return a.repeat(repeats, axis)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy/_core/core.pyx", line 846, in cupy._core.core._ndarray_base.repeat
  File "cupy/_core/core.pyx", line 854, in cupy._core.core._ndarray_base.repeat
  File "cupy/_core/_routines_manipulation.pyx", line 256, in cupy._core._routines_manipulation._ndarray_repeat
  File "cupy/_core/_routines_manipulation.pyx", line 560, in cupy._core._routines_manipulation._repeat
  File "cupy/_core/internal.pyx", line 438, in cupy._core.internal._normalize_axis_index
numpy.exceptions.AxisError: axis 0 is out of bounds for array of dimension 0
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-5.15.0-94-generic-x86_64-with-glibc2.35
Python Version               : 3.12.3
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.3
SciPy Version                : None
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12060 (linked to CuPy) / 12010 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120100
cuFFT Version                : 11002
cuRAND Version               : 10302
cuSOLVER Version             : (11, 4, 5)
cuSPARSE Version             : 12002
NVRTC Version                : (12, 1)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : 8801
cuDNN Version                : 8900
NCCL Build Version           : 21602
NCCL Runtime Version         : 21701
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4090 D
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:A8:00.0
```

**Comment by kmaehashi** [comment]
Let's discuss this one altogether in #8748.
