### ISSUE TITLE
The `__cluster_dims__` annotation doesn't work as expected with CuPy.

### ISSUE THREAD

**Issue by mrakgr** [cupy/cupy#8778]
### Description

I am getting weird `CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE: too many blocks in cooperative launch` and `CUDA_ERROR_INVALID_CLUSTER_SIZE: a kernel launch error has occurred due to cluster misconfiguration` errors when I try out kernels with `__cluster_dims__` annotations. The number of blocks I am launching should be entirely sufficient for the GPU. In particular I am getting `CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE` when I try to use a cluster size of 16, and the other when I try 8 or less.

### To Reproduce

```py
kernel = r"""
extern "C" __global__ void __cluster_dims__(4,1,1) entry0() {
    return ;
}
"""
import cupy as cp

raw_module = cp.RawModule(code=kernel, backend='nvcc', enable_cooperative_groups=True)
def main():
    v9 = raw_module.get_function(f"entry0")
    v9.max_dynamic_shared_size_bytes = 229376 
    v9((128,),(256,),(),shared_mem=229376)
    return 

if __name__ == '__main__': print(main())
```

The full error:

```
(trt) ceti@ceti16:~/Spiral-s-ML-Library$  cd /home/ceti/Spiral-s-ML-Library ; /usr/bin/env /home/ceti/miniconda3/envs/trt/bin/python /home/ceti/.vscode-server/extensions/ms-python.debugpy-2024.12.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 52065 -- /home/ceti/Spiral-s-ML-Library/tests/distributed_shared_memory/test0.py 
Traceback (most recent call last):
  File "/home/ceti/Spiral-s-ML-Library/tests/distributed_shared_memory/test0.py", line 15, in <module>
    if __name__ == '__main__': print(main())
  File "/home/ceti/Spiral-s-ML-Library/tests/distributed_shared_memory/test0.py", line 12, in main
    v9((128,),(256,),(),shared_mem=229376)
  File "cupy/_core/raw.pyx", line 93, in cupy._core.raw.RawKernel.__call__
  File "cupy/cuda/function.pyx", line 223, in cupy.cuda.function.Function.__call__
  File "cupy/cuda/function.pyx", line 201, in cupy.cuda.function._launch
  File "cupy_backends/cuda/api/driver.pyx", line 288, in cupy_backends.cuda.api.driver.launchCooperativeKernel
  File "cupy_backends/cuda/api/driver.pyx", line 63, in cupy_backends.cuda.api.driver.check_status
cupy_backends.cuda.api.driver.CUDADriverError: CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE: too many blocks in cooperative launch
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
(trt) ceti@ceti16:~/Spiral-s-ML-Library$ python -c "import cupy; cupy.show_config(_full=True)"
OS                           : Linux-5.15.0-125-generic-x86_64-with-glibc2.35
Python Version               : 3.10.13
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.26.4
SciPy Version                : 1.14.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : /usr/local/cuda-12.6
nvcc PATH                    : /usr/local/cuda-12.6/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12060
CUDA Runtime Version         : 12060 (linked to CuPy) / 12040 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120603
cuFFT Version                : 11300
cuRAND Version               : 10307
cuSOLVER Version             : (11, 7, 1)
cuSPARSE Version             : 12504
NVRTC Version                : (12, 6)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : 21602
NCCL Runtime Version         : 22304
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA H100 80GB HBM3
Device 0 Compute Capability  : 90
Device 0 PCI Bus ID          : 0000:18:00.0
Device 1 Name                : NVIDIA H100 80GB HBM3
Device 1 Compute Capability  : 90
Device 1 PCI Bus ID          : 0000:2A:00.0
Device 2 Name                : NVIDIA H100 80GB HBM3
Device 2 Compute Capability  : 90
Device 2 PCI Bus ID          : 0000:3A:00.0
Device 3 Name                : NVIDIA H100 80GB HBM3
Device 3 Compute Capability  : 90
Device 3 PCI Bus ID          : 0000:5D:00.0
Device 4 Name                : NVIDIA H100 80GB HBM3
Device 4 Compute Capability  : 90
Device 4 PCI Bus ID          : 0000:84:00.0
Device 5 Name                : NVIDIA H100 80GB HBM3
Device 5 Compute Capability  : 90
Device 5 PCI Bus ID          : 0000:8B:00.0
Device 6 Name                : NVIDIA H100 80GB HBM3
Device 6 Compute Capability  : 90
Device 6 PCI Bus ID          : 0000:91:00.0
Device 7 Name                : NVIDIA H100 80GB HBM3
Device 7 Compute Capability  : 90
Device 7 PCI Bus ID          : 0000:E4:00.0
```

**Comment by mrakgr** [comment]
It's my first time using thread block clusters, but the Cuda manual does state the following:

```
        // The grid dimension is not affected by cluster launch, and is still enumerated
        // using number of blocks.
        // The grid dimension should be a multiple of cluster size.
        config.gridDim = numBlocks;
        config.blockDim = threadsPerBlock;
```

Given that the kernel launch works with the cluster dims set to 1, I am thinking that there might be something wrong on the CuPy side.

**Comment by mrakgr** [comment]
```
kernel = r"""
extern "C" __global__ void __cluster_dims__(8,1,1) entry0() {
    return ;
}
"""
import cupy as cp

raw_module = cp.RawModule(code=kernel, backend='nvcc', enable_cooperative_groups=False)
def main():
    v9 = raw_module.get_function(f"entry0")
    v9.max_dynamic_shared_size_bytes = 229376 
    v9((128,),(256,),(),shared_mem=229376)
    return 

if __name__ == '__main__': print(main())
```

It does work when `enable_cooperative_groups` is set to false. It works only up to 8 though, and I want to get it working with the cluster dims set to 16. When I try it with 16, I get the `CUDA_ERROR_INVALID_CLUSTER_SIZE`, which shouldn't be happening because I am using an H100 GPU.

**Comment by mrakgr** [comment]
I did some testing, and I am getting the same kinds of errors in native Cuda code, so this isn't a CuPy specific error. Maybe I should be asking on the Cuda forums how to use cluster dims properly. I'll do some more testing and then close this issue after I am satisfied.

**Comment by mrakgr** [comment]
I found the limit.

```
#include <stdio.h>
#include <cuda_runtime.h>
#include <iostream>

#define gpuErrchk(ans) { gpuAssert((ans), __FILE__, __LINE__); }
inline void gpuAssert(cudaError error, const char *file, int line, bool abort=true) {
    if (error != cudaSuccess) {
        fprintf(stderr, "GPUassert: %s %s %d\n", cudaGetErrorString(error), file, line);
        if (abort) exit(error);
    }
}

__global__ void __cluster_dims__(8) hello(int a, int b) {
    if (threadIdx.x == 0 && blockIdx.x == 0) {
        printf("Hello, CUDA! %i + %i = %i\n", a, b, a + b);
    }
}

int main() {
    size_t maxDynamicSharedMemory = 113 * (1 << 10);
    cudaError_t error = cudaFuncSetAttribute(hello, cudaFuncAttributeMaxDynamicSharedMemorySize, maxDynamicSharedMemory);

    int i = 0;
    int dev = 0;
    cudaDeviceProp deviceProp;
    cudaGetDeviceProperties(&deviceProp, dev);
    void * args[] = {reinterpret_cast<void*>(&i), reinterpret_cast<void*>(&i)};
    gpuErrchk(cudaLaunchCooperativeKernel(hello, 128, 256, args, maxDynamicSharedMemory));
    gpuErrchk(cudaDeviceSynchronize());
    std::cout << "Done." << std::endl;
    return 0;
}
```

This example works, but when I try setting the max dynamic shared memory size to 114kb, I get the `GPUassert: too many blocks in cooperative launch /home/ceti/Spiral-s-ML-Library/tests/native_cuda/nvcc_test.cu 29` error. I guess when paired with cooperative groups, the thread block cluster dimensions as well as the amount of shared memory allowed to them is drastically limited.

I'll ask in Cuda forums about this.

**Comment by mrakgr** [comment]
```
$dir = "$env:HOME/Spiral-s-ML-Library/tests/native_cuda"
$file = "nvcc_test"
nvcc $dir/$file.cu `
    -arch=sm_90a `
    '-gencode=arch=compute_90a,code=sm_90a' `
    -std=c++20 `
    -o $dir/out/$file
Start-Process $dir/out/$file -Wait
```

For completion here are the options I've been using to invoke `nvcc` using a Powershell script. Powershell uses ` instead of \ for line continuations.

**Comment by mrakgr** [comment]
Here is [the question](https://forums.developer.nvidia.com/t/why-is-the-amount-of-thread-blocks-per-cluster-and-the-dynamic-shared-memory-that-i-can-allocate-much-lower-than-expected/316095) in the Cuda forums that I asked.

**Comment by leofang** [comment]
Sorry for late reply. I think you figured it out in the forum post. Just for completeness, below is a response from the NVIDIA team to the snippets shown in this issue:
> It seems none of the occupancy calculators are used, in that case the kernel working is more of a blind luck with the numbers put it, unless they are very small. There should be a call to `cudaOccupancyMaxActiveBlocksPerMultiprocessor` to check how many blocks can fit per SM, if clusters are used there should be a call to `cudaOccupancyMaxActiveClusters` as well

The bottom line is, there are programmatic ways to find out the upper limits for various sizes (shmem, cluster, ...), and we should rely on them.

**Comment by mrakgr** [comment]
Does CuPy support the occupancy calculators? I remember looking into them, but concluding that they're only usable in the C++ code.

**Comment by leofang** [comment]
I think it should be possible to use Python bindings to CUDA APIs from cuda-python, and pass the kernel pointer to it.
https://github.com/NVIDIA/cuda-python/blob/33b7366e308201f3bca8206ae331e399ac1b3379/cuda_bindings/examples/4_CUDA_Libraries/conjugateGradientMultiBlockCG_test.py#L287-L289
