### ISSUE TITLE
Bug Report: `cupy.ravel` behaves differently with `numpy.ravel`

### ISSUE THREAD

**Issue by AnonymousPlayer2000** [cupy/cupy#8779]
### Description

As claimed in [NumPy doc](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html):
> When order is ‘K’, it will preserve orderings that are neither ‘C’ nor ‘F’, but won’t reverse axes:
```py
>>> a = np.arange(12).reshape(2,3,2).swapaxes(1,2); a
array([[[ 0,  2,  4],
        [ 1,  3,  5]],
       [[ 6,  8, 10],
        [ 7,  9, 11]]])
>>> a.ravel(order='C')
array([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11])
>>> a.ravel(order='K')
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
```

I found that `cupy.ravel` does not keep this spec when the swapaxes's output is manipulated by other functions and then used as the `ravel`'s input.

### To Reproduce

```py
import numpy as np
import cupy as cp

a1 = np.arange(np.pi/6, np.pi*13/6, np.pi/6).reshape(2,3,2).swapaxes(1,2)
print("np a:", a1)
b1 = np.ravel(a1, order='K')
print("np a after ravel:", b1)
a2 = cp.arange(cp.pi/6, cp.pi*13/6, cp.pi/6).reshape(2,3,2).swapaxes(1,2)
print("cp a:", a2)
b2 = cp.ravel(a2, order='K')
print("cp a after ravel:", b2)
cp.testing.assert_array_almost_equal(b1, b2) # pass

print()
c1 = np.rad2deg(a1)
d1 = np.ravel(c1, order='K')
print("np rad2deg(a) after ravel:", d1)

c2 = cp.rad2deg(a2)
d2 = np.ravel(c2, order='K')
print("cp rad2deg(a) after ravel:", d2)
cp.testing.assert_array_almost_equal(d1, d2) # fail
```

Output shows that `b1` and `b2` (`a1` and `a2` after `ravel`) are equal, but `d1` and `d2` (`rad2deg(a1)` and `rad2deg(a2)` after `ravel`) are not:
```py
np a: [[[0.52359878 1.57079633 2.61799388]
  [1.04719755 2.0943951  3.14159265]]

 [[3.66519143 4.71238898 5.75958653]
  [4.1887902  5.23598776 6.28318531]]]
np a after ravel: [0.52359878 1.04719755 1.57079633 2.0943951  2.61799388 3.14159265
 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653 6.28318531]
cp a: [[[0.52359878 1.57079633 2.61799388]
  [1.04719755 2.0943951  3.14159265]]

 [[3.66519143 4.71238898 5.75958653]
  [4.1887902  5.23598776 6.28318531]]]
cp a after ravel: [0.52359878 1.04719755 1.57079633 2.0943951  2.61799388 3.14159265
 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653 6.28318531]

np rad2deg(a) after ravel: [ 30.  60.  90. 120. 150. 180. 210. 240. 270. 300. 330. 360.]
cp rad2deg(a) after ravel: [ 30.  90. 150.  60. 120. 180. 210. 270. 330. 240. 300. 360.]
Traceback (most recent call last):
  File "/code/test1.py", line 22, in <module>
    cp.testing.assert_array_almost_equal(d1, d2) # fail
  File "/usr/local/lib/python3.10/dist-packages/cupy/testing/_array.py", line 42, in assert_array_almost_equal
    numpy.testing.assert_array_almost_equal(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/_utils/__init__.py", line 85, in wrapper
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1141, in assert_array_almost_equal
    assert_array_compare(compare, actual, desired, err_msg=err_msg,
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

Mismatched elements: 8 / 12 (66.7%)
Max absolute difference among violations: 60.
Max relative difference among violations: 1.
 ACTUAL: array([ 30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300., 330.,
       360.])
 DESIRED: array([ 30.,  90., 150.,  60., 120., 180., 210., 270., 330., 240., 300.,
       360.])
```

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.0
SciPy Version                : 1.13.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.37
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12060 (linked to CuPy) / 12020 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120201
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 2)
cuSPARSE Version             : 12101
NVRTC Version                : (12, 2)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4070 Laptop GPU
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
When submitting an issue please try to provide a **minimal and concise** example reproducing the problem. That helps us a lot to understand the problem quickly.

For example:

```py
# NumPy
a_cpu = np.arange(12).reshape(2,3,2).swapaxes(1,2)
np.ravel(np.rad2deg(a_cpu), order='K')

# CuPy
a_gpu = cp.arange(12).reshape(2,3,2).swapaxes(1,2)
cp.ravel(cp.rad2deg(a_gpu), order='K')
```

As for this specific case, it is by design. For details please refer to https://docs.cupy.dev/en/latest/user_guide/difference.html#contiguity-strides.
