### ISSUE TITLE
Bug Report: `cupy.linalg.inv`and `numpy.linalg.inv`behave differently on singular matrix

### ISSUE THREAD

**Issue by AnonymousPlayer2000** [cupy/cupy#8833]
### Description

`cupy.linalg.inv`and `numpy.linalg.inv`behave differently on singular matrix

### To Reproduce

```py
import numpy as np
import cupy as cp

a1 = cp.array([[0]])
a2 = cp.linalg.inv(a1)
print(a1, a2)
print(a1 @ a2, np.eye(a1.shape[0]))

print(np.linalg.inv(np.array([[0]])))
```
Output:
```
[[0]] [[inf]]
[[nan]] [[1.]]
Traceback (most recent call last):
  File "/test.py", line 9, in <module>
    print(np.linalg.inv(np.array([[0]])))
  File "/usr/local/lib/python3.10/dist-packages/numpy/linalg/_linalg.py", line 615, in inv
    ainv = _umath_linalg.inv(a, signature=signature)
  File "/usr/local/lib/python3.10/dist-packages/numpy/linalg/_linalg.py", line 104, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

NumPy throws an error, while CuPy returns `[[inf]]`. As [numpy doc](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html) claims,
> Given a square matrix `a`, `inv` returns the matrix `ainv` satisfying ``a @ ainv = ainv @ a = eye(a.shape[0])``.

`a1 @ a2==[[nan]]` and `eye(a1.shape[0])==[[1.]]`. Hence, the return of CuPy is not very sensible.

### Installation

Wheel (`pip install cupy-***`)

### Environment

```
OS                           : Linux-6.8.0-49-generic-x86_64-with-glibc2.35
Python Version               : 3.10.12
CuPy Version                 : 13.3.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 2.1.0
SciPy Version                : 1.13.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : 0.29.37
CUDA Root                    : /usr/local/cuda
nvcc PATH                    : /usr/local/cuda/bin/nvcc
CUDA Build Version           : 12060
CUDA Driver Version          : 12040
CUDA Runtime Version         : 12060 (linked to CuPy) / 12020 (locally installed)
CUDA Extra Include Dirs      : []
cuBLAS Version               : 120201
cuFFT Version                : 11008
cuRAND Version               : 10303
cuSOLVER Version             : (11, 5, 2)
cuSPARSE Version             : 12101
NVRTC Version                : (12, 2)
Thrust Version               : 200600
CUB Build Version            : 200600
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 4070 Laptop GPU
Device 0 Compute Capability  : 89
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
> I notice cupy's doc:
> 
> > This function calls one or more cuSOLVER routine(s) which may yield invalid results if input conditions are not met. To detect these invalid results, you can set the `linalg` configuration to a value that is not `ignore` in :func:`cupyx.errstate` or :func:`cupyx.seterr`.
> 
> But I am not be able to find `cupyx.seterr`.

This is by design as documented. `cupyx.seterr` is currently undocumented but should be there.
