### ISSUE TITLE
Cannot generate a binary with cupy

### ISSUE THREAD

**Issue by siddmittal** [cupy/cupy#8850]
### Description

I want to generate a binary for my python program however, if a copy import statement is present in the program, the generated binary does not work. It is always crashes complaining about one or another CUDA libraries that could not be found. I have tried the generation of binaries on Windows as well as on Ubuntu system, but in this ticket, I am reporting with the issue faced on Windows 11 system.

I have a single python file with a very simple code as given below:

```
import os
import cupy

print("Program running using binaries...")

```

Then I generate a binary by executing the command below:

`pyinstaller --onefile --distpath="D:/TestBinGeneration/dist" --workpath="D:/TestBinGeneration/build" D:/TestBinGeneration/TestProgram.py`

The above command would generate two new folders `dist` and `build`, where the `dist` folder would contain the binary. But when I try to run the executable binary, it throws the following error:

```
(fmri_python_env) D:\TestBinGeneration\dist>TestProgram.exe
Traceback (most recent call last):
  File "TestProgram.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "cupy\__init__.py", line 11, in <module>
  File "cupy\_environment.py", line 234, in _setup_win32_dll_directory
  File "os.py", line 1118, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\siddh\\anaconda3\\envs\\fmri_python_env\\bin'
[42332] Failed to execute script 'TestProgram' due to unhandled exception!
```

**NOTE:** The was a little different on an Ubuntu system which stated that the some cuda libraries could not be found. 

### To Reproduce

**Steps:**

1. Download the attached zip folder
2. Extarct the content of zip folder which contain a single folder called "TestBinGeneration" with a single file in it called "TestProgram.py"
3. Run `pyinstalled` to generate the binary file for the above python file by executing the command, `pyinstaller --onefile --distpath="D:/TestBinGeneration/dist" --workpath="D:/TestBinGeneration/build" D:/TestBinGeneration/TestProgram.py` (NOTE: Don't forget to adjust your path in the command)
4. The execution of above command would generated the new folders called `dist` and `build`
5. Try to run the binary file (called `TestProgram.exe`) present in the `dist` folder

Dummy Folder and file for binary generation: [TestBinGeneration.zip](https://github.com/user-attachments/files/18213109/TestBinGeneration.zip)
Output log of Pyinstaller: [pyinstaller log.txt](https://github.com/user-attachments/files/18213088/pyinstaller.log.txt)

### Installation

Conda-Forge (`conda install ...`)

### Environment

```
(fmri_python_env) C:\Users\siddh>python -c "import cupy; cupy.show_config(_full=True)"
OS                           : Windows-10-10.0.22631-SP0
Python Version               : 3.10.12
CuPy Version                 : 12.2.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.25.2
SciPy Version                : 1.11.1
Cython Build Version         : 0.29.36
Cython Runtime Version       : None
CUDA Root                    : C:\Users\siddh\anaconda3\envs\fmri_python_env
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 12030
CUDA Runtime Version         : 11080
cuBLAS Version               : 111103
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : 11705
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : <unknown>
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 3050 Ti Laptop GPU
Device 0 Compute Capability  : 86
Device 0 PCI Bus ID          : 0000:01:00.0
```

**Comment by kmaehashi** [comment]
Can you try using CuPy from PyPI wheels for pyinstaller instead of conda-forge ones? conda-forge distribution contains a special adjustments to find CUDA Toolkit installed by conda-forge's CUDA distribution, so it might cause a problem when making a portable binary. Also note that you might need a manifest, please see the past issues for details. https://github.com/cupy/cupy/issues?q=is%3Aissue%20state%3Aclosed%20pyinstaller

**Comment by kmaehashi** [comment]
I'm closing this one as it's inactive for a while. Feel free to request reopening if necessary.
