### ISSUE TITLE
How to compile and install cupy on Windows 10 x64

### ISSUE THREAD

**Issue by sharpstill** [cupy/cupy#914]
When I use pip to install cupy on windows 10,  the following error reported, I am pretty sure that cupy 1.0.3 can install on windows.

```
C:\WINDOWS\system32>pip install cupy
Collecting cupy
  Using cached cupy-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    **************************************************
    *** WARNING: Cannot find nvToolsExt. nvtx was disabled.
    **************************************************
    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
    Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
    Unable to find a compatible Visual Studio installation.
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\machen\AppData\Local\Temp\pip-build-po8si2ni\cupy\setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\machen\AppData\Local\Temp\pip-build-po8si2ni\cupy\cupy_setup_build.py", line 378, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\machen\AppData\Local\Temp\pip-build-po8si2ni\cupy\cupy_setup_build.py", line 268, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\machen\AppData\Local\Temp\pip-build-po8si2ni\cupy\
```

**Comment by hknerdgn** [comment]
From the error, it looks like you may need to install visual c++ build tools on your machine.

**Comment by sharpstill** [comment]
@hknerdgn but inside downloaded cupy source code folder, there is no visual C++ .sln file or any visual studio project file I can used to compile it???

**Comment by sharpstill** [comment]
@hknerdgn The only reason I choose chainer and cupy is that PyTorch don't support windows system, but chainer can! So please help me please.

**Comment by hknerdgn** [comment]
you do not need a sln file, you just need a visual c++ compiler installed. Just run pip install cupy as you did before.

**Comment by sharpstill** [comment]
@hknerdgn Although I install visual studio 2015 & visual studio 2017 and use MsBuild command tools (rather than regular cmd.exe) to pip install
it still report:
```
E:\develop\cupy>python setup.py build
**************************************************
*** WARNING: Cannot find nvToolsExt. nvtx was disabled.
**************************************************
Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
Unable to find a compatible Visual Studio installation.
**************************************************
*** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
*** WARNING: Skip installing cuda support
*** WARNING: Check your CFLAGS environment variable
**************************************************
Traceback (most recent call last):
  File "setup.py", line 32, in <module>
    ext_modules = cupy_setup_build.get_ext_modules()
  File "E:\develop\cupy\cupy_setup_build.py", line 382, in get_ext_modules
    extensions = make_extensions(arg_options, compiler, use_cython)
  File "E:\develop\cupy\cupy_setup_build.py", line 272, in make_extensions
    raise Exception('Your CUDA environment is invalid. '
Exception: Your CUDA environment is invalid. Please check above error log.
```

**Comment by sharpstill** [comment]
@hknerdgn Is that because I use cuda 8.0?

**Comment by sharpstill** [comment]
@hknerdgn if cupy document can write a tutorial about how to compile & install cupy on window OS, I would thank you very much.

**Comment by hknerdgn** [comment]
I also have cuda 8.0 and I have installed 2015 build tools (free one, not even visual studio). I am running from build tools command prompt. I agree we need a windows installation document.

**Comment by hknerdgn** [comment]
Check that you can run cl.exe and link.exe from your command line.

**Comment by sharpstill** [comment]
Yes , I can run cl.exe and link.exe, but `pip install cupy` or `git clone cupy` & `python setup.py build` still error:

```
C:\WINDOWS\system32>pip install cupy --no-cache-dir -vvvv
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting cupy
  1 location(s) to search for versions of cupy:
  * https://pypi.python.org/simple/cupy/
  Getting page https://pypi.python.org/simple/cupy/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/cupy/ HTTP/1.1" 200 1419
  Analyzing links from page https://pypi.python.org/simple/cupy/
    Found link https://pypi.python.org/packages/07/a3/826820b9d08f85c9f4c651ce44357568c66ac6ad2077dee613a9c2c9a0a3/cupy-2.1.0.1.tar.gz#md5=85633ca2446bedcc841fa34c2dac856e (from https://pypi.python.org/simple/cupy/), version: 2.1.0.1
    Found link https://pypi.python.org/packages/09/75/df5be6a1ccb8b4c5299d5ed6694fcb64123b0b6ba3ca05d5825c220578e0/cupy-2.0.0.tar.gz#md5=df9977fb40fbc79fd21884c4be35d68e (from https://pypi.python.org/simple/cupy/), version: 2.0.0
    Found link https://pypi.python.org/packages/0c/3f/11d7f5e742f60a62beec3177b5bd43824683794b958c73a32e6c63c12044/cupy-3.0.0a1.tar.gz#md5=199d6b0c3ab99a77bc52b7b25b473629 (from https://pypi.python.org/simple/cupy/), version: 3.0.0a1
    Found link https://pypi.python.org/packages/32/09/31c3c37ac0393293bcfd5404fd12512e16961cbeb48939c50fa1f395fb47/cupy-1.0.1.tar.gz#md5=2cfa2e280309d8e7fae30a364885517d (from https://pypi.python.org/simple/cupy/), version: 1.0.1
    Found link https://pypi.python.org/packages/3d/42/662cab10a52b6dfe77cdae53fe533ccd16f01d5d4113a3b0b958b496443f/cupy-1.0.0.1.tar.gz#md5=134d0f89e61deb8e21bba05615f8cfe8 (from https://pypi.python.org/simple/cupy/), version: 1.0.0.1
    Found link https://pypi.python.org/packages/44/f0/9f1d8fca928a1081c5c71a3313b541f6089b8109050aa490ac44038137f4/cupy-2.1.0.tar.gz#md5=23d28b2e5d9f5038537caf4ce84951e5 (from https://pypi.python.org/simple/cupy/), version: 2.1.0
    Found link https://pypi.python.org/packages/4f/84/ff4c79b1b7120504909181f4b767be9c2542434ba1b8f2d126bace21c015/cupy-1.0.3.tar.gz#md5=a95f1d6126410feebce44e157f301234 (from https://pypi.python.org/simple/cupy/), version: 1.0.3
    Found link https://pypi.python.org/packages/4f/ee/0209b0288d43cb277715c9fbd91cd232e5f7f07895c78e9e75a9d6ad25ec/cupy-1.0.0b1.tar.gz#md5=197ff55ef415bf0260435c61db1e3915 (from https://pypi.python.org/simple/cupy/), version: 1.0.0b1
    Found link https://pypi.python.org/packages/51/ce/9c4789dd570935c5fd8c9f71aa4e0761aaaef195ef1f017e4174e7c266dc/cupy-2.3.0.tar.gz#md5=7dcbf8d7451f7acda797f870180441ea (from https://pypi.python.org/simple/cupy/), version: 2.3.0
    Found link https://pypi.python.org/packages/54/dd/540398a7e9532daac41da1cf15fd69710e77d5bf7df377d4d42851ec60c1/cupy-2.0.0a1.tar.gz#md5=d5ddb78058ef369649bb36dd4f82608c (from https://pypi.python.org/simple/cupy/), version: 2.0.0a1
    Found link https://pypi.python.org/packages/6e/21/7c7d94ba61e020ddf5e4204f345ded442a76543951cef7a0f8f96a69a73a/cupy-2.0.0b1.tar.gz#md5=3e4b64aab304ceefa87a60f888217dae (from https://pypi.python.org/simple/cupy/), version: 2.0.0b1
    Found link https://pypi.python.org/packages/79/e5/c7febd2964bf5e319423045e440ef43ad3aad2dcbe347854e1ad6cc6485a/cupy-1.0.0a1.tar.gz#md5=c3c2647aa825f5f5cf538f3fe02c9bd4 (from https://pypi.python.org/simple/cupy/), version: 1.0.0a1
    Found link https://pypi.python.org/packages/9e/12/6a4120fdc8156a3e05816e99ce73884d02ee1d64a4d1beedd31d37144d63/cupy-2.0.0rc1.tar.gz#md5=a1f759b941f2ab48bb154dbdc12851c8 (from https://pypi.python.org/simple/cupy/), version: 2.0.0rc1
    Found link https://pypi.python.org/packages/9f/24/93c73848af724b5db61c5082544e89db8a11e16a14fedc4e55497fe986f9/cupy-4.0.0b2.tar.gz#md5=ad3b5231b35eb3c3d82ca19868cc221c (from https://pypi.python.org/simple/cupy/), version: 4.0.0b2
    Found link https://pypi.python.org/packages/b5/0a/c800906e16c9f9049e1a4273a66aa29d32a204b7961b6e156efe3af1a9ec/cupy-4.0.0b3.tar.gz#md5=f22d421e23b370182cee10313a81aca4 (from https://pypi.python.org/simple/cupy/), version: 4.0.0b3
    Found link https://pypi.python.org/packages/b8/2a/1d00603840f2e32a989c89042cbf1630bac8f4a32aacb05873287a334fc8/cupy-2.2.0.tar.gz#md5=9fc2e04caf9d56b278e565f40ce3eabf (from https://pypi.python.org/simple/cupy/), version: 2.2.0
    Found link https://pypi.python.org/packages/ca/8a/f0691716fc46dfacadcf2fa045f51d1f3598b64fb8a92825ae73286f0f65/cupy-4.0.0b1.tar.gz#md5=df8540aa435acf8e456f5b3622e37b48 (from https://pypi.python.org/simple/cupy/), version: 4.0.0b1
    Found link https://pypi.python.org/packages/d4/0f/79b84c548e0898ff39fa8a27f2a5134a5328b4f94e96bfc09fe60f63a167/cupy-1.0.2.tar.gz#md5=70d8691521d7961a418e94b7a61baf51 (from https://pypi.python.org/simple/cupy/), version: 1.0.2
  Using version 2.3.0 (newest of versions: 1.0.0.1, 1.0.1, 1.0.2, 1.0.3, 2.0.0, 2.1.0, 2.1.0.1, 2.2.0, 2.3.0)
  "GET /packages/51/ce/9c4789dd570935c5fd8c9f71aa4e0761aaaef195ef1f017e4174e7c266dc/cupy-2.3.0.tar.gz HTTP/1.1" 200 1940883
  Downloading cupy-2.3.0.tar.gz (1.9MB)
  Downloading from URL https://pypi.python.org/packages/51/ce/9c4789dd570935c5fd8c9f71aa4e0761aaaef195ef1f017e4174e7c266dc/cupy-2.3.0.tar.gz#md5=7dcbf8d7451f7acda797f870180441ea (from https://pypi.python.org/simple/cupy/)
    100% |████████████████████████████████| 1.9MB 11.4MB/s
  Running setup.py (path:C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\setup.py) egg_info for package cupy
    Running command python setup.py egg_info
    **************************************************
    *** WARNING: Cannot find nvToolsExt. nvtx was disabled.
    **************************************************
    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\include']
    Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v8.0\\lib\\x64']
    Unable to find a compatible Visual Studio installation.
    **************************************************
    *** WARNING: Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your CFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\cupy_setup_build.py", line 378, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\cupy_setup_build.py", line 268, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\
Exception information:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in C:\Users\machen\AppData\Local\Temp\pip-build-ucp4w25c\cupy\

```

**Comment by sharpstill** [comment]
I think maybe cuda or enviroment something incorrect results in failed?

**Comment by sharpstill** [comment]
#604 also reported similar error on windows.

**Comment by hknerdgn** [comment]
You still get "Unable to find a compatible Visual Studio installation" in your error log. So I guess it may be your version of VC++ that is not working for you. I suggest clean installing both CUDA-8.0 and VC++ build tools 2015 and trying again. Also, you may need to set some environment variables such as library paths.

**Comment by sharpstill** [comment]
@hknerdgn still can't install and work, hope to supply a detailed tutorial document  on how to compile and install on windows system.     PS: May be some subtle difference exists between our environment, be careful and test on different machine.
thanks

**Comment by sharpstill** [comment]
@hknerdgn Thanks anyway, I will clean my system  and do what you said

**Comment by hknerdgn** [comment]
@sharpstill I built a cupy windows wheel on my own computer running windows 10. These are supposed to be installable without a compiler. I put them in this repo: https://github.com/hknerdgn/cupy_windows_wheels.git . Just download them, and install each package by pip install wheelname.whl .

**Comment by sharpstill** [comment]
frustrated, import cupy still error( install from your compiled whl file):
```
E:\develop>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\cuda\__init__.py", line 3, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 5, in init cupy.cuda.device
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\__init__.py", line 22, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "C:\Program Files\Anaconda3\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\core\__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy\core\core.pyx", line 1, in init cupy.core.core
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\cuda\__init__.py", line 3, in <module>
    from cupy.cuda import compiler  # NOQA
  File "C:\Program Files\Anaconda3\lib\site-packages\cupy\cuda\compiler.py", line 11, in <module>
    from cupy.cuda import device
  File "cupy\cuda\runtime.pxd", line 5, in init cupy.cuda.device
ImportError: CuPy is not correctly installed. Please check your environment, uninstall CuPy and reinstall it with `pip install cupy --no-cache-dir -vvvv`.

original error: DLL load failed: 找不到指定的模块。
```

**Comment by sharpstill** [comment]
Does this because I use anaconda???

**Comment by hknerdgn** [comment]
I guess everything should match. I use windows 10, cuda 8.0 and anaconda with python 3.6.1.

**Comment by sharpstill** [comment]
@ can the reason be the PATH or dll path configuration? can you give me your enviroment variable configuration?

**Comment by j2l** [comment]
I tried:
```
PS E:\Anaconda3python\Scripts> .\pip install .\fastrlock-0.3-cp36-cp36m-win_amd64.whl
Processing e:\anaconda3python\scripts\fastrlock-0.3-cp36-cp36m-win_amd64.whl
Installing collected packages: fastrlock
Successfully installed fastrlock-0.3
```
then 
```
PS E:\Anaconda3python\Scripts> .\pip install .\cupy-4.0.0b3-cp36-cp36m-win_amd64.whl
Processing e:\anaconda3python\scripts\cupy-4.0.0b3-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy>=1.9.0 in e:\anaconda3python\lib\site-packages (from cupy==4.0.0b3)
Requirement already satisfied: six>=1.9.0 in e:\anaconda3python\lib\site-packages (from cupy==4.0.0b3)
Requirement already satisfied: fastrlock>=0.3 in e:\anaconda3python\lib\site-packages (from cupy==4.0.0b3)
Installing collected packages: cupy
Successfully installed cupy-4.0.0b3
```
and it worked for me (Win10 x64).
Thanks @hknerdgn

**Comment by kmaehashi** [comment]
We now provide wheels of development releases for Windows.
Try `pip install cupy-cuda92` etc. as in the installation docs.
