### ISSUE TITLE
Can't install via Pip

### ISSUE THREAD

**Issue by yissachar** [cupy/cupy#952]
Tried to install via `pip install cupy` but got the following error:

```
Collecting cupy
  Using cached cupy-2.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /home/ubuntu/anaconda2/envs/thingy/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcuda
    Options: {'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    Include directories: ['/usr/local/cuda/include']
    Library directories: ['/usr/local/cuda/lib64']
    Cannot build a stub file.
    Original error: command '/home/ubuntu/anaconda2/envs/thingy/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1
    **************************************************
    *** WARNING: Cannot link libraries: ['cublas', 'cuda', 'cudart', 'curand', 'cusparse', 'nvrtc', 'nvToolsExt']
    *** WARNING: Skip installing cuda support
    *** WARNING: Check your LDFLAGS environment variable
    **************************************************
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-r2jn275v/cupy/setup.py", line 32, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-build-r2jn275v/cupy/cupy_setup_build.py", line 378, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-build-r2jn275v/cupy/cupy_setup_build.py", line 268, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r2jn275v/cupy/
```

**Comment by okuta** [comment]
Cloud you use latest version? You can run `pip install cupy --pre` command. We improved message during installation. Maybe you can get more useful information.

And, we provides binary package as experimental ( [link](https://docs-cupy.chainer.org/en/latest/install.html?highlight=cuda90#install-cupy-using-wheel) ).

**Comment by yissachar** [comment]
Sorry for the late reply. Here is the output of  `pip install cupy --pre`:

```
Collecting cupy
  Downloading cupy-4.0.0b4.tar.gz (1.9MB)
    100% |████████████████████████████████| 1.9MB 730kB/s
    Complete output from command python setup.py egg_info:
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}

    -------- Configuring Module: cuda --------
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    /home/ubuntu/anaconda2/envs/thingy/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lcuda
    Cannot build a stub file.
    Original error: command '/home/ubuntu/anaconda2/envs/thingy/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1

    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['/usr/local/cuda/include']
      Library directories: ['/usr/local/cuda/lib64']
      nvcc command       : ['/usr/local/cuda/bin/nvcc']

    Environment Variables:
      CFLAGS          : -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
      LDFLAGS         : -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
      LIBRARY_PATH    : /home/ubuntu/anaconda2/envs/thingy/lib:
      CUDA_PATH       : (none)
      NVCC            : (none)

    Modules:
      cuda      : No
        -> Cannot link libraries: ['cublas', 'cuda', 'cudart', 'cufft', 'curand', 'cusparse', 'nvrtc', 'nvToolsExt']
        -> Check your LDFLAGS environment variable.

    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html

    ************************************************************

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t10b5fk5/cupy/setup.py", line 64, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/tmp/pip-build-t10b5fk5/cupy/cupy_setup_build.py", line 547, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/tmp/pip-build-t10b5fk5/cupy/cupy_setup_build.py", line 374, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t10b5fk5/cupy/
```
/usr/local/cuda exists and  I have CUDA working with TensorFlow.

Installing the prebuilt wheel worked for me, thanks!

**Comment by okuta** [comment]
Please use `CUDA_PATH`
Document is [here](https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cuda)

**Comment by yueqiw** [comment]
I'm getting the exact same error message when installing cupy, with CUDA_PATH set correctly. 
I have CUDA 9.0 installed and TensorFlow works fine. Thanks!

**Comment by yueqiw** [comment]
Actually, `pip install --pre cupy-cuda90` solved the problem.

**Comment by okuta** [comment]
> I'm getting the exact same error message when installing cupy, with CUDA_PATH set correctly.
hmm...

> Actually, pip install --pre cupy-cuda90 solved the problem.
OK, please use it.

**Comment by qbilius** [comment]
Seems like having the information that CUDA's version matters and a different command should be used for installation if you have CUDA 9.0 (`pip install --pre cupy-cuda90`) would be very helpful on the installation docs.

**Comment by MLikelihood** [comment]
for cuda 9.0:
pip install --pre cupy-cuda90

Or you may want to first do:
1. check you module list : module list
2. unload pgi module: module unload pgi/16.9

**Comment by kmaehashi** [comment]
As we now provide wheels (cupy-cudaXX) for stable releases, generally you don't have to specify `--pre` (unless you want to install pre-release (alpha/beta/rc) versions).
See the installation guide for details. It now covers the installation steps to install wheels:
https://docs-cupy.chainer.org/en/stable/install.html#install-cupy

**Comment by pylearndl** [comment]
I'm unable to install cupy on Mac. I need some help please

```
Collecting cupy
  Downloading https://files.pythonhosted.org/packages/9a/5e/63ddb72e3ef1b3d65484ebf415651d36c08d36df61d8a7898cd2da7b3460/cupy-5.2.0.tar.gz (2.5MB)
    100% |████████████████████████████████| 2.5MB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    **************************************************
    *** WARNING: nvcc path != CUDA_PATH
    *** WARNING: nvcc path: /usr/local/cuda
    *** WARNING: CUDA_PATH: /Developer/NVIDIA/CUDA-9.1/bin
    **************************************************
    
    -------- Configuring Module: cuda --------
    /tmp/tmp6_zpf170/a.cpp:1:10: fatal error: 'cublas_v2.h' file not found
    #include <cublas_v2.h>
             ^
    1 error generated.
    command 'gcc' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: []
      Library directories: ['/usr/local/cuda/lib']
      nvcc command       : (not found)
    
    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : /Developer/NVIDIA/CUDA-9.1/bin
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-2wjvqs8i/cupy/setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/private/tmp/pip-install-2wjvqs8i/cupy/cupy_setup_build.py", line 588, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/private/tmp/pip-install-2wjvqs8i/cupy/cupy_setup_build.py", line 384, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-2wjvqs8i/cupy/
```

**Comment by kmaehashi** [comment]
Try `CUDA_PATH` must be a root of your CUDA installation. Try `CUDA_PATH=/Developer/NVIDIA/CUDA-9.1`.

**Comment by pylearndl** [comment]
@kmaehashi 
Thanks but doesn't work. Problem is Mac os x. I think cupy doesn't support Mac yet.

**Comment by leofang** [comment]
+1. I don't think Mac is supported anymore:

```shell
leofang@Leos-MacBook-Pro:~$ CUDA_PATH=/Developer/NVIDIA/CUDA-9.2
leofang@Leos-MacBook-Pro:~$ pip install 'cupy>=6.0.0b3'
Collecting cupy>=6.0.0b3
  Downloading https://files.pythonhosted.org/packages/9d/da/25658fef5eca202580d5741551e4ad97f4bdc962410bea403536602474b4/cupy-6.0.0rc1.tar.gz (3.1MB)
     |████████████████████████████████| 3.1MB 2.3MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    
    -------- Configuring Module: cuda --------
    Cannot build a stub file.
    Original error: command 'x86_64-apple-darwin13.4.0-clang++' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/Developer/NVIDIA/CUDA-9.2/include']
      Library directories: ['/Developer/NVIDIA/CUDA-9.2/lib', '/usr/local/cuda/lib']
      nvcc command       : ['/Developer/NVIDIA/CUDA-9.2/bin/nvcc']
    
    Environment Variables:
      CFLAGS          : -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
      LDFLAGS         : -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs
      LIBRARY_PATH    : (none)
      CUDA_PATH       : (none)
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-olupg58d/cupy/setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-olupg58d/cupy/cupy_setup_build.py", line 601, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-olupg58d/cupy/cupy_setup_build.py", line 392, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-olupg58d/cupy/
```
and there's no wheel supporting Mac:
```shell
leofang@Leos-MacBook-Pro:~$ pip install 'cupy-cuda92>=6.0.0b3'
Collecting cupy-cuda92>=6.0.0b3
  ERROR: Could not find a version that satisfies the requirement cupy-cuda92>=6.0.0b3 (from versions: none)
ERROR: No matching distribution found for cupy-cuda92>=6.0.0b3
```

**Comment by kmaehashi** [comment]
* `CUDA_PATH=/Developer/NVIDIA/CUDA-9.2` should be `export CUDA_PATH=/Developer/NVIDIA/CUDA-9.2`.
* Could you confirm that all header files (`['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']`) are installed under `/Developer/NVIDIA/CUDA-9.2/include`?

**Comment by leofang** [comment]
Dear @kmaehashi, Thanks for the heads up. Sorry I copied the wrong output, which was from an earlier test. The correct ones are pasted below, and I did already confirm both points you raised prior to my last post.

Check headers exist:
```shell
leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ ls -l cublas_v2.h cuda.h cuda_profiler_api.h cuda_runtime.h cufft.h curand.h cusparse.h nvrtc.h
-rw-r--r--@ 1 root  wheel   10263  6 13  2018 cublas_v2.h
-rw-r--r--@ 1 root  wheel  502446  6 13  2018 cuda.h
-rw-r--r--@ 1 root  wheel    6128  6 13  2018 cuda_profiler_api.h
-rw-r--r--@ 1 root  wheel   89006  6 13  2018 cuda_runtime.h
-rw-r--r--@ 1 root  wheel   12786  6 13  2018 cufft.h
-rw-r--r--@ 1 root  wheel   42662  6 13  2018 curand.h
-rw-r--r--@ 1 root  wheel  384375  6 13  2018 cusparse.h
-rw-r--r--@ 1 root  wheel   20291  6 13  2018 nvrtc.h
```

Install from source:
```shell
leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ export CUDA_PATH=/Developer/NVIDIA/CUDA-9.2
leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ pip install 'cupy>=6.0.0b3'
Collecting cupy>=6.0.0b3
  Using cached https://files.pythonhosted.org/packages/9d/da/25658fef5eca202580d5741551e4ad97f4bdc962410bea403536602474b4/cupy-6.0.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
    
    -------- Configuring Module: cuda --------
    Cannot build a stub file.
    Original error: command 'x86_64-apple-darwin13.4.0-clang++' failed with exit status 1
    
    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************
    
    Build Environment:
      Include directories: ['/Developer/NVIDIA/CUDA-9.2/include']
      Library directories: ['/Developer/NVIDIA/CUDA-9.2/lib', '/usr/local/cuda/lib']
      nvcc command       : ['/Developer/NVIDIA/CUDA-9.2/bin/nvcc']
    
    Environment Variables:
      CFLAGS          : -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
      LDFLAGS         : -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs
      LIBRARY_PATH    : (none)
      CUDA_PATH       : /Developer/NVIDIA/CUDA-9.2
      NVTOOLSEXT_PATH : (none)
      NVCC            : (none)
    
    Modules:
      cuda      : No
        -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -> Check your CFLAGS environment variable.
    
    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html
    
    ************************************************************
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/setup.py", line 120, in <module>
        ext_modules = cupy_setup_build.get_ext_modules()
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/cupy_setup_build.py", line 601, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/cupy_setup_build.py", line 392, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/
```

Install wheel:
```shell
(qutip-env) leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ pip install 'cupy-cuda92>=6.0.0b3'
Collecting cupy-cuda92>=6.0.0b3
  Could not find a version that satisfies the requirement cupy-cuda92>=6.0.0b3 (from versions: )
No matching distribution found for cupy-cuda92>=6.0.0b3
```

**Comment by Stephenfang51** [comment]
> Dear @kmaehashi, Thanks for the heads up. Sorry I copied the wrong output, which was from an earlier test. The correct ones are pasted below, and I did already confirm both points you raised prior to my last post.
> 
> Check headers exist:
> 
> ```shell
> leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ ls -l cublas_v2.h cuda.h cuda_profiler_api.h cuda_runtime.h cufft.h curand.h cusparse.h nvrtc.h
> -rw-r--r--@ 1 root  wheel   10263  6 13  2018 cublas_v2.h
> -rw-r--r--@ 1 root  wheel  502446  6 13  2018 cuda.h
> -rw-r--r--@ 1 root  wheel    6128  6 13  2018 cuda_profiler_api.h
> -rw-r--r--@ 1 root  wheel   89006  6 13  2018 cuda_runtime.h
> -rw-r--r--@ 1 root  wheel   12786  6 13  2018 cufft.h
> -rw-r--r--@ 1 root  wheel   42662  6 13  2018 curand.h
> -rw-r--r--@ 1 root  wheel  384375  6 13  2018 cusparse.h
> -rw-r--r--@ 1 root  wheel   20291  6 13  2018 nvrtc.h
> ```
> 
> Install from source:
> 
> ```shell
> leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ export CUDA_PATH=/Developer/NVIDIA/CUDA-9.2
> leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ pip install 'cupy>=6.0.0b3'
> Collecting cupy>=6.0.0b3
>   Using cached https://files.pythonhosted.org/packages/9d/da/25658fef5eca202580d5741551e4ad97f4bdc962410bea403536602474b4/cupy-6.0.0rc1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': [], 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'no_cuda': False}
>     
>     -------- Configuring Module: cuda --------
>     Cannot build a stub file.
>     Original error: command 'x86_64-apple-darwin13.4.0-clang++' failed with exit status 1
>     
>     ************************************************************
>     * CuPy Configuration Summary                               *
>     ************************************************************
>     
>     Build Environment:
>       Include directories: ['/Developer/NVIDIA/CUDA-9.2/include']
>       Library directories: ['/Developer/NVIDIA/CUDA-9.2/lib', '/usr/local/cuda/lib']
>       nvcc command       : ['/Developer/NVIDIA/CUDA-9.2/bin/nvcc']
>     
>     Environment Variables:
>       CFLAGS          : -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe
>       LDFLAGS         : -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs
>       LIBRARY_PATH    : (none)
>       CUDA_PATH       : /Developer/NVIDIA/CUDA-9.2
>       NVTOOLSEXT_PATH : (none)
>       NVCC            : (none)
>     
>     Modules:
>       cuda      : No
>         -> Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
>         -> Check your CFLAGS environment variable.
>     
>     ERROR: CUDA could not be found on your system.
>     Please refer to the Installation Guide for details:
>     https://docs-cupy.chainer.org/en/stable/install.html
>     
>     ************************************************************
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/setup.py", line 120, in <module>
>         ext_modules = cupy_setup_build.get_ext_modules()
>       File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/cupy_setup_build.py", line 601, in get_ext_modules
>         extensions = make_extensions(arg_options, compiler, use_cython)
>       File "/private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/cupy_setup_build.py", line 392, in make_extensions
>         raise Exception('Your CUDA environment is invalid. '
>     Exception: Your CUDA environment is invalid. Please check above error log.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wz/176fb_ld4cv51n4cwrwhr81c0000gq/T/pip-install-a5_q4fqf/cupy/
> ```
> 
> Install wheel:
> 
> ```shell
> leofang@Leos-MacBook-Pro:/Developer/NVIDIA/CUDA-9.2/include$ pip install 'cupy-cuda92>=6.0.0b3'
> Collecting cupy-cuda92>=6.0.0b3
>   Could not find a version that satisfies the requirement cupy-cuda92>=6.0.0b3 (from versions: )
> No matching distribution found for cupy-cuda92>=6.0.0b3
> ```

Dear SIr

Did you solve the installation problem on Mac ?

Thank you ！

**Comment by hemangjoshi37a** [comment]
CUDA | Command
<br>
v11.2 ~ 11.8 (x86_64 / aarch64) | `pip install cupy-cuda11x`
<br>
v12.x (x86_64 / aarch64) | `pip install cupy-cuda12x`


</section>
