### ISSUE TITLE
 invalid value for --gpu-architecture (-arch)

### ISSUE THREAD

**Issue by 0i0** [cupy/cupy#973]
running:
`import cupy as cp
x = cp.arange(6).reshape(2, 3).astype('f')
x.sum(axis=1)`

and getting:
`Traceback (most recent call last):
  File "test.py", line 2, in <module>
    x = cp.arange(6).reshape(2, 3).astype('f')
  File "/home/lior/.local/lib/python2.7/site-packages/cupy/creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/elementwise.pxi", line 826, in cupy.core.core.ufunc.__call__
  File "cupy/util.pyx", line 39, in cupy.util.memoize.decorator.ret
  File "cupy/core/elementwise.pxi", line 625, in cupy.core.core._get_ufunc_kernel
  File "cupy/core/elementwise.pxi", line 33, in cupy.core.core._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 170, in cupy.core.core.compile_with_cache
  File "/home/lior/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 123, in compile_with_cache
    base = _preprocess('', options, arch)
  File "/home/lior/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 86, in _preprocess
    result = prog.compile(options)
  File "/home/lior/.local/lib/python2.7/site-packages/cupy/cuda/compiler.py", line 233, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: nvrtc: error: invalid value for --gpu-architecture (-arch)
`

please help

**Comment by kmaehashi** [comment]
What version of CUDA and GPU are you using? If you are using Pascal or later, please use CUDA 8.0 or later.
If you are using CUDA 8.0 or later, could you please try again with environment variable `export CUPY_DUMP_CUDA_SOURCE_ON_ERROR=1` and tell us the result?

**Comment by 0i0** [comment]
using CUDA 8.0
gtx 1060

and getting 

`Traceback (most recent call last):
  File "test.py", line 12, in <module>
    """)
  File "/home/lior/.local/lib/python3.5/site-packages/pycuda/compiler.py", line 291, in __init__
    arch, code, cache_dir, include_dirs)
  File "/home/lior/.local/lib/python3.5/site-packages/pycuda/compiler.py", line 255, in compile
    return compile_plain(source, options, keep, nvcc, cache_dir, target)
  File "/home/lior/.local/lib/python3.5/site-packages/pycuda/compiler.py", line 137, in compile_plain
    stderr=stderr.decode("utf-8", "replace"))
pycuda.driver.CompileError: nvcc compilation of /tmp/tmpszp230sz/kernel.cu failed
[command: nvcc --cubin -arch sm_61 -I/home/lior/.local/lib/python3.5/site-packages/pycuda/cuda kernel.cu]
[stderr:
nvcc fatal   : Value 'sm_61' is not defined for option 'gpu-architecture'
]
`

**Comment by 0i0** [comment]
sorry for that, i was runnig the wrong project
PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
did the trick

**Comment by kmaehashi** [comment]
OK, please reopen if you find any issues again.
